OPENING = {
    "id": "carokann",
    "name": "Caro-Kann Defence",
    "eco": "B10–B19",
    "section": "black-e4",
    "orientation": "black",
    "tagline": "Everything the French does, but without the bad bishop. The most structurally sound reply to 1.e4.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "1...c6 prepares ...d5 with pawn support, exactly like the French — but with a crucial difference: the c8-bishop gets out to f5 or g4 before the ...e6 pawn locks it in. Black gets a French position with the French's main problem already solved. The price is a tempo (the c-pawn takes two moves to reach c5) and a slightly passive position. The Caro-Kann is the choice of players who want to reach a good endgame with a healthy structure.",
        "structure": "After the Classical (3.Nc3 dxe4 4.Nxe4), Black has pawns on c6, e6 and a solid, symmetrical, weakness-free structure. Black is slightly cramped but has literally nothing to attack. In the Advance Variation the position becomes French-like but with the bishop already outside. In the Panov-Botvinnik, White gets an isolated queen's pawn and a sharp attacking game.",
        "white_plans": [
            "Classical (3.Nc3): trade on e4, chase the bishop with h4–h5, castle queenside and attack.",
            "Advance (3.e5): grab space and harass the f5-bishop with Nf3, Be2 and h4/Nh4.",
            "Panov-Botvinnik (3.exd5 cxd5 4.c4): open the game, take an isolated d-pawn and play for a kingside attack.",
            "Exchange (3.exd5 cxd5 4.Bd3): quiet, symmetrical, with a slow minority attack.",
        ],
        "black_plans": [
            "Develop the light-squared bishop outside the chain first, then play ...e6 — the whole point of the opening.",
            "Trade off pieces and head for an endgame where the healthy structure counts.",
            "Break with ...c5 (in the Advance) or ...e5 (in the Classical) once development is complete.",
            "Meet a kingside attack by castling queenside or leaving the king in the centre in closed positions.",
        ],
        "traps": [
            "Never play 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6?? 6.Nd6# — the smothered mate every Caro-Kann player must know.",
            "In the Advance, ...Bf5 4.h4!? h5 5.Bd3 is a genuine try — Black must know to take with ...Bxd3.",
            "After 4...Bf5 5.Ng3 Bg6 6.h4 h6 7.Nf3, do not forget 7...e6! — 7...Nf6? 8.Ne5 is very unpleasant.",
        ],
        "who": "Play this if you want a solid, low-risk defence to 1.e4 that still gives real winning chances in the endgame. Karpov, Anand and Carlsen have all used it as a main weapon.",
    },
    "lines": [
        {
            "name": "Classical Variation — Main Line",
            "note": "The historical main line. Black develops the bishop outside the pawn chain, then builds a fortress.",
            "moves": "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4",
            "notes": {
                3: "White takes the full centre.",
                4: "Black challenges with support — exactly as in the French, but the c8-bishop is still free.",
                5: "Defending e4 with a piece.",
                6: "Black resolves the tension. White gets a small space edge; Black gets a completely healthy structure with no weak pawns anywhere.",
                7: "Recapturing with the knight, which now sits actively in the centre.",
                8: "The whole point of the Caro-Kann. The problem bishop from the French is developed to an active square before ...e6 shuts it in.",
                9: "Kicking the bishop with tempo.",
                10: "The bishop retreats to a safe square where it still eyes the b1–h7 diagonal.",
                11: "The signature move. White gains space and threatens h5, trapping the bishop's retreat squares.",
                12: "Essential — creating a square for the bishop so that h4–h5 does not win a piece.",
                13: "Development.",
                14: "Now Black plays ...e6, and the bishop is already outside. The French's problem is solved.",
                15: "The knight jumps to a strong outpost, hitting f7 and preparing Bd3.",
                16: "The bishop steps back one more time. It looks silly on h7, but it is safe and Black's structure is untouched.",
                17: "Offering the trade of the good bishops.",
                18: "Black accepts, relieving the pressure.",
                19: "White recaptures with the queen, eyeing h7 and the b1–h7 diagonal.",
                20: "Development, challenging the strong knight on e5.",
                21: "Supporting the knight and preparing a kingside pawn storm. White has more space and attacking chances; Black is extremely solid and will castle queenside. This exact position has been played at the very top level for eighty years.",
            },
        },
        {
            "name": "Advance Variation — Short System",
            "note": "The most popular line today. White gains space; Black gets the bishop out first and hits back with ...c5.",
            "moves": "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 O-O Nbc6 Nxf5 Nxf5 c3 Be7",
            "notes": {
                5: "The Advance. White grabs space and locks the centre, exactly as in the French.",
                6: "And here is the difference. In the French this bishop would be trapped forever behind the e6-pawn. Here it comes out first — this single move is why many players prefer the Caro-Kann.",
                7: "The Short System, named after Nigel Short. White develops modestly and refuses to weaken with an early g4 or h4.",
                8: "Only now does Black play ...e6, with the bishop already safely outside.",
                9: "The quiet approach. White will castle and play on the queenside or in the centre.",
                10: "The standard break at the base of the chain.",
                11: "Developing and reinforcing d4.",
                12: "Black releases the tension.",
                13: "Recapturing with the piece, keeping the pawn structure clean.",
                14: "The knight goes to e7 rather than f6 (where e5 attacks it), heading for f5 or g6.",
                15: "King safety.",
                16: "Development, hitting the d4-knight.",
                17: "White trades off Black's good bishop.",
                18: "Black recaptures with the knight, which now sits actively on f5 hitting e3 and d4.",
                19: "Solidifying d4 and preparing Nd2–f3 or Bd3.",
                20: "Black completes development. The position is balanced: White has more space, Black has a healthy structure and pressure on d4.",
            },
        },
        {
            "name": "Panov-Botvinnik Attack",
            "note": "White refuses the quiet game, opens the centre and plays for an isolated-pawn attack. Every Caro-Kann player must know this.",
            "plan": {
                "structure": 'isolani',
                "point": "You have swapped the Caro-Kann's reputation for a middlegame: an isolated pawn on d4, the c5 and e5 squares that come with it, and a clock that starts running the moment the queens come off.",
                "next": [
                    'Re1 and Bg5 or Bf4, then Ne5. Three pieces at the kingside before Black finishes untangling — the isolani pays for activity, so spend it.',
                    'The d4–d5 break at the moment Black stops covering it. The pawn stops being weak the instant it advances.',
                    "Refuse every trade that is not part of a concrete win, and especially the queens. Each pair off the board moves the game from your half to Black's.",
                ],
                "endgame": 'You do not want one. A blockaded d4-pawn with a knight in front of it is simply a weak pawn, and the same structure you are attacking with is the one you lose in a rook ending. If it simplifies, aim for opposite-coloured bishops and a draw.',
            },
            "moves": "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Bb4 cxd5 Nxd5 Bd2 Nc6 Bd3 O-O O-O Be7",
            "notes": {
                5: "The Exchange. Now Black has a pawn on d5 and an open c-file, and the position resembles a Queen's Gambit with colours reversed.",
                6: "Forced — recapturing toward the centre.",
                7: "The Panov-Botvinnik Attack. White hits d5 immediately and heads for an open, tactical game. This is the sharpest anti-Caro-Kann there is.",
                8: "Development and defence of d5.",
                9: "Adding pressure to d5.",
                10: "Solid, supporting d5 for the third time.",
                11: "Development.",
                12: "Pinning the knight and relieving the pressure on d5.",
                13: "White resolves the tension and heads for the isolated pawn structure — but here White gets the isolated pawn, not Black.",
                14: "Recapturing with the knight, hitting c3.",
                15: "Breaking the pin and keeping all the pieces.",
                16: "Blockading and pressuring d4.",
                17: "The bishop takes the attacking diagonal aimed at h7.",
                18: "King safety.",
                19: "King safety.",
                20: "Black retreats the bishop to safety. White has an isolated d4-pawn: a weakness in the endgame, a source of attacking squares (c5 and e5) in the middlegame. The rule is simple — White must attack now, Black must trade pieces and win the pawn later.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — Caro-Kann into the endgame",
        "note": "The structure never cracks. Watch Black castle long, break with ...c5 and simplify toward a position with no weaknesses.",
        "moves": "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4 Ngf6 Bd2 Qc7 O-O-O O-O-O Kb1 c5 Nxd7 Rxd7 dxc5 Bxc5 Ne4 Nxe4 Qxe4",
        "notes": {
            22: "The last knight develops. Black's setup is now complete and, crucially, contains not a single weak pawn.",
            23: "Development, preparing to castle queenside.",
            24: "The queen takes the c-file post, eyeing c2 and supporting the coming ...c5.",
            25: "White castles long, which commits the king to the wing Black's queen already aims at.",
            26: "Black castles long too. Same-side castling means no pawn storms and a slow, technical game — exactly what a Caro-Kann player wants.",
            27: "A useful prophylactic move, taking the king off the c-file and out of any ...Nb6–c4 tricks.",
            28: "The break. This is the move Black has been building toward for twenty-seven moves. It challenges d4 and opens the c-file behind White's king.",
            29: "White trades off the strong e5-knight before it gets kicked.",
            30: "Black recaptures with the rook, which lands on the file it wants.",
            31: "White resolves the centre.",
            32: "Black recaptures with the bishop, which now stares at the a7–g1 diagonal and at f2.",
            33: "Trading again.",
            34: "And again. Every trade suits Black, because Black has no weaknesses and White's extra kingside space becomes meaningless without pieces.",
            35: "White recaptures. Material is level, structures are healthy, queens are still on — but look at the pawns. White has pawns on a2, b2, c2, f4, g2, h4; Black has a7, b7, e6, f7, g7, h6. Neither side has a weakness, and Black has a completely comfortable game. That is the Caro-Kann's promise, delivered.",
        },
    },
    "progression": {
        "arc": "The Caro-Kann is the French with the main problem removed. It costs you a tempo and buys you a lifetime of healthy positions.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Learn the one rule that defines the whole opening.",
                "learn": [
                    "The rule: develop the light-squared bishop before playing ...e6. Break it and you have a worse French.",
                    "White's four options: 3.Nc3/3.Nd2 (Classical), 3.e5 (Advance), 3.exd5 (Exchange/Panov), 2.c4 (Accelerated Panov).",
                    "The mate you must know: 1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6?? 6.Nd6#.",
                ],
                "drill": "Play the Classical twenty times, focusing only on getting ...Bf5, ...e6, ...Nd7 and ...Ngf6 in the right order.",
                "mistake": "Playing ...Bf5 when White can hit it with Qb3 or Nh4 favourably. Check the tactics before every bishop move.",
                "ready": "You never lock the bishop in behind ...e6.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Learn to be slightly worse and completely safe.",
                "learn": [
                    "In the Classical, Black has no weaknesses at all — the plan is to trade pieces and reach an equal endgame.",
                    "In the Advance, the plan is the same as the French: ...c5 at the base of the chain, but with your bishop already out.",
                    "In the Panov, you face an isolated queen's pawn — the most important structure in chess after the Carlsbad.",
                ],
                "drill": "Play the Classical to move twenty and stop. Count your weaknesses. If the answer is zero, you played it correctly.",
                "mistake": "Trying to equalise with an early ...c5 in the Classical. Complete development first; the break comes later.",
                "ready": "You can explain why Black's structure has no weaknesses and why that is worth being cramped.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Play for a win, not just a draw.",
                "learn": [
                    "Castling queenside in the Classical when White commits to a kingside storm — the game becomes a race you are well placed for.",
                    "The ...c5 and ...e5 breaks and how to prepare them properly.",
                    "How to play against the isolated queen's pawn: blockade on d5, trade minor pieces, win the pawn in the endgame.",
                ],
                "drill": "Study ten IQP games from the blockading side. This one structure appears in the Panov, the Tarrasch French, the Nimzo and the QGA.",
                "mistake": "Playing for a draw. The Caro-Kann's solidity is a platform for winning endgames, not a defensive shell.",
                "ready": "You have won a Caro-Kann endgame from a position you would once have called equal.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Cover every White try and refine the endgames.",
                "learn": [
                    "The modern 3...c5 and 3...Nd7 systems against the Advance, which are the current fashion.",
                    "The Fantasy Variation 3.f3 and the Two Knights 2.Nf3, both common surprise weapons.",
                    "Endgames with the healthy 4v4 structure: this is where Caro-Kann players actually score their wins.",
                ],
                "drill": "Prepare a line against 3.f3 and 2.Nf3 specifically. Most Caro-Kann players are unprepared and lose the opening battle immediately.",
                "mistake": "Assuming every White player will enter the Classical. Below master level, most will not.",
                "ready": "You have a written answer to every White second and third move.",
            },
        ],
        "study": "Anatoly Karpov's Caro-Kann games are the model of risk-free winning. Viswanathan Anand and Magnus Carlsen both use it at the highest level.",
        "next": "Add the French as a sharper alternative, or go the other way and learn the Sicilian when you want to play for a win with Black more often.",
    },
}
