OPENING = {
    "id": "carokann",
    "name": "Caro-Kann Defence",
    "eco": "B10–B19",
    "section": "black-e4",
    "orientation": "black",
    "tagline": "Everything the French does, but without the bad bishop. The most structurally sound reply to 1.e4.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "1...c6 prepares ...d5 with pawn support, exactly like the French — but with one difference that decides the whole opening: the c8-bishop gets out to f5 before the ...e6 pawn walls it in. Black reaches a French position with the French's oldest problem already solved. The price is a tempo, because the c-pawn needs two moves to reach c5 and in the French it needs one, and a little less space. It is the choice of players who want a healthy structure and an endgame.",
        "structure": "In the Classical (3.Nc3 dxe4 4.Nxe4) White's e-pawn and Black's d-pawn both leave the board on move three: White ends up with a spare pawn on d4 and Black with one on e6, three pawns a side on each wing, and no weakness anywhere. In the Advance (3.e5) the pawns lock into the French chain with an extra black pawn on c6 — the bishop is already outside, and the ...c5 break costs the tempo the bishop bought. In the Panov (3.exd5 cxd5 4.c4) both c-pawns come off too, White takes an isolated pawn on d4 and the game turns tactical.",
        "white_plans": [
            "Classical (3.Nc3): trade on e4, chase the bishop with Ng3 and h4, trade the light-squared bishops on d3, and castle queenside with more space.",
            "Advance (3.e5): grab the space and put the question to the f5-bishop — quietly with Nf3 and Be2, or at once with 4.h4 or 4.g4.",
            "Panov-Botvinnik (3.exd5 cxd5 4.c4): open the game, accept an isolated queen's pawn and play for the attack while it is still strong.",
            "Exchange (3.exd5 cxd5 4.Bd3): quiet and symmetrical, with the pawn majorities of a Carlsbad and the colours the wrong way round.",
        ],
        "black_plans": [
            "Develop the light-squared bishop outside the chain first, then play ...e6. Break that order and you have a worse French.",
            "Trade pieces. There is no weakness in Black's structure to defend, so every exchange takes something away from White and nothing from Black.",
            "Break with ...c5 — in the Advance at the base of the chain, in the Classical once every piece is out.",
            "In the Classical, castle wherever White is not. With both light-squared bishops traded off, White's kingside attack has no piece behind it.",
        ],
        "traps": [
            "The mate every Caro-Kann player must know: 1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6?? 6.Nd6#. The knight on d7 and the bishop on f8 take every escape square away from their own king.",
            "In the Advance after 3...Bf5 4.h4, the automatic 4...e6? is close to losing: 5.g4 Be4 6.f3 and the bishop has to give itself up for the c2-pawn. Answer 4...h5, and the position is level.",
            "In the Panov after 5...e6 6.Nf3 Bb4 7.cxd5 Nxd5, White's natural 8.Bd3? drops the exchange to 8...Nxc3 9.bxc3 Bxc3+ 10.Bd2 Bxa1. The bishop on b4 has been looking at that rook since move six.",
        ],
        "who": "Play this if you want a solid, low-risk defence to 1.e4 that still gives real winning chances in the endgame. Karpov, Anand and Carlsen have all used it as a main weapon — Carlsen with it in the 2013 World Championship match is the deep dive below.",
    },
    "lines": [
        {
            "name": "Classical Variation — Main Line",
            "note": "The historical main line and still the top-level one. Black gets the bishop out, trades it off, and arrives at a position with no weaknesses in it.",
            "moves": "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": "Foundation",
                "point": "Count the board before you worry about the space. Material is dead level and so are the pieces — a queen, two rooks, two knights and one dark-squared bishop each, because both light-squared bishops came off on move nine. The pawns are three a side on both wings, and each side's seventh is a lone centre pawn — White's on d4, yours on e6. There is no majority anywhere, no weak pawn anywhere, and one asymmetry that is worth knowing: you have no d-pawn, so the d-file belongs to your rooks, and White has no e-pawn, so the e-file belongs to White's.",
                "next": [
                    "11...Bb4+ before anything else. It is a question, and the two answers worth playing both suit you: 12.c3 spends a move and commits the pawn to c3 instead of c4, and 12.Bd2 Bxd2+ trades a pair of bishops, which by the engine's count is the better of the two for Black.",
                    "...Be7, ...Ngf6 and castle. Short is right even when White castles long, and the reason is the piece that is missing: with the light-squared bishops already traded there is no Bxh7 and no battery on b1–h7, and the h-file stays shut as long as your pawn sits on h6.",
                    "...Nxe5 at a moment of your choosing, and then ...c5. The knight on e5 is White's best piece and it is held there by two pawns, d4 and f4 — take it off, and whichever pawn recaptures, White is left with a big centre and nothing to attack with.",
                ],
                "endgame": "Three against three on both wings, and each side's spare centre pawn faces two enemy pawns that could capture it, so nobody makes a passed pawn by force. A queenless position therefore turns on the two bishops that are left, and they are both dark-squared. Count what stands in their way: four of White's seven pawns are on dark squares — b2, d4, f4 and h4 — and three of yours are, on a7, g7 and h6. That is the whole difference, and it is why you should be happy to trade every other piece on the board.",
            },
            "notes": {
                3: "White takes the second centre pawn. The pawn on c6 is not a lost move — it is the support the next one needs.",
                4: "The point of 1...c6. Black challenges e4 with a pawn behind it, exactly as in the French, and the c8-bishop is not shut in.",
                5: "Defending e4 with a piece. 3.Nd2 does the same job and almost always transposes.",
                6: "Black resolves the tension. It looks like a concession and it is the move the whole opening is built on: the light-squared bishop comes out next, and it comes out attacking something.",
                7: "Recapturing with the knight, which stands in the middle of the board with nothing hitting it. That lasts exactly one move.",
                8: "The move the Caro-Kann exists for. The bishop leaves the pawn chain before ...e6 walls it in, and on the way out it attacks the knight on e4.",
                9: "The knight steps off the attack and hits the bishop back — from g3 it covers f5, which is where the bishop is standing.",
                10: "The retreat that keeps the bishop on the b1–h7 diagonal and out of the way of Black's own coming ...e6.",
                11: "The signature move. The threat is h4–h5, and the point is not that the bishop is trapped — it is that h7, the square the bishop wants, is occupied by Black's own pawn.",
                12: "So the pawn moves first, and it is close to forced — the engine has both natural developing moves costing a pawn and a half. Without it, 7.h5 hits the bishop while h7 is still occupied by your own pawn, and the bishop has to come to f5 where the knight on g3 simply takes it.",
                13: "Development. 7.h5 first is the other main move and usually reaches the same positions.",
                14: "Only now ...e6, with the bishop already outside — the French's oldest problem solved without ever arising. The pawn also covers f5 and backs up d5.",
                15: "The outpost, and it comes with a threat: the knight on e5 attacks the bishop on g6 as well as d7 and f7.",
                16: "So the bishop goes to h7, the square move six made for it. It looks absurd there and it is completely safe, and White's next move offers to buy it.",
                17: "White offers the trade of the last light-squared bishops. It is the standard deal in this variation: White gets the queen onto the b1–h7 diagonal, Black gets a piece off the board.",
                18: "Take. The bishop on h7 has nothing to do and the piece it trades for is the one that would otherwise be aimed at your king for the next twenty moves.",
                19: "Recapturing with the queen, which takes over the diagonal the bishop just left and eyes b5 and c4 on the way.",
                20: "The knight goes to d7 rather than c6, because c6 is occupied and because from d7 it does three jobs at once: it attacks the knight on e5, it clears the way for ...Ngf6, and it supports the ...c5 break.",
                21: "White props the e5-knight up with a pawn and starts a kingside front. It is also a commitment — the f-pawn is not coming back, and the knight on e5 is now the only reason the pawn on f4 is not simply loose. Both sides are one move from finishing development; the plan card says which move.",
            },
        },
        {
            "name": "Advance Variation — Short System",
            "note": "The most popular line today. White takes the space and develops quietly; Black gets the bishop out, breaks with ...c5 and ends up with the two bishops.",
            "moves": "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 O-O Nbc6 Bb5 a6 Bxc6+ bxc6",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "Count the minor pieces, because that is what the last two moves were about: White has one bishop and two knights, you have two bishops and one knight. Everything else is level at seven pawns each. What you have paid for the pair is a queenside where White has three pawns to your two, and what you have bought is a position that opens the moment you want it to. And look at e5 while you are counting — the pawn that has cramped you since move three is defended by absolutely nothing.",
                "next": [
                    "...Ng6 and then ...Qc7 or ...Nd7, in whatever order suits. Nothing defends e5, so every piece you point at it is a free attacker and White has to answer with f2–f4 or Re1 — moves that do not improve anything else.",
                    "Castle short, and soon. Your king is still on e8 and the one file White can use is the d-file, because White's d-pawn died on move seven and yours is still on d5.",
                    "...c5 when the moment comes. Nothing in your position attacks the knight on d4 yet, so this is the first attacker and it takes the square away for good. After it moves, the bishop on f5 and the half-open b-file are both pointing at a queenside White would rather keep quiet.",
                ],
                "endgame": "Be honest about the bargain. Three pawns against two on the queenside is a real White majority and three against three on the kingside makes nothing, so a pure pawn ending favours White. The compensation is the bishop pair in a position with two half-open files already and two pawn breaks still available. Keep the bishops, keep opening the position, and do not trade into a rook ending because the structure looks tidy.",
            },
            "notes": {
                5: "The Advance. White locks the centre and takes the space, exactly as in the French — and this is the move the Caro-Kann was designed to collect on.",
                6: "Out, before the wall goes up. In the French this bishop spends the game behind a pawn on e6; here it takes the b1–h7 diagonal first and ...e6 follows.",
                7: "The Short System, named for Nigel Short. White refuses to chase the bishop with 4.g4 or 4.h4 and simply develops, which is both the most popular and the most sensible treatment.",
                8: "And now ...e6. The pawn supports d5 and covers f5 — which matters, because f5 is where the bishop is standing.",
                9: "Modest, and pointed. From e2 the bishop keeps the a4–e8 diagonal in reserve, and the pin it plays on move nine is what makes this system awkward rather than harmless.",
                10: "The break, at the base of White's chain. Here is the tempo the Caro-Kann pays for its bishop: the c-pawn takes two moves to reach c5, and in the French it takes one.",
                11: "The defining move of the system. White holds d4 with a piece rather than a pawn, keeping c2–c4 available for later.",
                12: "Taking now, while White has to recapture with a piece — the c-pawn is still at home, so there will be no pawn on d4 to attack. What lands there instead is a knight, and a knight can be hit.",
                13: "The knight takes the centre. It looks strong, and it is also the only thing in White's position you can put a piece on.",
                14: "To e7 rather than f6, where the pawn on e5 would simply attack it. From e7 the knight goes to g6, hitting e5, or to f5, hitting d4 and the bishop on e3.",
                15: "King safety.",
                16: "The second knight, from b8, hitting d4. The other knight stays on e7 because it has better squares in front of it.",
                17: "The critical move, and the reason White's bishop went to e2 rather than d3: it pins the knight on c6 against your king. Do not treat the pin as scenery — 9...Ng6?? 10.Nxc6 wins material by force, and the deviation panel has the lines.",
                18: "Putting the question first. While the pin is on, the knight on c6 cannot move at all, so the pawn move is the fastest way to end the argument.",
                19: "White cashes in. Retreating instead hands you ...a6 for nothing, so this is the honest test of the whole variation.",
                20: "Recapture toward the centre. The pawn on c6 now covers b5 and d5, you have the two bishops, and the pawn on e5 that has cramped you for ten moves has no defender at all. The plan card is about that last one.",
            },
        },
        {
            "name": "Panov-Botvinnik Attack",
            "note": "White refuses the quiet game, opens the centre and takes an isolated queen's pawn to attack with. Every Caro-Kann player has to know this from the Black side.",
            "moves": "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Bb4 cxd5 Nxd5 Bd2 Nc6 Bd3 O-O O-O Be7",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "structure": "isolani",
                "tier": "Structure",
                "point": "Both c-pawns and White's e-pawn have left the board, so the c-file is completely open and there is not a pawn on it. White's sixth pawn is the isolated one on d4 and yours is on e6; the wings are two against two and three against three. That single pawn is the whole game. It is strong for about fifteen moves, because it hands White the c5 and e5 squares and open lines for every piece, and weak for the rest of the game. Your job is to survive the fifteen.",
                "next": [
                    "...Rc8, and before White gets Rc1. It is the only fully open file on the board and both sides want it.",
                    "Leave the knight on d5. It is not doing anything spectacular there and it is the single reason the pawn on d4 can never advance — and d4–d5 is the one move that would stop the pawn being weak.",
                    "Solve the c8-bishop with ...b6 and ...Bb7. The isolani card recommends ...Be6, and that belongs to the version of this structure where Black's spare pawn is on c7; here it is standing on e6, so the bishop takes the long road instead.",
                ],
                "endgame": "This is the half of the game you are playing for, and the arithmetic says why. Two against two and three against three means neither side can make a passed pawn, so the only material on the board that can actually be won is the pawn on d4 — and it cannot be defended by another pawn, because there is no white pawn left on the c- or e-file. With queens on it is an attacking asset; with queens off it is a target with a knight sitting on top of it. Trade the queens first and everything else afterwards.",
            },
            "notes": {
                5: "The Exchange. White kills the tension before it exists: your c-pawn is about to land on d5 and the c-file opens for good.",
                6: "Toward the centre, and it opens the c8–h3 diagonal for the bishop at the same time.",
                7: "The Panov-Botvinnik Attack. White puts the first attacker on d5 and accepts an open, tactical game — the sharpest thing there is against the Caro-Kann, and the one line where your solid structure is not the story.",
                8: "Development, and a defender for d5.",
                9: "A second attacker on d5. The count is two against two: the pawn on c4 and the knight on c3 against the knight on f6 and the queen on d8.",
                10: "The third defender, and the move that shuts in your own bishop — the French problem arriving in the Caro-Kann by the back door. You get the bishop back later, when the c-file gives it a job.",
                11: "Development.",
                12: "The pin, and it is worth more than it looks: an absolutely pinned knight cannot move, so the knight on c3 has stopped being an attacker of d5 even though it still watches the square.",
                13: "So White resolves it first, and takes the isolated pawn on purpose. This is the deal the whole variation is about — the c-pawn goes, and what is left on d4 will never have a pawn beside it again.",
                14: "Recapture with the knight, which lands on the blockading square directly in front of the isolated pawn. That is where it wants to be for the rest of the game.",
                15: "Breaking the pin and keeping every piece on the board. The natural 8.Bd3? drops the exchange instead — the panel walks through it.",
                16: "Development, and the first piece pointing at d4. Count it: the pawn is attacked by the knight on c6 and defended by the knight on f3 — and not by the queen on d1, because White's own bishop on d2 stands between them. The model game turns on exactly that.",
                17: "The bishop takes the b1–h7 diagonal. This is what an isolated queen's pawn buys — every white piece gets a good square, and the pawn gets weaker every time one of them is traded off.",
                18: "King safety, and it matters more here than usual: White's next few moves are all going to point at this corner.",
                19: "White castles too.",
                20: "The bishop steps back to a square where nothing can hit it, and Black is fully developed. Take stock: the c-file is open and yours to take first, the knight on d5 is glued to the square in front of White's weakness, and the only awkward piece you own is the bishop on c8. All three are on the plan card.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — Carlsen's answer, World Championship 2013",
        "note": "Anand against Carlsen, Chennai, game two. White has more space, both knights and a pawn front; Carlsen trades three pairs of pieces in four moves and the attack simply stops existing.",
        "moves": "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4 Bb4+ c3 Be7 Bd2 Ngf6 O-O-O O-O Ne4 Nxe4 Qxe4 Nxe5 fxe5 Qd5 Qxd5 cxd5",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "tier": "Plans",
            "point": "Eighteen moves and the middle of the board is a wall: your pawn on d5 stops d4–d5, your pawn on e6 stops e5–e6, and White's two do the same to yours. Queens are off, all four knights are off, and the two bishops left are both dark-squared. What is left is one half-open file each — the c-file for you, the f-file for White — and one majority each: White three against two on the queenside, you three against two on the kingside.",
            "next": [
                "...Rac8 and the half-open file. It is the only line you own and it runs at a king sitting on c1 behind the pawns you are about to push at it.",
                "...b5 and ...a5, which is what Carlsen played. The majority you are advancing is not the kingside one — it is the queenside pawns aimed at White's king, and your own king is at the other end of the board.",
                "Leave the kingside alone until White commits. Your three pawns there against White's two are the majority that actually makes a passer, and every one of them that moves is a square White's rook on the f-file gets for free.",
            ],
            "endgame": "Same-coloured bishops with a locked centre is the most drawish combination on a chessboard, and that is the honest verdict — Carlsen repeated the position seven moves later and took the half point against the World Champion. What is worth taking away is which side had to work for it. Five of White's seven pawns stand on dark squares — b2, c3, d4, e5 and h4 — and three of yours do. The bishops are equal in name and yours is the one with room.",
        },
        "notes": {
            22: "The check first, and it is a question rather than a threat. There are only two sensible answers and both cost White something.",
            23: "White blocks with the pawn and keeps the bishop. The one reply that does not work is 12.Qd2, when 12...Bxd2+ 13.Bxd2 Nxe5 collects a pawn in a position with no queens left to complicate it.",
            24: "And back again. Two bishop moves for one pawn move looks like a poor trade until you notice which pawn: White's c-pawn is now committed to c3, and c4 is a move away instead of a move.",
            25: "White develops the last minor piece and prepares to castle long.",
            26: "The last knight comes out. Black is now one move from castling and has not created a weakness anywhere on the board.",
            27: "White castles into the quiet wing and declares the plan: a king on c1, a rook arriving on h1 behind the h4-pawn, and a kingside pawn front to push.",
            28: "Short, straight into it — and it is correct. The pieces that make that attack work are not on the board: both light-squared bishops came off on move nine, so there is no Bxh7 and no battery on b1–h7, and the h-file cannot open while your pawn stands on h6.",
            29: "White offers the knight trade, hoping to open a line before Black is organised.",
            30: "Take it. This is the first of three trades in four moves, and each one removes a piece that was pointing at your king.",
            31: "Recapturing with the queen, which lands on the diagonal the bishop left on move nine with nothing at the end of it.",
            32: "The second trade, and the one ...Nd7 was played for twenty plies ago: the knight on e5 has been White's best piece since move eight and it comes off for a knight that was doing nothing in particular.",
            33: "The f-pawn recaptures, which is right — 17.dxe5 would open the d-file at White's own rook. The pawn on e5 is now permanent, defended by the pawn on d4, and the only thing that could ever challenge it is the pawn on f7.",
            34: "The third offer, and it is not only a trade. From d5 the queen also looks down the diagonal at a2, a pawn that White's queenside castling left defended by nothing at all, so declining costs a pawn in front of the king.",
            35: "White takes. Keeping the queens on with 18.Qg4 is the engine's preference by about a tenth of a pawn; Anand took, and by then there was very little left to attack with.",
            36: "Recapture with the c-pawn and look at what is on the board. Seven pawns each, one dark-squared bishop each, two rooks each, and a centre where all four central pawns are jammed against each other: d4 against d5, e5 against e6, and not one of them can advance. You have the c-file half-open and three kingside pawns against two; White has the f-file and three queenside pawns against two. Carlsen repeated the position and took the draw — against the World Champion, in a World Championship match, that is the Caro-Kann doing precisely its job.",
        },
    },
    # Deviations, keyed by the position they answer rather than by a ply number.
    # This is a Black repertoire, so most of the sets below answer a WHITE move:
    # the entries are what your opponent might play instead of the main line, and
    # the `why` says what you do about it. The sets at a Black-to-move position
    # are your own alternatives, and they are labelled as such.
    "branches": {

        # ── ply 2 · White's second move — everything except 2.d4 ─────────────────
        "e4 c6": [
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "name": "Two Knights Attack",
             "why": "White defends e4 with a piece and keeps the d-pawn at home, intending 3.Nf3 and only then d4. Play 2...d5 anyway — it is the move whatever White does — and after 3.Nf3 the pin 3...Bg4 is the point of the whole system for Black: White's knight on f3 is what would otherwise recapture on d4 or e5, and pinning it means the centre never gets built the way White wanted.",
             "line": "d5 Nf3 Bg4 d4 e6"},
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "name": "Two Knights Attack",
             "why": "The same system with the knights in the other order, and it costs about a tenth of a pawn. Same answer: 2...d5 and then 3...Bg4 against 3.Nc3. What you must not do is drift — 2...d6 or 2...e6 turn the Caro-Kann into something you have not prepared, and the whole point of 1...c6 was the pawn coming to d5.",
             "line": "d5 Nc3 Bg4 d4 e6"},
            {"san": "c4", "severity": "playable", "tier": "Structure",
             "name": "Accelerated Panov Attack",
             "why": "White attacks d5 before you have got there, so that you cannot hold it with ...e6 and ...Nf6 in comfort. It transposes: 2...d5 3.exd5 cxd5 4.d4 Nf6 and you are in the Panov a move early, with everything you know about it still true. Do not be talked out of 2...d5 — 2...e5 and 2...d6 both hand White a free hand in the centre for nothing.",
             "line": "d5 exd5 cxd5 d4 Nf6",
             "see": "carokann#panov"},
            {"san": "d3", "severity": "playable", "tier": "Structure",
             "name": "Breyer Variation",
             "why": "Unambitious and completely sound — about a quarter of a pawn behind 2.d4. White will not take the big centre and plans Nd2, Ngf3, g3 and a slow King's Indian Attack. One honest line tells you what it is worth: 2...d5 3.Nf3 dxe4 4.dxe4 Qxd1+ 5.Kxd1 and the queens are off on move four in a dead-level position. Play it if a draw suits you; if it does not, keep the queens on with 3...e5 instead.",
             "line": "d5 Nf3 dxe4 dxe4 Qxd1+"},
            {"san": "Ne2", "severity": "playable", "tier": "Plans",
             "why": "The knight goes to e2 so that after ...dxe4 it can recapture there and keep the f3-square for the other one. It costs White about four tenths of a pawn — the knight on e2 blocks the bishop on f1 and does nothing about d5 — and 2...d5 3.exd5 cxd5 4.d4 Nf6 is a good Exchange Variation where White has spent a move on a square the knight did not want.",
             "line": "d5 exd5 cxd5 d4 Nf6"},
            {"san": "f4", "severity": "playable", "tier": "Plans",
             "why": "A King's Gambit shape without the gambit, and it does nothing at all about d5 — which is the only square this opening is about. It costs White a little over four tenths of a pawn. Take the centre with 2...d5, and note that after 3.d3 dxe4 4.dxe4 Qxd1+ 5.Kxd1 you have traded queens with White's king on d1 and a pawn already committed to f4.",
             "line": "d5 d3 dxe4 dxe4 Qxd1+"},
        ],

        # ── ply 4 · White's third move — the four doors and two gambits ──────────
        "e4 c6 d4 d5": [
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "name": "Classical Variation",
             "why": "The main line and the engine's own first choice. White defends e4 with a piece and lets you decide the game: 3...dxe4 4.Nxe4 and then 4...Bf5, 4...Nd7 or 4...Nf6. Everything in the Classical line above starts here.",
             "line": "dxe4 Nxe4 Bf5 Ng3 Bg6",
             "see": "carokann#classical"},
            {"san": "Nd2", "severity": "playable", "tier": "Foundation",
             "name": "Modern Variation",
             "why": "The same job with the other knight, and the engine rates it identically. The difference is that the knight on d2 blocks the c1-bishop for a move and cannot be pinned or hit by ...b5 — which matters only if you were planning 3...g6 or 3...b5. After 3...dxe4 4.Nxe4 the two moves reach the same position and nothing you have learned changes.",
             "line": "dxe4 Nxe4 Bf5 Ng3 Bg6"},
            {"san": "e5", "severity": "playable", "tier": "Foundation",
             "name": "Advance Variation",
             "why": "The most popular move at every level today. White locks the centre into the French chain — d4 and e5 against d5 and e6 — with one difference from the French that decides everything: your c-pawn is on c6 rather than your e-pawn on e6, so the light-squared bishop comes out first and the ...c5 break costs a tempo. Play 3...Bf5 before anything else.",
             "line": "Bf5 Nf3 e6 Be2 c5",
             "see": "carokann#advance"},
            {"san": "exd5", "severity": "playable", "tier": "Foundation",
             "name": "Exchange Variation",
             "why": "White resolves the centre, and then chooses: 4.c4 is the Panov-Botvinnik and 4.Bd3 is the quiet Exchange. Recapture 3...cxd5 without thinking — it opens the c-file and the c8–h3 diagonal at the same time — and read the panel at the next position for the fork in the road.",
             "line": "cxd5 c4 Nf6 Nc3 e6",
             "see": "carokann#panov"},
            {"san": "f3", "severity": "playable", "tier": "Structure",
             "name": "Fantasy Variation",
             "why": "Also called the Maróczy, and it is a genuine try rather than a bluff — the engine has it four hundredths of a pawn behind 3.Nc3. White intends to recapture on e4 with the f-pawn and own the whole centre. The cleanest answer is 3...e6, keeping the tension and treating the position as a French where White has weakened the e1–h4 diagonal: 4.Nc3 Bb4 5.a3 Bxc3+ 6.bxc3 and White's structure is broken before anything has been decided.",
             "line": "e6 Nc3 Bb4 a3 Bxc3+"},
            {"san": "c4", "severity": "inaccuracy", "tier": "Mastery",
             "why": "White refuses to defend e4 at all, hoping for a Diemer-style gambit. Take it: after 3...dxe4 the engine already prefers Black by about three quarters of a pawn. Then hold it sensibly rather than greedily — 4.Nc3 Nf6 5.f3 Qc7 and you keep the extra pawn with the queen off the file White wants to open.",
             "line": "dxe4 Nc3 Nf6 f3 Qc7"},
        ],

        # ── ply 5 · YOUR third move after 3.Nc3 ─────────────────────────────────
        "e4 c6 d4 d5 Nc3": [
            {"san": "g6", "severity": "playable", "tier": "Mastery",
             "name": "Gurgenidze System",
             "why": "A completely different opening: Black gives up on ...dxe4 and builds a King's-Indian wall with ...Bg7, ...Nh6 or ...Nd7 and, eventually, ...f6 or ...c5. It costs a little under half a pawn, which is the price of a system nobody prepares for. White's best is the simple 4.e5, and after 4...Bg7 5.Bf4 Nd7 you are playing a French chain with the bishop on the long diagonal instead of the b1–h7 one.",
             "line": "e5 Bg7 Bf4 Nd7 Qd2"},
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "why": "This is the move the whole opening was played to avoid — it shuts the c8-bishop in and reaches a French where the c-pawn is on c6 rather than doing something useful. It is not losing, it is about four tenths of a pawn, and the position is genuinely solid. But be clear about what you have done: you have paid a tempo for a bishop and then locked the bishop in anyway.",
             "line": "Bd3 dxe4 Nxe4 Qxd4 Nf3"},
            {"san": "b5", "severity": "inaccuracy", "tier": "Mastery",
             "why": "Queenside space before development, and it costs six tenths of a pawn. The problem is that it does nothing about the centre: 4.e5 and the pawn on b5 is not attacking anything while White has a free hand — 4...b4 5.Na4 e6 6.Bd2 and the knight on a4 is heading for c5 — a hole you have made permanent, because the b-pawn is past it and the d-pawn can never reach d6.",
             "line": "e5 b4 Na4 e6 Bd2"},
            {"san": "Nf6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Development, and it walks into 4.e5 with tempo. The engine's answer to that is worth quoting because it is so blunt: it retreats the knight all the way home with 4...Ng8, and still rates the position nearly a pawn better for White. The alternative 4...Nfd7 leaves you in a French chain having spent two moves on a knight. Take on e4 first; the knight comes out afterwards and better.",
             "line": "e5 Ng8 Bd3 c5 dxc5"},
        ],

        # ── ply 7 · YOUR fourth move after 4.Nxe4 ───────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4": [
            {"san": "Nd7", "severity": "playable", "tier": "Structure",
             "name": "Smyslov–Karpov Variation",
             "why": "Karpov's system, and a whole repertoire in itself. The knight covers f6 so that ...Ngf6 can be played without the trade 5.Nxf6+ wrecking the structure; the cost is that the c8-bishop stays home for several more moves. It is worth about a seventh of a pawn against 4...Bf5, which is nothing. One thing has to be memorised before you play it: 5.Qe2 Ngf6?? 6.Nd6 is mate.",
             "line": "Bd3 Ngf6 Ng5 e6 N1f3"},
            {"san": "Nf6", "severity": "playable", "tier": "Mastery",
             "name": "Tartakower / Bronstein-Larsen",
             "why": "Black invites 5.Nxf6+ and chooses which pawn recaptures. 5...exf6 is the Tartakower: doubled f-pawns, an open e-file, the bishop free and rapid development — the engine likes it as much as 4...Bf5. 5...gxf6 is the Bronstein-Larsen, a much wilder structure where Black plays for the open g-file and White for the endgame. Both are real; only the first is a repertoire you can rely on.",
             "line": "Nxf6+ exf6 c3 Bd6 Bd3"},
            {"san": "h6", "severity": "playable", "tier": "Mastery",
             "name": "Finnish Variation",
             "why": "The useful little move first, so that ...Bf5 later cannot be met by a knight arriving on g5 or h4 and the bishop always has h7. It costs under a fifth of a pawn and it usually transposes straight back: 5.Nf3 Bf5 6.Ng3 Bh7 and you are in the main line having saved yourself the whole ...Bg6 and h4 discussion.",
             "line": "Nf3 Bf5 Ng3 Bh7 Bd3"},
            {"san": "Bg4", "severity": "blunder", "tier": "Foundation",
             "why": "The wrong diagonal, and it simply drops a piece: 5.Qxg4 and nothing on the board defends g4. The bishop belongs on f5, where it attacks the knight on e4 and is covered by nothing because it does not need to be. This is the one move in the whole variation that loses on the spot, and it is played because f5 and g4 look alike.",
             "line": "Qxg4 e6 Qd1 c5 Nf3"},
        ],

        # ── ply 8 · White's fifth — where the knight goes ────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5": [
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "The knight goes back where it came from rather than to g3. It costs about a third of a pawn and it means White has spent three moves to reach a position where the knight is on its original square and yours is not — but it also keeps the knight off g3, which is where it blocks White's own g-pawn. Answer 5...Nd7 and 6...e6 and treat it as a slower version of the main line.",
             "line": "Nd7 Bd3 Bxd3 Qxd3 e6"},
            {"san": "Nc5", "severity": "playable", "tier": "Plans",
             "why": "The knight jumps at b7 instead of retreating, and the answer is a pawn move you would not otherwise consider: 5...e5! — hitting d4 and opening the f8-bishop before White can do anything with the b-pawn. If White takes anyway, 6.Nxb7 Qb6 7.Nc5 exd4 and White has a pawn and a knight that has been to b7 and back while your pieces are all coming out.",
             "line": "e5 Nxb7 Qb6 Nc5 exd4"},
            {"san": "Ng5", "severity": "inaccuracy", "tier": "Mastery",
             "why": "Straight at f7, and it is premature by about half a pawn — there is nothing on f7 to win while your king still has the whole board. Answer 5...e6, which defends nothing and needs to defend nothing, and let White spend the next two moves bringing the knight home: 6.c3 Nf6 7.Ne2 c5 and the knight has been to g5 and back to e2 while you have completed development.",
             "line": "e6 c3 Nf6 Ne2 c5"},
        ],

        # ── ply 10 · White's sixth ───────────────────────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "Developing before pushing the h-pawn, and it is worth exactly the same as 6.h4 — a hundredth of a pawn apart at depth twenty. It usually transposes: 6...Nd7 7.h4 h6 and you are back in the main line. The one thing to notice is that with the knight already on f3, White's h4–h5 arrives a move sooner, so ...h6 is the move to have ready.",
             "line": "Nd7 h4 h6 Bd3 Bxd3"},
            {"san": "Bc4", "severity": "playable", "tier": "Structure",
             "why": "The bishop takes the a2–g8 diagonal instead of offering itself on d3, which means the trade of light-squared bishops never happens and your bishop on g6 keeps its job. That suits you: 6...e6 7.Nf3 Nd7 8.Qe2 Ngf6 and White has a bishop on a diagonal your own pawn on e6 has just blocked.",
             "line": "e6 Nf3 Nd7 Qe2 Ngf6"},
            {"san": "Nh3", "severity": "playable", "tier": "Plans",
             "why": "The knight goes the odd way round, heading for f4 where it hits g6 and d5. It is sound and it costs a little over a tenth of a pawn. The reply that punishes the plan rather than the move is 6...Nf6, and if 7.Nf4 then 7...e5!, opening the game against a knight that has taken two moves to reach a square a pawn can chase it from.",
             "line": "Nf6 Nf4 e5 Nxg6 hxg6"},
        ],

        # ── ply 11 · YOUR sixth move — why ...h6 is not a slow move ─────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4": [
            {"san": "e6", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Getting on with development, and it costs about a pawn and three quarters — the single most expensive natural move in the whole variation. 7.h5! and the bishop is attacked with h7 occupied by your own pawn, so it has to go to f5 where 8.Nxf5 takes it: 8...Qa5+ 9.Bd2 Qxf5 wins the piece back and leaves your queen on f5 with nothing developed. Spend the move on ...h6 first; it is not a waiting move, it is the retreat square.",
             "line": "h5 Bf5 Nxf5 Qa5+ Bd2 Qxf5"},
            {"san": "Nf6", "severity": "inaccuracy", "tier": "Structure",
             "why": "The same mistake with a different developing move, and it costs a pawn and a half. 7.h5 Be4 is the move — the bishop steps forward instead of back, because on f5 the knight on g3 simply takes it — and after 8.Rh4! the rook attacks the bishop along the fourth rank, which is a square the rook only has because the h-pawn went to h5.",
             "line": "h5 Be4 Rh4 Bd5 c4"},
            {"san": "h5", "severity": "inaccuracy", "tier": "Plans",
             "why": "Stopping the pawn with a pawn, which is the right reflex in the Advance and the wrong one here. It costs two thirds of a pawn, and the reason is the square it gives away: 7.Nh3! heads for f4, where the knight attacks g6 and h5 at the same time. With your pawn still on h7 that knight would have nothing to hit. ...h6 stops h4–h5 just as well and gives nothing back.",
             "line": "Nh3 e5 Be3 Qa5+ c3"},
        ],

        # ── ply 12 · White's seventh ─────────────────────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6": [
            {"san": "h5", "severity": "playable", "tier": "Foundation",
             "why": "Pushing on and taking the square immediately. This is the other main move and it is worth the same as 7.Nf3 to within a couple of hundredths. 7...Bh7 and the bishop sits on h7 for the rest of the opening exactly as it does in the main line — the only difference is that White's pawn on h5 is now fixed, which takes g6 and h6 away from White's own pieces as well as yours.",
             "line": "Bh7 Nf3 Nf6 Bd3 Bxd3"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "Offering the bishop trade a few moves early. Take it — 7...Bxd3 8.Qxd3 e6 — and you have reached the main-line structure without ever having to work out where the bishop was going. It costs White about a tenth of a pawn compared with 7.Nf3, because the knight on g1 is now the piece that still has not moved.",
             "line": "Bxd3 Qxd3 e6 Bd2 Nf6"},
            {"san": "N1e2", "severity": "playable", "tier": "Plans",
             "why": "The second knight heads for f4, doubling up on g6 and d5. It is about two tenths of a pawn behind 7.Nf3 and the reason is time: White now has two knights on the kingside and no development anywhere else. 7...Nf6 8.Nf4 Bh7 and the bishop is on its square with White still needing three moves to castle.",
             "line": "Nf6 Nf4 Bh7 c3 e6"},
        ],

        # ── ply 13 · YOUR seventh move ───────────────────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3": [
            {"san": "Nd7", "severity": "playable", "tier": "Foundation",
             "why": "The other main move, and there is nothing between them — six hundredths of a pawn at depth twenty. The knight comes out first and ...e6 follows; the practical difference is that 8.h5 Bh7 9.Bd3 is then White's most testing set-up, whereas after 7...e6 the knight jumps to e5 first. Both are main lines and both are fine. Pick one and know it.",
             "line": "h5 Bh7 Bd3 Bxd3 Qxd3"},
            {"san": "Nf6", "severity": "playable", "tier": "Structure",
             "why": "Also completely sound — the engine has it level with 7...e6 — and it is worth saying so, because this move is often given a question mark on the grounds that 8.Ne5 is dangerous. It is not: after 8...Bh7 9.Bc4 e6 10.Qe2 Nd5 Black is fine. The real reason to prefer 7...e6 or 7...Nd7 is that they keep the option of putting this knight on f6 later with the other one already on d7.",
             "line": "Ne5 Bh7 Bc4 e6 Qe2"},
            {"san": "Qc7", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The queen comes out before a single minor piece and it costs over two pawns. The refutation is not a trick, it is a tempo count: 8.Ne5 Bh7 9.Bf4 and the queen has to move again, having achieved nothing, while White has two pieces out and a bishop hitting c7 down the b8–h2 diagonal. Develop the knights first; the queen has a good square on c7 and it will still be there in five moves.",
             "line": "Ne5 Bh7 Bf4 Qa5+ Bd2"},
        ],

        # ── ply 14 · White's eighth ──────────────────────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6": [
            {"san": "h5", "severity": "playable", "tier": "Foundation",
             "why": "Fixing the h-pawn before jumping the knight, which is the older treatment and about a tenth of a pawn behind 8.Ne5. It transposes more often than not: 8...Bh7 9.Bd3 Bxd3 10.Qxd3 Nd7 and the only thing that has changed is that White's pawn is on h5 rather than h4, which shuts the h-file for good.",
             "line": "Bh7 Bd3 Bxd3 Qxd3 Nd7"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "The trade offered without the knight going to e5 first. It costs White about a quarter of a pawn, and the reason is worth understanding: with a knight on e5 the bishop trade comes with an attacking piece already in place, and without one it is just a trade. 8...Bxd3 9.Qxd3 Nf6 and you are a move further on than in the main line.",
             "line": "Bxd3 Qxd3 Nf6 Bd2 Nbd7"},
            {"san": "Be2", "severity": "inaccuracy", "tier": "Plans",
             "why": "The modest square, and here it is the wrong one — over half a pawn behind 8.Ne5. On e2 the bishop does not offer the trade, does not take a diagonal, and blocks the queen's own route to e2. Answer 8...Nd7 and then, when White finally plays Bd3, take: 9.Bd3 Bxd3 10.Qxd3 Ngf6 and White has spent two moves putting a bishop on a square it could have reached in one.",
             "line": "Nd7 Bd3 Bxd3 Qxd3 Ngf6"},
        ],

        # ── ply 20 · White's eleventh ────────────────────────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7": [
            {"san": "Qe2", "severity": "playable", "tier": "Structure",
             "why": "The engine's own choice and level with 11.f4 to within four hundredths. The queen steps off the d-file, which is the file your rooks are going to use, and keeps the knight on e5 without committing the f-pawn. It is the more flexible move and the less committal one; against it, 11...Ngf6 12.Bd2 c5 is the standard break and you get a normal game.",
             "line": "Ngf6 Bd2 c5 dxc5 Bxc5"},
            {"san": "Bf4", "severity": "playable", "tier": "Foundation",
             "why": "Developing the last minor piece to its natural square, and it is worth about a tenth of a pawn less than 11.f4. It hands you a trade: 11...Nxe5 12.Bxe5 Qa5+ 13.c3 and the check has forced a pawn onto c3, after which 13...Nf6 completes development. Note what did not happen — the bishop on f4 never got to trade itself for anything, because your dark-squared bishop is still on f8.",
             "line": "Nxe5 Bxe5 Qa5+ c3 Nf6"},
            {"san": "Nxd7", "severity": "playable", "tier": "Structure",
             "why": "White trades the strong knight voluntarily, which costs about three tenths of a pawn — the knight on e5 was the best piece on the board and the one on d7 was not. Recapture with the queen — no bishop of yours can reach d7 anyway. 11...Qxd7 develops and clears d8 for a rook, and after 12.Bf4 Nf6 13.O-O-O Bd6 you are trading again into a position with nothing to attack.",
             "line": "Qxd7 Bf4 Nf6 O-O-O Bd6"},
            {"san": "O-O", "severity": "inaccuracy", "tier": "Plans",
             "why": "Castling short costs White nearly two thirds of a pawn, and the trade is the reason. 11...Nxe5! 12.dxe5 Qxd3 13.cxd3 and the queens are off with White's queenside scattered on a2, b2 and d3 — three healthy pawns of yours against two of White's on that wing, and an endgame you are happy to reach on move thirteen. This is why White spends a move on 11.f4 or 11.Qe2 first.",
             "line": "Nxe5 dxe5 Qxd3 cxd3 Ne7"},
        ],

        # ── ply 21 · YOUR eleventh move — the check, and the alternatives ────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4": [
            {"san": "Be7", "severity": "playable", "tier": "Structure",
             "why": "Developing without the check, and by the engine's count it is actually the best move here — about seven hundredths of a pawn ahead of 11...Bb4+. It sets a small trap of its own: 12.Bd2 Nxe5 13.fxe5 Bxh4! and the pawn is defended by the rook on h1 alone — which cannot take it, because 14.Rxh4 Qxh4 sends your queen down the diagonal the bishop has just cleared and collects the rook. Take the pawn when it is offered.",
             "line": "Bd2 Nxe5 fxe5 Bxh4 O-O-O"},
            {"san": "Ngf6", "severity": "playable", "tier": "Foundation",
             "why": "Completing development in the most natural order, and it costs about four tenths of a pawn against the check-first treatment. The difference is one tempo and one pawn move: White gets to develop the c1-bishop and castle without ever being asked to commit the c-pawn, so c2–c4 stays available in a single move instead of two.",
             "line": "Bd2 Be7 O-O-O O-O Qf3"},
            {"san": "Nxe5", "severity": "playable", "tier": "Plans",
             "why": "Trading the strong knight at once. It is sound and it costs about four tenths of a pawn, because the recapture 12.fxe5 gives White a protected pawn on e5 and the half-open f-file, and you have used your best trade before your pieces were out. Keep the option; it is worth more than the trade.",
             "line": "fxe5 c5 Qb5+ Qd7 Qxd7+"},
        ],

        # ── ply 26 · White's fourteenth, in the deep dive ────────────────────────
        "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4 Bb4+ c3 Be7 Bd2 Ngf6": [
            {"san": "c4", "severity": "playable", "tier": "Structure",
             "why": "White spends the second move on the c-pawn to take d5 and b5 away from your pieces. It is worth the same as castling long to within a tenth of a pawn, and it is the move that shows what 11...Bb4+ bought: White needed two moves to get the pawn where it wanted to be. 14...O-O and get on with it — with the pawn on c4 rather than c3, the d4-pawn has one fewer defender.",
             "line": "O-O Qf3 Qb6 O-O-O Rad8"},
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Castling short instead, into the wing White has just spent three pawn moves loosening. It costs a little under half a pawn and it changes your plan completely: with both kings on the same side there is no race, so break in the centre instead. 14...c5 15.Be3 Qc7 and the game is about d4, not about anybody's king.",
             "line": "c5 Be3 Qc7 Nxd7 Qxd7"},
            {"san": "Ne4", "severity": "inaccuracy", "tier": "Plans",
             "why": "The trade offered one move too early, and it drops the h-pawn with check. 14...Nxe4 15.Qxe4 Bxh4+! — the knight has left g3 and the pawn on f4 has left f2, so the whole e1–h4 diagonal is open at a king that has not castled. 16.Kd1 Nxe5 and you are a clean pawn up with White's king in the middle. Nearly nine tenths of a pawn.",
             "line": "Nxe4 Qxe4 Bxh4+ Kd1 Nxe5"},
        ],

        # ══ ADVANCE VARIATION ════════════════════════════════════════════════════

        # ── ply 5 · YOUR third move against 3.e5 ─────────────────────────────────
        "e4 c6 d4 d5 e5": [
            {"san": "c5", "severity": "playable", "tier": "Mastery",
             "name": "Botvinnik-Carls Defence",
             "why": "The modern fashion, and the engine has it three hundredths of a pawn behind 3...Bf5 — which is to say, identical. Black hits d4 at once and accepts that the c8-bishop may have to wait. The critical test is 4.dxc5, and after 4...Nc6 5.Nf3 Bg4 Black gets the pawn back or better; the quiet 4.Nf3 cxd4 5.Qxd4 is the main line. Play it if you would rather have an open game than a pawn chain.",
             "line": "Nf3 cxd4 Qxd4 Nc6 Qf4"},
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "why": "The move that throws the opening away, and it is not a blunder — about two tenths of a pawn — which is exactly why it is worth a panel. You have now reached a French Advance with a pawn on c6 doing nothing, a bishop on c8 that will never come out, and a ...c5 break that costs two moves instead of one. Everything the Caro-Kann is for was in the bishop, and this move buries it.",
             "line": "c3 c5 Nf3 Nc6 Bd3"},
            {"san": "g6", "severity": "playable", "tier": "Mastery",
             "why": "The Gurgenidze treatment against the Advance: the bishop goes to g7 rather than f5 and Black plays for ...f6 against the head of the chain instead of ...c5 against its base. It costs about a third of a pawn and it is a system rather than a move — you need to know 4.Nc3 f6 and the positions after it, because there is no transposing back.",
             "line": "Nc3 f6 f4 Nh6 Nf3"},
        ],

        # ── ply 6 · White's fourth in the Advance — the whole fork ───────────────
        "e4 c6 d4 d5 e5 Bf5": [
            {"san": "h4", "severity": "playable", "tier": "Foundation",
             "name": "Tal Variation",
             "why": "The most direct assault on the bishop, and it is perfectly sound — a tenth of a pawn behind 4.Nf3. Everything turns on your reply. 4...h5! is the move: it stops h4–h5 dead and the position is level. The automatic 4...e6? is close to losing, because 5.g4! Be4 6.f3 attacks the bishop with the whole board shut and it ends up trading itself for the c2-pawn. Answer a pawn with a pawn.",
             "line": "h5 Bd3 Bxd3 Qxd3 Qa5+"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "name": "van der Wiel Attack",
             "why": "White develops and prepares g2–g4 with the knight already covering e4 and e2, which is the detail that makes it work. It costs about two tenths of a pawn. Meet it with 4...e6 and then answer g4 with ...h5 in the same way: 5.h4 h5 6.Bd3 Bxd3 7.Qxd3 and the bishop has been traded rather than chased, which is all you ever wanted from it.",
             "line": "e6 h4 h5 Bd3 Bxd3"},
            {"san": "g4", "severity": "playable", "tier": "Mastery",
             "name": "Bayonet Attack",
             "why": "The most violent version, and it costs White three tenths of a pawn for one reason: the pawn in front of the king has gone and the king has not castled. The answer is 4...Be4!, stepping into the middle rather than retreating — 5.f3 Bg6 6.e6 fxe6 breaks up your kingside and gives you the extra pawn and the f-file in return, and the engine already prefers Black in a wild position.",
             "line": "Be4 f3 Bg6 e6 fxe6"},
            {"san": "Bd3", "severity": "playable", "tier": "Foundation",
             "why": "The trade offer, and it is the most common move you will meet from a club player. Take it: 4...Bxd3 5.Qxd3 e6 and you have solved the bad bishop by giving it away for White's good one. It costs White two tenths of a pawn, and what it really costs is the whole idea of the Advance — White has no piece left aimed at your kingside.",
             "line": "Bxd3 Qxd3 e6 Nf3 c5"},
            {"san": "c4", "severity": "playable", "tier": "Plans",
             "why": "White hits d5 from the side before developing, hoping to open the position while your king is still at home. It costs a little under two tenths of a pawn. Do not take — 4...dxc4 gives up the centre for a pawn you cannot keep — play 4...e6 and hold the pawn with pieces: 5.Nc3 Ne7 and the knight is heading for f5 or g6 with d5 defended three times.",
             "line": "e6 Nc3 Ne7 h4 h6"},
        ],

        # ── ply 8 · White's fifth ────────────────────────────────────────────────
        "e4 c6 d4 d5 e5 Bf5 Nf3 e6": [
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "why": "Holding d4 with a pawn instead of a piece, which is the French treatment. It costs about an eighth of a pawn and it changes what ...c5 is worth: after 5...c5 6.Be2 Nc6 7.O-O cxd4 8.cxd4 there is a pawn on d4 to attack rather than a knight, so ...Qb6 and ...Nge7–f5 become the plan instead of hitting the knight.",
             "line": "c5 Be2 Nc6 O-O cxd4"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "The trade offered a move later than usual, and it costs about a quarter of a pawn. Take it — 5...Bxd3 6.Qxd3 c5 — and note what White has spent: two moves on a bishop that has been traded for the piece it was chasing, in a structure where your remaining bishop has ...c5 and ...Nc6 to open lines for it.",
             "line": "Bxd3 Qxd3 c5 c3 Nc6"},
            {"san": "Be3", "severity": "playable", "tier": "Plans",
             "why": "Backing up d4 before the bishop on f1 has decided anything. It costs about a quarter of a pawn, and the reason is b2: with the bishop off c1, 5...Qb6 comes with a real threat and White has to spend a move on 6.Qc1 or 6.b3 rather than developing. Take the free tempo, then play ...f6 or ...c5 at leisure.",
             "line": "Qb6 Qc1 f6 Be2 Nd7"},
            {"san": "h4", "severity": "playable", "tier": "Mastery",
             "why": "The Tal idea a move late, and the delay costs almost half a pawn. With the knight committed to f3, the follow-up g2–g4 simply drops a pawn to ...Bxg4 — the knight covers g5 and h4 but not g4, and nothing else does either — so the h-pawn is advancing on its own. Do not chase it; hit the centre. 5...c5 6.c4 cxd4 7.Nxd4 Bxb1! trades the bishop for the piece that has not moved and leaves White's kingside pawns loose.",
             "line": "c5 c4 cxd4 Nxd4 Bxb1"},
        ],

        # ── ply 10 · White's sixth ───────────────────────────────────────────────
        "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5": [
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "why": "The pawn holds d4 and the position becomes an ordinary French Advance with your bishop already outside. It costs a tenth of a pawn against 6.Be3. Play 6...Nc6 and 7...cxd4, and after 8.cxd4 you have a target on d4 rather than a knight to chase — the plan is ...Qb6 and ...Nge7–f5, exactly as in the French.",
             "line": "Nc6 O-O cxd4 cxd4 Nge7"},
            {"san": "O-O", "severity": "playable", "tier": "Structure",
             "why": "Castling first and deciding about d4 afterwards, which is worth about a fourteenth of a pawn less than 6.Be3 and is completely reasonable. It transposes to the c3 lines most of the time: 6...Nc6 7.c3 cxd4 8.cxd4 Nge7 and the structures are the same. Take the free move to finish your own development rather than resolving anything.",
             "line": "Nc6 c3 cxd4 cxd4 Nge7"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Giving up the centre to hold a pawn, and it costs three quarters of a pawn — the engine already prefers Black. Look at what leaves d4: the pawn on e5 was defended twice and is now defended once, by the knight on f3 alone, and after 6...Bxc5 your bishop lands on the a7–g1 diagonal with the square it wanted vacated. 7.c4 Ne7 8.cxd5 Nxd5 and every open line points at White.",
             "line": "Bxc5 c4 Ne7 cxd5 Nxd5"},
        ],

        # ── ply 16 · White's ninth ───────────────────────────────────────────────
        "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 O-O Nbc6": [
            {"san": "c3", "severity": "playable", "tier": "Structure",
             "why": "Solid, and it costs about an eighth of a pawn against the pin. It also loses the pawn on e5, which nothing defends: 9...Nxe5! and White has to work for it — 10.Bb5+ N5c6 11.Qa4 a6 12.Bxc6+ regains the piece pressure but not the pawn. Count the defenders of e5 in this whole variation; the answer is almost always none.",
             "line": "Nxe5 Bb5+ N5c6 Qa4 a6"},
            {"san": "f4", "severity": "playable", "tier": "Plans",
             "why": "Propping up e5 with a pawn, which is the one move that actually defends it — and it costs about a third of a pawn, because the move goes to a pawn rather than to the piece you most want traded. 9...Nxd4! 10.Qxd4 a6 removes White's best-placed piece, and after 11.c3 Bxb1 12.Raxb1 White is left with the two bishops, a pawn front, and not one piece anywhere near your king.",
             "line": "Nxd4 Qxd4 a6 c3 Bxb1"},
            {"san": "Nxc6", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Trading on c6 without the bishop check first, which throws away six tenths of a pawn: recapture 9...Nxc6! with the other knight and the pawn on e5 is attacked and undefended all over again, while your structure stays completely healthy. Take with the knight, not the pawn — 9...bxc6 would repair White's position for nothing.",
             "line": "Nxc6 f4 d4 Bf2 g5"},
            {"san": "Nxf5", "severity": "inaccuracy", "tier": "Structure",
             "why": "White trades off your good bishop, and it costs a whole pawn by the engine's count. The knight that recaptures is better than the bishop that left: from f5 it attacks the bishop on e3 and the d4-square at once, and White has no pawn that can chase it — the e-pawn is fixed on e5 and the g-pawn would have to advance two squares in front of a castled king. 9...Nxf5 10.Bf4 g5! and White is already scrambling.",
             "line": "Nxf5 Bf4 g5 Bd2 Nxe5"},
        ],

        # ── ply 17 · YOUR ninth move — the pin has to be answered ────────────────
        "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 O-O Nbc6 Bb5": [
            {"san": "Rc8", "severity": "playable", "tier": "Structure",
             "why": "Taking the half-open file and adding a defender to the pinned knight. It costs about a quarter of a pawn against 9...a6, and the reason is that it does not put the question: White simply retreats with 10.Ba4 and the pin is still there, so ...a6 has to be played anyway a move later. Ask first, develop second.",
             "line": "Ba4 a6 Nc3 Bg6 Qe2"},
            {"san": "Qd7", "severity": "playable", "tier": "Plans",
             "why": "Unpinning by defending the knight with the queen, which is sound and costs about half a pawn. The problem is the square: White has no d-pawn and you do, so the d-file is the one White's rook wants — and the queen has just put itself on it, directly behind the pawn on d5. 9...a6 solves the pin by removing the bishop instead of by standing on a target.",
             "line": "Ba4 a6 Na3 Be4 c4"},
            {"san": "Ng6", "severity": "blunder", "tier": "Foundation",
             "why": "The knight heads for e5 and forgets that the other one cannot move. 10.Nxc6! and there is no good answer: 10...bxc6 11.Bxc6+ forks the king and the rook on a8, and leaving the knight where it is loses more: 11.Nd4+ is a discovered check the moment White's knight steps off c6, so 10...Qc7 11.Nd4+ Kd8 12.Nxf5 leaves White two pieces up. Deal with a pin before you touch anything else.",
             "line": "Nxc6 Qc7 Nd4+ Kd8 Nxf5"},
        ],

        # ══ EXCHANGE AND PANOV ═══════════════════════════════════════════════════

        # ── ply 6 · White's fourth after 3.exd5 cxd5 ────────────────────────────
        "e4 c6 d4 d5 exd5 cxd5": [
            {"san": "Bd3", "severity": "playable", "tier": "Foundation",
             "name": "Exchange Variation",
             "why": "The quiet half of the Exchange, and by the engine's count it costs White five hundredths of a pawn — nothing. It is also the version most Caro-Kann players have never studied. Count the pawns and you have the whole game: White has three on the queenside to your two, and you have four on the e-, f-, g- and h-files to White's three, because White's e-pawn died on d5. That is a Carlsbad with the colours swapped. The minority attack is yours — ...b5 and ...b4 — and White's play is on the other wing. The structure card is written from the White side of those pawns; read it and reverse it.",
             "line": "Nc6 c3 Qc7 h3 e6",
             "see": "structure#carlsbad"},
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "Development first, keeping both c4 and Bd3 available. It costs under a tenth of a pawn. The move to be ready for is the check: 4...Nf6 5.Bb5+ Bd7 6.Bd3 and White has provoked ...Bd7, which is a slightly worse square for the bishop than f5 — so consider 5...Nc6 as the interposition instead and keep the c8–h3 diagonal for the bishop.",
             "line": "Nf6 Bb5+ Bd7 Bd3 Bg4"},
            {"san": "Bb5+", "severity": "playable", "tier": "Structure",
             "why": "The check before anything else, aimed at making you block with the bishop rather than develop it to f5. Do not block with the bishop: 4...Bd7 is fine because after 5.Be2 you have a free move to play ...Bf5 anyway, and the engine already calls the position level. Two tenths of a pawn, and no lasting harm.",
             "line": "Bd7 Be2 Bf5 Nf3 e6"},
            {"san": "Nc3", "severity": "playable", "tier": "Plans",
             "why": "Development that gives up the c4 break, and it costs about a third of a pawn — with the knight on c3 the c-pawn cannot come to c4 and the whole Panov idea is gone. Answer 4...Nc6 and then 5...Bg4: with no c2–c4 coming, the pin costs you nothing, and 6.h3 Bxf3 7.Qxf3 leaves White with the bishop pair and a loosened kingside while you keep two knights and a centre nobody can hit. The engine already prefers Black.",
             "line": "Nc6 Nf3 Bg4 h3 Bxf3"},
        ],

        # ── ply 7 · YOUR fourth move against the Panov ───────────────────────────
        "e4 c6 d4 d5 exd5 cxd5 c4": [
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "why": "Holding d5 with a pawn straight away. It is sound and costs six hundredths of a pawn, and it transposes into the main line more often than not — 5.Nc3 Nf6 6.Nf3 Bb4 is exactly the position the line above reaches. The one thing you give up is the choice of 4...Nf6 5.Nc3 g6, which is a different game entirely.",
             "line": "Nc3 Nf6 Nf3 Bb4 cxd5"},
            {"san": "g6", "severity": "playable", "tier": "Mastery",
             "why": "The fianchetto answer to the Panov, and it is a real system — about a tenth of a pawn behind 4...Nf6. Black lets White take on d5 and blockades the isolated pawn from the long diagonal instead of from d5. 5.cxd5 Nf6 6.Nc3 Nxd5 7.Qb3 Nb6 and the game is about d4 and c5 rather than about anybody's king.",
             "line": "cxd5 Nf6 Nc3 Nxd5 Qb3"},
            {"san": "Nc6", "severity": "playable", "tier": "Plans",
             "why": "Development that lets White resolve the centre on White's terms, and it costs about a fifth of a pawn. 5.cxd5 Qxd5 and the queen is in the middle of the board with 6.Nf3 and 7.Nc3 coming at it — you will spend the next four moves moving the queen instead of the pieces. Defend d5 with a piece that wants to be there.",
             "line": "cxd5 Qxd5 Nf3 Bg4 Nc3"},
            {"san": "dxc4", "severity": "playable", "tier": "Foundation",
             "why": "Taking the pawn, and you cannot keep it — 5.Bxc4 and White has a free centre, a developed bishop and no isolated pawn to worry about. It costs a quarter of a pawn, which is less than its reputation, and it is still the wrong decision: the whole point of the Panov from Black's side is that White ends up with a weak pawn on d4, and this move takes the weakness away.",
             "line": "Bxc4 Nf6 Nf3 g6 Ne5"},
        ],

        # ── ply 9 · YOUR fifth move ──────────────────────────────────────────────
        "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3": [
            {"san": "Nc6", "severity": "playable", "tier": "Structure",
             "why": "The engine's own first choice here, ahead of 5...e6 by six hundredths of a pawn, and a completely different game: the bishop on c8 stays free and goes to g4, and Black plays against d4 rather than blockading d5. 6.Nf3 Bg4 7.Be3 e6 8.c5 is the critical try, where White grabs space instead of taking the isolated pawn.",
             "line": "Nf3 Bg4 Be3 e6 c5"},
            {"san": "g6", "severity": "playable", "tier": "Mastery",
             "why": "The fianchetto again, and it costs three hundredths of a pawn. The point is that after 6.cxd5 Nxd5 7.Qb3 the queen hits d5 and b7 at once, so you must know 7...Nb6 rather than trying to hold everything. What you get is a bishop on g7 aimed permanently at d4 — the pawn the whole variation is about.",
             "line": "cxd5 Nxd5 Qb3 Nb6 Be3"},
            {"san": "e5", "severity": "blunder", "tier": "Foundation",
             "why": "Striking at the centre in the one position where it drops a pawn and the castling rights: 6.dxe5! d4 7.exf6 dxc3 8.Qxd8+ Kxd8 and the queens come off with your king on d8 and White a clean pawn ahead. The pawn on d5 is pinned to nothing and defending nothing extra — it is the knight on f6 that holds the position together, and this move puts a pawn where the knight needed a retreat.",
             "line": "dxe5 d4 exf6 dxc3 Qxd8+ Kxd8"},
        ],

        # ── ply 10 · White's sixth ───────────────────────────────────────────────
        "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6": [
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "why": "White takes at once and hands you the isolated pawn instead: 6...exd5! and now the pawn on d5 is yours, not White's. That is a different structure and a fair one — you have the isolani's activity and the c8-bishop is free again. It costs White about a tenth of a pawn, and 6...Nxd5 recapturing with the knight is also playable but gives White the freer game.",
             "line": "exd5 Nf3 Nc6 Bb5 Bd6"},
            {"san": "c5", "severity": "playable", "tier": "Structure",
             "why": "White declines the isolated pawn and takes space instead, locking the queenside. It costs a tenth of a pawn. The pawn on c5 is the target now: play 6...Be7 and then ...b6 to hit its base, and remember the check first — 7.Bb5+ Bd7 8.Bxd7+ Qxd7 trades White's best minor piece off for nothing.",
             "line": "Be7 Bb5+ Bd7 Bxd7+ Qxd7"},
            {"san": "Bg5", "severity": "playable", "tier": "Plans",
             "why": "The pin, and it costs White about a third of a pawn because it does nothing about d5 and walks into ...Be7 with tempo. 6...Be7 7.Nf3 O-O and White has to decide what the bishop on g5 was for; taking on f6 gives you the bishop pair and taking on d5 gives you an open e-file at White's king.",
             "line": "Be7 Nf3 O-O Rc1 h6"},
        ],

        # ── ply 12 · White's seventh ─────────────────────────────────────────────
        "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Bb4": [
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "White develops and leaves the tension, which the engine likes marginally better than 7.cxd5. Now taking is right: 7...dxc4! 8.Bxc4 O-O and you reach the same isolated-pawn structure as the main line by another door, with White having spent two moves getting the bishop to c4 and the pin on c3 still on. Put a knight on d5 and the plan card applies unchanged.",
             "line": "dxc4 Bxc4 O-O O-O b6"},
            {"san": "a3", "severity": "playable", "tier": "Plans",
             "why": "Putting the question to the bishop, and it costs about a quarter of a pawn. Take: 7...Bxc3+ 8.bxc3 and White's queenside is broken for the rest of the game — doubled c-pawns with no c-file to compensate. You give up the bishop pair, and in a position with a fixed pawn structure and a permanent target that is a good trade.",
             "line": "Bxc3+ bxc3 O-O Bf4 Nc6"},
            {"san": "Bd2", "severity": "playable", "tier": "Structure",
             "why": "Unpinning without committing the pawn structure, and it is worth about a quarter of a pawn less than the main move. It also asks nothing, so take the free move: 7...O-O and then meet 8.Rc1 with 8...Nc6, keeping the tension on d5 while every one of your pieces comes out. The trade on c3 is worth more later than now.",
             "line": "O-O Rc1 Nc6 a3 Bxc3"},
        ],

        # ── ply 14 · White's eighth ──────────────────────────────────────────────
        "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Bb4 cxd5 Nxd5": [
            {"san": "Qc2", "severity": "playable", "tier": "Structure",
             "why": "The queen takes the c-file and the b1–h7 diagonal, which is where the attack lives in every isolated-pawn position. It costs under a tenth of a pawn. Castle straight into it — 8...O-O — and then remember what the whole structure is about: 9.Bd3 h6 takes g5 and the Bxh7 check away in one move, and after that White's attack has nowhere to arrive.",
             "line": "O-O Bd3 h6 O-O Nc6"},
            {"san": "Qb3", "severity": "playable", "tier": "Plans",
             "why": "The queen hits d5 and eyes b7 — which is not actually attacked, because your own bishop on b4 is standing on the file, and moving it is exactly what White wants. It costs about a quarter of a pawn. 8...Nc6 develops and holds everything, and 9.Bd3 Qb6 then offers the trade: White accepts or retreats, and either way the queen has spent two moves reaching a square it has to leave.",
             "line": "Nc6 Bd3 Qb6 Bd2 Bd6"},
            {"san": "Bd3", "severity": "blunder", "tier": "Foundation",
             "why": "The most natural developing move on the board, and it drops the exchange. 8...Nxc3! 9.bxc3 Bxc3+ 10.Bd2 Bxa1 11.Qxa1 and you have a rook and a pawn for a bishop. The bishop on b4 has been looking down the a5–e1 diagonal at that rook since move six, and the only thing between them was the knight on c3 — take it off and the diagonal is live.",
             "line": "Nxc3 bxc3 Bxc3+ Bd2 Bxa1 Qxa1"},
        ],
    },
    "games": [
        {
            "id": "anand-carlsen-2013",
            "name": "Anand – Carlsen, World Championship, Chennai 2013, game two — the wall",
            "tier": "Foundation",
            "note": "The whole Classical main line, played by the reigning World Champion against the challenger who was about to take the title. The first eighteen moves are the deep dive exactly. Then Carlsen pushes the queenside pawns at White's king, takes the only file he can use, and repeats the position — and the point is not that it was drawn, it is that from move sixteen there was never anything for White to play for.",
            "moves": (
                "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 e6 "
                "Ne5 Bh7 Bd3 Bxd3 Qxd3 Nd7 f4 Bb4+ c3 Be7 Bd2 Ngf6 "
                "O-O-O O-O Ne4 Nxe4 Qxe4 Nxe5 fxe5 Qd5 Qxd5 cxd5 "
                "h5 b5 Rh3 a5 Rf1 Rac8 Rg3 Kh7 Rgf3 Kg8 Rg3 Kh7 Rgf3 Kg8"
            ),
            "notes": {
                18: "The trade that decides everything after it. Both light-squared bishops are now off the board — remember that when White castles queenside on move fourteen and the h-pawn starts looking dangerous.",
                22: "The check. It is worth a tempo and a pawn move, and the deviation panel at this position shows the two alternatives and what they cost.",
                27: "White castles long and sets up the attack: king on c1, rook coming to h1's file, pawns on f4 and h4 with a knight behind them.",
                28: "And Carlsen castles straight into it. The pieces that make this attack work are not on the board: no light-squared bishop, so no Bxh7 and no battery, and the h-file cannot open while the pawn sits on h6.",
                30: "The first of three trades in four moves.",
                32: "The second, and the biggest — the knight that has sat on e5 since move eight comes off for a knight that had not done anything.",
                34: "The third offer, and it comes with a threat: from d5 the queen also looks at a2, which queenside castling left defended by nothing.",
                36: "Eighteen moves, and the position is a wall. Queens off, all four knights off, one dark-squared bishop each, and a centre where no pawn can advance: d4 against d5 and e5 against e6.",
                37: "White fixes the h-pawn. It shuts the h-file for the rest of the game, which is the file White's own rook was standing on.",
                38: "Carlsen starts on the queenside without a moment's thought. His pawns are aimed at a king on c1 and White's are aimed at a corner nobody lives in.",
                41: "White takes the only file there is on that side — the f-pawn was spent recapturing on e5, so this one is half-open.",
                42: "And Black takes the other one. Both c-pawns are gone from the c-file except White's on c3, so this rook is looking straight at the pawn in front of White's king.",
                48: "The position appears for the second time. Neither side can improve it: no pawn in the centre can move, the majorities are on opposite wings, and the bishops are the same colour.",
                50: "Kg8, and the game was drawn here. The engine calls the position exactly 0.00. Carlsen went on to win the match 6½–3½ and take the title — and this was the game where he demonstrated that the Caro-Kann was not going to be the way in.",
            },
        },
        {
            "id": "polgar-adams-1992",
            "name": "Polgar – Adams, Roquebrune rapid 1992 — the isolated pawn falls",
            "tier": "Structure",
            "note": "The Panov line above, move for move, reached by a transposition on move nine. Adams wins the isolated d-pawn on move thirteen and the engine calls the position dead level — which is the whole truth about an isolani. What happens next is what usually happens: the attacking side has to find something within about fifteen moves, and when there is nothing there the pawn starts to count.",
            "moves": (
                "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Bb4 cxd5 Nxd5 "
                "Bd2 Nc6 Bd3 Be7 O-O O-O Rc1 Ndb4 Bb1 Nxd4 Nxd4 Qxd4 "
                "Qe2 Nc6 Nb5 Qe5 Qd3 Qh5 Be3 Rd8 Qb3 a6 Nc7 Bd6 f4 Bxc7 "
                "Rf3 f5 Rg3 Qf7 Bb6 Bxb6+ Qxb6 Bd7 Qxb7 Nd4"
            ),
            "notes": {
                18: "Adams develops the bishop before castling and Polgar castles a move later than the line above does. After ten moves the two boards are identical — worth knowing, because your opponent may reach this position by either order.",
                21: "White takes the open c-file, which is exactly what the plan card tells you to do first, and it costs two tenths of a pawn against 11.Qe2. That is the isolani in one move: the file and the attack both need the tempo and there is only one.",
                22: "The order is the whole point. The knight steps off d5 attacking the bishop on d3, so it comes with tempo — and taking on d4 first instead is worth four tenths of a pawn less, because 13.Nxd5 comes with it and 13...exd5 leaves you with an isolated pawn of your own.",
                24: "And the pawn goes. Count d4: attacked by the knight on c6, defended by the knight on f3 — and not by the queen on d1, because White's own bishop on d2 is standing between them. That is why the bishop usually belongs on g5 or f4 in this structure.",
                26: "Black is a pawn up and the engine calls the position exactly level. Both halves of that sentence are true, and together they are the isolani: the weakness has been collected and the activity has to be worth something now or never.",
                31: "The first drift. Three quarters of a pawn, and the queen has now moved three times without creating a threat.",
                33: "And a pawn and a half. White has spent four of the last five moves on the queen and the bishop; Black has spent them finishing development.",
                37: "The losing move. It attacks the rook on a8 and the pawn on e6 at once, and 19...Bd6! answers both: the bishop hits the knight and lands on the b8–h2 diagonal behind the queen on h5, so 20.Nxa8 is mate in one to 20...Qxh2. Polgar had to block with 20.f4 and let the knight go. Four pawns in a single move, by the engine's count.",
                41: "The rook heads for g3 and one last try at the king, a whole piece down.",
                50: "Nd4, and ...Ne2+ next would fork the king on g1 and the rook on c1. The engine calls the position more than six pawns for Black; the game was scored 0–1 here.",
            },
        },
    ],
    "progression": {
        "arc": "The Caro-Kann is the French with the main problem removed. It costs you a tempo and buys you a lifetime of healthy positions.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Learn the one rule that defines the whole opening.",
                "learn": [
                    "The rule: develop the light-squared bishop before playing ...e6. Break it and you have a worse French.",
                    "White's four doors on move three: 3.Nc3 and 3.Nd2 (Classical), 3.e5 (Advance), 3.exd5 (Exchange and Panov), plus 3.f3 (Fantasy) as a surprise.",
                    "The mate you must know: 1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6?? 6.Nd6#.",
                ],
                "drill": "Play the Classical twenty times, focusing only on getting ...Bf5, ...h6, ...e6 and ...Nd7 in the right order.",
                "mistake": "Playing ...Bf5 without checking what attacks it. In the Advance after 4.h4 it needs ...h5 immediately, and after 4.Nc3 White is coming with g4 next.",
                "ready": "You never lock the bishop in behind ...e6.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Learn to be slightly worse and completely safe.",
                "learn": [
                    "In the Classical, count the position rather than looking at it: material level, three pawns a side on each wing, no weakness anywhere, White a pawn further forward in the centre.",
                    "In the Advance the plan is the French plan — ...c5 at the base of the chain — with your bishop already outside and the break one tempo slower.",
                    "In the Panov you face an isolated queen's pawn from the defending side. Blockade d5 with a knight, take the open c-file, trade queens.",
                ],
                "drill": "Play the Classical to move twenty and stop. Count your weaknesses. If the answer is zero, you played it correctly.",
                "mistake": "Trying to equalise with an early ...c5 in the Classical. Finish developing; the break is a reward, not an opening move.",
                "ready": "You can explain why a slightly cramped position with no weaknesses is worth having.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Play for a win, not just a draw.",
                "learn": [
                    "Where to castle in the Classical, and why short is usually right even against O-O-O: with the light-squared bishops traded, White's attack has no piece behind the pawns.",
                    "The ...c5 and ...Nxe5 trades that end an attack before it starts — the deep dive is three of them in four moves.",
                    "Playing against the isolated queen's pawn: blockade, trade, then win the pawn in the ending. The same structure turns up in the Tarrasch French, the Nimzo and the Queen's Gambit Accepted.",
                ],
                "drill": "Study ten isolated-queen's-pawn games from the blockading side, and write down in each one the move where the attack ran out.",
                "mistake": "Playing for a draw. The solidity is a platform for grinding out endgames, not a shell to sit in.",
                "ready": "You have won a Caro-Kann endgame from a position you would once have called equal.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Cover every White try and refine the endgames.",
                "learn": [
                    "The 4...Nd7 and 4...Nf6 systems in the Classical, which are whole repertoires of their own, and the 3...c5 Botvinnik-Carls against the Advance.",
                    "The Fantasy Variation 3.f3, the Two Knights 2.Nf3 and the Accelerated Panov 2.c4 — none of them refutes anything and all of them win games against unprepared opponents.",
                    "Endgames with three pawns a side on each wing. This is where Caro-Kann players actually score their points, and nobody studies them.",
                ],
                "drill": "Write a one-line answer to each of White's second moves and each of White's third moves. If any line is blank, that is your next study session.",
                "mistake": "Assuming every White player will enter the Classical. Below master level, most will not.",
                "ready": "You have a written answer to every White second and third move.",
            },
        ],
        "study": "Anatoly Karpov's Caro-Kann games are the model of risk-free winning. Viswanathan Anand played it against Nepomniachtchi in 2023 and Magnus Carlsen used it in game two of the 2013 World Championship match — the deep dive above.",
        "next": "Add the French as a sharper alternative — the ideas transfer almost completely — or go the other way and learn the Sicilian when you want to unbalance the game from move one.",
    },
}
