OPENING = {
    "id": "catalan",
    "name": "Catalan Opening",
    "eco": "E00–E09",
    "section": "white-d4",
    "orientation": "white",
    "tagline": "d4 and c4 plus a fianchettoed bishop. Positional pressure that lasts into the endgame.",
    "level": "Advanced → World Championship",
    "theory": {
        "big_idea": "White combines the Queen's Gambit pawns (d4, c4) with a king's-Indian style fianchetto (g3, Bg2). The bishop on g2 — the 'Catalan bishop' — fires down the long diagonal at b7, d5 and c6 and it never stops. White is often willing to give up the c4-pawn for a while, because the resulting pressure and the eventual recovery of the pawn is worth more than the material. Games are decided in the endgame, when the Catalan bishop is still the best piece on the board.",
        "structure": "White pawns on d4 and (temporarily) c4, with the fianchetto on g3. Black usually plays ...d5 and ...e6. The critical structural question is whether Black takes on c4 (Open Catalan, sharp) or holds with ...c6/...Nbd7 (Closed Catalan, cramped but solid).",
        "white_plans": [
            "Regain the c4-pawn with Qa4/Qc2 and Ne5, keeping the bishop's diagonal open.",
            "Push e2–e4 to gain the full centre once Black's pieces are tied down.",
            "Play a4 to stop ...b5, then invade on c6 or the c-file.",
            "Trade queens and grind: the Catalan bishop is at its most powerful in endgames.",
        ],
        "black_plans": [
            "Take on c4 and try to hold with ...a6 and ...b5, gaining queenside space.",
            "Block the diagonal with ...c6 and ...b5, or neutralise it directly with ...Bb7 and ...Be4.",
            "The freeing break ...c5 or ...e5, the standard antidotes to a space disadvantage.",
            "Play ...Bb4+ early to provoke Bd2 and gain time for ...dxc4 and ...a6/...b5.",
        ],
        "traps": [
            "Trying to hold the pawn with ...b5 and ...c6 often collapses to a well-timed a4 or Ne5 hitting c6 and b5 at once.",
            "Black's ...Bb4+ lines must be met with Bd2 (not Nc3, which blocks the bishop's support of the c-pawn recovery).",
            "Never let the g2-bishop get shut in permanently — if Black plays ...c6 and ...b5, look for e4 or a4 immediately.",
        ],
        "who": "Play this if you enjoy positions where you have no risk of losing and endless small chances to win. Kramnik, Anand, Ding and Carlsen have all used it as a main weapon.",
    },
    "lines": [
        {
            "name": "Open Catalan — Main Line",
            "note": "Black grabs the pawn on c4 and tries to hold it with ...a6 and ...b5. White regains it with a lasting edge.",
            "moves": "d4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3 O-O O-O dxc4 Qc2 a6 Qxc4 b5 Qc2 Bb7 Bd2 Be4 Qc1",
            "notes": {
                4: "Black prepares ...d5 and keeps the Nimzo-Indian option open.",
                5: "The Catalan move. White prepares to fianchetto instead of playing Nc3, so that the g2-bishop can pressure the queenside forever.",
                6: "Black takes the classical centre.",
                7: "The Catalan bishop takes its post. From here it eyes d5, c6, b7 and a8 for the entire game.",
                8: "Development.",
                9: "Development, adding pressure to d5 and preparing to castle.",
                10: "King safety.",
                11: "King safety.",
                12: "The Open Catalan. Black grabs the pawn — this is the critical test, because holding it costs Black time.",
                13: "The queen heads for c4 to regain the pawn while keeping the bishop's diagonal clear. (The alternative 7.Ne5 is also strong.)",
                14: "Black prepares ...b5 to keep the extra pawn.",
                15: "Regaining the pawn just in time.",
                16: "Now Black kicks the queen and gains queenside space. Material is level and the structural fight begins.",
                17: "The queen steps back and eyes the c-file and the b1–h7 diagonal.",
                18: "Black challenges the Catalan bishop on its own diagonal — the standard antidote.",
                19: "Developing and preparing a4 to attack the b5-pawn, the base of Black's queenside chain.",
                20: "Black offers the trade of the powerful bishops.",
                21: "White sidesteps and keeps the bishop. The game continues with a4, Bc3 and Nbd2, with a small but very durable edge.",
            },
        },
        {
            "name": "Closed Catalan",
            "note": "Black keeps the tension with ...c6 and ...Nbd7. Cramped but extremely solid — a genuine grinding battle.",
            "moves": "d4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3 O-O O-O Nbd7 Qc2 c6 Nbd2 b6 e4 Bb7 b3 Rc8",
            "notes": {
                12: "Black declines to take on c4 and instead builds a solid wall. The knight supports both e5 and c5 breaks.",
                13: "Supporting e4 and eyeing the c-file.",
                14: "The defining Closed Catalan move. Black blocks the g2-bishop's diagonal with a pawn. It is passive but very hard to break.",
                15: "The knight goes to d2 rather than c3 so it does not block the c-pawn and can support e4.",
                16: "Black prepares ...Bb7 or ...Ba6 to finally develop the problem bishop.",
                17: "The big break. White seizes the full centre while Black is still untangling. This is the Closed Catalan's central point: if White gets in e4 under good circumstances, White is simply better.",
                18: "Black develops behind the wall.",
                19: "Solidifying c4 so the centre cannot be undermined.",
                20: "Black prepares the ...c5 break, the only real way to free the position. White stands better with more space and the bishop pair pointing at Black's king.",
                5: "The Catalan move. Instead of Nc3, White prepares the fianchetto so the g2-bishop can pressure the queenside for the rest of the game.",
                6: "Black takes the classical centre.",
                7: "The Catalan bishop takes its post. From here it eyes d5, c6, b7 and a8 — permanently.",
                8: "Development.",
                9: "Development, adding pressure to d5.",
                10: "King safety.",
                11: "King safety. Now Black must decide: take on c4 (Open) or hold the centre (Closed).",
            },
        },
        {
            "name": "Fianchetto Benoni (Anti-Catalan ...c5)",
            "note": "How the Catalan handles an early ...c5. The position becomes a Benoni where White's fianchetto is ideally placed.",
            "moves": "d4 Nf6 c4 e6 g3 c5 d5 exd5 cxd5 d6 Nc3 g6 Bg2 Bg7 Nf3 O-O O-O Re8 Nd2 Na6 h3",
            "notes": {
                6: "Black strikes at the centre immediately rather than allowing a Catalan structure.",
                7: "White pushes past and grabs a space advantage. This is a Benoni structure: White has pawns on c4 and d5 against Black's on d6 and e-file open.",
                8: "Forced.",
                9: "Now the pawn chain c4–d5 is set. White has extra space, Black has the half-open e-file and a queenside majority.",
                10: "Black takes the standard Benoni setup.",
                11: "Development.",
                12: "The fianchetto is exactly what White wants against a Benoni — the bishop supports e4 and covers the long diagonal from a safe distance.",
                13: "Black's bishop faces White's on the long diagonal.",
                14: "Development.",
                15: "Development.",
                16: "King safety.",
                17: "King safety.",
                18: "The rook eyes the e-file, where the action will be.",
                19: "The knight redeploys toward c4, the ideal square in a Benoni, hitting d6 and b6.",
                20: "Black brings the last knight into play, heading for c7 and b5.",
                21: "Useful prophylaxis. White stands slightly better with more space and a clear plan of Nc4, a4 and Rb1 with queenside pressure.",
                5: "The Catalan setup. White fianchettoes before committing the queen's knight.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Catalan squeeze",
        "note": "Nothing dramatic happens. That is the point. Watch a4 undermine the queenside and the g2-bishop wait.",
        "moves": "d4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3 O-O O-O dxc4 Qc2 a6 Qxc4 b5 Qc2 Bb7 Bd2 Be4 Qc1 Nbd7 Bf4 Rc8 Nbd2 Bb7 a4 c5 axb5 axb5 Ra7 Qb6 Nb3",
        "notes": {
            22: "Development. The knight supports c5 and e5, the two breaks Black needs.",
            23: "The bishop finds a better diagonal, eyeing c7 and the queenside dark squares.",
            24: "Black prepares the freeing ...c5 and contests the c-file before White gets there.",
            25: "The knight develops to d2 rather than c3 — from there it goes to b3 hitting c5 and a5, or to e5 supporting the kingside.",
            26: "The bishop steps back to b7. Black has spent moves neutralising the Catalan bishop; that is time not spent on ...c5.",
            27: "The key Catalan move. It attacks b5, the base of Black's entire queenside pawn chain. If b5 falls, so does everything behind it.",
            28: "Black breaks at last, and only just in time.",
            29: "White resolves the tension favourably.",
            30: "Forced.",
            31: "The rook invades on the seventh. The a-file opened because of a4, and now White's most passive piece is the most active on the board.",
            32: "Black defends and offers a queen trade.",
            33: "The knight comes to b3, hitting c5 and eyeing a5 — a third piece joining the queenside pressure. White is not winning here, and probably never will be by force. But Black has to be accurate for another thirty moves, and White does not. That asymmetry is the Catalan's entire value.",
        },
    },
    "progression": {
        "arc": "The Catalan is a long game. You accept a tiny edge on move ten and you are still pressing on move sixty. It rewards patience more than any other opening.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to three",
                "goal": "Get the setup right and know how to recover the c4-pawn.",
                "learn": [
                    "The setup: d4, c4, g3, Bg2, Nf3, O-O. The order matters mostly for avoiding the Nimzo-Indian.",
                    "The two pawn-recovery methods after ...dxc4: Qa4+/Qc2–xc4, and Ne5 hitting c6 and c4 at once.",
                    "Why Bd2 rather than Nc3 against ...Bb4+ — the knight would block your own c-file pressure.",
                ],
                "drill": "Play ten games where Black takes on c4 and hold yourself to recovering it within six moves.",
                "mistake": "Chasing the pawn immediately with a4 and Na3. Development and the bishop's diagonal are worth more than the pawn for several moves.",
                "ready": "You are comfortable being a pawn down for five or six moves.",
            },
            {
                "tier": "Structure",
                "when": "Months one to two",
                "goal": "Understand what the g2-bishop is actually doing.",
                "learn": [
                    "The long diagonal a8–h1 and the three squares that matter on it: d5, c6, b7.",
                    "Open Catalan (Black takes on c4) versus Closed (Black holds with ...c6) — completely different games.",
                    "Why ...c6 is annoying: it blocks the diagonal with a pawn, so your answer is the e4 break.",
                ],
                "drill": "Set up the Closed Catalan and play only for the e4 break. Ten games. Notice how much better your position is once it lands.",
                "mistake": "Letting the g2-bishop stay blocked. If you cannot play e4 or a4, you have no advantage at all.",
                "ready": "You can look at a Catalan and say in one sentence what your bishop is doing.",
            },
            {
                "tier": "Plans",
                "when": "Months two to six",
                "goal": "Learn the squeeze.",
                "learn": [
                    "a4 against the b5-pawn — undermining the base of Black's queenside chain is the standard method.",
                    "Ne5 and Nd2–c4 or Nd2–b3, piling onto c5, c6 and a5.",
                    "The queen trade. The Catalan bishop is stronger in the endgame than the middlegame — trading queens is often an improvement.",
                ],
                "drill": "Take twenty Catalan games by Kramnik and note the move on which he trades queens. It is almost never a concession.",
                "mistake": "Looking for a kingside attack. The Catalan wins on the queenside and in the endgame.",
                "ready": "You have converted a Catalan endgame where your only advantage was the bishop.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Handle everything Black tries to avoid it.",
                "learn": [
                    "The ...c5 lines that steer into a fianchetto Benoni — a different but equally good game for White.",
                    "The Bogo-Indian (...Bb4+) and Queen's Indian (...b6) move orders.",
                    "Open Catalan theory with ...a6 and ...b5 — this is the main line and it is genuinely deep.",
                ],
                "drill": "Prepare a line against 3...c5 and 3...Bb4+ before you play the Catalan in a serious game.",
                "mistake": "Playing g3 too early and allowing a favourable Nimzo-Indian move order. Know why you chose 3.g3 over 3.Nf3.",
                "ready": "Every Black third move has a prepared answer.",
            },
        ],
        "study": "Vladimir Kramnik made the Catalan a world-championship weapon; Ding Liren, Anish Giri and Fabiano Caruana all use it as a main line today.",
        "next": "Pair it with the Queen's Gambit Exchange. Between them you can steer almost any 1.d4 game into a structure you understand better than your opponent.",
    },
}
