OPENING = {
    "id": "french",
    "name": "French Defence",
    "eco": "C00–C19",
    "section": "black-e4",
    "orientation": "black",
    "tagline": "A pawn chain, a bad bishop, and a devastating counterattack. Black chooses structure over freedom.",
    "level": "Beginner → Grandmaster",
    "theory": {
        "big_idea": "1...e6 prepares ...d5 with pawn support. Black accepts one real problem — the c8-bishop is locked behind the e6-pawn — in exchange for a rock-solid pawn chain and a very clear plan: attack the base of White's chain with ...c5 and ...f6. The French is the most 'plan-driven' opening in chess. You know from move three exactly what you are doing for the next twenty-five moves.",
        "structure": "The classic French chain: White pawns d4–e5, Black pawns d5–e6. A pawn chain is attacked at its base, so Black plays ...c5 (hitting d4) and later ...f6 (hitting e5). White defends with c3 and f4 and tries to exploit the extra kingside space. Almost every French middlegame is about these two breaks.",
        "white_plans": [
            "Advance Variation (3.e5): grab space, defend d4 with c3 and Nf3, then attack on the kingside with Bd3, Ne2 and the g- and h-pawns.",
            "Winawer (3.Nc3 Bb4 4.e5): accept doubled c-pawns for the bishop pair and an immediate Qg4 hitting g7, which after ...Bxc3+ nothing defends.",
            "Tarrasch (3.Nd2): avoid the pin, keep the structure clean and play for an isolated-queen's-pawn edge.",
            "Exchange (3.exd5): kill the tension before it exists. Symmetrical, and much less drawish than its reputation once one side castles the other way.",
        ],
        "black_plans": [
            "Hit the base of the chain with ...c5, then ...Nc6 and ...Qb6 piling on d4. In the Advance main line d4 ends up attacked three times, and White has to spend four moves keeping the count level.",
            "Undermine the front of the chain with ...f6 once your king has chosen a wing — the file it opens runs at whoever is standing on it.",
            "Solve the bad bishop: ...b6 and ...Ba6, or ...Bd7–b5, or ...Bd7–e8–h5. In the Tarrasch and the Exchange the problem never arises, because the e6-pawn leaves.",
            "In the Winawer, target White's doubled c-pawns and the dark squares with ...Qa5, ...Qc7 and a rook on the c-file.",
        ],
        "traps": [
            "The Advance b2 trap: after 1.e4 e6 2.d4 d5 3.e5 c5 4.c3 Nc6 5.Nf3 Qb6 6.a3 Nh6, the natural 7.Bxh6? loses a pawn to 7...Qxb2! — the bishop on c1 was the only thing defending b2, and it has just left.",
            "The Poisoned Pawn c3 trap: after 7.Qg4 Qc7 8.Qxg7 Rg8 9.Qxh7 cxd4 White must play 10.Ne2, the one move that guards c3. 10.Nf3? and 10.cxd4? both lose to ...Qxc3+ and ...Qc3+, picking up the rook on a1.",
            "The Milner-Barry Gambit (Advance, 6.Bd3 cxd4 7.cxd4 Bd7 8.O-O Nxd4 9.Nxd4 Qxd4 10.Nc3) — two pawns for a raging attack. Know how to decline it before you decide to take it.",
        ],
        "who": "Play this if you like clear structural plans, you do not mind a cramped position, and you want to punish White for over-extending. The French wins more games by counterattack than any other defence.",
    },
    "lines": [
        {
            "name": "Advance Variation — Main Line",
            "note": "White grabs space, Black attacks the base of the chain. The purest illustration of pawn-chain strategy in chess.",
            "moves": "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "structure": 'french-chain',
                "tier": "Foundation",
                "point": "Ten moves, and every one of them was about a single square. d4 is attacked by the knight on c6, the knight on f5 and the queen on b6, and defended by the knight on f3, the queen on d1 and the bishop on b2 — three against three, which is exactly why 10.g4 had to be played. The only way White can improve that count is to take one of your attackers off f5, and the only way to do that is with a pawn from in front of the king.",
                "next": [
                    "10...Nfe7 and then ...Ng6: from g6 the knight hits e5 and covers f4 and h4, which are the three squares White's attack needs. That is the deep dive, and it starts here.",
                    "...Rc8 is free. Both c-pawns died on d4, so the c-file is fully open and it is the only open file on the board — take it before White plays Rc1.",
                    "The second break is ...f6, and it waits for your king. It opens the f-file at whoever is standing on it, so castle queenside first, then play it.",
                ],
                "endgame": "Count the pawns: two, two and three a side, so nobody has a majority anywhere and there is no passer to make. What decides it is the bishops. White's on b2 stares down a long diagonal that White's own pawn on d4 blocks, and yours on d7 has the whole c6–a4 diagonal waiting for it the moment the knight standing on c6 moves. Keep that comparison alive through the trades and the endgame is yours to press.",
            },
            "notes": {
                3: "White takes the centre.",
                4: "Now Black challenges it with full pawn support — the point of 1...e6.",
                5: "The Advance Variation. White grabs maximum space and locks the centre. Black's c8-bishop is now definitively the 'bad' bishop.",
                6: "Immediately. A pawn chain is attacked at its base, and d4 is the base of White's chain.",
                7: "Defending d4 with a pawn. Now the whole game is a fight over this one square.",
                8: "A second attacker on d4.",
                9: "The third defender. The pawn on c3 and the queen on d1 already hold d4; this adds the knight, and now the square is held three times and hit twice.",
                10: "The key French move, and it is not about b2 yet — b2 is still guarded by the bishop on c1. It is the third attacker on d4, and it means White can never defend d4 with a piece for free: the b1-knight cannot reach c3, and the c1-bishop can only get to e3 or d2 by leaving b2 loose behind it.",
                11: "White prepares b4. It takes queenside space, and the b-pawn stepping off b2 does two things at once: it clears the long diagonal for the bishop, and it removes the pawn that ...Qxb2 was ever going to take.",
                12: "Ugly and correct. The knight is going to f5, where it becomes a third attacker on d4. It could get there from e7 too — but on e7 it shuts the f8-bishop in while it waits, and on h6 it does not. And it sets a trap, because b2 has exactly one defender: 7.Bxh6? runs into 7...Qxb2.",
                13: "White declines the bait in the simplest way there is: once the pawn has gone to b4 there is nothing on b2 to take. It also takes queenside space and opens the diagonal the bishop needs to back up d4.",
                14: "Now the tension is worth releasing. Whatever White recaptures with, the knight on c6 and the queen on b6 are already hitting d4, and the knight on h6 is one move from making it three.",
                15: "The pawn recapture, and it is the only one that leaves a pawn on d4: 8.Nxd4 Nxd4 9.cxd4 arrives at the same thing a tempo later, and 8.Qxd4? loses the queen to ...Nxd4.",
                16: "The knight lands on f5. Three attackers on d4 against two defenders, which is why White's next four moves are all about that square.",
                17: "The bishop finally develops, guarding b2 and backing up d4 along the a1–h8 diagonal. It is also now blocked by its own pawn on d4 — that is the price.",
                18: "Black develops the bad bishop toward b5 and a4. Its own knight on c6 is in the way for now — and that knight has plenty of places to go, which is exactly what makes this the right square rather than a pretty one.",
                19: "White chases the knight off f5 with the only unit that attacks it, rather than trading it with Bd3. It gains space, and it spends the pawn cover in front of a king that has not castled yet. Both sides now have a real game: White on the kingside, Black on the c-file and at d4.",
            },
        },
        {
            "name": "Winawer — Poisoned Pawn",
            "note": "The sharpest line in the French. Black gives White the bishop pair and two kingside pawns; White gets an attack and a queen with no way home.",
            "moves": "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 Qc7 Qxg7 Rg8 Qxh7 cxd4 Ne2 Nbc6",
            "tier": "Mastery",
            "drill": True,
            "plan": {
                "tier": "Mastery",
                "point": "Do the arithmetic before the fear sets in. You gave up g7 and h7 and took d4, so you are one pawn down, not two: seven white pawns against six. What it bought is a rook already on the g-file, a pawn on d4 hitting the doubled c-pawns, and a white queen on h7 that not one white piece defends.",
                "next": [
                    "11.f4 Bd7 is the main road, and the bishop is going to b5 to trade itself for the one on f1 — the piece that has to move before White's king can castle at all.",
                    "...O-O-O, always, and early. Your king walks away from the file White's queen is on, and the rook on g8 stays where it is: the g-file is what the two pawns bought.",
                    "The two d-pawns are a battering ram, not a weakness. ...dxc3 takes one of the doubled pawns off and ...d4 comes again behind it — that is the plan Korchnoi used against Spassky in the model game.",
                ],
                "endgame": "This is not a line to trade into, and the pawns say why: White has three on the kingside to your one, which makes a passed pawn by force, and three on two files against your two on the queenside, which does not. With the bishop pair on top of that, every exchange helps White. Play for the initiative or do not play the line.",
            },
            "notes": {
                5: "White develops and defends e4 with a piece rather than pushing past.",
                6: "The Winawer. Black pins the knight, so e4 is attacked twice and defended once.",
                7: "White pushes past and gains space, unpinning at the cost of committing the centre.",
                8: "The standard break at the base of the chain.",
                9: "Putting the question to the bishop.",
                10: "Black takes, permanently damaging White's structure. White will have doubled c-pawns for the rest of the game.",
                11: "Forced in practice. The check has to be answered, and the other ways of answering it — 6.Bd2 and 6.Qd2 — undevelop White and give Black the trade for free. Taking is what buys the bishop pair and the open b-file.",
                12: "Not 6...Nc6, which walks into 7.Qg4 with the g-pawn still needing defence and no good way to give it. On e7 the knight covers f5 and g6 and, more to the point, it clears g8 so that after Qxg7 the rook arrives on the g-file with tempo.",
                13: "The critical move. g7 is attacked and nothing defends it — the bishop that used to has been traded on c3.",
                14: "The Poisoned Pawn. Black ignores g7 and puts the queen on the diagonal that watches e5, ready to swing to c3 the moment the c5-pawn moves — and dares White to spend three moves eating on the wrong side of the board.",
                15: "White takes.",
                16: "The rook comes to the half-open g-file attacking the queen. That tempo is what the pawn was sold for.",
                17: "A second pawn — and three of White's first nine moves have now been queen moves to the same corner of the board.",
                18: "Black cashes in: the pawn count comes back to seven against six and the new pawn on d4 attacks c3.",
                19: "The only move, and the reason this line is playable for White at all: from e2 the knight guards c3. 10.Nf3? and 10.cxd4? both lose the exchange to a queen check on c3 — the deviation panel walks through both.",
                20: "Black develops the last knight, defending d4 and hitting e5. One of the most analysed positions in chess: engines call it about half a pawn for White, humans call it chaos.",
            },
        },
        {
            "name": "Tarrasch Variation",
            "note": "White's modern, low-risk answer. Nd2 avoids the pin at the cost of a passive knight; in return Black usually ends up with an isolated pawn.",
            "moves": "e4 e6 d4 d5 Nd2 c5 exd5 exd5 Ngf3 Nc6 Bb5 Bd6 O-O Nge7 dxc5 Bxc5 Nb3 Bd6 Re1",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "This is the one variation where the French costs you nothing at all up front: after 4.exd5 exd5 the c8-bishop has the whole c8–h3 diagonal for the first time in the opening. The bill arrives on move seven. 7.dxc5 leaves you an isolated pawn on d5, and from here every plan on the board is about that pawn.",
                "next": [
                    "9...O-O first, and without thinking. The rook on e1 is looking down the open e-file at your knight on e7 with your king directly behind it.",
                    "...Bg4 and ...Qd7, then a rook to e8. An isolated pawn is an engine in the middlegame and a liability in the endgame, so your pieces come out fast and you play for the attack, not for the pawn.",
                    "The break is ...d4. It is not a pawn push, it is the move that stops the pawn being weak — time it for a moment when White's blockading knight has left d4 and the pawn cannot simply be rounded up.",
                ],
                "endgame": "Count the wings and the bargain is obvious: White has three pawns to two on the queenside, three against three on the kingside, and your sixth pawn is the isolated one on d5. White's majority makes a passer; your d-pawn makes nothing. So White wants every trade and you want none of them — refuse the queens, and only trade a piece when the piece you take is the one blockading d5.",
            },
            "notes": {
                5: "The Tarrasch. The knight blocks its own bishop, but it sidesteps the Winawer pin entirely and keeps White's structure pristine.",
                6: "The most active reply, hitting d4 at once. The alternative 3...Nf6 leads to a completely different, closed game where White plays e5 and Black spends ten moves untangling.",
                7: "White resolves the tension and heads for an isolated-pawn structure.",
                8: "Recapturing with the pawn opens the c8–h3 diagonal, which is the French's oldest problem solved in one move. That is why the Tarrasch is annoying rather than frightening — and why the isolated pawn you are about to get is a price worth paying.",
                9: "Development, and the knight on f3 already eyes the square in front of your future isolated pawn.",
                10: "Development, hitting d4.",
                11: "Pinning the knight against the king down the a4–e8 diagonal. That knight is the only piece Black has attacking d4, so White would like it traded or tied down before the pawn structure is settled.",
                12: "Active development. The bishop takes the b8–h2 diagonal, which is empty all the way to h2.",
                13: "King safety.",
                14: "Development, defending c6 and unpinning by preparing to castle.",
                15: "White gives Black the isolated d-pawn. Now the structure is fixed and both plans are set.",
                16: "Black recaptures with the bishop and gains a tempo on the way, because the bishop has to be dealt with.",
                17: "Hitting the bishop and heading for d4 — the blockading square in front of the isolani.",
                18: "The bishop returns to its best diagonal rather than to a square where a knight can hit it again.",
                19: "The rook takes the open e-file. Both e-pawns are gone, so the file is genuinely open, and White's rook is looking straight at the knight on e7 with the black king behind it. Castle. This structure appears in the Panov Caro-Kann, the Queen's Gambit Accepted and the Nimzo — learning it once pays out four times.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the French counterattack",
        "note": "White expands on the kingside, Black castles into the safer wing and gets on with the c-file. Seventeen moves in, White's king still has nowhere to go.",
        "moves": "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4 Nfe7 Nc3 Ng6 h4 h5 g5 Be7 Bd3 O-O-O Na4 Qc7 Rc1 Kb8 Qd2",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "structure": 'french-chain',
            "tier": "Plans",
            "point": "Seventeen moves and White's king is still on e1 — and it is stuck there. The a1-rook has gone to c1, so queenside castling is now illegal, and the g- and h-pawns have gone to g5 and h4, so castling short means a king on g1 with one pawn in front of it. Your king has been on the queenside since move fourteen.",
            "next": [
                "...Rc8 and double. The c-file is open because both c-pawns died on d4, and it runs straight at the rook White has just put on c1.",
                "Stop counting d4. It is defended by the knight on f3 and the bishop on b2 against your one knight on c6 — and note that the queen on d2 is not a third defender, because White's own bishop on d3 stands between them. Two against one is enough; the pressure has moved to the file.",
                "...f6 is the break that is left, and it hits e5 and g5 at the same time. Every recapture White chooses opens a line toward a king that cannot leave the centre.",
            ],
            "endgame": "Two, two and three a side again: no majority anywhere, so nobody is making a passed pawn. What is left on the board is two frozen white pawns — h4 cannot advance because your pawn is on h5, g5 cannot advance because your knight is on g6 — sitting on a wing where neither king lives. Trade into any endgame you like from here; you are the one with the open file and the better bishop.",
        },
        "notes": {
            20: "The knight steps back rather than be taken. It is heading for g6, where it hits e5 and covers f4 and h4 — the three squares White's attack wants.",
            21: "White finally develops the queen's knight. From c3 it eyes a4 and b5.",
            22: "The knight arrives. Note what it does to the g-pawn: g5 is now available but g6 is not, and the difference decides where White's attack goes.",
            23: "White plays on the only wing where there is space. The pawns are committed now, and the squares they left behind are the ones White's own king would have used.",
            24: "The right answer to a pawn storm — stop it with a pawn. h4–h5 is gone for good; what is left on that wing is g4–g5, gxh5 and f2–f4, and the game continues with the first of them.",
            25: "White takes the space anyway and locks the wing. The g-pawn can go no further: g6 is occupied by your knight.",
            26: "Development, and it hits g5 down the e7–g5 diagonal. White is holding that pawn with the h4-pawn and the knight on f3 — two units tied to a pawn on a wing where nothing else is happening.",
            27: "White develops the bishop onto the b1–h7 diagonal, pointing at a kingside that Black's king is about to leave for good.",
            28: "Black castles into the wing where White has no pawns and no attack, and next door to the file Black is about to use.",
            29: "White hits the queen and heads for c5, which is a genuine hole: your b- and d-pawns can never cover it again.",
            30: "The queen steps onto the file it wants to fight on, and out of the knight's way.",
            31: "White contests the file — and pays for it. With the rook off a1, queenside castling is now impossible, so White's king is choosing between e1 and a g1 with the pawn cover already spent.",
            32: "Tucking the king away and preparing ...Rc8. Note the shape: White's pawns are on the wing where nobody lives, and Black's pieces are on the wing where White's king has to survive.",
            33: "White connects the rooks and eyes the queenside. A rich, unbalanced position, and a perfect illustration of the French bargain: Black looked passive for eight moves and now owns the only open file on the board.",
        },
    },
    # Deviations, keyed by the position they answer rather than by a ply number.
    # This is a Black repertoire, so almost every set below answers a WHITE move:
    # the entries are what your opponent might play instead of the main line, and
    # the `why` says what you do about it. The three sets at a Black-to-move
    # position are your own alternatives, and they are labelled as such.
    "branches": {

        # ── ply 2 · White's second move — the ones no book covers ────────────────
        "e4 e6": [
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "why": "Development instead of the big centre, and the engine likes it as much as 2.d4. Answer 2...d5 anyway: after 3.d4 you are in a normal 3.Nc3 French and nothing you have learned is wasted. What White has kept is the option of leaving the d-pawn at home — annoying, not dangerous.",
             "line": "d5 d4 Nf6 Bg5 dxe4"},
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "The same story with the other knight, and 2...d5 is again the move. The engine's line is 3.exd5 exd5 4.d4 Nf6, which is the Exchange Variation reached one move late — read the panel on 3.exd5 for what to do with it. If White plays 3.e5 instead you get an Advance with the knight already committed to f3, which suits you: it is c2–c3, not Nf3, that holds d4 together.",
             "line": "d5 exd5 exd5 d4 Nf6"},
            {"san": "d3", "severity": "playable", "tier": "Structure",
             "name": "King's Indian Attack",
             "why": "White declines the centre and builds a set-up instead: Nd2, Ngf3, g3, Bg2, O-O and then e4–e5 and a kingside attack, the same shape every game. There is nothing to refute — take the free centre with 2...d5 and 3...c5, and then remember the one rule that decides these games: get your pieces to the queenside and play there, because White's whole plan needs about ten moves and you only get to punish it by being faster somewhere else.",
             "line": "d5 Nf3 c5 exd5 exd5"},
            {"san": "Qe2", "severity": "playable", "tier": "Structure",
             "name": "Chigorin Variation",
             "why": "Chigorin's move, and it is aimed at exactly one thing: after 2...d5 3.exd5 your king and the white queen are on the same file, so you cannot recapture with the pawn. This is the one second move where the automatic 2...d5 is genuinely bad — the engine has it costing you nearly half a pawn. Change the subject instead: 2...c5 heads for a Sicilian where White's queen is already misplaced, and it is the engine's own first choice. 2...Be7 followed by ...d5 also works, and sidesteps the e-file altogether.",
             "line": "c5 Nf3 Nc6 g3 g6"},
            {"san": "c4", "severity": "playable", "tier": "Structure",
             "name": "Steiner Variation",
             "why": "White adds a second attacker to d5 before you have got there. 2...d5 is still correct and the engine already prefers Black: 3.exd5 exd5 4.d4 Bb4+ is a comfortable game, and the greedy 4.cxd5 grabs a pawn in a position where ...Nf6, ...Bb4+ and ...O-O all come with tempo and White has not developed a piece. Do not go looking for a punishment — there isn't one — go looking for the recapture.",
             "line": "d5 exd5 exd5 d4 Bb4+"},
            {"san": "b3", "severity": "playable", "tier": "Plans",
             "name": "Horwitz Attack",
             "why": "White fianchettoes the queen's bishop and aims it down the a1–h8 diagonal. Take the centre with 2...d5 — the engine already has Black better — and if 3.Bb2 Nc6 4.e5, then 4...d4! and the bishop's own diagonal is blocked by a pawn your knight on c6 already defends.",
             "line": "d5 Bb2 Nc6 e5 d4"},
            {"san": "f4", "severity": "playable", "tier": "Plans",
             "name": "La Bourdonnais Variation",
             "why": "A King's Gambit shape without the gambit. It looks aggressive and it costs about half a pawn, because f4 does nothing about d5 and leaves the a7–g1 diagonal and the e1–h4 diagonal open at the same time. 2...d5 3.Nc3 d4 gains space with tempo and White has to spend a move sending the knight backwards.",
             "line": "d5 Nc3 d4 Nce2 c5"},
        ],

        # ── ply 4 · White's third move — the four doors, and three sideshows ─────
        "e4 e6 d4 d5": [
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "name": "Paulsen Variation",
             "why": "The main line and the engine's own first choice. White defends e4 with a piece and keeps every option: you choose the game from here with 3...Bb4 (the Winawer), 3...Nf6 (the Classical) or 3...dxe4 (the Rubinstein). Step through the Winawer line, then read the panel at this position's next stop for the other two.",
             "line": "Bb4 e5 c5 a3 Bxc3+",
             "see": "french#winawer"},
            {"san": "Nd2", "severity": "playable", "tier": "Foundation",
             "name": "Tarrasch Variation",
             "why": "The safe modern choice: it defends e4 without allowing ...Bb4, at the cost of blocking the c1-bishop and giving up the pressure on d5. Meet it with 3...c5 and the whole variation follows — you get your bishop out and White gets to hand you an isolated pawn for it.",
             "line": "c5 exd5 exd5 Ngf3 Nc6",
             "see": "french#tarrasch"},
            {"san": "e5", "severity": "playable", "tier": "Foundation",
             "name": "Advance Variation",
             "why": "The most common move you will meet below master level, and the one the whole opening is built to answer: White locks the centre and you attack the base of the chain with 3...c5. Everything from here is the main line.",
             "line": "c5 c3 Nc6 Nf3 Qb6",
             "see": "french#advance"},
            {"san": "exd5", "severity": "playable", "tier": "Foundation",
             "name": "Exchange Variation",
             "why": "Be honest about this one, because it is the move most club opponents play and the one most French players have never studied. It is not a refutation and it is not a mistake — by the engine's count it costs White almost nothing — and it deletes the entire opening: no pawn chain, no bad bishop, no ...c5 break, a symmetrical structure and a completely open c8–h3 diagonal. What it does not do is force a draw. Play ...Nf6, ...Bd6, ...c6, ...O-O and ...Bg4, and then castle on the opposite wing to White or push the queenside pawns. Symmetry is only drawish while both sides copy each other; the moment one of you stops, it is an ordinary game with everything still on the board.",
             "line": "exd5 Nf3 Nf6 Bd3 c5"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "name": "Schlechter Variation",
             "why": "Defending e4 with a piece that would rather be somewhere else. 3...dxe4 4.Bxe4 and now the bishop is the one in the middle of the board getting hit: 4...Nf6 forces it to move again and 5...c5 follows. You have the freest French position on this page.",
             "line": "dxe4 Bxe4 Nf6 Bd3 c5"},
            {"san": "Be3", "severity": "inaccuracy", "tier": "Structure",
             "name": "Alapin Gambit",
             "why": "White offers the e-pawn, planning 3...dxe4 4.Nd2 and f3 with a lead in development. Take it — the engine gives Black a third of a pawn — and then give it back on your own terms rather than clinging to it: 4...Nf6 5.c3 and you have a solid position where the pawn is a bonus rather than a debt. The two moves that do not work are 3...c5 and 3...Nf6, which both leave White comfortably better.",
             "line": "dxe4 Nd2 Nf6 c3 b6"},
            {"san": "c4", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Diemer-Duhm Gambit",
             "why": "White does not defend e4 at all. Take it: 3...dxe4 is worth about two thirds of a pawn and it is the only move that is — 3...Nf6, 3...c6 and 3...dxc4 all hand the advantage straight back. Then hold it with 4.Nc3 f5, which defends the extra pawn with another pawn, and let White show what the open lines are for.",
             "line": "dxe4 Nc3 f5 Nh3 Nf6"},
            {"san": "f3", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The same gambit by a worse door: the f-pawn is the one in front of White's king. 3...dxe4 4.Nc3 Bb4! and White has to unravel with the pin still on — 5.fxe4 Bxc3+ 6.bxc3 Qh4+ and the check exists precisely because the f-pawn has left f2. Doubled c-pawns, an exposed king and a pawn deficit.",
             "line": "dxe4 Nc3 Bb4 fxe4 Bxc3+ bxc3 Qh4+"},
        ],

        # ══ ADVANCE VARIATION ════════════════════════════════════════════════════

        # ── ply 6 · White's fourth in the Advance ───────────────────────────────
        "e4 e6 d4 d5 e5 c5": [
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "Developing before propping up d4, which means d4 can simply be taken: 4...cxd4 5.Nxd4 and White has an open game with a knight in the centre and no pawn chain left. That is a fair trade for White and a good one for you — the base of the chain has gone on move four, and 5...Ne7 and ...Nbc6 both come out hitting the knight that replaced it.",
             "line": "cxd4 Nxd4 Ne7 Bd3 Nbc6"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "name": "Steinitz Variation",
             "why": "White hands you the centre to hold a pawn that cannot be held. Note what has just happened to e5: the pawn on d4 was defending it, and now the pawn on d4 is on c5. So 4...Nc6 comes with a threat and White has to spend the next move on 5.Nf3 before taking the pawn back with 5...Bxc5. Recapturing at once with 4...Bxc5 is worth exactly the same by the engine's count — take with the bishop if you want the simple game.",
             "line": "Nc6 Nf3 Bxc5 Nc3 Qc7"},
            {"san": "Qg4", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The Nimzowitsch idea: forget d4 and go for g7. It costs White well over a pawn, because there is nothing on g7 to win — 4...Nc6 defends nothing and needs to defend nothing, it simply develops and hits d4. After 5.Nf3 cxd4 6.Bd3 h5 the queen is being chased around while your position builds itself. 4...cxd4 first is just as good; the queen sortie is premature either way.",
             "line": "Nc6 Nf3 cxd4 Bd3 h5"},
            {"san": "Be3", "severity": "inaccuracy", "tier": "Structure",
             "why": "Defending d4 with the wrong unit. 4...cxd4 5.Bxd4 and the bishop is in the middle of the board where every developing move you make attacks it: 5...Nc6 6.Nf3 Nge7 and White has to move it again. A piece defending a pawn is only good while nothing can hit the piece.",
             "line": "cxd4 Bxd4 Nc6 Nf3 Nge7"},
            {"san": "f4", "severity": "playable", "tier": "Plans",
             "why": "Propping up e5 rather than d4 — a real system, and the one that makes ...f6 harder later, because e5 will be defended twice before you can hit it. What it does not do is add anything to d4. 4...Nh6 is the engine's answer and the thematic one: the knight heads for f5, and it goes there knowing that the pawn which would have chased it off has already been spent on f4.",
             "line": "Nh6 Nf3 Nc6 Bd3 Bd7"},
        ],

        # ── ply 7 · YOUR fourth move — the three French systems ──────────────────
        "e4 e6 d4 d5 e5 c5 c3": [
            {"san": "Qb6", "severity": "playable", "tier": "Structure",
             "name": "Wade Variation",
             "why": "The same idea as the main line with the moves swapped: the queen comes to b6 before the knight to c6, which keeps ...Bd7 and ...Bb5 available as a way of trading the bad bishop for White's good one. Completely sound, and it costs nothing. The only difference worth knowing is that White gets the option of 5.Nf3 Bd7 6.Be2, avoiding the a3 and b4 plan of the main line.",
             "line": "Nf3 Nc6 Be2 cxd4 cxd4"},
            {"san": "Bd7", "severity": "playable", "tier": "Plans",
             "why": "Solving the bad bishop before anything else — it is going to b5 to trade itself for whichever white bishop comes to d3 or e2. Korchnoi's system, and the one he used to beat Spassky in the eighteenth game of the 1977 Candidates final; he reached it by 4...Nc6 5.Nf3 Bd7, which is the same thing one move later. It is a system rather than a move order: you accept a slower build-up against d4 in exchange for never having a bad bishop at all.",
             "line": "Nf3 Nc6 Be2 Nge7 Na3"},
            {"san": "Nh6", "severity": "playable", "tier": "Structure",
             "why": "The knight route to f5 played one move early, and it costs about a quarter of a pawn. 5.Bxh6 gxh6 is the critical try — the engine rates it level with the quiet 5.Nf3 — and here there is no ...Qxb2 in return, because your queen is still sitting on d8. The trap on move seven needs the queen already on b6; that is the entire difference, and it is one tempo wide.",
             "line": "Bxh6 gxh6 Bb5+ Bd7 Bxd7+"},
            {"san": "cxd4", "severity": "playable", "tier": "Foundation",
             "why": "Releasing the tension at once, and the received wisdom is that it is a mistake. It is not — the engine puts it about a tenth of a pawn behind 4...Nc6, which is nothing. What is true is that it is a decision you never have to make yet: after 5.cxd4 White's pawn on d4 is fixed and you have given up the option of ever taking on d4 at a better moment, or of leaving the tension there while you develop. Take when the recapture is forced, not when it is available.",
             "line": "cxd4 Ne7 Nf3 Nbc6 Nc3"},
        ],

        # ── ply 8 · White's fifth ────────────────────────────────────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6": [
            {"san": "Be3", "severity": "playable", "tier": "Structure",
             "why": "A fourth defender for d4, and it invites 5...Qb6 hitting b2 — White then has to spend a move on Qb3 or Qd2 rather than developing. The cleaner answer is 5...Nh6: the knight is going to f5, where it attacks the bishop on e3 and the pawn on d4 in the same breath.",
             "line": "Nh6 Bd3 Qb6 Ne2 Bd7"},
            {"san": "f4", "severity": "inaccuracy", "tier": "Plans",
             "why": "Propping up the front of the chain and leaving the base alone. It adds nothing at all to d4, and it commits the pawn that would otherwise answer ...f6 later on. 5...Qb6 6.Nf3 Nh6 and the knight is on its way to f5 in a position where White has spent a move that does not defend the square everything is aimed at. Two thirds of a pawn.",
             "line": "Qb6 Nf3 Nh6 Nbd2 cxd4"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The same mistake as on move four and worse, because your knight is already on c6. e5 now has no pawn defending it and no piece either: 5...Nxe5 wins it back at once and you are the one with the extra centre pawn and the open lines. Do not settle for 5...Bxc5 — count the defenders of e5 first.",
             "line": "Nxe5 Be3 Nh6 Nf3 Nxf3+"},
            {"san": "Nd2", "severity": "inaccuracy", "tier": "Structure",
             "why": "It develops, and it drops a pawn. The knight on d2 stands between the queen on d1 and the pawn on d4, so after 5...cxd4 6.cxd4 the recapture on d4 is gone: 6...Nxd4! and nothing takes back. This is the cleanest example in the whole opening of why you count defenders rather than pieces.",
             "line": "cxd4 cxd4 Nxd4 Ngf3 Nc6"},
        ],

        # ── ply 10 · White's sixth — the Milner-Barry crossroads ─────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6": [
            {"san": "Bd3", "severity": "playable", "tier": "Mastery",
             "name": "Milner-Barry Gambit",
             "why": "The most dangerous practical try in the Advance, and objectively fine for both sides — four centipawns behind 6.a3 at depth twenty. White plays 6...cxd4 7.cxd4 Bd7 8.O-O and invites you to take twice on d4: 8...Nxd4 9.Nxd4 Qxd4 10.Nc3, two pawns for an attack on a king still standing in the centre. Take them. The engine has Black about seven tenths of a pawn better after 10...a6, and declining with 8...Rc8 is actually the worse choice by a third of a pawn. But 10...a6 is the move and you have to know it: it takes b5 from the knight, which is the only square the attack has. The natural 10...Ne7? loses the whole advantage to 11.Nb5, and 10...Qxe5 grabs a third pawn and turns seven tenths into nothing.",
             "line": "cxd4 cxd4 Bd7 O-O Nxd4 Nxd4 Qxd4 Nc3 a6"},
            {"san": "Be2", "severity": "playable", "tier": "Structure",
             "why": "The quiet version: White develops without offering anything and keeps d4 held. It is exactly as good as 6.a3 and it walks into the same idea one move earlier — 6...cxd4 7.cxd4 Nh6! and if 8.Bxh6 Qxb2, because the bishop leaving c1 is the whole trap and White has not spent a move making b2 safe.",
             "line": "cxd4 cxd4 Nh6 Bxh6 Qxb2"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Giving up the centre to hold a pawn, with your queen already on b6 hitting the pawn it wants to keep. 6...Bxc5 recaptures with tempo and the position opens with your pieces already better placed: 7.Qe2 f6! and the front of the chain goes too.",
             "line": "Bxc5 Qe2 f6 b4 Be7"},
            {"san": "Na3", "severity": "playable", "tier": "Plans",
             "why": "The knight goes the long way round to c2, which is the one square from which the b1-knight can defend d4 at all — c3 is taken by a pawn. It costs a little time and it works. Answer 6...cxd4 7.cxd4 Bb4+, using the check that only exists while the knight is on a3 rather than c3.",
             "line": "cxd4 cxd4 Bb4+ Bd2 Nge7"},
        ],

        # ── ply 12 · White's seventh — two ways to lose material ─────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6": [
            {"san": "Bxh6", "severity": "blunder", "tier": "Foundation",
             "why": "The reflex — damage the structure, remove the knight that was heading for f5 — and it drops a pawn on the other side of the board. Count b2 before you allow it: the bishop on c1 is its only defender, and it has just left. 7...Qxb2! and after 8.Nbd2 there is no need to go rook-hunting — 8...gxh6 9.dxc5 Qxc3 leaves you a clean pawn up with the queen sitting in White's position and the king still on e1. Take on h6 at the right moment and it is a good move: the model game shows White doing exactly that one move later, when ...cxd4 has already been played and there is no ...Qxb2 to answer it.",
             "line": "Qxb2 Nbd2 gxh6 dxc5 Qxc3",
             "see": "french#fressinet"},
            {"san": "dxc5", "severity": "blunder", "tier": "Structure",
             "why": "It looks like it wins a pawn and it loses two and a half. 7...Bxc5 comes with the bishop landing on the a7–g1 diagonal, and f2 is defended by the king alone: 8.Bd3 Ng4 puts a second attacker on it and 9.Qe2 Bxf2+ 10.Kd1 leaves White's king in the middle of an open board. Count what is looking at f2 before you take on c5.",
             "line": "Bxc5 Bd3 Ng4 Qe2 Bxf2+"},
            {"san": "Be2", "severity": "playable", "tier": "Structure",
             "why": "Developing and letting the b4 plan wait. Perfectly sound, and it gives you the easiest game on this page: 7...cxd4 8.O-O Nf5 9.Bd3 dxc3 10.Nxc3 and the position is dead level with your knight on its best square, your bishop still to come to d7 and no weaknesses anywhere.",
             "line": "cxd4 O-O Nf5 Bd3 dxc3"},
            {"san": "Bd3", "severity": "playable", "tier": "Plans",
             "why": "The most testing alternative to 7.b4 and the engine's equal. White keeps the option of Bxf5 later — trading off the knight that is your best piece and leaving you with the bad bishop and nothing to trade it for. Answer 7...cxd4 8.O-O Bd7 and get the bishop to b5 before White's has anything to hit.",
             "line": "cxd4 O-O Bd7 b4 Rc8"},
        ],

        # ── ply 16 · White's ninth — d4 is attacked three times ──────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5": [
            {"san": "Bd3", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Developing and forgetting the count — and it is worse than doing nothing, because the bishop landing on d3 blocks the queen's own defence of d4 down the d-file. Three attackers, one defender: 9...Nfxd4! wins a pawn outright. This is the position the whole variation has been building toward, and the only moves that hold it are the ones that add a defender.",
             "line": "Nfxd4 Nbd2 Be7 b5 Nxb5"},
            {"san": "Nc3", "severity": "inaccuracy", "tier": "Structure",
             "why": "The natural developing square, and the pawn is gone the moment it is played: 9...Nfxd4 10.Be3 Nxf3+ 11.Qxf3 and you are a clean pawn ahead. The knight on c3 hits d5 and covers b5 and e2 — every square except the one that mattered.",
             "line": "Nfxd4 Be3 Nxf3+ Qxf3 Qc7"},
            {"san": "h4", "severity": "inaccuracy", "tier": "Plans",
             "why": "Starting the attack before the centre is safe. 9...Ncxd4! and the whole thing collapses into an endgame a pawn down: 10.Nxd4 Qxd4 11.Qxd4 Nxd4 and White has a pawn on h4 to show for it. When your opponent's pawns start marching on the wing, count the centre — it is almost always the answer.",
             "line": "Ncxd4 Nxd4 Qxd4 Qxd4 Nxd4"},
        ],

        # ── ply 18 · White's tenth ───────────────────────────────────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7": [
            {"san": "Be2", "severity": "playable", "tier": "Structure",
             "why": "The solid move, and the one that leaves the knight on f5 where it is. That suits you: 10...Be7 11.O-O Rc8 and you have the open file, the knight on its best square and no weaknesses. White's game is easier to play and yours is easier to win.",
             "line": "Be7 O-O Rc8 b5 Na5"},
            {"san": "Bd3", "severity": "playable", "tier": "Plans",
             "why": "The trade offer: White wants Bxf5, which leaves you with the bad bishop and no counterpart for it. Take the tempo before the trade happens — 10...a5! hits the b4-pawn, and after 11.Bxf5 exf5 your pawn structure changes completely: the e6-pawn has gone, the bishop on d7 is suddenly a good piece, and the e-file is half-open for your rook.",
             "line": "a5 Bxf5 exf5 Nc3 axb4"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "It looks like it drops d4 the way it did one move ago, and this time it does not — quite. 10...Ncxd4 11.Nxd4 Qxd4 12.Qxd4 Nxd4 13.Nxd5! and the pawn comes straight back, because the bishop on b2 has been looking at that knight since move nine. Play it if you want the endgame; do not play it thinking you are a pawn up.",
             "line": "Ncxd4 Nxd4 Qxd4 Qxd4 Nxd4 Nxd5"},
        ],

        # ── ply 20 · White's eleventh, in the deep dive ──────────────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4 Nfe7": [
            {"san": "h4", "severity": "playable", "tier": "Plans",
             "why": "Pushing the second pawn before the pieces are out. 11...h5! is the standard answer to a pawn storm — stop it with a pawn — and after 12.g5 Nf5 the knight is back on its square with White's kingside pawns fixed and no attack behind them.",
             "line": "h5 g5 Nf5 Bh3 Nce7"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "Developing rather than pushing, and it transposes into the same shape one move later: 11...Ng6 12.h4 h5 and you are in the deep dive. The one difference to notice is that with the bishop already on d3, the knight arriving on g6 is asking to be taken — which is a trade you are happy to allow, because it removes the e6-pawn and frees your other bishop.",
             "line": "Ng6 h4 h5 g5 Rc8"},
        ],

        # ── ply 22 · White's twelfth, in the deep dive ───────────────────────────
        "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4 Nfe7 Nc3 Ng6": [
            {"san": "Bd3", "severity": "blunder", "tier": "Structure",
             "why": "Two pawns, and it takes three moves to see why. 12...Nxd4! 13.Bxg6 Nxf3+ — the knight leaves d4 with check, which is the move that makes it work — 14.Qxf3 hxg6 and you are a pawn up with the h-file half-open at a white king that is still sitting on e1. The bishop on d3 was supposed to be another defender of d4 and it was never anything of the kind.",
             "line": "Nxd4 Bxg6 Nxf3+ Qxf3 hxg6"},
            {"san": "Na4", "severity": "playable", "tier": "Plans",
             "why": "The knight heads for c5 before the rook comes to c1. Answer 12...Qd8 — the queen has done its job on b6 and c5 is not a square worth arguing about — and then get on with ...Rc8 and the file.",
             "line": "Qd8 Rc1 Rc8 h4 h5"},
            {"san": "Rc1", "severity": "playable", "tier": "Plans",
             "why": "White grabs the open file before starting anything on the wing. It also means White's king has given up queenside castling for good — the deep dive reaches the same decision four moves later, and the plan card explains what it is worth.",
             "line": "h5 Na4 Qd8 Rg1 Rc8"},
        ],

        # ══ WINAWER AND CLASSICAL ════════════════════════════════════════════════

        # ── ply 5 · YOUR third move after 3.Nc3 ─────────────────────────────────
        "e4 e6 d4 d5 Nc3": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Classical Variation",
             "why": "The other half of the French, and by the engine's count a shade better than the Winawer: you develop, hit e4 and keep the bishop. White chooses between 4.e5 Nfd7 — a French chain where the knight tucks in behind and the ...c5 break follows exactly as usual — and 4.Bg5, which is where the theory lives. It is the more solid and the less forcing of the two; if the Winawer's doubled-pawn bargain does not appeal, this is the line to learn instead.",
             "line": "Bg5 dxe4 Nxe4 Be7 Bxf6"},
            {"san": "dxe4", "severity": "playable", "tier": "Structure",
             "name": "Rubinstein Variation",
             "why": "Give up the centre, get the bishop out, and answer both 3.Nc3 and 3.Nd2 with one move — that last part is the real selling point, because it halves the theory. The price is that White has more space and no weaknesses, and you have to be content playing for a draw against a good player. 4.Nxe4 Nd7 and ...Ngf6 is the modern treatment.",
             "line": "Nxe4 Nd7 Nf3 Ngf6 Nxf6+"},
            {"san": "Nc6", "severity": "playable", "tier": "Mastery",
             "name": "Hecht-Reefschläger Variation",
             "why": "A rare developing move with one very real cost: the knight is standing on the square the c-pawn needs, so ...c5 — the move the whole opening is about — is off the table until it moves again. After 4.e5 f6 you are committed to the other break instead, which is a legitimate way to play and about a third of a pawn behind the main choices.",
             "line": "e5 f6 Nf3 a6 Bd3"},
            {"san": "c5", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The break played a move too early, and it drops a pawn to a check. 4.exd5 exd5 5.Bb5+! is the move — not 5.dxc5, which lets you play ...d4 — and after 5...Nc6 6.dxc5 you are a pawn down with an isolated d-pawn and nothing for it. In the French the ...c5 break needs the centre settled first; this is the position that shows why.",
             "line": "exd5 exd5 Bb5+ Nc6 dxc5"},
        ],

        # ── ply 6 · White's fourth against the Winawer ───────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4": [
            {"san": "exd5", "severity": "playable", "tier": "Foundation",
             "why": "The Exchange with the bishop already committed to b4, and it is the most common way club players duck the whole variation. Symmetrical and about a third of a pawn behind 4.e5, and the bishop on b4 is not misplaced at all: 4...exd5 5.Bd3 Nf6 6.a3 Bxc3+ 7.bxc3 gives White the same doubled pawns as the main line in a structure with no attack attached to them.",
             "line": "exd5 Bd3 Nf6 a3 Bxc3+"},
            {"san": "a3", "severity": "inaccuracy", "tier": "Structure",
             "name": "Winckelmann-Reimer Gambit",
             "why": "White forces the trade immediately and offers the e-pawn for it. 4...Bxc3+ 5.bxc3 dxe4 and you are a pawn up with White's structure already broken; the compensation is 6.Qg4 and the usual attack on g7, which you meet with 6...Nf6 and give the pawn back if you have to. Six tenths of a pawn, and a line worth taking on rather than avoiding.",
             "line": "Bxc3+ bxc3 dxe4 Qg4 Nf6"},
            {"san": "Bd2", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Fingerslip Variation",
             "why": "White unpins by interposing and offers e4 for development. 4...dxe4 is correct and then the critical test is 5.Qg4, going straight for g7 while your king is in the middle: 5...Nf6! 6.Qxg7 Rg8 7.Qh6 and the rook is already on the half-open file. Play 5...Nf6 because it is the move that develops with tempo and keeps the extra pawn, not because it looks brave.",
             "line": "dxe4 Qg4 Nf6 Qxg7 Rg8"},
            {"san": "Ne2", "severity": "playable", "tier": "Mastery",
             "name": "Alekhine-Maróczy Gambit",
             "why": "White gives up e4 for a lead in development and the knight on e2, which will recapture on c3 and leave the pawns healthy — that last part is the whole idea, and it is the one thing the main-line Winawer never allows. 4...dxe4 5.a3 Bxc3+ 6.Nxc3 Nc6 and you are a pawn up with a solid game; give the pawn back for development if White gets in Bf4 and Qd2 before you castle.",
             "line": "dxe4 a3 Bxc3+ Nxc3 Nc6"},
            {"san": "Qg4", "severity": "inaccuracy", "tier": "Mastery",
             "why": "Straight for g7 on move four, and it is premature by about two thirds of a pawn. 4...Nf6! is the move — develop with tempo and let the pawn go: 5.Qxg7 Rg8 6.Qh6 c5 and you have the g-file, the centre and a white queen on h6 with nothing around it. It is the Poisoned Pawn played before White has any of the things that make the Poisoned Pawn work.",
             "line": "Nf6 Qxg7 Rg8 Qh6 c5"},
        ],

        # ── ply 8 · White's fifth after 4.e5 c5 ──────────────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5": [
            {"san": "Bd2", "severity": "playable", "tier": "Structure",
             "why": "White refuses the doubled pawns: after ...Bxc3 the bishop recaptures and the structure stays healthy. The cost is time and the dark squares — 5...Ne7 6.a3 Bxc3 7.Bxc3 Nbc6 and White's bishop is now the piece defending d4, which is exactly the piece you want tied down. A serious line and a much quieter game than the main Winawer.",
             "line": "Ne7 a3 Bxc3 Bxc3 Nbc6"},
            {"san": "dxc5", "severity": "playable", "tier": "Plans",
             "why": "Giving up the centre to keep a pawn, and the pawn is not keepable. 5...Ne7 first — develop and let White try to hold c5 — and after 6.Nf3 Nd7 7.Bd3 Nxc5 you have the pawn back and a knight on c5 that nothing can chase.",
             "line": "Ne7 Nf3 Nd7 Bd3 Nxc5"},
            {"san": "Qg4", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The attack before the structure. It costs over half a pawn because g7 is not yet weak — your bishop is still on b4 rather than traded on c3, and 5...Ne7 covers everything. After 6.dxc5 Nbc6 7.Nf3 d4! the centre opens with White's queen offside.",
             "line": "Ne7 dxc5 Nbc6 Nf3 d4"},
        ],

        # ── ply 9 · YOUR fifth move after 5.a3 ───────────────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3": [
            {"san": "Ba5", "severity": "playable", "tier": "Mastery",
             "why": "Keeping the bishop instead of trading it, and at depth twenty it is exactly as good as 5...Bxc3+. The whole character changes: White gets in 6.b4 with tempo, the pawns stay healthy, and the bishop on a5 spends the game slightly awkward but alive. Choose between them on temperament — the trade is a structural bet, this is a piece bet.",
             "line": "b4 cxd4 Qg4 Kf8 Qxd4"},
            {"san": "cxd4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Taking the pawn and forgetting what a3 attacked. 6.axb4! and the bishop is gone. You get two pawns for it, three if you also collect b2, and the engine still calls the position more than a pawn better for White — 6...dxc3 7.Qg4 comes at g7 into the bargain. Deal with the attacked piece before you touch anything else; that is the whole content of this position.",
             "line": "axb4 dxc3 Qg4 Ne7 Qxg7"},
        ],

        # ── ply 11 · YOUR sixth move after 6.bxc3 ───────────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3": [
            {"san": "Qc7", "severity": "playable", "tier": "Structure",
             "why": "The queen goes to c7 first, backing the c-pawn and taking a lot of the sting out of Qg4 before it happens: with the knight still on g8 there is no ...Ne7 to hang, so Black can answer 7.Qg4 with ...f5 or ...f6 and keep the pawns. Exactly as good as 6...Ne7 by the engine's count, and about half as sharp.",
             "line": "Nf3 Ne7 h4 h6 h5"},
            {"san": "Qa5", "severity": "playable", "tier": "Mastery",
             "name": "Portisch-Hook Variation",
             "why": "The queen comes out on the other diagonal, aiming at a3 and c3 and provoking more queenside weaknesses before Black commits anywhere. Sound and rare, which is most of its value. White's best is 7.Bd2 and then the queen has to decide whether it was going anywhere.",
             "line": "Bd2 Qa4 Qg4 Kf8 h4"},
            {"san": "cxd4", "severity": "playable", "tier": "Foundation",
             "why": "Taking first and developing afterwards. It is sound and it hands White a choice you would rather not give: 7.cxd4 leaves White with a healthy pawn on d4 and only one c-pawn to attack. The whole reason the Winawer trades on c3 is to give White two pawns on that file — do not undo it for free.",
             "line": "cxd4 Qc7 Bd2 Nc6 Nf3"},
        ],

        # ── ply 13 · White's seventh ─────────────────────────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7": [
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "The positional main line: White declines the pawn-grab entirely and plays for the bishop pair and the centre. It is a genuinely different game — no attack, no gambit, just White's two bishops against your structure. 7...b6 and ...Ba6 is the standard reply, trading the bad bishop for the good one before it has a diagonal.",
             "line": "b6 Bb5+ Bd7 a4 Bxb5"},
            {"san": "a4", "severity": "playable", "tier": "Plans",
             "why": "A useful little move aimed squarely at your bishop plan: with a4–a5 available, the b6 square is contested and ...b6 and ...Ba6 stop being free. Answer 7...Nbc6 and get on with your own game — a4 is a move that stops something, and stopping something is not the same as doing something.",
             "line": "Nbc6 h4 Qa5 Bd2 Bd7"},
            {"san": "h4", "severity": "playable", "tier": "Mastery",
             "why": "The engine's own first choice here, and a completely different attacking scheme: the rook comes to h3 and swings across, and Qg4 arrives later with the h-pawn already in place. 7...Qc7 and 8...b6 is the plan — you are not going to stop the attack, you are going to be quicker on the other side.",
             "line": "Qc7 h5 h6 Rb1 b6"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Releasing the centre in the one structure where White must not. 7...Nd7! and the knight attacks c5 and e5 at once, both of them defended by nothing — one of the two is coming off, and White's doubled c-pawns are left standing in an open position with nothing to show for them.",
             "line": "Nd7 Nf3 Qc7 Be3 Nf5"},
        ],

        # ── ply 15 · White's eighth ──────────────────────────────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 Qc7": [
            {"san": "Bd3", "severity": "playable", "tier": "Plans",
             "why": "Declining the pawn and developing with the threat of Bxh7 hanging over the position. It usually transposes: 8...cxd4 9.Ne2 dxc3 10.Qxg7 Rg8 11.Qxh7 is the Poisoned Pawn by another route, so know the main line and the move order stops mattering.",
             "line": "cxd4 Ne2 dxc3 Qxg7 Rg8"},
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "White develops instead of grabbing, keeping the queen on g4 as a permanent threat. This is the sober choice and it is about a third of a pawn behind taking. 8...cxd4 9.Rb1 Ng6 and both sides get a normal game — you have the extra centre pawn, White has the bishop pair.",
             "line": "cxd4 Rb1 Ng6 h4 h5"},
            {"san": "dxc5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "It hangs the e-pawn with check. The queen on c7 has been looking at e5 down the c7–e5 diagonal since move seven, and the pawn on d4 was the only thing defending it — so 8...Qxe5+! collects it with check, and after 9.Ne2 Nd7 you are a pawn up with the better structure and a white queen on g4 defending nothing at all.",
             "line": "Qxe5+ Ne2 Nd7 Qd4 Nc6"},
        ],

        # ── ply 19 · White's tenth — the move that guards c3 ─────────────────────
        "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 Qc7 Qxg7 Rg8 Qxh7 cxd4": [
            {"san": "Nf3", "severity": "blunder", "tier": "Foundation",
             "why": "The natural developing square, and it costs the exchange and more: 10...Qxc3+! 11.Kd1 Qxa1 and the queen has eaten the rook on the way through. The knight on f3 defends d4 and e5 and g5 and everything except the one pawn holding White's queenside together. This is why 10.Ne2 is not a preference, it is the move.",
             "line": "Qxc3+ Kd1 Qxa1 h4 d3"},
            {"san": "cxd4", "severity": "blunder", "tier": "Foundation",
             "why": "Recapturing, which is the most human move on the board, and it loses the same rook by the same route: 10...Qc3+! 11.Kd1 Qxd4+ picks up the second pawn with check and 12.Bd3 Qxa1 collects the rook. Do not recapture on d4 in this position at all — the pawn on c3 is worth more than the pawn on d4, because it is the one shielding a1.",
             "line": "Qc3+ Kd1 Qxd4+ Bd3 Qxa1"},
            {"san": "Kd1", "severity": "playable", "tier": "Mastery",
             "why": "The other real move: White steps aside instead of guarding, so that ...Qxc3 is answered by a rook on b1 or c1. It costs about four tenths of a pawn against 10.Ne2 and it is much less studied, which makes it a practical weapon. 10...Nbc6 and ...dxc3, and the king on d1 has to live next to the pawn you have just planted on c3.",
             "line": "Nbc6 Nf3 dxc3 Ng5 Nxe5"},
        ],

        # ══ TARRASCH ═════════════════════════════════════════════════════════════

        # ── ply 5 · YOUR third move after 3.Nd2 ─────────────────────────────────
        "e4 e6 d4 d5 Nd2": [
            {"san": "Nf6", "severity": "playable", "tier": "Structure",
             "name": "Closed Tarrasch",
             "why": "The other main move, and a completely different game: 4.e5 Nfd7 5.c3 c5 and you have a French chain where your knight sits on d7 rather than being exchanged. Slower, safer, and it keeps the bad bishop — which is the whole trade-off against 3...c5, where the e6-pawn disappears on move four and the bishop is free.",
             "line": "e5 Nfd7 c3 c5 Bd3"},
            {"san": "Be7", "severity": "playable", "tier": "Mastery",
             "name": "Morozevich Variation",
             "why": "A waiting move with a point: it keeps ...Nf6 and ...c5 both available and asks White to commit first. Objectively as good as anything else here and almost nobody has looked at it, which is worth more than the quarter of a pawn it costs.",
             "line": "Ngf3 Nf6 e5 Nfd7 Bd3"},
            {"san": "dxe4", "severity": "playable", "tier": "Structure",
             "name": "Rubinstein Variation",
             "why": "The same simplifying idea as against 3.Nc3, and after 4.Nxe4 the two positions are identical — that is the reason to play it, because one system answers both of White's third moves. Solid, and a little passive: White keeps more space and you keep no weaknesses.",
             "line": "Nxe4 Nd7 Nf3 Ngf6 Nxf6+"},
            {"san": "Nc6", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Guimard Defence",
             "why": "It develops and it blocks the pawn the whole opening depends on. After 4.Ngf3 Nf6 5.e5 Nd7 you cannot play ...c5 without moving the knight first, so the standard break costs two moves instead of one — close to half a pawn, which is a lot to pay for a developing move.",
             "line": "Ngf3 Nf6 e5 Nd7 Nb3"},
        ],

        # ── ply 7 · White's fourth in the Open Tarrasch ──────────────────────────
        "e4 e6 d4 d5 Nd2 c5": [
            {"san": "Ngf3", "severity": "playable", "tier": "Structure",
             "name": "Euwe-Keres Variation",
             "why": "White develops first so that the recapture on d4 can be made with a knight rather than a pawn. It is as good as 4.exd5 and it changes your reply: 4...cxd4 5.exd5 Qxd5 and the queen comes to the centre because there is nothing to hit it with — that is the modern main line, and it avoids the isolated pawn altogether.",
             "line": "cxd4 exd5 Qxd5 Bc4 Qd6"},
            {"san": "c3", "severity": "playable", "tier": "Plans",
             "name": "Süchting Variation",
             "why": "Holding d4 with a pawn while the e-pawn is still on e4 — which means it is still hanging. 4...dxe4 5.Nxe4 cxd4 6.cxd4 and now White has the isolated pawn instead of you. That is the entire point: take on e4 first, take on d4 second, and the structure reverses.",
             "line": "dxe4 Nxe4 cxd4 cxd4 Nf6"},
            {"san": "dxc5", "severity": "playable", "tier": "Foundation",
             "why": "Giving up the centre for nothing. 4...Bxc5 recaptures with the piece that had nowhere else to go, and now your extra centre pawn on d5 is the strong one rather than the isolated one. White gains a tempo on the bishop later with Nb3, which is worth less than the centre.",
             "line": "Bxc5 Bd3 Nf6 Qe2 Nc6"},
        ],

        # ── ply 9 · White's fifth ────────────────────────────────────────────────
        "e4 e6 d4 d5 Nd2 c5 exd5 exd5": [
            {"san": "Bb5+", "severity": "playable", "tier": "Foundation",
             "why": "The check first, to trade off the bishop that the exchange on d5 has just set free. 5...Bd7 and take back with the knight — 6.Bxd7+ Nxd7 — so the trade costs you nothing and the knight ends up on the square it was going to want anyway. Interposing with 5...Nc6 is also fine and keeps more pieces on.",
             "line": "Bd7 Bxd7+ Nxd7 Ngf3 Ngf6"},
            {"san": "Nb3", "severity": "inaccuracy", "tier": "Plans",
             "why": "Hitting c5 before anything is developed, and you should not take. 5...c4! pushes past and gains space with tempo, shutting the knight out of the game: 6.Nd2 Nc6 and White has a knight on d2 for the second time in five moves and no plan. About two thirds of a pawn.",
             "line": "c4 Nd2 Nc6 Ne2 Nf6"},
        ],

        # ── ply 11 · White's sixth ───────────────────────────────────────────────
        "e4 e6 d4 d5 Nd2 c5 exd5 exd5 Ngf3 Nc6": [
            {"san": "Be2", "severity": "playable", "tier": "Structure",
             "why": "The quiet development, and it gives up the pin that makes 6.Bb5 awkward. 6...Nf6 7.O-O Be7 and you have a free, comfortable game — this is the Tarrasch at its most harmless.",
             "line": "Nf6 O-O Be7 dxc5 Bxc5"},
            {"san": "dxc5", "severity": "playable", "tier": "Foundation",
             "why": "The isolated pawn, given to you a move earlier than the main line. 6...Bxc5 and the bishop is on c5 rather than d6, which is a better square while White's knight is still on d2 — the difference is worth a tempo and no more. This is the structure the whole variation is about; the isolani card explains both sides of it, with the colours reversed.",
             "line": "Bxc5 Nb3 Bb6 Bd3 Nf6",
             "see": "structure#isolani"},
            {"san": "Bd3", "severity": "inaccuracy", "tier": "Plans",
             "why": "The natural square is the wrong one here, because it does nothing about c5 and blocks the d-file. 6...c4! and the bishop has to move again with the queenside space already yours: 7.Be2 Nf6 and White has spent two moves on a bishop and one on a knight that is still on d2.",
             "line": "c4 Be2 Nf6 c3 Qa5"},
        ],

        # ── ply 15 · White's eighth ──────────────────────────────────────────────
        "e4 e6 d4 d5 Nd2 c5 exd5 exd5 Ngf3 Nc6 Bb5 Bd6 O-O Nge7": [
            {"san": "Re1", "severity": "playable", "tier": "Structure",
             "why": "The rook takes the open file before the structure is settled. 8...cxd4 9.Nxd4 O-O and this time White has the isolated pawn's opposite number — a knight on d4 and no pawn there — which is a normal, balanced game. Castle first, always: the rook on e1 and your king on e8 are on the same file with one knight between them.",
             "line": "cxd4 Nxd4 O-O N2f3 Bg4"},
            {"san": "c4", "severity": "playable", "tier": "Plans",
             "why": "White plays on the queenside instead of the centre: c4 and then c5, taking space and putting the question to your d-pawn. Let it come — 8...O-O 9.dxc5 Bxc5 10.Nb3 Bb6 11.c5 Bc7 and the bishop steps back to a diagonal it likes, while White's advanced pawns are the ones that now need watching.",
             "line": "O-O dxc5 Bxc5 Nb3 Bb6"},
            {"san": "Nb3", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Hitting c5 one move too late. 8...c4! and the knight is pushed to the edge with your queenside space secured for good: 9.Nbd2 O-O 10.c3 Qa5 and White has two knights on the first three ranks and nothing to attack. Four fifths of a pawn, and the same mistake as 5.Nb3.",
             "line": "c4 Nbd2 O-O c3 Qa5"},
        ],
    },
    "games": [
        {
            "id": "fressinet-korchnoi-1996",
            "name": "Fressinet – Korchnoi, Cannes 1996 — the base of the chain falls",
            "tier": "Foundation",
            "note": "The first seven moves are the main line exactly. Then White takes on h6 — one move after the same capture would have lost a pawn to ...Qxb2 — and Korchnoi spends the next five moves doing nothing except adding attackers to d4 and e5. The pawn on d4 goes on move thirteen, the pawn on e5 on move fourteen, and the game is over as a contest.",
            "moves": (
                "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 "
                "Bxh6 gxh6 cxd4 Bd7 Be2 Rc8 O-O Bg7 Qd2 O-O Nc3 Nxd4 "
                "Nxd4 Bxe5 Rad1 Bxd4 Nxd5 Bxf2+ Rxf2 exd5 Qxd5 Ba4 "
                "Rf1 Bc2 Kh1 Bg6 h4 Rc1 Qf3 Rxf1+ Rxf1 Re8 h5 Re4 "
                "g3 Re3 Qg4 Qc6+ Bf3 Rxf3 Rxf3 f5 Qf4 Bxh5"
            ),
            "notes": {
                12: "The move that sets the trap. Here 7.Bxh6? loses a pawn to 7...Qxb2 — the deviation panel walks through it.",
                15: "And now it is a good move, for a reason worth saying out loud: there is no ...Qxb2 because there is no pawn on b2. White spent it on b4 last move. One tempo, and the same capture goes from losing a pawn to winning a tempo.",
                16: "Korchnoi takes toward the centre and accepts a broken kingside. The file it opens is the g-file — and White is about to castle into it on move eleven.",
                20: "The rook goes to the open file without being asked twice. Both c-pawns died on d4 on moves seven and eight, so this file will not close again for the rest of the game.",
                22: "The bishop comes out on the long diagonal and stops at the pawn on e5 — which is the pawn it is going to take on move fourteen. Both black bishops are now aimed at the two pawns the whole opening is about.",
                26: "Not a free pawn, a combination. The knight goes so that the bishop on g7 can take on e5 next move with an attack on whatever recaptured on d4.",
                28: "And there it is. Once the f3-knight has gone to d4, nothing at all defends e5 — so the bishop takes the front of the chain and hits the knight in the same move. Base first, head second, and nothing was sacrificed to do it.",
                31: "White's only try: the knight takes the d5-pawn and attacks the queen on b6, so Black has no time to save the bishop on d4.",
                32: "Bxf2+ is the refutation. It comes with check, which is what buys the time to take on d5 next move, and the bishop is untouchable in between.",
                42: "The rook lands on the back rank via the file the opening opened. Nothing about this game happened anywhere else.",
                57: "The last try — the queen steps across to defend the h5-pawn.",
                58: "Bxh5 takes it anyway, and the point is what the bishop does when it lands: f3 is now attacked by the bishop on h5 and the queen on c6 and defended only by the queen on f4. The engine calls the position six and a half pawns for Black; the game was scored 0–1 from here.",
            },
        },
        {
            "id": "spassky-korchnoi-1977",
            "name": "Spassky – Korchnoi, Candidates final, Belgrade 1977 — the Poisoned Pawn",
            "tier": "Mastery",
            "note": "Game two of the match that decided who played Karpov. Spassky takes both pawns, Korchnoi transposes into the exact position the Winawer line above ends on, and then spends twelve moves proving that the queen on h7 was not worth what it cost.",
            "moves": (
                "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 cxd4 "
                "Qxg7 Rg8 Qxh7 Qc7 Ne2 Nbc6 f4 Bd7 Qd3 dxc3 Be3 d4 "
                "Bf2 O-O-O Nxd4 Nxd4 Qxd4 b6 Bh4 Bb5 Qe4 Bxf1 Rxf1 Rd5 "
                "Bxe7 Qxe7 Rf3 Kb8 Kf1 Rd2 Rf2 Rgd8 Qf3 Rxf2+ Kxf2 Rd2+ "
                "Kg3 Qd8 Qe4 Qg8+ Kh3 Qh8+ Kg3 Qg7+ Kh3 Rd8 g4 Rh8+ "
                "Kg3 Qh6 Qg2 Qh4+ Kf3 Rd8 Qg3 Qe7 g5 Rd2 Kg4 Qb7 "
                "Qxc3 Rg2+ Kh3 Rf2 Kg4 Qe4"
            ),
            "notes": {
                14: "Korchnoi takes on d4 first and plays ...Qc7 later — the same position by a different order, which is worth knowing because your opponent may reach it either way.",
                18: "Now the queen arrives, and the transposition is complete: this is the position the Winawer line above finishes on, one ply from the end.",
                19: "The only move, guarding c3. Spassky knows what 10.Nf3? costs.",
                20: "The tabiya. Seven white pawns against six, a rook on the open g-file, a queen on h7 that no white piece defends, and Black to prove it is enough.",
                21: "White props up e5 and gives the king a square on f2. Note what it does not do: nothing has been added to c3.",
                24: "There it goes. One of the doubled pawns comes off, and the pawn that takes it lands on c3 where it is a permanent problem for a king that never castles.",
                26: "And the second d-pawn marches. Black has two pawns in the middle of White's position and White has a queen on the edge of the board.",
                28: "O-O-O. The king walks to the wing White has no pieces on, and the rook on g8 never has to move — the g-file was the compensation and Korchnoi never spends it.",
                34: "Bb5 — the bad bishop finally reaches the diagonal that matters, and it is going to trade itself for the one piece keeping White's king in the centre.",
                36: "It does. After 19.Rxf1 the rook has come from h1, so White's king is on e1 with castling gone for good and the bad bishop traded for the good one.",
                44: "The rook lands on White's second rank. Every trade from here helps Black, because the pawn on c3 never goes anywhere and White's king never finds a square.",
                58: "The checks are not random: Korchnoi is walking the white king onto squares where the rook on d8 comes back with tempo, and reaching the same position twice on the way costs him nothing.",
                72: "Rd2 again, and this time with the queen on e7 covering the escape squares. White's king has walked from e1 to f3 and it is not finished.",
                75: "Qxc3 wins the pawn back at last, and it is far too late — the queen leaves the kingside at the exact moment Black's rook and queen arrive there.",
                80: "Qe4, and the king on g4 has four squares and no defence: ...Rg2+ is coming and the queen has to be given up for it. The engine calls it six and a half pawns. Scored 0–1 — and Korchnoi went on to win the match and play Karpov for the world title.",
            },
        },
    ],
    "progression": {
        "arc": "The French teaches you pawn chains better than any other opening, and pawn chains are the skeleton of positional chess.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Accept the bad bishop and learn the one universal plan.",
                "learn": [
                    "The plan in every French: hit the base of White's chain with ...c5, then the front with ...f6. That is the whole opening.",
                    "The four things White can do on move three: 3.e5 (Advance), 3.Nc3 (Classical or Winawer), 3.Nd2 (Tarrasch), 3.exd5 (Exchange).",
                    "Why ...Qb6 is the key move in the Advance: it is the third attacker on d4, and it stops White defending d4 with a piece for free.",
                ],
                "drill": "Play the Advance from the Black side twenty times, aiming only for ...c5, ...Nc6, ...Qb6 and a third attacker on d4.",
                "mistake": "Taking on d4 because you are not sure what else to do. It is not a blunder — the engine barely notices — but it is a decision made for you instead of by you, and it fixes White's pawn on the square you wanted to attack.",
                "ready": "You can explain, without a board, why ...c5 comes before ...Nf6.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Solve the light-squared bishop, permanently.",
                "learn": [
                    "Route 1: ...b6 and ...Ba6, trading it for White's good bishop.",
                    "Route 2: ...Bd7–b5 or ...Bd7–a4, using the queenside — this is what Korchnoi did to Spassky in game two of the 1977 Candidates final, trading it for the bishop on f1.",
                    "Route 3: ...Bd7–e8 and then –g6 or –h5, the slow route to the kingside — same match, game eighteen.",
                    "Route 4: let White trade it off. In the Tarrasch and the Exchange the e6-pawn disappears on move four and the problem never exists.",
                ],
                "drill": "In your next ten French games, write down on move ten which route you have chosen. If you cannot name one, that is the problem.",
                "mistake": "Playing ...Nf6 and ...Be7 and hoping the bishop sorts itself out. It never does.",
                "ready": "You choose the bishop's route by move ten, deliberately.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Counterattack rather than defend.",
                "learn": [
                    "The ...f6 break: it opens the f-file, so it belongs to whichever king has already left it. Castle first, break second.",
                    "Queenside play with ...a5, ...Rc8 and the open c-file both c-pawns leave behind when they trade on d4.",
                    "Meeting White's kingside pawn storm: answer a pawn with a pawn (...h5 against g4) and count the centre before you defend the wing.",
                ],
                "drill": "Study ten games where Black wins with ...f6 and ten where ...f6 backfires. Write down the difference.",
                "mistake": "Sitting still. The French is cramped, and a cramped position that never breaks out simply loses slowly.",
                "ready": "You have won a game where White attacked the kingside and you won on the other wing.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Handle the sharp lines and the endgames.",
                "learn": [
                    "The Winawer with its doubled c-pawns, and the Poisoned Pawn — the sharpest bargain in the opening and the one worth knowing from both sides.",
                    "The Tarrasch and the isolated-pawn positions it produces; you need to know both sides of an isolani.",
                    "The Milner-Barry Gambit, from the defending side. Take both pawns — declining is objectively the worse choice — and know 10...a6, because that one move is the difference between being better and being under fire.",
                ],
                "drill": "Learn the Winawer Poisoned Pawn to move fifteen from both sides, even if you never play it. The patterns appear everywhere.",
                "mistake": "Treating the Exchange Variation as an agreed draw. It is symmetrical, not dead — castle on the opposite wing from White, or push the queenside pawns, and it becomes an ordinary game with every piece still on the board.",
                "ready": "You are comfortable against all four of White's third moves and all seven of the second ones.",
            },
        ],
        "study": "Mikhail Botvinnik and Viktor Korchnoi built the modern French — both model games here are Korchnoi's. For sharp modern play, look at Alexander Morozevich and Wesley So.",
        "next": "The French and Caro-Kann share almost every idea, and the Caro-Kann solves the bishop problem by playing ...c6 instead of ...e6. Learning it second is fast and gives you a second answer to 1.e4.",
    },
}
