OPENING = {
    "id": "french",
    "name": "French Defence",
    "eco": "C00–C19",
    "section": "black-e4",
    "orientation": "black",
    "tagline": "A pawn chain, a bad bishop, and a devastating counterattack. Black chooses structure over freedom.",
    "level": "Beginner → Grandmaster",
    "theory": {
        "big_idea": "1...e6 prepares ...d5 with pawn support. Black accepts one real problem — the c8-bishop is locked behind the e6-pawn — in exchange for a rock-solid pawn chain and a very clear plan: attack the base of White's chain with ...c5 and ...f6. The French is the most 'plan-driven' opening in chess. You know from move three exactly what you are doing for the next twenty-five moves.",
        "structure": "The classic French chain: White pawns d4–e5, Black pawns d5–e6. A pawn chain is attacked at its base, so Black plays ...c5 (hitting d4) and later ...f6 (hitting e5). White defends with c3 and f4 and tries to exploit the extra kingside space. Almost every French middlegame is about these two breaks.",
        "white_plans": [
            "Advance Variation (3.e5): grab space, defend d4 with c3 and Nf3, then attack on the kingside with Bd3, Ne2, h4 and Nf4.",
            "Winawer (3.Nc3 Bb4 4.e5): accept doubled c-pawns for the bishop pair and a huge attack with Qg4 hitting g7.",
            "Tarrasch (3.Nd2): avoid the pin, keep the structure clean and play for an isolated-queen's-pawn edge.",
            "Exchange (3.exd5): a solid, symmetrical, drawish structure.",
        ],
        "black_plans": [
            "Hit the base of the chain with ...c5, then ...Qb6 and ...Nc6 piling on d4.",
            "Undermine the front of the chain with ...f6 once the queenside is secure.",
            "Solve the bad bishop: ...b6 and ...Ba6, or ...Bd7–b5, or ...Bd7–e8–h5.",
            "In the Winawer, target White's doubled c-pawns and the dark squares with ...Qa5 and ...Ba6.",
        ],
        "traps": [
            "In the Winawer Poisoned Pawn (6...Ne7 7.Qg4 Qc7 8.Qxg7 Rg8 9.Qxh7 cxd4), Black gives up two kingside pawns for a huge lead in development — one of the sharpest lines in all of chess.",
            "Never play ...cxd4 too early in the Advance; keeping the tension is Black's main source of pressure.",
            "The Milner-Barry Gambit (Advance, 6.Bd3 cxd4 7.cxd4 Bd7 8.O-O Nxd4 9.Nxd4 Qxd4 10.Nc3!) — Black must know how to defend the resulting attack.",
        ],
        "who": "Play this if you like clear structural plans, you do not mind a cramped position, and you want to punish White for over-extending. The French wins more games by counterattack than any other defence.",
    },
    "lines": [
        {
            "name": "Advance Variation — Main Line",
            "note": "White grabs space, Black attacks the base of the chain. The purest illustration of pawn-chain strategy in chess.",
            "moves": "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4",
            "notes": {
                3: "White takes the centre.",
                4: "Now Black challenges it with full pawn support — the point of 1...e6.",
                5: "The Advance Variation. White grabs maximum space and locks the centre. Black's c8-bishop is now definitively the 'bad' bishop.",
                6: "Immediately. A pawn chain is attacked at its base, and d4 is the base of White's chain.",
                7: "Defending d4 with the pawn. Now the whole game is a fight over this one square.",
                8: "Adding a second attacker to d4.",
                9: "Adding a defender.",
                10: "The key French move. The queen hits d4 a third time — and also b2, since the b-pawn is now loose. White cannot defend d4 with the b1-knight (c3 is occupied) or the c1-bishop (b2 hangs).",
                11: "Preparing b4 to gain queenside space and shut Black's pieces out.",
                12: "Note: not ...Nge7, because White would take. The knight goes to h6 heading for f5, where it hits d4 for a fourth time. Ugly-looking, absolutely correct.",
                13: "Grabbing queenside space and preparing Bb2.",
                14: "Black releases the tension at the right moment.",
                15: "Recapturing.",
                16: "The knight lands on f5. It attacks d4, cannot easily be kicked, and Black's pressure on the base of the chain is now maximal.",
                17: "The bishop finally develops, defending d4 from behind.",
                18: "Black develops the bad bishop toward b5 or a4 where it will actually be useful.",
                19: "White must kick the f5-knight, but this weakens the kingside permanently. Both sides have real chances — Black on the queenside and against d4, White with space and a kingside attack.",
            },
        },
        {
            "name": "Winawer — Poisoned Pawn",
            "note": "The sharpest line in the French. Black gives White the bishop pair and grabs the pawns; White gets a monstrous attack.",
            "moves": "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Qg4 Qc7 Qxg7 Rg8 Qxh7 cxd4 Ne2 Nbc6",
            "notes": {
                5: "White develops and defends e4 with a piece rather than pushing past.",
                6: "The Winawer. Black pins the knight, so the e4-pawn is effectively attacked twice and defended once.",
                7: "White pushes past and gains space, unpinning at the cost of committing the centre.",
                8: "The standard break at the base of the chain.",
                9: "Putting the question to the bishop.",
                10: "Black takes, permanently damaging White's structure. White now has doubled c-pawns — a lifelong weakness.",
                11: "Forced. White accepts the doubled pawns in exchange for the bishop pair and the open b-file.",
                12: "Not ...Nc6, because White has Qg4 hitting g7 — and the knight on e7 blocks that check while defending.",
                13: "The critical move. White attacks g7, which is now defended only by the rook.",
                14: "The Poisoned Pawn Variation. Black ignores g7 completely and instead develops, hits e5 and prepares to attack the c-pawns. This is a genuine two-pawn sacrifice.",
                15: "White takes.",
                16: "The rook comes to the open g-file with tempo — this is the compensation.",
                17: "White takes a second pawn. Objectively the position is balanced; practically it is terrifying for both sides.",
                18: "Black cashes in on the queenside and opens lines toward the c3-pawns.",
                19: "The knight develops to e2 (not f3, where ...Qxe5+ ideas and the d4-pawn cause trouble) and defends c3.",
                20: "Black develops with pressure on d4 and e5. One of the most analysed positions in chess: engines say equal, humans say chaos.",
            },
        },
        {
            "name": "Tarrasch Variation",
            "note": "White's modern, low-risk answer. Nd2 avoids the pin at the cost of a slightly passive knight; Black usually gets an isolated pawn.",
            "moves": "e4 e6 d4 d5 Nd2 c5 exd5 exd5 Ngf3 Nc6 Bb5 Bd6 O-O Nge7 dxc5 Bxc5 Nb3 Bd6 Re1",
            "notes": {
                5: "The Tarrasch. The knight blocks its own bishop, but it sidesteps the Winawer pin entirely and keeps White's structure pristine.",
                6: "The most active reply, hitting d4 at once. The alternative 3...Nf6 leads to a completely different closed game.",
                7: "White resolves the tension and heads for an isolated-pawn structure.",
                8: "Recapturing with the pawn keeps the centre and frees the c8-bishop — which solves the French's main problem. That is why the Tarrasch is not so scary.",
                9: "Development.",
                10: "Development.",
                11: "Pinning and pressuring the knight that will have to defend the isolated pawn.",
                12: "Active development. The bishop eyes h2.",
                13: "King safety.",
                14: "Development, defending c6 and preparing ...O-O.",
                15: "White gives Black an isolated d-pawn.",
                16: "Black recaptures with the bishop.",
                17: "Hitting the bishop and preparing to blockade on d4.",
                18: "The bishop returns to its best diagonal.",
                19: "The rook takes the open file. The whole game now revolves around the d5-pawn: White blockades it on d4 and trades pieces, Black uses the extra activity and the open lines to attack. Learn this structure — it appears in dozens of openings.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the French counterattack",
        "note": "White expands on the kingside, Black castles into the safer wing and gets on with attacking d4.",
        "moves": "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7 g4 Nfe7 Nc3 Ng6 h4 h5 g5 Be7 Bd3 O-O-O Na4 Qc7 Rc1 Kb8 Qd2",
        "notes": {
            20: "The knight steps back rather than be captured. It is heading for g6, where it will hit h4 and e5 and help defend the kingside.",
            21: "White finally develops the queen's knight, aiming at b5 and a4.",
            22: "The knight arrives. It attacks e5 and h4 and blocks White's g-pawn from advancing further.",
            23: "White pushes on. The kingside pawns are committed now, which means White's king will not be going there.",
            24: "The correct answer to a pawn storm: stop it with a pawn of your own. Now g5 is the only advance available.",
            25: "White plays it anyway, gaining space and locking the kingside.",
            26: "Development, and the bishop is ready to castle behind.",
            27: "White develops the bishop to its natural diagonal.",
            28: "Black castles queenside — into the side of the board where White has no attack, and next to the c-file Black is about to use.",
            29: "White hits the queen and heads for c5, a strong outpost.",
            30: "The queen steps to the file it wants to fight on.",
            31: "Both sides contest the c-file. Note the shape of the game: White's pawns are on the kingside where nobody lives, Black's pieces are on the queenside where White's king will eventually have to go.",
            32: "Tucking the king safely away and preparing ...Rc8.",
            33: "White connects and prepares to castle long or push in the centre. A rich, unbalanced position — and a perfect illustration of the French bargain: Black's position looked passive for eight moves and is now the one with a clear plan.",
        },
    },
    "progression": {
        "arc": "The French teaches you pawn chains better than any other opening, and pawn chains are the skeleton of positional chess.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Accept the bad bishop and learn the one universal plan.",
                "learn": [
                    "The plan in every French: hit the base of White's chain with ...c5, then the front with ...f6. That is the whole opening.",
                    "The four things White can do on move three: 3.e5 (Advance), 3.Nc3 (Classical/Winawer), 3.Nd2 (Tarrasch), 3.exd5 (Exchange).",
                    "Why ...Qb6 is the key move in the Advance — it hits d4 a third time and b2 at the same time.",
                ],
                "drill": "Play the Advance from the Black side twenty times, aiming only for ...c5, ...Nc6, ...Qb6 and pressure on d4.",
                "mistake": "Trading on d4 too early. The tension on d4 is your entire source of pressure; releasing it hands White a free hand.",
                "ready": "You can explain, without a board, why ...c5 comes before ...Nf6.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Solve the light-squared bishop, permanently.",
                "learn": [
                    "Route 1: ...b6 and ...Ba6, trading it for White's good bishop.",
                    "Route 2: ...Bd7–b5 or ...Bd7–a4, using the queenside.",
                    "Route 3: ...Bd7–e8–h5, the slow route to the kingside.",
                    "Route 4: leave it and play with pieces on the dark squares instead — sometimes correct.",
                ],
                "drill": "In your next ten French games, write down on move ten which route you have chosen. If you cannot name one, that is the problem.",
                "mistake": "Playing ...Nf6 and ...Be7 and hoping the bishop sorts itself out. It never does.",
                "ready": "You choose the bishop's route by move ten, deliberately.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Counterattack rather than defend.",
                "learn": [
                    "The ...f6 break: when it opens the f-file for you and when it just weakens e6.",
                    "Queenside play with ...a5, ...Rc8, ...Na5–c4 and the pressure on c3 or c2.",
                    "Meeting White's kingside attack: ...h6 and ...g6 are usually wrong; counterattack in the centre instead.",
                ],
                "drill": "Study ten games where Black wins with ...f6 and ten where ...f6 backfires. Write down the difference.",
                "mistake": "Sitting still. The French is cramped, and a cramped position that never breaks out simply loses slowly.",
                "ready": "You have won a game where White attacked the kingside and you won on the other wing.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Handle the sharp lines and the endgames.",
                "learn": [
                    "The Winawer with its doubled c-pawns and the Poisoned Pawn — Black's most ambitious try.",
                    "The Tarrasch and the isolated-pawn positions it produces; you need to know both sides of an IQP.",
                    "French endgames: the bad bishop is a real long-term problem, so learn which trades help you.",
                ],
                "drill": "Learn the Winawer Poisoned Pawn to move fifteen from both sides, even if you never play it. The patterns appear everywhere.",
                "mistake": "Fearing the Exchange Variation. It looks drawish; play ...Nf6, ...Bd6, ...O-O and ...c6 and play for a win with the extra tempo pattern.",
                "ready": "You are comfortable against all four of White's third moves.",
            },
        ],
        "study": "Mikhail Botvinnik and Viktor Korchnoi built the modern French. For sharp modern play, look at Alexander Morozevich and Wesley So.",
        "next": "The French and Caro-Kann share almost every idea. Learning the Caro-Kann second is fast and gives you a second answer to 1.e4.",
    },
}
