OPENING = {
    "id": "friedliver",
    "name": "Fried Liver Attack",
    "eco": "C57–C58",
    "section": "traps",
    "orientation": "white",
    "tagline": "A knight lands on f7 and the king walks. Learn to spring it — and to never be its victim.",
    "level": "Beginner → Intermediate",
    "theory": {
        "big_idea": "After 3.Bc4 Nf6 4.Ng5 two white pieces attack f7 and only the king defends it. Everything in this chapter is the argument about that square: Black must block the bishop's diagonal with 4...d5, and the whole trap is what happens to players who recapture on d5 with the knight afterwards — 6.Nxf7! drags the king into the middle of the board on move six. This page teaches the attack from White's chair and the two answers from Black's: the defence that avoids it and the counterattack that ignores it.",
        "structure": "There is no pawn structure to study — that is the point. The centre opens on move five, the e-file and the a2–g8 diagonal are the terrain, and the position is decided by piece activity against a king that has lost the right to castle. The one fixed feature is the d5 square: White's attack is exactly as strong as the pressure on it.",
        "white_plans": [
            "Spring it only in the right order: 4.Ng5 d5 5.exd5, and 6.Nxf7 only after Black has recaptured with the knight. One move early, and the same sacrifice simply loses a piece.",
            "After 6...Kxf7 7.Qf3+ Ke6, pile everything onto the pinned knight: Nc3, d4, Bg5 or O-O — count the defenders of d5 every single move.",
            "Keep lines opening while the king is in the middle: d4 hits e5 so that a capture opens the d-file, and castling long puts the last rook on it.",
            "Against the Traxler 4...Bc5, refuse the bait: 5.Bxf7+! wins a clean pawn with the king stuck on e7. Taking with the knight is what Black is praying for.",
        ],
        "black_plans": [
            "Meet 4.Ng5 with 4...d5 — the only good move, and the reason it works is that it blocks the c4-bishop, which is what makes ...Kxf7 a legal answer to the sacrifice.",
            "Play 5...Na5!, the Polerio Defence: give the d5-pawn back, chase the bishop with ...c6, and take over the game with a lead in development. This is the move that makes the whole Fried Liver a museum piece.",
            "If you do land in the attack, defend by counting: keep three defenders on d5, prefer moves that defend by attacking — 8...Nb4 hits c2 while it guards d5 — and walk the king to d7 and home the moment White stops for breath.",
            "As a counter-trap, the Traxler 4...Bc5!? offers a whole bishop — objectively White stands better by taking with the bishop, but the player who grabs with the knight is defending against mate four moves later.",
        ],
        "traps": [
            "The Fried Liver itself: 4.Ng5 d5 5.exd5 Nxd5?! 6.Nxf7! Kxf7 7.Qf3+ and the king must come forward — 7...Ke8 gives the piece back, 7...Kg8 is mate in three.",
            "The same sacrifice one move early — 5.Nxf7?? before Black recaptures — loses a piece for a pawn: with the pawn still on d5 the bishop's diagonal is blocked and ...Kxf7 is simply legal.",
            "The Traxler tripwire: after 4...Bc5, the greedy 5.Nxf7? walks into 5...Bxf2+! 6.Kxf2 Nxe4+ and it is White's king that gets hunted.",
            "5...Qxd5?? recaptures with the wrong piece: 6.Bxd5 Nxd5 wins the queen, because the bishop on c4 was watching d5 the whole time.",
        ],
        "who": "Everyone below about 1400 meets 4.Ng5 constantly, from both chairs. Learn it as White for the games it wins outright, and as Black so that a ten-move loss can never happen to you. It is also the best first lesson in attacking an uncastled king.",
    },
    "lines": [
        {
            "name": "The Fried Liver, executed",
            "note": "The trap sprung in full: the knight sacrifice on f7, the king dragged to e6, and every white piece arriving at the pinned knight on d5.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nce7 d4 c6 dxe5",
            "tier": "Foundation",
            "drill": True,
            "record": {"at": 11, "games": 425, "white": 76, "draw": 5, "black": 19},
            "plan": {
                "tier": 'Plans',
                "point": 'There is no pawn structure here; there is a black king on e6 and a piece-count that says you must finish the job before Black finishes developing. The engine puts White more than two pawns up after the capture — the attack has stopped being speculative.',
                "next": [
                    'Against 10...Qe8, the engine\'s defence, keep developing into the attack: 11.Be3, and every white piece has a job before move twelve.',
                    'The tempting 10.Bg5 pin instead of the capture lets the whole advantage go — the d-file opening beside the king is worth more than any pin.',
                    'Count the defenders of d5 every single move. The whole attack is one square wide.',
                ],
                "endgame": 'Simplification still favours Black: a knight for two pawns with the queens off is a grind you lose slowly. The +3 on the bar is attack, not material — cash it while the king is still on e6.',
            },
            "notes": {
                6: "The Two Knights Defence. Black ignores the threat to f7 and counterattacks e4 instead — and invites everything this page is about.",
                7: "The trap is set: knight and bishop both hit f7, which only the king defends. Objectively 4.d4 and 4.d3 are just as good — but this is the move that asks Black the question, and below master level the question wins games.",
                8: "The only good move, and the reason is precise: it blocks the c4-bishop's diagonal, which is what makes ...Kxf7 a legal reply to the coming sacrifice. Every piece move that 'defends' f7 instead loses material on the spot — the deviation panel walks through each one.",
                9: "Taking, and setting the real fork in the road for Black.",
                10: "The move that walks in. It looks like the most natural recapture on the board, and 5...Na5! — giving the pawn up to chase your bishop — is the move that would have ended the attack before it starts.",
                11: "The Fried Liver. A whole knight for one pawn, to drag the black king into the centre on move six. From here you are committed: this only works if every move adds an attacker.",
                12: "Effectively forced. The knight forks d8 and h8, so declining costs the queen or a rook — the deviation panel shows both.",
                13: "The point of the sacrifice. The check forces the king forward: 7...Ke8 hands the piece back with interest, and 7...Kg8 walks into mate in three.",
                14: "The only square, and the picture to remember: the king on e6 is not defending your attack away — it is tied to the knight on d5, which is pinned against it by your bishop.",
                15: "A third attacker on the pinned knight. Black can only keep adding defenders.",
                16: "The old book move: it does hold d5 a third time. The engine prefers 8...Nb4, defending d5 and hitting c2 at once — reinforcing is the human instinct, counter-attacking is the machine's, and the Black chapter of this page drills the machine's.",
                17: "Opening lines toward the king. Count it honestly: you are a knight for a pawn down — two pawns' worth of material — and every single white piece is pouring in.",
                18: "Propping up the knight again. Black has no other plan: everything is chained to d5.",
                19: "The capture the d4-push existed for: the d-file opens with the black king standing beside it, and the e5-square becomes White property. Do not reach for the Bg5 pin instead — the engine's verdict drops from over two pawns to nothing, because the file matters more than any pin.",
            },
        },
        {
            "name": "Polerio Defence — 5...Na5!",
            "note": "Black's cure, drilled from Black's chair: give the pawn back, chase the bishop, and let the lead in development do the arguing.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Be2 h6 Nf3 e4 Ne5 Bd6",
            "tier": "Structure",
            "drill": True,
            "side": "black",
            "record": {"at": 10, "games": 6374, "white": 42, "draw": 18, "black": 40},
            "plan": {
                "tier": 'Structure',
                "point": 'You are a pawn down and it does not matter: the bishop that owned the a2–g8 diagonal has been chased to e2, the knight that raided f7 has been kicked back to e5, and every one of your pieces develops with a threat attached.',
                "next": [
                    'After 11.d4 exd3 12.Nxd3, keep the initiative: ...Qc7 hits h2 and e5 at once, then ...O-O and the rooks come to the open files.',
                    'The c6-pawn is not weak yet — it guards d5 and b5. Only ...c5, in your own time, when the knight on e5 has been dealt with.',
                    'The a5-knight comes home via c4 or b7. Do not leave it on the rim once its job — evicting the bishop — is done.',
                ],
                "endgame": 'A pawn down with the bishop pair and every file for your rooks is a draw you have to work for — which is why you keep the queens on and play for the attack instead. Trade pieces only when a trade wins the pawn back.',
            },
            "notes": {
                6: "The Two Knights: you invite 4.Ng5 on purpose, because you know the answer and most of the people who play it do not.",
                7: "The question: two pieces on f7, one defender. Do not panic — this move has a refutation, and you are about to play it.",
                8: "The only good move. It blocks the bishop's diagonal — nothing else deals with both attackers. Play it instantly, every time.",
                9: "Taking. Now comes the move this whole line exists for.",
                10: "The Polerio Defence, and the move that killed the Fried Liver at every level above the playground. You offer the d5-pawn permanently: what you buy is the bishop chased off the diagonal, the knight about to be kicked, and three free developing moves.",
                11: "The best try — check first, so the bishop escapes the ...c6 fork with tempo. 6.d3 and 6.Be2 are the quiet admissions that Black is fine.",
                12: "Blocking with the pawn you were going to play anyway. The bishop must now choose a bad square.",
                13: "White grabs the pawn while it is there. This is the honest accounting: White is a pawn up and will spend the next five moves undeveloping.",
                14: "Recapture toward the centre. Your queenside pawns are ugly and irrelevant; the half-open b-file is not.",
                15: "The bishop's best retreat, and look at it: from the diagonal that attacked f7 to a square where it stands in its own queen's way. That is what your knight on a5 bought.",
                16: "Kick the raider before it settles. Every move of this defence attacks something.",
                17: "Retreat — 9.Nh3 runs into ...Bxh3 wrecking the kingside pawns.",
                18: "The pawn advances with tempo again: the knight on f3 must move a second time. Count White's developed pieces when it lands on e5: one, and it is about to be hit a third time.",
                19: "The knight finds its only active square. Now comes the move that shows why Black is better developed a pawn down.",
                20: "Development with a threat — the bishop hits e5 and eyes h2 behind it. White's extra pawn sits on c6 doing nothing; every Black piece is pointing at the kingside. This is what 'compensation' means, drawn in one diagram.",
            },
        },
        {
            "name": "Surviving it as Black",
            "note": "You recaptured with the knight and the sacrifice came. The defence exists — this is it, move by engine-checked move.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nb4 O-O c6 d4 Qf6 Qd1 Ke7",
            "tier": "Mastery",
            "drill": True,
            "side": "black",
            "plan": {
                "tier": 'Mastery',
                "point": 'You are a piece up and the position is still only equal — that is the price of the king on e6. The defensive rules that got you here are the ones that get you out: defend by attacking, keep three defenders on d5, and walk the king home the moment White stops giving checks.',
                "next": [
                    'The king leaves through the back door — e7, then d8 or f7 as the position asks. Not d7: with the d-file half-open, d7 walks straight into dxe5 and Bxd5 tricks.',
                    'Give the knight back at the right moment: ...Nxc2 or ...Nxd4-ideas that trade into a position where your king is safe convert the attack into a material count.',
                    'The move to fear is a rook arriving on e1 or d1 with tempo. Meet every lift by asking what it attacks — most of White\'s moves from here are threats only if you panic.',
                ],
                "endgame": 'Every trade helps you. A piece up with the queens off is not a defence any more, it is a win — which is why White must refuse every exchange and why you offer them.',
            },
            "notes": {
                6: "The Two Knights. This chapter assumes the worst: you will meet the sacrifice head-on and survive it.",
                7: "The attack on f7 you know from the White chapter. You also know the answer.",
                8: "Always this. It blocks the bishop, which is the whole defence in one move.",
                9: "Taking. Here 5...Na5! avoids everything — that line has its own chapter. This one is about what happens when you take.",
                10: "The natural move, and the one theory calls dubious. Play the Polerio instead when you can — but every club player takes here sooner or later, so learn what comes next.",
                11: "The sacrifice. Do not decline it: the knight forks d8 and h8, so refusing costs the queen or a rook. Take, and defend with a piece for a pawn in the bank.",
                12: "Take it. The compensation is White's; the material is yours — keep the accounting straight and you will make the right choices.",
                13: "The check that drags you forward. Both retreats lose: 7...Ke8 8.Bxd5 hands the piece back with interest, 7...Kg8 8.Bxd5+ is mate in three.",
                14: "Forward, to the only square that holds the knight. This feels terrifying; the engine prices White's whole attack at well under a pawn. Trust the count: you are up a piece for a pawn, and every defensive move you find keeps it that way.",
                15: "The third attacker arrives on d5. Now the move that separates this line from the old books.",
                16: "The engine's defence, and the shape to memorise: the knight defends d5 a third time and attacks c2 at the same time. Defending by attacking — White must now spend a move on the threat of ...Nxc2, and a move is exactly what the attack cannot spare.",
                17: "Sidestepping ...Nxc2. The rook is coming to e1 or d1; your next moves must make luft for the king before it arrives.",
                18: "A fourth defender of d5, and a flight square on c7. The pawn move you were told never to make in an opening is correct here: this is not an opening any more, it is a rescue.",
                19: "Opening the centre — the last wave of the attack.",
                20: "The queen steps up to block the file and offer the trade White must refuse. Every offered exchange is a defensive move when you are the one with the extra piece.",
                21: "The retreat that admits it: with queens about to come off, the attack is over.",
                22: "And the king simply steps back. Not to d7 — the half-open d-file makes that square a tactic — but toward home, where the h8-rook finally rejoins the game. White's best from here trades the attack back into a knight-against-pawns material balance; the mating pressure is gone, and the pressure was the only thing you were ever defending against.",
            },
        },
        {
            "name": "Traxler Counterattack",
            "note": "Black's counter-trap: ignore f7, offer the bishop, and hunt the white king instead. Objectively risky — practically lethal against the greedy.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5 Nxf7 Bxf2+ Kxf2 Nxe4+ Kg1 Qh4 g3 Nxg3 hxg3 Qxg3+ Kf1 Rf8",
            "tier": "Mastery",
            "drill": True,
            "side": "black",
            "record": {"at": 8, "games": 514, "white": 40, "draw": 18, "black": 42},
            "plan": {
                "tier": 'Mastery',
                "point": 'Be honest about what this is: against 5.Bxf7+! the engine gives White a clean pawn and the better game, and you are playing on practical chances. Against 5.Nxf7 — a third of master games, and far more below that — you have a forced attack that wins far more often than it should.',
                "next": [
                    'The rook on f8 pins the knight that started it all. ...d5 comes next, opening the c8-bishop with tempo, and White\'s extra rook sits on h1 watching.',
                    'Every move must check or threaten mate. The moment White consolidates, the material count wins — you are betting the game on never giving a free move.',
                    'If the attack peters into a queen trade, take the perpetual. A draw from a lost opening against a greedy opponent is the Traxler working as designed.',
                ],
                "endgame": 'There is none worth having: simplification is defeat. The whole line is a promise never to reach one.',
            },
            "notes": {
                6: "The Two Knights move order — but this time you have no intention of playing ...d5.",
                7: "The trap White thinks is being set. You are about to set the other one.",
                8: "The Traxler. You ignore the attack on f7 entirely and aim your bishop at f2 — the mirror of White's target. Know the honest verdict before you play it: 5.Bxf7+! keeps a safe extra pawn, and everything else is your attack.",
                9: "The greedy move, and a third of your opponents play it: the fork on d8 and h8 looks like it wins on the spot. It does not — from this square the knight never gets home, and Black's next move shows why f2 mattered more than f7.",
                10: "The point. The king must take — declining leaves Black a free path to a huge attack with the bishop already in the walls.",
                11: "Taken. Now the king on f2 stands where your knight and queen can reach it.",
                12: "The knight joins with check, opening the queen's diagonal to h4. White's king has no good square: this line follows the natural retreat, and the deviation panel prices the alternatives — including the computer's cold-blooded 7.Ke3.",
                13: "Back home — natural, and it walks into the attack this line drills to the end.",
                14: "The queen arrives with mate on f2 in the air. White has exactly one defence.",
                15: "Forced: only the pawn can block the h4–f2 road.",
                16: "Ripping the cover off. The knight has done its work on e4; it dies opening the g-file.",
                17: "Recapturing — and now the g3-pawn is a target with a rook's pension behind it.",
                18: "Check, and the harvest begins: the g3-pawn is gone, the king is naked on f1, and the h1-rook is a spectator for the rest of the game.",
                19: "The only square. Note what White's extra material is doing: the rook on h1 and the bishop on c1 have not moved and will not.",
                20: "The quiet move that ends the forcing sequence: the rook pins the f7-knight against the king and every Black piece aims at a bare king. Material says White; every practical factor says Black. That bargain is the Traxler.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the attack cashes in",
        "note": "The main attack, four plies further along the engine's own line: Black's queen runs for g6, and White simply finishes developing into the open files.",
        "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nce7 d4 c6 dxe5 Qe8 Be3 b5 Bb3",
        "notes": {
            20: "The engine's defence: the queen leaves the d-file the capture just opened and heads for g6, where trading queens would end the attack.",
            21: "No forcing move helps yet, so the last minor piece develops. This is the discipline of the whole line: every quiet move that adds a piece is worth more than a check that spends one.",
            22: "Black's only gesture at counterplay: hit the bishop before it settles. Nothing about the position changes.",
            23: "Keep the diagonal — the pin on d5 runs through b3 exactly as it ran through c4. Count the square one more time: three attackers against a pawn, a knight and a king, and it is White to develop the rooks. This is what winning the opening argument looks like with the king still on e6.",
        },
    },
    "branches": {
        # ── ply 7 · White's fourth move — the calmer roads ──────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6": [
            {"san": "d4", "severity": "playable", "tier": "Plans",
             "why": "The modern anti-theory choice: 4...exd4 5.O-O and Black cannot fall back on memorised Polerio and Fritz lines. At depth twenty it is level with 4.Ng5 — what it buys is a game nobody has prepared.",
             "line": "exd4 e5 Ne4 Qe2 Nc5 O-O"},
            {"san": "d3", "severity": "playable", "tier": "Foundation",
             "why": "The quiet move the top players prefer, transposing to the slow Italian: Black plays ...Bc5 or ...Be7 and no piece gets sacrificed on f7 by anybody.",
             "see": "italian"},
        ],

        # ── ply 8 · after 4.Ng5 — the whole chapter in one panel ────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5": [
            {"san": "Bc5", "severity": "playable", "tier": "Mastery",
             "name": "Traxler Counterattack",
             "why": "Black ignores f7 completely and offers a whole piece for the attack. Against the greedy 5.Nxf7? it is White who defends for their life. The safe answer is 5.Bxf7+!: a pawn up, and it is Black's king that has moved.",
             "line": "Bxf7+ Ke7 Bb3 Rf8 d3",
             "see": "friedliver#traxler"},
            {"san": "d5", "severity": "playable", "tier": "Foundation",
             "why": "The main road, and the only move that answers both attackers on f7: it blocks the bishop's diagonal, which is what makes ...Kxf7 legal against the sacrifice. The rest of this page lives on the other side of it.",
             "see": "friedliver#executed"},
            {"san": "h6", "severity": "blunder", "tier": "Foundation",
             "why": "The move club players actually reach for, and it loses material on the spot, because kicking the knight is not the same as guarding f7. 5.Nxf7! and Black cannot take — the c4-bishop covers the square. The knight forks d8 and h8, so 5...Qe7 6.Nxh8 is a rook and a pawn for a knight.",
             "line": "Nxf7 Qe7 Nxh8"},
            {"san": "d6", "severity": "blunder", "tier": "Foundation",
             "why": "This is the move that proves why 4...d5 is forced. f7 is attacked twice and defended once, and ...d6 does nothing about it: 5.Nxf7! Qe7 6.Nxh8 wins the exchange and a pawn. Only 4...d5 blocks the c4-bishop — and blocking that diagonal is the entire defence.",
             "line": "Nxf7 Qe7 Nxh8"},
            {"san": "Be7", "severity": "blunder", "tier": "Foundation",
             "why": "The instinctive defensive move, and it loses on the spot: 5.Nxf7! and Black cannot take, because the c4-bishop covers f7 too. 5...Kf8 6.Nxd8 Nxd8 hands over the queen for a knight.",
             "line": "Nxf7 Kf8 Nxd8 Nxd8"},
            {"san": "Nxe4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Grabbing the pawn and forgetting the diagonal. 5.Bxf7+! Ke7 6.d4! opens the centre while the king stands in it: material comes out level and Black has paid with the right to castle and a king on the walk.",
             "line": "Bxf7+ Ke7 d4 h6 Nxe4 Kxf7"},
        ],

        # ── ply 9 · your own fifth move — three ways to lose a piece ────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5": [
            {"san": "d3", "severity": "blunder", "tier": "Foundation",
             "why": "Propping up e4 and forgetting what ...d5 attacked: 5...dxc4! and the bishop goes. Black's fourth move hit the e4-pawn and the c4-bishop at once, and only one of them can be saved by a pawn move.",
             "line": "dxc4 dxc4"},
            {"san": "Bxd5", "severity": "blunder", "tier": "Foundation",
             "why": "Taking with the bishop drops the knight on g5: 5...Nxd5 6.exd5 Qxg5! — the queen on d8 was watching g5 the whole time, and once the bishop leaves c4 there is nothing on f7 to distract her. 7.dxc6 Qxg2 8.Rf1 gets the piece back and loses the position: king stuck, rook on f1, queen loose in your camp.",
             "line": "Nxd5 exd5 Qxg5 dxc6 Qxg2"},
            {"san": "Nxf7", "severity": "blunder", "tier": "Foundation",
             "why": "The Fried Liver played one move early, and it is not the same move at all: with the pawn still on d5 the c4-bishop's diagonal is blocked, so 5...Kxf7 is simply legal and Black is a piece up for a pawn. Take on d5 first. That is the entire difference between the attack and the blunder.",
             "line": "Kxf7 exd5 b5 Bf1 Nd4"},
        ],

        # ── ply 10 · after 5.exd5 — the real fork in the road ────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5": [
            {"san": "Na5", "severity": "playable", "tier": "Structure",
             "name": "Polerio Defence",
             "why": "Black's best, and the move that ends the Fried Liver: the pawn is given up to chase the bishop off the a2–g8 diagonal, and Black gets a huge lead in development for it. Drilled move by move in its own line.",
             "line": "Bb5+ c6 dxc6 bxc6 Be2 h6 Nf3 e4 Ne5",
             "see": "friedliver#polerio"},
            {"san": "Nxd5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The most natural recapture on the board, and the trap's front door: 6.Nxf7! drags the king out, and even the quieter 6.d4! keeps a grip Black never fully shakes. If you must live here, the survival line is drilled from Black's chair on this page.",
             "line": "Nxf7 Kxf7 Qf3+ Ke6 Nc3",
             "see": "friedliver#surviving"},
            {"san": "Nd4", "severity": "playable", "tier": "Mastery",
             "name": "Fritz Variation",
             "why": "The sharpest of the lot: 6.c3 b5 7.Bf1 Nxd5 8.cxd4 Qxg5 and both kings end up in trouble at once. Do not walk into this without having looked at it — nobody finds these moves at the board.",
             "line": "c3 b5 Bf1 Nxd5 cxd4 Qxg5"},
            {"san": "b5", "severity": "playable", "tier": "Mastery",
             "name": "Ulvestad Variation",
             "why": "The same idea by a different door — deflect the bishop first, then take on d5. After 6.Bf1 Nd4 it usually transposes straight into the Fritz.",
             "line": "Bf1 Nd4 c3 Nxd5 cxd4 Qxg5"},
            {"san": "Qxd5", "severity": "blunder", "tier": "Foundation",
             "why": "Recapturing with the wrong piece, and it costs the queen: d5 is guarded by the bishop, so 6.Bxd5! Nxd5 is a queen for a bishop. The knight recapture has the queen on d8 behind it; a queen on d5 has nothing behind her at all.",
             "line": "Bxd5 Nxd5 d4"},
        ],

        # ── ply 11 · your own sixth move — the Fried Liver or Fischer's move ────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5": [
            {"san": "d4", "severity": "playable", "tier": "Plans",
             "name": "Lolli Attack",
             "why": "The quieter road to the same attack, and at depth twenty the engine cannot separate it from 6.Nxf7. Fischer thought 6.d4! was so strong that 5...Nxd5 is barely played any more: you keep the knight, open the centre against a king that cannot castle, and Nxf7 is still there next move.",
             "line": "Nxd4 c3 b5 Bd3 h6 Nxf7"},
            {"san": "O-O", "severity": "inaccuracy", "tier": "Structure",
             "why": "Losing the thread. 6...Qxg5! wins the knight — it was only ever safe while it threatened f7 — and 7.Bxd5 gets the piece back at the price of the attack: dead level, with nothing left to play for.",
             "line": "Qxg5 Bxd5 Bd7 d4 Qg6"},
            {"san": "Bxd5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Trading the best piece in the opening for the knight it was attacking. 6...Qxd5 7.O-O Bf5 and Black is better: the queen sits safely on d5 now that no bishop looks at it, and the knight on g5 has to run.",
             "line": "Qxd5 O-O Bf5 d3 O-O-O"},
        ],

        # ── ply 12 · after 6.Nxf7 — declining costs more ────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7": [
            {"san": "Ke7", "severity": "blunder", "tier": "Foundation",
             "why": "Declining costs the queen: 7.Nxd8 Kxd8 and White has a queen for a knight. When a knight lands on f7 and hits d8 and h8 at once, the only question left is which one you can afford to lose.",
             "line": "Nxd8 Kxd8"},
            {"san": "Qe7", "severity": "blunder", "tier": "Foundation",
             "why": "Saving the queen loses more than the rook — take in the right order: 7.Bxd5! wins the pinned knight first, 8.Bxc6+ collects its brother with check, and the h8-rook is still there afterwards. Grabbing the rook at once lets Black's pieces out; the bishop harvest does not.",
             "line": "Bxd5 Bf5 Bxc6+ bxc6 Nxh8"},
        ],

        # ── ply 14 · after 7.Qf3+ — the king must go forward ────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+": [
            {"san": "Ke8", "severity": "blunder", "tier": "Foundation",
             "why": "Running backwards loses the piece back: 8.Bxd5 and White is a pawn up with a black king that will never castle. Worse, 8...Qxd5?? 9.Qxd5 drops the queen outright — nothing else on the board guards d5.",
             "line": "Bxd5"},
            {"san": "Kg8", "severity": "blunder", "tier": "Foundation",
             "why": "8.Bxd5+, and this one is not merely the piece back — it is mate: 8...Qxd5 9.Qxd5+ Be6 10.Qxe6#. Tucking the king into the corner puts it on the a2–g8 diagonal, which is the one place in this whole opening you must never stand.",
             "line": "Bxd5+ Qxd5 Qxd5+ Be6 Qxe6#"},
            {"san": "Kg6", "severity": "blunder", "tier": "Foundation",
             "why": "Walking toward the attack. Take the piece first: 8.Bxd5! Qf6 9.Qg3+ Qg5 10.Qxg5+ Kxg5 11.d3+ and the pawn move uncovers the c1-bishop — one pawn up with the queens off and the black king on g5 among all your pieces. The move that does not work is the natural 8.Qf5+??, because the d-pawn is gone and the c8-bishop has a clear road to f5: 8...Bxf5 wins the queen.",
             "line": "Bxd5 Qf6 Qg3+ Qg5 Qxg5+ Kxg5 d3+"},
        ],

        # ── ply 16 · after 8.Nc3 — the two ways to hold d5 ──────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3": [
            {"san": "Nce7", "severity": "inaccuracy", "tier": "Structure",
             "why": "The old book move, and the one the White chapter follows, because a century of miniatures did: it holds d5 a third time and concedes nearly two pawns of evaluation to 9.d4. Passive defence against a piece sacrifice is how the sacrifice gets paid for.",
             "see": "friedliver#executed"},
            {"san": "Nb4", "severity": "playable", "tier": "Mastery",
             "why": "The engine's defence and the better one — d5 is defended and c2 is attacked in the same move, so White must spend a tempo the attack cannot spare. The survival line on this page drills it from Black's chair.",
             "line": "O-O c6 d4 Qf6 Qd1",
             "see": "friedliver#surviving"},
            {"san": "Nd4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Hitting the queen looks like a tempo and it abandons d5. 9.Bxd5+! Kd7 10.Qd1 c6 11.Be4 and the king walks to c7 with White a pawn up and every piece still pouring in. Count the defenders of d5 before you touch anything else.",
             "line": "Bxd5+ Kd7 Qd1 c6 Be4"},
        ],

        # ── ply 9 (Traxler) · your own fifth move after 4...Bc5 ─────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5": [
            {"san": "Bxf7+", "severity": "playable", "tier": "Mastery",
             "why": "The refutation, as far as one exists: take with the bishop, not the knight. 5...Ke7 6.Bb3 and White is a clean pawn up with the black king stuck on e7 — the engine's verdict on the whole Traxler, and the reason it is a weapon rather than a repertoire.",
             "line": "Ke7 Bb3 Rf8 d3"},
            {"san": "d4", "severity": "playable", "tier": "Mastery",
             "why": "Declining by counter-strike: the centre opens and the c5-bishop is hit, so Black has no time for ...Bxf2 ideas. Sound, but it lets Black back into a normal sharp game — 5.Bxf7+ is the move that keeps the extra pawn.",
             "line": "exd4 O-O"},
        ],

        # ── ply 11 (Traxler) · after 5.Nxf7 Bxf2+ — take, or step aside ─────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5 Nxf7 Bxf2+": [
            {"san": "Kf1", "severity": "playable", "tier": "Mastery",
             "why": "Declining is just as sound as taking: the king steps off the check-to-come, the f2-bishop must retreat or be lost, and after 6...Qe7 7.Nxh8 d5 the engine calls the madness dead level. What it costs is only the brilliancy — and Black's whole setup was priced for the taking.",
             "line": "Qe7 Nxh8 d5 exd5 Nd4"},
            {"san": "Ke2", "severity": "blunder", "tier": "Mastery",
             "why": "The one square that loses: 6...Nd4+! arrives with tempo — the knight hits the king and covers the escape squares, and by the time the king finds shelter Black's attack has paid for the bishop twice over.",
             "line": "Nd4+ Kf1 Qe7"},
        ],

        # ── ply 13 (Traxler) · after 6.Kxf2 Nxe4+ — the king's choice ───────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5 Nxf7 Bxf2+ Kxf2 Nxe4+": [
            {"san": "Ke3", "severity": "playable", "tier": "Mastery",
             "why": "The computer's move: walk the king INTO the storm, hold everything tactically, and keep the material argument alive. It holds at depth twenty and it has rarely worked for a human with a clock running — the Traxler bargain stated as a chess move.",
             "line": "Qh4 g3 Nxg3 hxg3 Qd4+ Kf3"},
            {"san": "Kf1", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The one honest-looking square that concedes something real: 7...Qh4 8.Qe1 Ng3+! 9.Qxg3 Qxc4+ forks king and bishop — the knight vacates e4 with check and the queen harvests along the rank. Two pawns of evaluation, given up by a king move that looks identical to the right ones.",
             "line": "Qh4 Qe1 Ng3+ Qxg3 Qxc4+"},
        ],
    },
    "progression": {
        "arc": "One square, three chapters: spring the attack as White, defuse it as Black, and know the counter-trap from both chairs.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Your first session",
                "goal": "Own the move order as White and never lose to it as Black.",
                "learn": [
                    "The order that makes the sacrifice work: Ng5 hits f7, ...d5 blocks, exd5, and Nxf7 only after ...Nxd5. One move early and it loses a piece.",
                    "Why 4...d5 is the only defence: it is not about defending f7, it is about making ...Kxf7 legal.",
                    "The two declines that lose on the spot: a king move drops the queen to Nxd8, a queen move drops the rook to Nxh8.",
                ],
                "drill": "Play the main line twenty times as White against an engine on low strength. Then flip the board and play 4...d5 5.exd5 Na5 twenty times as Black. The point is that neither side ever has to think before move six.",
                "mistake": "Playing 5.Nxf7 before Black has recaptured on d5. Count it every time: if the pawn still stands on d5, the bishop does not see f7 and the sacrifice is just a lost piece.",
                "ready": "You can say, without the board, why the sacrifice works after 5...Nxd5 and fails after 4...d5.",
            },
            {
                "tier": "Structure",
                "when": "Week two",
                "goal": "Make the Polerio your automatic answer as Black.",
                "learn": [
                    "The Polerio sequence to move ten: 5...Na5 6.Bb5+ c6 7.dxc6 bxc6 8.Be2 h6 9.Nf3 e4 10.Ne5 Bd6 — every Black move develops or attacks.",
                    "What the pawn bought: the bishop that owned f7 is on e2 blocking its own pieces, and Black's lead in development is permanent.",
                    "Which White deviations matter: 6.d3 and 6.Be2 decline the argument, and Black simply stands well.",
                ],
                "drill": "Drill the Polerio line until the ...c6 fork and the ...e4 kick are reflexes. Then play it against an engine that varies White's sixth move.",
                "mistake": "Trying to hold the d5-pawn with ...c6 before ...Na5. The pawn is the price of the position — pay it.",
                "ready": "You reach move ten of the Polerio from memory and can name what each Black move attacked.",
            },
            {
                "tier": "Mastery",
                "when": "When the pattern is automatic",
                "goal": "Survive the attack from inside, and carry the counter-trap.",
                "learn": [
                    "The survival line: 8...Nb4! and the defend-by-attacking rule, then the king walk to d7 once the checks stop.",
                    "The Traxler from Black's chair: the forced attack after 5.Nxf7 Bxf2+, and the honest verdict against 5.Bxf7+.",
                    "The Traxler from White's chair: one move — 5.Bxf7+! — and the discipline to play the pawn-up middlegame instead of the brilliancy.",
                ],
                "drill": "Set the position after 8.Nc3 and defend it as Black against the engine, once with 8...Nce7 and once with 8...Nb4. Lose it a few times; the defensive rules only stick after the king has been mated on e6.",
                "mistake": "Learning the Traxler's fireworks and not the refutation. Half the players who face your Traxler will play 5.Bxf7+, and you need a plan for a long game a pawn down.",
                "ready": "You have won with the attack as White, held it as Black, and know which chair you would rather be sitting in.",
            },
        ],
        "study": "Polerio's own analysis is four centuries old and still the last word on 5...Na5. For the attack, any collection of miniatures in the Two Knights; for the Traxler, the correspondence games of Karel Traxler himself.",
        "next": "The Italian Game chapter is this opening grown up: the same bishop, the same square, and the slow version of the same argument.",
    },
}
