OPENING = {
    "id": "italian",
    "name": "Italian Game",
    "eco": "C50–C54",
    "section": "white-e4",
    "orientation": "white",
    "tagline": "Bishop to c4, eyes on f7. The oldest opening still played at the top level.",
    "level": "Beginner → Master",
    "theory": {
        "big_idea": "White develops the light-squared bishop to its most aggressive diagonal (a2–g8) where it stares at f7. f7 is the weakest point in Black's position because it is defended only by the king. Everything else in the Italian flows from that one bishop: whether White builds a big pawn centre with c3 and d4, sacrifices a pawn to rip open lines, or plays a slow build-up and attacks later.",
        "structure": "Symmetrical e-pawns on e4/e5 with pawns still on d2/d7. This is the classic 'Open Game' skeleton. The tension is over whether White gets in d2–d4 under good circumstances. If White does, the position opens and development counts. If Black stops it, the game becomes a slow manoeuvring battle where knight routes decide everything.",
        "white_plans": [
            "Play c3 then d4, building the ideal pawn duo on d4+e4 and opening lines while ahead in development.",
            "The modern slow build: d3, O-O, Re1, Nbd2–f1–g3, then h3 and a delayed d4. White keeps the tension for twenty moves and outmanoeuvres Black.",
            "Direct attack on f7 with Ng5 (in the Two Knights) or a pawn sacrifice with b4 (Evans Gambit) to seize the centre by force.",
            "Rook lift Re1–e3–g3 or a kingside pawn storm once Black's counterplay on the queenside is contained.",
        ],
        "black_plans": [
            "Mirror the setup with ...Bc5, ...d6, ...Nf6, ...O-O and hold the centre; then re-route a knight via ...Ne7–g6 or hit back with ...d5.",
            "Play the sharp ...Nf6 (Two Knights) inviting 4.Ng5 and answering with the Polerio counter-gambit 4...d5 5.exd5 Na5!",
            "Retreat the bishop to a7 in advance so that White's d4 never comes with tempo.",
            "Trade off White's strong Italian bishop with ...Na5 or ...Be6.",
        ],
        "traps": [
            "The Fried Liver Attack: 3...Nf6 4.Ng5 d5 5.exd5 Nxd5?? 6.Nxf7! Kxf7 7.Qf3+ and Black's king is dragged into the open. Black must play 5...Na5!",
            "The Legal Trap pattern: if Black pins with ...Bg4 and grabs too greedily, White can sometimes sacrifice the queen with Nxe5 followed by Bxf7+ and Nd5#.",
            "Blackburne Shilling Trap (Black's trap): 3...Nd4?! 4.Nxe5?? Qg5! 5.Nxf7 Qxg2 6.Rf1 Qxe4+ and White collapses. Correct is 4.Nxd4.",
        ],
        "who": "Play this if you like clear, natural development and open positions where tactics decide. It teaches you more about basic chess principles than any other opening.",
    },
    "lines": [
        {
            "name": "Giuoco Pianissimo — Main Line",
            "note": "The modern main line. White plays d3 instead of d4 and manoeuvres slowly. This is what Carlsen, Caruana and Nepomniachtchi actually play.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3 Ne7 d4",
            "notes": {
                5: "The Italian bishop takes aim at f7 and controls the a2–g8 diagonal, the fastest route into Black's position.",
                6: "Black mirrors. Now both bishops stare at the opponent's weakest square — f7 and f2. This is the Giuoco Piano, 'the quiet game'.",
                7: "Preparing d2–d4 to build the ideal centre. The cost: the c3-pawn takes the natural square away from the b1-knight, which will have to go the long way round via d2.",
                8: "Develops and attacks e4. Black gains a tempo while completing kingside development.",
                9: "The modern choice. Instead of the immediate 5.d4, which lets Black liquidate, White props up e4 and prepares a much better version of d4 later. Nicknamed the Giuoco Pianissimo — 'the very quiet game'.",
                10: "Solid. It supports e5 and opens a path for the c8-bishop. Black is in no rush.",
                11: "King safety first. Notice that both sides have followed the same three rules: control the centre, develop, castle.",
                12: "Black completes the same plan one move behind.",
                13: "The rook goes behind the e-pawn. It looks passive now, but the moment the e-file opens it will be the best-placed piece on the board.",
                14: "A tiny move with three jobs: it stops Bb5 and Nb5 forever, prepares ...b5 to kick the bishop, and clears a6 for a piece.",
                15: "The knight begins its famous journey: d2–f1–g3 (or e3). It takes three moves, but on g3 it supports f5 and h5 and joins a kingside attack. This manoeuvre was borrowed straight from the Ruy Lopez.",
                16: "The bishop steps off the a7–g1 diagonal's firing line before White plays d4 with tempo. Prophylaxis: stopping the opponent's idea before it exists.",
                17: "Luft for the king and, more importantly, control of g4 so that Black can never pin the f3-knight with ...Bg4.",
                18: "Black re-routes too: the knight is heading for g6 where it eyes f4 and h4 and helps defend the kingside.",
                19: "At last. White has spent nine moves preparing this single pawn push, and now it comes with every piece supporting it. This is the whole point of the slow Italian: play the break only when it is unanswerable.",
            },
        },
        {
            "name": "Evans Gambit",
            "note": "White throws a pawn at Black on move four to gain time and build a huge centre. Beloved by Morphy, Kasparov and every attacking player since.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O dxc3 Qb3 Qf6 e5 Qg6",
            "notes": {
                7: "The Evans Gambit! White offers the b-pawn purely to deflect the bishop, so that c3 comes with tempo and White gets the centre for free.",
                8: "Declining with 4...Bb6 is respectable, but taking is the critical test — and the point of studying gambits is to know what happens when they are accepted.",
                9: "Now this comes with gain of time because the bishop is attacked. White has effectively bought a tempo for a pawn.",
                10: "The main retreat, keeping the bishop active on the a5–e1 diagonal. 5...Bc5 and 5...Be7 are the alternatives.",
                11: "The dream centre. For one pawn White has pawns on d4 and e4, a developed bishop and a lead in development.",
                12: "Black grabs again. Greedy, but Black must take something for the coming attack to be worth it.",
                13: "Castling before recapturing. Development and king safety are worth more than a pawn here.",
                14: "Black is now two pawns up and about to be very uncomfortable.",
                15: "Double attack: the queen hits both f7 and, along with the bishop, the whole a2–g8 diagonal. Black must find precise defence.",
                16: "Defending f7 and hitting f2 — the only good square.",
                17: "Kicking the queen with tempo and clinching the centre. White has huge activity for the two pawns; engines call it roughly balanced, but in a real game it is far easier to play White.",
                6: "Black mirrors. Both bishops now stare at the opponent's weakest square, f7 and f2. This is the Giuoco Piano — and the position White wants for the Evans.",
                18: "The only square. Now White plays Re1, Ba3 and Nbd2 with a raging initiative. Practically speaking, most club players lose this as Black.",
            },
        },
        {
            "name": "Two Knights — Fried Liver Attack",
            "note": "The most famous attacking pattern in beginner chess. Learn it from both sides: it wins games, and knowing it stops you losing in ten moves.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nce7 d4 c6 Bg5",
            "notes": {
                6: "The Two Knights Defence. Black ignores the threat to f7 and counterattacks e4 instead. Sharper than 3...Bc5.",
                7: "Crude, and against a prepared opponent not the best move — but it creates a genuine double attack on f7 that Black must answer accurately.",
                8: "The only good reply. Black hits back in the centre rather than defending passively. Do not play 4...Bc5?? 5.Nxf7 forking queen and rook.",
                9: "Now the critical fork in the road for Black.",
                10: "The natural recapture — and the losing mistake. Correct is 5...Na5!, the Polerio Defence: Black gives up a pawn to chase the strong bishop away and gets excellent play.",
                11: "The Fried Liver. White gives up a knight to drag the black king into the middle of the board on move six.",
                12: "Forced — otherwise Black is just a piece down for nothing.",
                13: "The point. The check forces the king forward, because 7...Ke8 loses instantly to 8.Bxd5 and 7...Kg8 runs into 8.Bxd5+.",
                14: "The only square. The king now stands in the centre of an open board defending its own knight.",
                15: "Adding a third attacker to the pinned knight on d5.",
                16: "The best defence — Black must reinforce d5 at all costs.",
                17: "Opening lines toward the exposed king. White is a piece down but every single white piece is pouring in.",
                18: "Propping up the knight again.",
                19: "The bishop joins with a pin and a threat. Engines say Black can survive with perfect defence, but no human ever does over the board.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Pianissimo plan in action",
        "note": "The main line continued to move seventeen. Watch the knight tour finish, the tension hold, and White finally break on both wings.",
        "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3 Ne7 d4 Ng6 Nf1 c6 Ng3 Qc7 Bg5 h6 Bd2 Re8 a4 Be6 Bxe6 Rxe6 b4",
        "notes": {
            20: "The knight completes its journey to g6. From there it defends the kingside and eyes f4 — Black's pieces are awkward but perfectly coordinated.",
            21: "White's knight tour continues: d2–f1, heading for g3 or e3. Two slow moves that will matter in fifteen more.",
            22: "Solid. It supports d5, gives the queen the c7 square, and takes b5 and d5 away from White's pieces.",
            23: "The knight arrives. Now White has a real kingside presence: Ng3, Bc1 and the h-pawn ready to advance.",
            24: "The queen takes the standard Italian post — pressure on the c-file, support for e5, and out of the way of the rooks.",
            25: "Provoking. White asks the h-pawn to commit, because ...h6 gives the g-pawn a target later.",
            26: "Black kicks the bishop. Necessary, but it is a small permanent concession — the kingside now has a hook.",
            27: "Back to safety. The bishop has done its job and White has gained a tempo's worth of structural information.",
            28: "Both rooks are now on their best files. Black is fully developed and completely solid.",
            29: "The other wing. White creates a second front, because a position with only one weakness is usually holdable.",
            30: "Black challenges the strong bishop. Trading it is worth a small structural cost.",
            31: "White accepts. The Italian bishop has served its purpose and now Black must recapture with a piece.",
            32: "The rook takes toward the centre, keeping the e-file. Structure intact.",
            33: "The break. Two wings, two threats: b5 hitting c6, and eventually a5 and Ba3 against d6. This is what the nine quiet moves were for — White now attacks on the side where Black is weakest, with every piece already placed.",
        },
    },
    "progression": {
        "arc": "The Italian is where you learn what the opening principles actually mean. Everything you build later stands on this.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Your first week with it",
                "goal": "Reach a healthy position by move ten without thinking.",
                "learn": [
                    "The six-move skeleton: e4, Nf3, Bc4, c3, d3, O-O. Play it against anything Black does on move three.",
                    "Why Bc4 and not Bb5 or Be2 — the f7 square is defended only by the king, so it is the one target that exists from move one.",
                    "The three ways Black can answer 3.Bc4: 3...Bc5 (Giuoco), 3...Nf6 (Two Knights), 3...Be7 (Hungarian). You need a reply to each.",
                ],
                "drill": "Set the board up and play the six-move skeleton twenty times against a friend or an engine at low strength. Your hands should know it before your head does.",
                "mistake": "Playing 4.Ng5 in every position because it 'attacks f7'. It is one idea, not a plan, and a prepared opponent punishes it.",
                "ready": "You can play the first eight moves without pausing and explain why each piece went where it did.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to four",
                "goal": "Understand the d4 break — when it wins the game and when it throws it away.",
                "learn": [
                    "The difference between 5.d4 (immediate, opens the game while Black is behind) and 5.d3 (slow, keeps the tension). Modern practice prefers d3.",
                    "What happens to the pawn structure after ...exd4 cxd4 — White gets d4+e4 and the c-file, Black gets the d5 square and a target.",
                    "Why ...a6 and ...Ba7 exist: Black is removing d4 from your list of good moves before you play it.",
                ],
                "drill": "Take the main-line position after 8.Nbd2 and write down, in words, three plans for White and three for Black. Then check them against the plans card above.",
                "mistake": "Playing d4 the moment it is legal. In the Pianissimo you are supposed to spend eight moves earning it.",
                "ready": "You can look at an Italian position and say whether the centre should be opened or kept closed, and why.",
            },
            {
                "tier": "Plans",
                "when": "Months two and three",
                "goal": "Play the middlegame, not just the opening.",
                "learn": [
                    "The knight tour Nb1–d2–f1–g3 and its cousin ...Nc6–e7–g6. Both sides re-route toward the kingside; whoever finishes first attacks first.",
                    "The rook lift Re1–e3–g3 and when the e-file is worth more than the attack.",
                    "How to meet ...d5: usually exd5 followed by piece pressure, occasionally e5 gaining space.",
                ],
                "drill": "Play ten games where you commit to reaching the Pianissimo tabiya and then attacking the kingside. Lose some. Note where the attack ran out of pieces.",
                "mistake": "Attacking with two pieces. An attack needs three or four attackers against the defenders present — count before you commit.",
                "ready": "You have won a game with the Nf1–g3 manoeuvre and lost one because you attacked too early. Both lessons matter.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Own the sharp branches and the endgames.",
                "learn": [
                    "The Evans Gambit as a surprise weapon, including the critical defences 5...Ba5, 5...Bc5 and 5...Be7.",
                    "The Two Knights in full: the Fried Liver, the Polerio 5...Na5, the Traxler 4...Bc5!?, and the modern 4.d4.",
                    "Endgames from the Italian: bishop against knight with pawns on both wings, and how the extra central pawn tells.",
                ],
                "drill": "Take one Evans Gambit line and analyse it thirty moves deep with an engine, then close the engine and try to explain the evaluation.",
                "mistake": "Treating the gambit lines as tricks. At any decent level they are real openings with real theory.",
                "ready": "You can play both sides of the Two Knights and you know which side you would rather have.",
            },
        ],
        "study": "Paul Morphy for the attacking version, Anatoly Karpov and Magnus Carlsen for the modern slow build. Kasparov–Anand, Riga 1995 is the most famous Evans Gambit of the last century.",
        "next": "Once the Italian feels automatic, learn the Ruy Lopez. The ideas transfer directly and the Ruy is simply a better version of the same opening.",
    },
}
