OPENING = {
    "id": "italian",
    "name": "Italian Game",
    "eco": "C50–C59",
    "section": "open",
    "orientation": "white",
    "tagline": "Bishop to c4, eyes on f7. The oldest opening still played at the top level.",
    "level": "Beginner → Master",
    "theory": {
        "big_idea": "White develops the light-squared bishop to its most aggressive diagonal (a2–g8) where it stares at f7. f7 is the weakest point in Black's position because it is defended only by the king. Everything else in the Italian flows from that one bishop: whether White builds a big pawn centre with c3 and d4, sacrifices a pawn to rip open lines, or plays a slow build-up and attacks later.",
        "structure": "Symmetrical e-pawns on e4/e5 with pawns still on d2/d7. This is the classic 'Open Game' skeleton. The tension is over whether White gets in d2–d4 under good circumstances. If White does, the position opens and development counts. If Black stops it, the game becomes a slow manoeuvring battle where knight routes decide everything.",
        "white_plans": [
            "Play c3 then d4, building the ideal pawn duo on d4+e4 and opening lines while ahead in development.",
            "The modern slow build: d3, O-O, Re1, Nbd2–f1–g3, then h3 and a delayed d4. White keeps the tension for twenty moves and outmanoeuvres Black.",
            "Direct attack on f7 with Ng5 (in the Two Knights) or a pawn sacrifice with b4 (Evans Gambit) to seize the centre by force.",
            "Rook lift Re1–e3–g3 or a kingside pawn storm once Black's counterplay on the queenside is contained.",
        ],
        "black_plans": [
            "Mirror the setup with ...Bc5, ...d6, ...Nf6, ...O-O and hold the centre; then re-route a knight via ...Ne7–g6 or hit back with ...d5.",
            "Play the sharp ...Nf6 (Two Knights) inviting 4.Ng5, then give the pawn back with 4...d5 and chase the bishop: 5.exd5 Na5!, the Polerio Defence.",
            "Retreat the bishop to a7 in advance so that White's d4 never comes with tempo.",
            "Trade off White's strong Italian bishop with ...Na5 or ...Be6.",
        ],
        "traps": [
            "The Fried Liver Attack: 3...Nf6 4.Ng5 d5 5.exd5 Nxd5?! 6.Nxf7! Kxf7 7.Qf3+ and Black's king is dragged into the open. The move that avoids all of it is 5...Na5!",
            "The Legal Trap pattern: if Black pins with ...Bg4 and grabs too greedily, White can sometimes sacrifice the queen with Nxe5 followed by Bxf7+ and Nd5#.",
            "Blackburne Shilling Trap (Black's trap): 3...Nd4?! 4.Nxe5?? Qg5! 5.Nxf7 Qxg2 6.Rf1 Qxe4+ and White collapses. Correct is 4.Nxd4.",
        ],
        "who": "Play this if you like clear, natural development and open positions where tactics decide. It teaches you more about basic chess principles than any other opening.",
    },
    "lines": [
        {
            "name": "Giuoco Pianissimo — Main Line",
            "note": "The modern main line. White plays d3 instead of d4 and manoeuvres slowly. This is what Carlsen, Caruana and Nepomniachtchi actually play.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3 Ne7 d4",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "structure": 'italian-big-centre',
                "tier": 'Structure',
                "point": 'Nine quiet moves bought you the right to play d4 with every piece already supporting it — now the centre decides, and you are the one who gets to choose when it opens.',
                "next": [
                    'If Black holds with 10...Ng6, continue the tour: 11.Nf1 c6 12.Ng3 Qc7 13.Bg5. You are not attacking yet — you are finishing the deployment.',
                    'If Black releases with 10...exd4 11.cxd4, you own a pawn duo on d4+e4 and a half-open c-file. Rc1, then d4–d5 to lock the centre before storming the kingside.',
                    'If Black tries the pin with 10...Bg4, take it — 11.hxg4! and the bishop is simply yours. That is what the pawn on h3 was for: it is not a waiting move, it is a claim on g4, and this is the position where you cash it.',
                ],
                "endgame": 'If it simplifies, you are heading for bishop against knight with pawns on both wings. Keep the light-squared bishop, put your pawns on dark squares, and remember the extra central pawn is what wins it — not the bishop.',
            },
            "notes": {
                5: "The Italian bishop takes aim at f7 and controls the a2–g8 diagonal, the fastest route into Black's position.",
                6: "Black mirrors. Now both bishops stare at the opponent's weakest square — f7 and f2. This is the Giuoco Piano, 'the quiet game'.",
                7: "Preparing d2–d4 to build the ideal centre. The cost: the c3-pawn takes the natural square away from the b1-knight, which will have to go the long way round via d2.",
                8: "Develops and attacks e4. Black gains a tempo while completing kingside development.",
                9: "The modern choice. Instead of the immediate 5.d4, which lets Black liquidate, White props up e4 and prepares a much better version of d4 later. Nicknamed the Giuoco Pianissimo — 'the very quiet game'.",
                10: "Solid. It supports e5 and opens a path for the c8-bishop. Black is in no rush.",
                11: "King safety first. Notice that both sides have followed the same three rules: control the centre, develop, castle.",
                12: "Black completes the same plan one move behind.",
                13: "The rook goes behind the e-pawn. It looks passive now, but the moment the e-file opens it will be the best-placed piece on the board.",
                14: "A tiny move with three jobs: it stops Bb5 and Nb5 forever, prepares ...b5 to kick the bishop, and clears a7 for the bishop to back into.",
                15: "The knight begins its famous journey: d2–f1–g3 (or e3). It takes three moves, but on g3 it supports f5 and h5 and joins a kingside attack. This manoeuvre was borrowed straight from the Ruy Lopez.",
                16: "The bishop backs up along the same a7–g1 diagonal, out of the d-pawn's reach, so that d4 can never arrive with a threat attached. Prophylaxis: stopping the opponent's idea before it exists.",
                17: "Luft for the king and, more importantly, control of g4 so that Black can never pin the f3-knight with ...Bg4.",
                18: "Black re-routes too: the knight is heading for g6 where it eyes f4 and h4 and helps defend the kingside.",
                19: "At last. White has spent nine moves preparing this single pawn push, and now it comes with every piece supporting it. This is the whole point of the slow Italian: play the break only when it is unanswerable.",
            },
        },
        {
            "name": "Evans Gambit",
            "note": "White throws a pawn at Black on move four to gain time and build a huge centre. Beloved by Morphy, Kasparov and every attacking player since.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O dxc3 Qb3 Qf6 e5 Qg6",
            "tier": "Mastery",
            "drill": True,
            "plan": {
                "structure": 'evans-open-lines',
                "tier": 'Plans',
                "point": "Count them: five pawns against eight, three down, and that is the deal — every line into Black's position is open, Black still has a knight on g8, a bishop on c8 and both rooks where they started, and the pawn on c3 comes back the moment you want it.",
                "next": [
                    '10.Nxc3 first — this is the move, not Re1. The pawn comes back, the last knight develops, and the b-file opens toward b7 for free.',
                    '11.Ba3 after 10...Nge7. Be exact about what it does: the knight on e7 blocks the a3–f8 diagonal, so f8 is not attacked and Black can still castle — what the bishop hits is the knight, and that knight is the only thing keeping it out. Every plan Black has starts with moving it.',
                    'Then Rae1 or Nd5, adding the last piece. Never start the attack until every piece has a job — in the game below Anderssen played a quiet rook move on move nineteen for exactly this reason.',
                ],
                "endgame": 'If it simplifies you are lost — two pawns is two pawns once the pieces come off, and that is the count even after Nxc3. This line is a bet that it will not simplify, so refuse every queen trade that does not come with a check.',
            },
            "notes": {
                7: "The Evans Gambit! White offers the b-pawn purely to deflect the bishop, so that c3 comes with tempo and White gets the centre for free.",
                8: "Declining with 4...Bb6 is respectable, but taking is the critical test — and the point of studying gambits is to know what happens when they are accepted.",
                9: "Now this comes with gain of time because the bishop is attacked. White has effectively bought a tempo for a pawn.",
                10: "The main retreat, and here is exactly why: from a5 the bishop pins your c3-pawn against the king on e1. After 6.d4 exd4 the move 7.cxd4 is not merely bad, it is illegal — which is what forces the whole gambit down the road it takes. 5...Bc5 and 5...Be7 are the alternatives.",
                11: "The dream centre. For one pawn White has pawns on d4 and e4, a developed bishop and a lead in development.",
                12: "Black grabs again. Greedy, but Black must take something for the coming attack to be worth it.",
                13: "Castling before recapturing. Development and king safety are worth more than a pawn here.",
                14: "Black is now three pawns up and about to be very uncomfortable.",
                15: "The queen steps in behind the bishop, and that battery is what makes f7 unanswerable: after Bxf7+ the king can never take, because the queen is looking through c4. From b3 she also hits c3 a second time — that is how the gambit pawn comes back. Black must find precise defence.",
                16: "Defending f7 and hitting f2 — the only good square.",
                17: "Kicking the queen with tempo and clinching the centre. Count the pawns while you are here: five against eight, three down — though c3 comes straight back with Nxc3, so the standing deficit is two. Engines call the position roughly balanced; in a real game it is far easier to play White.",
                6: "Black mirrors. Both bishops now stare at the opponent's weakest square, f7 and f2. This is the Giuoco Piano — and the position White wants for the Evans.",
                18: "The main square — 9...Qf5 holds too, and everything else on the board loses the queen or f7. Now 10.Nxc3: the pawn comes back and the last knight develops in the same move, and Ba3 follows, onto the diagonal that runs at f8. Practically speaking, most club players lose this as Black.",
            },
        },
        {
            "name": "Two Knights — Fried Liver Attack",
            "note": "The most famous attacking pattern in beginner chess. Learn it from both sides: it wins games, and knowing it stops you losing in ten moves.",
            "moves": "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nce7 d4 c6 Bg5",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": 'Plans',
                "point": 'There is no pawn structure here; there is a black king on e6 and a piece-count that says you have to finish the job before Black finishes developing.',
                "next": [
                    '10...h6 11.Bxe7 Bxe7 12.dxe5! — the point is never the pawn, it is the line the capture opens toward e6, and Bxd5+ comes after it.',
                    'Castle long when there is nothing forcing: O-O-O puts the last rook on the d-file and takes the king out of the centre in one move.',
                    'Count the defenders of d5 every single move. The whole attack is one square wide.',
                ],
                "endgame": 'There is no endgame in this line. You are a knight down for one pawn; if the queens come off you resign. Engines say Black holds with perfect defence and no human ever does over the board — but you should know which of those two facts you are relying on.',
            },
            "notes": {
                6: "The Two Knights Defence. Black ignores the threat to f7 and counterattacks e4 instead. Sharper than 3...Bc5.",
                7: "Crude, and against a prepared opponent not the best move — but it creates a genuine double attack on f7 that Black must answer accurately.",
                8: "The move that makes ...Kxf7 legal later on, which is the only reason it is the main line: it blocks the c4-bishop's diagonal. Defending f7 with a piece instead loses material on the spot, and the one other serious try is the Traxler 4...Bc5!?, which ignores f7 altogether.",
                9: "Now the critical fork in the road for Black.",
                10: "The natural recapture, and the one that walks into the attack. 5...Na5!, the Polerio Defence, is the main line today: Black gives up the pawn to chase the strong bishop away and gets a fine game.",
                11: "The Fried Liver. White gives up a knight to drag the black king into the middle of the board on move six.",
                12: "Effectively forced. The knight on f7 forks d8 and h8, so declining costs the queen or a rook — the deviation panel shows both.",
                13: "The point. The check forces the king forward, because 7...Ke8 8.Bxd5 hands the piece straight back with a pawn's interest — and 7...Kg8 is worse than that: 8.Bxd5+ is mate in three, which the deviation panel walks through.",
                14: "The only square. The king now stands in the centre of an open board defending its own knight.",
                15: "Adding a third attacker to the pinned knight on d5.",
                16: "The move the old books give, and it does hold d5 a third time. The engine prefers 8...Nb4, which defends d5 and hits c2 at the same time — reinforcing is the human instinct, counter-attacking is the machine's.",
                17: "Opening lines toward the exposed king. Count it honestly: a knight for a pawn down, so two pawns' worth — and every single white piece is pouring in.",
                18: "Propping up the knight again.",
                19: "The bishop joins with a pin and a threat. Engines say Black can survive with perfect defence, but no human ever does over the board.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Pianissimo plan in action",
        "note": "The main line continued to move seventeen. Watch the knight tour finish, the tension hold, and White finally break on both wings.",
        "moves": "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3 Ne7 d4 Ng6 Nf1 c6 Ng3 Qc7 Bg5 h6 Bd2 Re8 a4 Be6 Bxe6 Rxe6 b4",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "structure": 'italian-big-centre',
            "tier": 'Plans',
            "point": 'The knight tour is finished, the centre is still tense, and now you open a second front — because a position with only one weakness is usually holdable.',
            "next": [
                '17...Rae8 18.b5 axb5 19.axb5 and the a-file points straight at the bishop on a7.',
                'b5 first, hitting c6; a4–a5 next, taking b6 away; and only then look at the kingside.',
                "Keep the centre tense as long as Black has to watch it. d4–d5 releases the tension and frees Black's pieces — save it for the moment you want the queenside closed.",
            ],
            "endgame": 'Count the pawns before you plan the endgame: three, two and three a side, so nobody has a majority anywhere and there is no passer to make. What you own is two extra ranks on the queenside, and that is enough — b5 makes Black choose which of b7 and c6 becomes the weak pawn on a half-open file, and rook endgames are decided by that.',
        },
        "notes": {
            20: "The knight completes its journey to g6. From there it defends the kingside and eyes f4 — Black's pieces are awkward but perfectly coordinated.",
            21: "White's knight tour continues: d2–f1, heading for g3 or e3. Two slow moves that will matter in fifteen more.",
            22: "Solid. It supports d5, gives the queen the c7 square, and takes b5 and d5 away from White's pieces.",
            23: "The knight arrives. Now White has a real kingside presence: Ng3, Bc1 and the h-pawn ready to advance.",
            24: "The queen takes the standard Italian post — pressure on the c-file, support for e5, and out of the way of the rooks.",
            25: "Provoking. White asks the h-pawn to commit, because ...h6 gives the g-pawn a target later.",
            26: "Black kicks the bishop. Necessary, but it is a small permanent concession — the kingside now has a hook.",
            27: "Back to safety. The bishop has done its job and White has gained a tempo's worth of structural information.",
            28: "Both rooks are now on their best files. Black is fully developed and completely solid.",
            29: "The other wing. White creates a second front, because a position with only one weakness is usually holdable.",
            30: "Black challenges the strong bishop. Trading it is worth a small structural cost.",
            31: "White accepts. The Italian bishop has served its purpose, and now Black has to choose: ...Rxe6 keeps the pawns healthy, ...fxe6 leaves doubled e-pawns with e6 backward behind e5. Be exact about what that is worth — the e-file is not open, your own pawn is on e4 — so e6 is a pawn that can never move, not a pawn you win. What Black gets for it is the half-open f-file.",
            32: "The rook takes toward the centre, keeping the e-file. Structure intact.",
            33: "The break. Two wings, two threats: b5 hitting c6, and eventually a5 and Ba3 against d6. This is what the nine quiet moves were for — White now attacks on the side where Black is weakest, with every piece already placed.",
        },
    },
    # Deviations, keyed by the position they answer rather than by a ply number.
    # The Giuoco and the Two Knights share their first five moves, so a branch
    # written once here fires in every line that reaches the same position.
    "branches": {

        # ── ply 4 · Black's second move ─────────────────────────────────────────
        "e4 e5 Nf3": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Petrov Defence",
             "why": "Black ignores e5 and counterattacks e4 — your own idea, played back at you. There is nothing to refute: 3.Nxe5 d6 4.Nf3 Nxe4 5.d4 gives a normal game with a small pull. You are simply not in the Italian any more, and that is allowed.",
             "line": "Nxe5 d6 Nf3 Nxe4 d4"},
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "name": "Philidor Defence",
             "why": "Black holds e5 with a pawn and shuts in the c8-bishop to do it. Play 3.d4 for space and a lasting edge — and notice that Bc4 still goes to c4 next move, so almost nothing you have learned is wasted.",
             "line": "d4 Nf6 Nc3 Nbd7 Bc4"},
            {"san": "d5", "severity": "inaccuracy", "tier": "Structure",
             "name": "Elephant Gambit",
             "why": "Black strikes in the centre before developing a single piece — one move too early. 3.exd5 e4 4.Qe2! and either the e4-pawn falls or Black's whole position does.",
             "line": "exd5 e4 Qe2"},
            {"san": "f5", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Latvian Gambit",
             "why": "A mirror-image King's Gambit played a tempo down, which is exactly one tempo too few. Take it: 3.Nxe5 Qf6 4.d4 d6 5.Nc4, and do not expect to keep the pawn — 5...fxe4 evens the count. What does not even out is the queen on f6 blocking Black's own development, the f-file open in front of Black's king, and the whole centre yours.",
             "line": "Nxe5 Qf6 d4 d6 Nc4"},
            {"san": "f6", "severity": "blunder", "tier": "Foundation",
             "name": "Damiano Defence",
             "why": "Black defends e5 with the one pawn that was holding the king's diagonal shut. 3.Nxe5! and the natural recapture loses: 3...fxe5 4.Qh5+ drags the king into the open on move four, and 5.Qxe5+ picks the pawn up again with the king on f7. Know the other move too, because a defended opponent plays it — 3...Qe7 4.Nf3 Qxe4+ 5.Be2 levels the pawns, and what Black is left with is a queen in the open, a hole on e6 and every white piece still to come. This is the oldest refutation in the literature and it still wins games every day.",
             "line": "Nxe5 fxe5 Qh5+ Ke7 Qxe5+ Kf7 Bc4+"},
        ],

        # ── ply 5 · your own third move: the three doors out of the Italian ─────
        "e4 e5 Nf3 Nc6": [
            {"san": "Bb5", "severity": "playable", "tier": "Plans",
             "why": "The Ruy Lopez. The same philosophy, a harder version, better long-term prospects. This is the upgrade to take once the Italian feels automatic — the knight tour, the h3 move and the c3–d4 centre transfer over untouched.",
             "see": "ruylopez"},
            {"san": "d4", "severity": "playable", "tier": "Plans",
             "why": "The Scotch. Opening the centre at once instead of spending nine moves earning the right to. Completely sound and far less to memorise; you give up the slow squeeze that makes the Italian what it is.",
             "see": "scotch"},
            {"san": "Nc3", "severity": "playable", "tier": "Plans",
             "why": "The Four Knights. Symmetrical, safe, and you can still play Bc4 next move and be straight back in Italian structures. A legitimate way to keep your opening and drop half the theory.",
             "see": "fourknights"},
        ],

        # ── ply 6 · after 3.Bc4 — the ply where club players actually deviate ───
        "e4 e5 Nf3 Nc6 Bc4": [
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "name": "Hungarian Defence",
             "why": "Black declines the fight for f2 and builds a small, unbreakable house. There is no refutation and there does not need to be one — take the centre with 4.d4 and enjoy the extra space for the next thirty moves.",
             "line": "d4 exd4 Nxd4"},
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "name": "Semi-Italian",
             "why": "Solid and a shade passive — the c8-bishop is now behind its own pawn. Black has spent a move on defence, so spend yours on the centre: 4.d4 immediately.",
             "line": "d4 exd4 Nxd4"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Extremely common and not a mistake, just a slow one. It stops Ng5 forever, which is fine, except that Ng5 was never your main plan. Take the free tempo with 4.d4 and thank Black for it.",
             "line": "d4 exd4 Nxd4"},
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Two Knights Defence",
             "why": "The sharpest answer to 3.Bc4: Black ignores f7 and hits e4 instead. This is a whole variation of its own — step through the Two Knights line before you meet it over the board.",
             "see": "italian#two-knights"},
            {"san": "Nd4", "severity": "inaccuracy", "tier": "Foundation",
             "name": "Blackburne Shilling Gambit",
             "why": "It breaks two rules at once — the same piece twice, to a square it can be kicked from — and it is played for exactly one reason: to see whether you grab on e5. Play 4.Nxd4! exd4 5.O-O: material is dead level, but Black has spent three moves to swap knights and been left holding a pawn on d4 that needs defending for the rest of the game. Grab with 4.Nxe5?? and 4...Qg5! wins on the spot.",
             "line": "Nxd4 exd4 O-O"},
            {"san": "Qe7", "severity": "inaccuracy", "tier": "Structure",
             "why": "Playable and horrible to look at: the queen takes the bishop's square and boxes in the f8-bishop behind her. Do not answer it with the automatic 4.d4 exd4 5.Nxd4?? — 5...Qxe4+ and Black is a pawn up, because the queen on e7 has been looking at that pawn since move three. If you play 4.d4 the follow-up is 5.O-O!, leaving the pawn on d4 alone. Simplest of all: 4.O-O and 5.Nc3, and let Black spend ten moves untangling a position that was never attacked.",
             "line": "O-O Nf6 Nc3 d6 h3"},
            {"san": "f5", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Rousseau Gambit",
             "why": "Black opens the f-file toward their own king while the king is still standing on it. Do not get tangled with 4.exf5 — play 4.d3, keep the centre closed, and let the holes on e5 and the a2–g8 diagonal do the work.",
             "line": "d3 Nf6 O-O"},
            {"san": "Na5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Attacking the bishop from the rim before developing anything — and the bishop does not have to move. 4.Nxe5! Nxc4 5.Nxc4 and you are a clean pawn up. If Black tries the Blackburne trick, 4...Qg5, the answer is 5.Qf3! — with the knight on a5 rather than d4 there is no ...Nf3+ to follow it up, and the engine calls that four pawns for White. Do not reach for 5.Nxf7? instead: that loses exactly as it does in the Blackburne, to 5...Qxg2 6.Rf1 Qxe4+. And do not defend the bishop with a developing move — 4.O-O, 4.d4 and 4.Nc3 all simply lose it to 4...Nxc4.",
             "line": "Nxe5 Nxc4 Nxc4 Nf6 d3"},
        ],

        # ── ply 7 · your own fourth move in the Giuoco ──────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5": [
            {"san": "d3", "severity": "playable", "tier": "Foundation",
             "why": "The move-order shortcut: d3 first, c3 later. You reach the same Pianissimo and you sidestep a couple of Black's sharper tries on the way. Nothing is lost."},
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Castling first is never wrong here. You will still play c3 and d3 — you have only changed the order, and the king was going to want that square anyway."},
            {"san": "b4", "severity": "playable", "tier": "Mastery",
             "name": "Evans Gambit",
             "why": "A pawn for a tempo and the centre. It is objectively sound and it is a different opening from the one you have been learning: the Pianissimo wins by out-manoeuvring, the Evans wins by getting there first. Step through the Evans line before you play it.",
             "line": "Bxb4 c3 Ba5 d4 d6 Qb3",
             "see": "italian#evans"},
            {"san": "d4", "severity": "playable", "tier": "Structure",
             "why": "The Italian Gambit — grabbing the centre a move before c3 supports it. Perfectly playable, and dead level at depth twenty. Do not assume 4...exd4 is what you will meet: 4...Bxd4 and 4...Nxd4 are both real answers, and after 4...Nxd4 5.Be3 Qe7 6.Bxd4 exd4 7.O-O you have an open game with a pawn on d4 to work against rather than the duo you wanted.",
             "line": "Nxd4 Be3 Qe7 Bxd4 exd4 O-O"},
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "why": "The Italian Four Knights. Nothing is lost — you can still play d3 and reach a Pianissimo with the knight on c3 instead of d2, which is a real line and one move shorter. What you give up is the d2–f1–g3 tour, and that tour is most of the plan.",
             "line": "Nf6 d3 a6 a3 d6 h3"},
            {"san": "Ng5", "severity": "blunder", "tier": "Foundation",
             "why": "The beginner's reflex, and here it simply hangs a knight: 4...Qxg5! — nothing guards g5, because your own d2-pawn still blocks the c1-bishop. There is no saving trick. 5.Bxf7+ Kxf7! is exactly what Black wants, two pieces for one pawn, and 6.Qh5+ loses on the spot to 6...Qxh5 — the queen sitting on g5 has been guarding h5 the whole time. Ng5 is a move against 3...Nf6 and against nothing else.",
             "line": "Qxg5 Bxf7+ Kxf7 Qh5+ Qxh5"},
        ],

        # ── ply 8 · after 4.c3 ──────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3": [
            {"san": "Bb6", "severity": "playable", "tier": "Foundation",
             "why": "Prophylaxis, four moves early. The bishop stays on the a7–g1 diagonal and steps out of the d-pawn's reach, so that d4 never arrives with tempo. Entirely sound — play 5.d4 anyway and accept an ordinary good position.",
             "line": "d4 Qe7 O-O"},
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "why": "Black holds e5 with a pawn and develops behind it. Play 5.d4 and you have exactly the fight you wanted.",
             "line": "d4 Bb6 O-O"},
            {"san": "Qe7", "severity": "playable", "tier": "Structure",
             "why": "A real line. The queen backs up e5 so that d4 can be met by ...exd4 with the e-file already covered. It costs Black the natural square for the g8-knight, which is the standing price of every early queen move.",
             "line": "d4 Bb6 O-O"},
            {"san": "Qf6", "severity": "inaccuracy", "tier": "Structure",
             "why": "The queen comes out to guard e5 and eye f2, and defends nothing that needed defending. She is now standing on the square the g8-knight wants. 5.d4! exd4 6.cxd4 and every tempo you spend from here arrives with a threat attached.",
             "line": "d4 exd4 cxd4 Bb6 Nc3"},
            {"san": "f5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Played because it 'attacks e4'. It opens a diagonal toward Black's own uncastled king to do it. 5.d4! fxe4 6.Nxe5! Nxe5 7.dxe5 and the centre is yours, the a2–g8 diagonal is open and the black king is still standing on e8. The move order matters: 6.Ng5 instead lets Black liquidate with ...d5 and the whole edge disappears.",
             "line": "d4 fxe4 Nxe5 Nxe5 dxe5"},
        ],

        # ── ply 9 · your own fifth move ─────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6": [
            {"san": "d4", "severity": "playable", "tier": "Structure",
             "name": "Giuoco Piano — main line",
             "why": "The old main line, and a completely different game: 5.d4 exd4 6.cxd4 Bb4+ 7.Bd2 Bxd2+ 8.Nbxd2 d5! 9.exd5 Nxd5 leaves White with an isolated d-pawn and free piece play. Worth knowing because the identical structure turns up in the Panov Caro-Kann, the Queen's Gambit Accepted and the Nimzo-Indian.",
             "line": "exd4 cxd4 Bb4+ Bd2 Bxd2+ Nbxd2 d5 exd5 Nxd5",
             "see": "structure#isolani"},
            {"san": "Ng5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Still not the move — and now it is worse, because the pawn on c3 means there is no Nc3 to follow up with, and Nc3 is what made the Fried Liver work in the first place. 5...d5! 6.exd5 Nxd5 and Black is fine. An attack with one attacker is not an attack.",
             "line": "d5 exd5 Nxd5"},
        ],

        # ── ply 10 · after 5.d3 ─────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3": [
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Same moves, different order. Black castles first and will play ...d6 next. Carry on with 6.O-O."},
            {"san": "a6", "severity": "playable", "tier": "Foundation",
             "why": "Black plays the useful little move first: it stops Bb5 and Nb5 forever and prepares ...b5. Nothing has changed for you — play 6.O-O."},
            {"san": "d5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The right break, three moves too early — the king is still on e8. 6.exd5 Nxd5 7.Qb3! stacks the queen behind the bishop and f7 cannot be held: 7...Nf6 8.Bxf7+ Kf8 9.O-O and Black is a pawn down with no castling rights. And 6...Nb4?? does not recapture at all, it only attacks the pawn on d5: 7.cxb4 and White is a knight and a pawn up for nothing.",
             "line": "exd5 Nxd5 Qb3"},
            {"san": "Ng4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "It looks like it wins f2 and it never does: 6.O-O, and 6...Nxf2 7.Rxf2 Bxf2+ 8.Kxf2 leaves Black two pieces down for a rook and a pawn. f2 is only weak when three pieces are hitting it.",
             "line": "O-O Nxf2 Rxf2 Bxf2+ Kxf2"},
        ],

        # ── ply 12 · after 6.O-O ────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O": [
            {"san": "Bg4", "severity": "inaccuracy", "tier": "Structure",
             "why": "The pin that isn't. With the pawn on d3 there is nothing behind the f3-knight worth pinning it against. 7.h3 asks the question, and after 7...Bh5 8.Nbd2 and 9.Re1 you have a free tempo and a target on h5.",
             "line": "h3 Bh5 Nbd2 O-O Re1"},
            {"san": "Na5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The right plan at the wrong moment. Trading off the Italian bishop is a real idea — but Black has not castled yet, so 7.Bb5+! arrives with check, and that one tempo is the whole difference: 7...c6 8.Ba4 b5 9.b4! and the knight on a5 is short of squares with the queenside coming apart. Retreat with 7.Bb3 and you have handed everything back: 7...Nxb3 8.axb3 is exactly the trade Black was asking for, for free. Once Black has castled, ...Na5 is a good move — see the position after 8.Nbd2.",
             "line": "Bb5+ c6 Ba4 b5 b4"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Not needed yet, not harmful. Black is making a useful move because there is nothing urgent to do — which is exactly the character of this opening. Play 7.Re1 and carry on.",
             "line": "Re1 O-O Nbd2"},
        ],

        # ── ply 13 · your own seventh move ──────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O": [
            {"san": "h3", "severity": "playable", "tier": "Foundation",
             "why": "The cheapest move in the opening: it takes g4 from the c8-bishop for good. The engine nominates 7.Nbd2 here and rates h3 within three centipawns of it, which is another way of saying it does not care. You are going to play it anyway, so playing it before Re1 closes one door early and costs nothing.",
             "line": "h6 Nbd2 Bb6 a4 a5 Bb3"},
            {"san": "a4", "severity": "playable", "tier": "Plans",
             "why": "One of the three modern moves here: it stops ...b5 before Black has spent a tempo on ...a6, so the bishop keeps c4 and you keep a4–a5 in hand. Anand and Caruana have both played it from this exact position — and both have played 7.Re1 and 7.h3 from it more often, so take it as an equal option rather than an improvement on them.",
             "line": "a5 h3 Be6 Bxe6 fxe6 Be3"},
            {"san": "Bb3", "severity": "playable", "tier": "Foundation",
             "why": "Answering the question before Black asks it. It costs the tempo you would have spent on Re1 and buys you never having to think about ...Na5 or ...b5 again. Carlsen plays it in the game below and plays it even earlier than this — on move six, before either king has castled.",
             "line": "a5 Re1 Be6 Bg5 h6 Bh4",
             "see": "italian#carlsen-nakamura-2011"},
            {"san": "d4", "severity": "inaccuracy", "tier": "Structure",
             "why": "The break, five moves early. 7.d4 exd4 8.cxd4 Bb6 and Black is comfortable: the whole reason d3 was played on move five is that d4 waits until the knight tour supports it. Legal is not the same as ready, and this is the mistake the Structure stage of the path is about.",
             "line": "Bb6 a4 exd4 cxd4 a5 Nc3"},
        ],

        # ── ply 14 · after 7.Re1 ────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1": [
            {"san": "Be6", "severity": "playable", "tier": "Structure",
             "why": "The principled trade. After 8.Bxe6 fxe6 Black gets the half-open f-file and a grip on d5; you get a permanently backward e6-pawn to aim at and a free hand on the kingside. Both sides get something — that is what a fair trade looks like.",
             "line": "Bxe6 fxe6 Nbd2"},
            {"san": "Ne7", "severity": "playable", "tier": "Plans",
             "why": "Black starts the knight tour early. It also takes the c6-knight off d4's neighbourhood, so 8.d4! arrives two moves sooner than in the main line and with more force.",
             "line": "d4 Ng6 Nbd2"},
            {"san": "Bg4", "severity": "inaccuracy", "tier": "Structure",
             "why": "The same pin, the same answer. 8.h3 Bh5 9.Nbd2 and the bishop on h5 is a long-term target for g2–g4 once your king is safe behind the knight tour.",
             "line": "h3 Bh5 Nbd2 Nd7 Nf1"},
        ],

        # ── ply 16 · after 8.Nbd2 ───────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2": [
            {"san": "b5", "severity": "playable", "tier": "Plans",
             "why": "Black gains queenside space and asks the bishop to move. 9.Bb3 and it is happier there than on c4 — out of reach of ...Na5, still pointing at f7, and now with a pawn on b5 to work against later with a2–a4.",
             "line": "Bb3 Ba7 h3"},
            {"san": "Be6", "severity": "playable", "tier": "Structure",
             "why": "The trade again, one move later. 9.Bxe6 fxe6 10.Nf1 and the knight tour continues against a structure that can no longer defend itself with ...d5.",
             "line": "Bxe6 fxe6 Nf1"},
            {"san": "Bb6", "severity": "playable", "tier": "Plans",
             "why": "The same idea as ...Ba7 — get off the a7–g1 diagonal before d4 — one square less committal and one square more exposed to a later d4–d5 and a3–b4.",
             "line": "Nf1 Be6 Bxe6"},
        ],

        # ── ply 17 · your own ninth move ────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7": [
            {"san": "Nf1", "severity": "playable", "tier": "Plans",
             "why": "Carrying straight on with the tour and leaving h3 for later. The engine rates it exactly level with 9.h3 — the cost is that ...Bg4 and ...Ng4 are briefly real, and 9...Na5 10.Bb3 Nxb3 11.axb3 gets the trade Black wants. Both move orders are fine; pick one and know why.",
             "line": "Na5 Bb3 Nxb3 axb3 Ng4"},
            {"san": "b4", "severity": "playable", "tier": "Plans",
             "why": "Space on the wing the pawns point at, before the kingside build-up starts. It is playable and it is a commitment: once b4 is played, c4 and the a2–g8 diagonal need watching, and 9...Ng4 immediately asks whether you had time.",
             "line": "Ng4 Re2 Kh8 a4 f5"},
            {"san": "d4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Two moves too early, and for a concrete reason: Black's knight is still on c6. 9...exd4 10.Nxd4 Nxd4 11.cxd4 Bxd4! and the bishop on a7 has been aimed at that square since move eight. In the main line 9.h3 Ne7 comes first — and the point of ...Ne7 is that it removes the very knight Black needs to strip d4 of its defenders.",
             "line": "exd4 Nxd4 Nxd4 cxd4 Bxd4"},
        ],

        # ── ply 18 · after 8...Ba7 — Black's whole family of ninth moves ─────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3": [
            {"san": "Na5", "severity": "playable", "tier": "Structure",
             "why": "The engine's first choice, and now it is sound — the king is castled, so there is no Bb5+ and the trade simply happens: 10.a4 Nxc4 11.Nxc4 b5. Compare it with 6...Na5 three moves ago, where the same idea loses a tempo to a check. Same move, different position, different verdict.",
             "line": "a4 Nxc4 Nxc4 b5 Na5"},
            {"san": "Be6", "severity": "playable", "tier": "Structure",
             "why": "The principled trade, and the one you should take: 10.Bxe6 fxe6 11.b4 and Black has the half-open f-file and a grip on d5, you have a backward pawn on e6 to aim at and a free hand on both wings. This is the trade the deep dive reaches by a different route.",
             "line": "Bxe6 fxe6 b4 h6 Nf1"},
            {"san": "Re8", "severity": "playable", "tier": "Foundation",
             "why": "A move that is never wrong and never urgent — the rook is doing nothing on f8 and the e-file is the file that will open. 10.Nf1 and carry on with the tour; nothing about your plan changes.",
             "line": "Nf1 h6 a4 Be6 Bxe6 Rxe6"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Black takes g5 away from your pieces and waits. It is exactly the character of this opening — no threats, no weaknesses, and a hook on the kingside that your h-pawn will remember in twenty moves. 10.a4 and get on with it.",
             "line": "a4 Re8 b4 Be6 Bxe6 Rxe6"},
            {"san": "Nb8", "severity": "inaccuracy", "tier": "Plans",
             "why": "The Breyer manoeuvre borrowed from the Ruy Lopez, and it does not transfer: there the knight goes home to support ...c5 against a d4-pawn that is already there, and here White has not committed the d-pawn yet. 10.Nf1 Nc6 11.Bb3 and you have had two free moves to improve while the knight travelled in a circle.",
             "line": "Nf1 Nc6 Bb3 h6 Ng3"},
        ],

        # ── ply 20 · after 9...Ne7 — your own tenth move, and Black's answers ────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7 h3 Ne7 d4": [
            {"san": "Bg4", "severity": "blunder", "tier": "Foundation",
             "why": "The pin, one move after you made it impossible. 11.hxg4! and the bishop is simply yours — 11...Nxg4 12.Nf1 and you are a piece up for a pawn with the knight on g4 achieving nothing. This is what the h3-pawn was bought for nine moves ago; it is not a waiting move, it is a claim on g4.",
             "line": "hxg4 Nxg4 Nf1 Ng6 N1h2"},
            {"san": "exd4", "severity": "playable", "tier": "Plans",
             "why": "Releasing the tension on Black's terms. 11.cxd4 d5! is the freeing operation and it is legitimate: you get the duo on d4 and e4 and the half-open c-file, Black gets rid of the cramp. Perfectly playable for both — this is the structure the plan card calls the big centre with the c-file open.",
             "line": "cxd4 d5 Bb3 dxe4 Nxe4",
             "see": "structure#broad-centre-open-c-file"},
            {"san": "Re8", "severity": "inaccuracy", "tier": "Structure",
             "why": "A useful move in a position where there is no time for one. 11.dxe5! dxe5 12.Nxe5 and the pawn is gone, because the rook on e8 does not defend e5 — the knight that used to sit on c6 is on e7 now, and nothing has replaced it.",
             "line": "dxe5 dxe5 Nxe5 Rf8 Qb3"},
            {"san": "c6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Solid-looking and a tempo too slow: 11.dxe5! dxe5 12.Nxe5 and you are a pawn up for the same reason. Count the defenders of e5 the moment the knight leaves c6 — in this structure that is the one square the whole tension hangs on.",
             "line": "dxe5 dxe5 Nxe5 Be6 Bxe6"},
        ],

        # ══ EVANS GAMBIT ════════════════════════════════════════════════════════

        # ── ply 8 · after 4.b4 ──────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4": [
            {"san": "Bb6", "severity": "playable", "tier": "Foundation",
             "name": "Evans Gambit Declined",
             "why": "The most common answer you will ever meet, and a good one: Black keeps the bishop and refuses to hand over the tempo. Play 5.a4! a6 6.Nc3 and you have queenside space for free. The b-pawn was never a gift — it was rent.",
             "line": "a4 a6 Nc3 Nf6 Nd5"},
            {"san": "d6", "severity": "blunder", "tier": "Foundation",
             "why": "Ignoring the pawn is a plan; ignoring the threat is not. b4 attacks the bishop, and ...d6 leaves it standing there: 5.bxc5! dxc5 and you are a bishop up for a pawn. Note what does not work — 5.O-O and 5.d4 both hand the piece back with ...Bxb4 — so look at what your own last move attacked before you carry on developing.",
             "line": "bxc5 dxc5 d3"},
            {"san": "Nxb4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Taking with the wrong piece. 5.c3 Nc6 6.d4 and the knight has made two journeys to arrive back where it started while you built the dream centre. The bishop was supposed to take — chasing the bishop is the entire point of the gambit.",
             "line": "c3 Nc6 d4 exd4 cxd4"},
            {"san": "Be7", "severity": "playable", "tier": "Structure",
             "why": "Declining by retreating all the way home, and it costs Black almost nothing. 5.b5! Na5 6.Bd3 d6 7.O-O gives you queenside space and a knight on a5 that needs three moves to matter — but your bishop now sits on d3 instead of c4 and f7 has stopped being anybody's problem. Do not try to punish it with 6.Nxe5: at depth twenty that is dead level.",
             "line": "b5 Na5 Bd3 d6 O-O"},
        ],

        # ── ply 10 · after 5.c3 ─────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3": [
            {"san": "Bc5", "severity": "playable", "tier": "Plans",
             "why": "The other main retreat. The bishop stays on the diagonal that matters and can be hit by d4. 6.d4 exd4 7.cxd4 Bb6 8.Nc3 — the same deal as the main line, one square different.",
             "line": "d4 exd4 cxd4 Bb6 Nc3"},
            {"san": "Be7", "severity": "playable", "tier": "Mastery",
             "name": "Anderssen Variation",
             "why": "The safest square on the board for that bishop: from e7 nothing can hit it again, so the tempo you bought with c3 is the last one you get. 6.d4 Na5! is the annoying follow-up — Black hunts the Italian bishop instead of defending, and the fireworks never start.",
             "line": "d4 Na5 Nxe5 Nxc4 Nxc4"},
            {"san": "Bd6", "severity": "inaccuracy", "tier": "Structure",
             "why": "The bishop blocks the one pawn Black needs to move in order to develop anything. 6.d4 and the position is a traffic jam with your pieces on the outside of it.",
             "line": "d4 Nf6 O-O O-O Re1"},
        ],

        # ── ply 12 · after 6.d4 ─────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4": [
            {"san": "d6", "severity": "playable", "tier": "Plans",
             "why": "Lasker's idea, and the reason the Evans is not simply winning. Black declines the second pawn, props up e5 and stays exactly one pawn ahead instead of three: 7.Qb3 — the Tartakower Attack — Qd7 8.dxe5 dxe5 9.O-O and at depth twenty this is dead level. Surviving the opening a pawn up is most of the job against the Evans, which is why this is the line to know. Be careful with the name, though: the Lasker Defence proper is the ...Bb6 that follows 7.O-O, not this move.",
             "line": "Qb3 Qd7 dxe5 dxe5 O-O"},
            {"san": "Bb6", "severity": "playable", "tier": "Plans",
             "why": "Stepping aside before taking, so that d4–d5 never comes with tempo. The reply that keeps the initiative is 7.Nxe5!: 7...Nxe5 8.dxe5 Ne7 9.Ba3 and you have the pawn back, the bishop on the diagonal that decides this opening and a black king with nowhere to go. The quiet 7.dxe5 instead lets Black consolidate with ...d6 and the gambit has bought nothing at all.",
             "line": "Nxe5 Nxe5 dxe5 Ne7 Ba3"},
            {"san": "Nf6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Developing into the storm. 7.dxe5! Nxe4 8.Qd5 hits the knight and f7 at the same time, and Black is fighting for a draw on move eight.",
             "line": "dxe5 Nxe4 Qd5 Nc5 Bg5"},
        ],

        # ── ply 14 · after 7.O-O ────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O": [
            {"san": "d6", "severity": "playable", "tier": "Mastery",
             "why": "The modern preference and much the most testing. Black gives the pawn back and finishes developing: 8.cxd4 Bb6 9.Nc3 Na5 10.Bg5 — a big centre for White, a sound game for Black. This is where Evans theory actually lives today.",
             "line": "cxd4 Bb6 Nc3 Na5 Bg5"},
            {"san": "d3", "severity": "playable", "tier": "Plans",
             "why": "Dufresne's move in the Evergreen Game. Black returns the pawn at once to kill White's centre before it exists. After 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 you reach the main line's position with the extra pawn sitting on d3 instead of c3 — and at depth twenty that position is a shade better for Black, so treat 7...d3 as a serious answer and not a curiosity. Step through the model game from here: Anderssen won it without the evaluation ever being on his side.",
             "line": "Qb3 Qf6 e5 Qg6 Re1 Nge7 Ba3",
             "see": "italian#anderssen-dufresne-1852"},
            {"san": "Nge7", "severity": "playable", "tier": "Plans",
             "why": "Developing under the guns and keeping f7 covered. 8.cxd4 d5 9.exd5 Nxd5 and Black is holding — the pawn count still favours Black and White still has every piece pointing at the king.",
             "line": "cxd4 d5 exd5 Nxd5"},
            {"san": "Nf6", "severity": "playable", "tier": "Structure",
             "why": "Developing, and the engine's own first choice here — Black finishes the kingside and asks you to show what the pawns bought. 8.Ba3! is the move: the bishop hits f8 before Black can castle, and 8...d6 9.e5 Ne4 10.exd6 keeps every line open. There is nothing forced and nothing winning; you are playing the initiative you paid for.",
             "line": "Ba3 d6 e5 Ne4 exd6"},
        ],

        # ── ply 16 · after 8.Qb3 ────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O dxc3 Qb3": [
            {"san": "Qe7", "severity": "inaccuracy", "tier": "Plans",
             "why": "The other way to guard f7, and it looks the more sober one — until you look at the e-file the queen has just stepped onto. 9.Nxc3! Nf6 10.Nd5 Nxd5 11.exd5 and White has the pawn back, every piece out, and a queen and a rook trained on a king that is not going to castle. Black is still two pawns up and it does not matter.",
             "line": "Nxc3 Nf6 Nd5 Nxd5 exd5"},
            {"san": "Nh6", "severity": "playable", "tier": "Structure",
             "why": "It does defend f7, and objectively it holds — but it is the only thing that knight will ever do. 9.Bxh6 gxh6 and Black's king has no roof on either wing, which is not an evaluation, it is a practical problem for the next twenty moves.",
             "line": "Bxh6 gxh6 Nxc3"},
            {"san": "Nf6", "severity": "blunder", "tier": "Foundation",
             "why": "This does not defend f7 — and f7 is attacked twice and defended once. 9.Bxf7+ Kf8 10.Bc4 wins a pawn, takes Black's castling rights for good, and leaves every white piece aimed at a king that cannot move. Count attackers and defenders on f7 before you touch anything else.",
             "line": "Bxf7+ Kf8 Bc4"},
        ],

        # ── ply 18 · after 9.e5 — the queen has one square ───────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O dxc3 Qb3 Qf6 e5": [
            {"san": "Qxe5", "severity": "blunder", "tier": "Foundation",
             "why": "Taking a fourth pawn with the king still on e8. 10.Nxe5! Nxe5 wins the queen for a knight, and 11.Re1 leaves the knight on e5 pinned to the king with nothing to save it: 11...Kd8 12.Rxe5 and count what is left — White is a queen up for four pawns. Every extra pawn Black has taken is on the wrong side of the board.",
             "line": "Nxe5 Nxe5 Re1 Kd8 Rxe5"},
            {"san": "Nxe5", "severity": "blunder", "tier": "Foundation",
             "why": "The same square, the same file, the same problem. 10.Re1! and the knight on e5 cannot be held — 10...d6 11.Bg5 and the queen has to leave f6, after which e5 falls with interest. This is why 9...Qg6 is the only move: it is the only square that keeps the queen off the e-file and still guards f7.",
             "line": "Re1 d6 Bg5"},
            {"san": "Qf5", "severity": "playable", "tier": "Mastery",
             "why": "The other square that works, and at depth twenty it costs Black about a third of a pawn against ...Qg6 — near enough that you should expect it. 10.Nxc3 Nge7 11.Ba3 and you are in the main plan anyway; the difference is that on f5 the queen watches d3 and c2, and on g6 she watches the kingside. Both are defensible; neither is comfortable.",
             "line": "Nxc3 Nge7 Ba3 a6 Nd5"},
            {"san": "Qe7", "severity": "blunder", "tier": "Structure",
             "why": "Retreating onto the file your rook is about to own, and it costs a pawn by force: 10.Nxc3 Qb4 11.Bxf7+! and the king has three squares, none of them f7 — the queen on b3 is looking straight through the bishop. 11...Kd8 12.Nd5 and Black has given up castling and f7 to keep pawns that will never move again.",
             "line": "Nxc3 Qb4 Bxf7+ Kd8 Nd5"},
        ],

        # ══ TWO KNIGHTS ═════════════════════════════════════════════════════════

        # ── ply 7 · your own fourth move after 3...Nf6 ──────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6": [
            {"san": "d4", "severity": "playable", "tier": "Plans",
             "why": "The modern main line — but not because the engine says so. At depth twenty 4.d4, 4.d3 and 4.Ng5 all sit within a tenth of a pawn of each other, with 4.d3 fractionally ahead. What 4.d4 buys is a game where Black cannot fall back on memorised Polerio and Fritz theory: 4...exd4 5.O-O Nxe4 6.Re1 d5 7.Bxd5 Qxd5 8.Nc3 — sharp, sound, and the right choice against anyone who has looked at the Two Knights for ten minutes.",
             "line": "exd4 O-O Nxe4 Re1 d5 Bxd5 Qxd5 Nc3"},
            {"san": "d3", "severity": "playable", "tier": "Foundation",
             "why": "The quiet move, and the one the top players use. It transposes straight back to the Pianissimo: Black plays ...Bc5 or ...Be7 and you get the slow game from the main line with none of the theory below.",
             "line": "Bc5 c3 a6 O-O"},
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "why": "The Four Knights. Symmetrical and completely safe — a legitimate way to sidestep every sharp line on this page.",
             "see": "fourknights"},
            {"san": "O-O", "severity": "playable", "tier": "Structure",
             "why": "Castling and letting Black take on e4 — playable, and a genuine concession, because getting the pawn back costs you the piece the whole opening is built around. 5.Bd5! Nf6 6.Bxc6 dxc6 7.Nxe5 levels the pawns at seven each and the engine calls the position dead level: you have traded the Italian bishop for a knight and bought Black a doubled c-pawn with it. What you must not do is reach for the pattern from the Four Knights: 5.Re1 d5 6.Bxd5?? Qxd5 7.Nc3 Nxc3! and you are a bishop down, because the knight that would recapture on d5 is the one standing on e4. If you play 5.Re1, answer 5...d5 with 6.Bb5.",
             "line": "Nxe4 Bd5 Nf6 Bxc6 dxc6 Nxe5"},
        ],

        # ── ply 8 · after 4.Ng5 ─────────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5": [
            {"san": "Bc5", "severity": "playable", "tier": "Mastery",
             "name": "Traxler Counterattack",
             "why": "Black ignores f7 completely and offers a whole piece for the attack. Against the greedy 5.Nxf7? Bxf2+! it is White who defends for their life. The safe answer is 5.Bxf7+! Ke7 6.Bb3: a pawn up, and it is Black's king on e7 instead of yours.",
             "line": "Bxf7+ Ke7 Bb3 Rf8 O-O"},
            {"san": "h6", "severity": "blunder", "tier": "Foundation",
             "why": "The move club players actually reach for, and it loses material on the spot, because kicking the knight is not the same as guarding f7. 5.Nxf7! and Black cannot take: 5...Kxf7 is not merely bad, it is illegal — the c4-bishop covers the square. The knight forks d8 and h8, so 5...Qe7 6.Nxh8 is a rook and a pawn for a knight, and unlike the 4...d6 version below the knight is not even stuck in the corner afterwards, because ...h6 gave up the guard on g6.",
             "line": "Nxf7 Qe7 Nxh8"},
            {"san": "d6", "severity": "blunder", "tier": "Foundation",
             "why": "This is the move that proves why 4...d5 is forced. f7 is attacked twice and defended once, and ...d6 does nothing about it: 5.Nxf7! Qe7 6.Nxh8 wins the exchange and a pawn. Only 4...d5 blocks the c4-bishop's diagonal — and blocking that diagonal is what makes ...Kxf7 legal at all.",
             "line": "Nxf7 Qe7 Nxh8"},
            {"san": "Be7", "severity": "blunder", "tier": "Foundation",
             "why": "The instinctive defensive move, and it loses on the spot: 5.Nxf7! and Black cannot take, because the c4-bishop covers f7 too. 5...Kf8 6.Nxd8 Nxd8 hands over the queen for a knight.",
             "line": "Nxf7 Kf8 Nxd8 Nxd8"},
            {"san": "Nxe4", "severity": "blunder", "tier": "Foundation",
             "why": "Grabbing the pawn and forgetting the diagonal. 5.Bxf7+! Ke7 and then 6.d4! — not 6.d3, which is the move that lets half of the advantage back. The point of d4 is that you open the centre while Black's king is standing in it: 6...h6 7.Nxe4 Kxf7 and everything is level again on material, seven pawns and equal pieces each. What Black actually paid was the right to castle, and a king on f7 with the centre already open.",
             "line": "Bxf7+ Ke7 d4 h6 Nxe4 Kxf7"},
            {"san": "Qe7", "severity": "inaccuracy", "tier": "Structure",
             "why": "It guards f7 with the queen — one move of development spent on the worst square available. 5.Bxf7+ Kd8 6.Bb3 and White is a pawn up with a black king stranded in the middle and a rook on h8 that may never move.",
             "line": "Bxf7+ Kd8 Bb3"},
        ],

        # ── ply 9 · your own fifth move — three ways to lose a piece ────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5": [
            {"san": "d3", "severity": "blunder", "tier": "Foundation",
             "why": "Propping up e4 and forgetting what ...d5 attacked: 5...dxc4! and the bishop goes. Take the pawn straight back — 6.dxc4 — because the alternative is worse: a bishop for a pawn is bad, a bishop for nothing is a resignation. Black's fourth move hit the pawn on e4 and the bishop on c4 at the same time, and only one of them can be dealt with by a pawn move.",
             "line": "dxc4 dxc4"},
            {"san": "Bxd5", "severity": "blunder", "tier": "Foundation",
             "why": "Taking with the bishop instead of the pawn, and it drops the knight on g5: 5...Nxd5 6.exd5 Qxg5! — the queen on d8 was watching g5 the whole time, and once the bishop has left c4 there is nothing on f7 to distract her. Do not be comforted by 7.dxc6, which wins a piece back and makes the material level again. Count the position instead of the pieces: 7...Qxg2! 8.Rf1 and you have a rook stuck on f1, a king that will never castle and a queen loose in your camp. At depth twenty that is nearly five pawns for Black.",
             "line": "Nxd5 exd5 Qxg5 dxc6 Qxg2"},
            {"san": "Nxf7", "severity": "blunder", "tier": "Foundation",
             "why": "The Fried Liver played one move early, and it is not the same move at all: with the pawn still on d5 the c4-bishop's diagonal is blocked, so 5...Kxf7 is simply legal and Black is a piece up for a pawn. Take on d5 first. That is the entire difference between the attack and the blunder.",
             "line": "Kxf7 exd5 b5 Bf1 Nd4"},
        ],

        # ── ply 10 · after 5.exd5 — the real fork in the road ────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5": [
            {"san": "Na5", "severity": "playable", "tier": "Mastery",
             "name": "Polerio Defence",
             "why": "Black's best, and the move that ends the Fried Liver. Black gives up the d5-pawn to chase the Italian bishop off the a2–g8 diagonal and gets a huge lead in development for it: 6.Bb5+ c6 7.dxc6 bxc6 8.Be2 h6 9.Nf3 e4 10.Ne5. White is a pawn up and hanging on; Black has all the fun.",
             "line": "Bb5+ c6 dxc6 bxc6 Be2 h6 Nf3 e4 Ne5"},
            {"san": "Nd4", "severity": "playable", "tier": "Mastery",
             "name": "Fritz Variation",
             "why": "The sharpest of the lot: 6.c3 b5 7.Bf1 Nxd5 8.cxd4 Qxg5 and both kings end up in trouble at once. Do not walk into this without having looked at it — nobody finds these moves at the board.",
             "line": "c3 b5 Bf1 Nxd5 cxd4 Qxg5"},
            {"san": "b5", "severity": "playable", "tier": "Mastery",
             "name": "Ulvestad Variation",
             "why": "The same idea by a different door — deflect the bishop first, then take on d5. After 6.Bf1 Nd4 it usually transposes straight into the Fritz.",
             "line": "Bf1 Nd4 c3 Nxd5 cxd4 Qxg5"},
            {"san": "Qxd5", "severity": "blunder", "tier": "Foundation",
             "why": "Recapturing with the wrong piece, and it costs the queen: d5 is guarded by your bishop, so 6.Bxd5! Nxd5 is a queen for a bishop. This is why the main line recaptures with the knight — the knight on d5 has the queen on d8 behind it, and a queen on d5 has nothing behind her at all. Count what defends the square before you choose which piece takes it.",
             "line": "Bxd5 Nxd5 d4"},
        ],

        # ── ply 11 · your own sixth move — the Fried Liver or the better move ───
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5": [
            {"san": "d4", "severity": "playable", "tier": "Plans",
             "name": "Lolli Attack",
             "why": "The quieter road to the same attack, and at depth twenty the engine cannot separate it from 6.Nxf7 — five centipawns apart, which is nothing. Fischer thought 6.d4! was so strong that 5...Nxd5 is barely played any more. You keep the knight, open the centre against a king that cannot castle, and Nxf7 is still there next move if you want it.",
             "line": "Nxd4 c3 b5 Bd3 h6 Nxf7"},
            {"san": "O-O", "severity": "inaccuracy", "tier": "Structure",
             "why": "Losing the thread. 6...Qxg5! wins the knight, because it was only ever safe while it was about to take on f7 — once you castle it is a piece standing where the queen can reach it. You do get it back, and that is the point to be honest about: 7.Bxd5 takes on d5 because nothing guards the knight there once the queen has left d8, and the material comes out level. So does the evaluation — dead level at depth twenty. You have not lost a piece, you have handed back the entire attack.",
             "line": "Qxg5 Bxd5 Bd7 d4 Qg6"},
            {"san": "Bxd5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Trading the best piece in the opening for the knight it was attacking. 6...Qxd5 7.O-O Bf5 and Black is better: the queen is fine on d5 now that no bishop looks at it, the knight on g5 has to run, and White has given up the a2–g8 diagonal for nothing.",
             "line": "Qxd5 O-O Bf5 d3 O-O-O"},
        ],

        # ── ply 12 · after 6.Nxf7 ───────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7": [
            {"san": "Ke7", "severity": "blunder", "tier": "Foundation",
             "why": "Declining costs the queen: 7.Nxd8 Kxd8 and White has a queen for a knight. When a knight lands on f7 and hits d8 and h8 at once, the only question left is which one you can afford to lose.",
             "line": "Nxd8 Kxd8"},
            {"san": "Qe7", "severity": "blunder", "tier": "Foundation",
             "why": "Saving the queen loses the rook: 7.Nxh8. Do not go looking for a way out for the knight — from h8 it has exactly two squares, f7 and g6, and Black's king, queen and h-pawn cover both. It is worth a rook and a pawn for a knight sitting in the corner, and that is the whole point.",
             "line": "Nxh8"},
        ],

        # ── ply 16 · after 8.Nc3 — how Black is actually supposed to defend ──────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3": [
            {"san": "Nb4", "severity": "playable", "tier": "Mastery",
             "why": "The engine's choice and the best defence there is — better than the 8...Nce7 of the main line, and worth knowing from both sides. The knight defends d5 a third time and hits c2 on the way, so 9.O-O c6 10.d4 Qf6 and White has to prove the attack rather than count on it. Note the shape of the answer: Black defends by attacking something.",
             "line": "O-O c6 d4 Qf6 Qd1"},
            {"san": "Nd4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Hitting the queen looks like a tempo and it abandons d5. 9.Bxd5+! Kd7 10.Qd1 c6 11.Be4 and the king walks to c7 with White a pawn up and every piece still pouring in. The rule in this position is the one on the plan card: count the defenders of d5 before you touch anything else.",
             "line": "Bxd5+ Kd7 Qd1 c6 Be4"},
        ],

        # ── ply 14 · after 7.Qf3+ ───────────────────────────────────────────────
        "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+": [
            {"san": "Ke8", "severity": "blunder", "tier": "Foundation",
             "why": "Running backwards loses the piece back: 8.Bxd5 and White is a pawn up with a black king that will never castle. Worse, 8...Qxd5?? 9.Qxd5 drops the queen outright — nothing else on the board guards d5.",
             "line": "Bxd5"},
            {"san": "Kg8", "severity": "blunder", "tier": "Foundation",
             "why": "8.Bxd5+, and this one is not merely the piece back — it is mate: 8...Qxd5 9.Qxd5+ Be6 10.Qxe6#. Tucking the king into the corner puts it on the a2–g8 diagonal, which is the one place in this whole opening you must never stand.",
             "line": "Bxd5+ Qxd5 Qxd5+ Be6 Qxe6#"},
            {"san": "Kg6", "severity": "blunder", "tier": "Foundation",
             "why": "Walking toward the attack, and it does lose — but not to a queen check. Take the piece first: 8.Bxd5! Qf6 9.Qg3+ Qg5 10.Qxg5+ Kxg5 11.d3+ and the pawn move uncovers the c1-bishop. Be clear about what that is worth: you are one pawn up with the queens off, and the engine still says four pawns, because the black king is standing on g5 with every white piece on the board. And 8...Qf6 is the only move — anything else is 9.Bf7+ Kg5 10.d3+ Kh4 11.Qg3#. The move that does not work is the natural-looking 8.Qf5+??, because Black's d-pawn is gone and the bishop on c8 has a clear road to f5 — 8...Bxf5 wins the queen. Every check in this attack has to be checked against that diagonal.",
             "line": "Bxd5 Qf6 Qg3+ Qg5 Qxg5+ Kxg5 d3+"},
        ],
    },
    "games": [
        {
            "id": 'carlsen-nakamura-2011',
            "name": "Carlsen – Nakamura, London 2011 — the slow Italian, start to finish",
            "tier": 'Structure',
            "note": "The main line's plan played by the man who brought it back. Nakamura chose the Two Knights, Carlsen answered 4.d3 and transposed into the Pianissimo, finished the knight tour, traded the bishop that was holding the centre shut — and then broke on move seventeen and again on move twenty-six. Nothing is sacrificed until move thirty-one, by which point it is not a sacrifice.",
            "moves": (
                'e4 e5 Nf3 Nc6 Bc4 Nf6 d3 Bc5 c3 d6 Bb3 a6 Nbd2 Ba7 Nf1 h6 '
                'Ng3 O-O O-O Be6 h3 Qd7 Be3 Ne7 Nh4 Ng6 Nhf5 Ne7 Nxe7+ Qxe7 '
                'Bxa7 Rxa7 f4 c5 Bc2 b5 Qd2 Rb7 a3 a5 Rf2 b4 axb4 axb4 '
                'Raf1 bxc3 bxc3 exf4 Rxf4 Nh7 d4 cxd4 cxd4 Qg5 Kh2 Nf6 Bd1 Rfb8 '
                'h4 Qg6 Rxf6 gxf6 Qf4 Rb2 Bh5 Qg7 Bf3 Ra8 d5 Bc8 Nh5 Qf8 '
                'Nxf6+ Kh8 Rc1 Kg7 e5 dxe5 Nh5+ Kh7 Be4+'
            ),
            "notes": {
                7: "The quiet move, and the whole reason it sits on the deviation panel after 3...Nf6: Carlsen declines the entire Fried Liver argument. Black answers 4...Bc5 and the game is back in the main line you have drilled, a move order later.",
                11: "The bishop leaves c4 before anyone asks it to. On b3 it is out of range of ...Na5 and ...b5 for the rest of the game — this is the tempo the main line spends on Re1, spent differently.",
                14: "The same prophylaxis as the main line, played for the same reason: back up along the a7–g1 diagonal, out of the d-pawn's reach, so that d4 can never arrive with a threat attached. Both players are following their own plan cards.",
                15: "The tour, d2–f1–g3, one move earlier than in the main line because White never played Re1. Two moves that look like nothing and buy the f5 square.",
                21: "Insurance, on schedule. Black has already put the bishop on e6 rather than g4 — which is what h3 is for whether or not the pin is ever available.",
                23: "The offer. Trace the a7–g1 diagonal before you decide what this move is for: the bishop on a7 covers d4 and points at f2, and Be3 steps into it and asks to trade — and notice White does not take on a7 yet. Black has to spend the moves deciding.",
                27: "The knight lands on f5 and the other one guards it from g3 — which is why the tour went to g3 first. That is the counting rule from the plans card: one piece arriving on a square is a visit, two is an attack.",
                31: "Now the trade, on White's terms. Black's rook is dragged to a7, off the file it wanted, and the a7–g1 diagonal is empty — which is the permission slip for the next move.",
                33: "Seventeen quiet moves for one pawn push, and it is f4, not d4. Every black piece is watching the centre, so White opens the file nobody is watching.",
                48: "Black resolves the tension and every white piece gets a line at once. Count the ones that bear on f4: both rooks are already stacked on the file and the queen on d2 backs them up, which is three, with the knight on g3 next door. And note where the Italian bishop is now — c2, on the b1–h7 diagonal, not the a2–g8 one it started on. It has swapped diagonals, and h7 is the square this game ends on.",
                51: "And now the other break, on move twenty-six. This is what 'you are the one who gets to choose when it opens' means: the pawn reached d3 on move four, so d4 had been legal for twenty moves and Carlsen had no use for it until the second front was open.",
                61: "A rook for a knight, and not for mate — it buys the f6 square and a black king with no pawn cover. Everything after this is technique.",
                69: "The pawn that took twenty-six moves to reach d4 now hits the bishop on e6 — and every active square it has loses it. Bxd5 and ...Bf5 run into the e4-pawn, ...Bg4 and ...Bh3 into the bishop on f3 and the g-pawn, so it goes back to c8 and does nothing for the rest of the game. Nothing on Black's queenside has moved in ten moves either; that is what playing on two wings does to a defence.",
                77: "The second central pawn joins in and the roof comes off. Both breaks, f4 and d4–d5–e5, came from the structure the plan card describes — no combination, just two pawn majorities arriving at the same king.",
                81: "Be4+ and Nakamura resigned. There are exactly four legal moves and they are worth walking. 41...Bf5 42.Bxf5+ is a piece for nothing, because Black has no recapture — only Kg8 and Kh8. 41...f5 42.Bxf5+ costs only a pawn, since the queen or the bishop can take on f5, but the king is left with nothing in front of it. And the two king moves keep the net closed: 41...Kg8 42.Nf6+, 41...Kh8 42.Qf6+. The bishop that stepped back to b3 on move six lands the last blow — from the other diagonal.",
            },
        },
        {
            "id": 'anderssen-dufresne-1852',
            "name": "Anderssen – Dufresne, Berlin 1852 — 'The Evergreen Game'",
            "tier": 'Plans',
            "note": "The most famous Evans Gambit ever played, and it starts from the position you have just stepped through. Dufresne chose 7...d3 instead of 7...dxc3 — giving the pawn straight back to kill White's centre — and reached the same tabiya with the extra pawn on d3.",
            "moves": (
                'e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 '
                'd4 exd4 O-O d3 Qb3 Qf6 e5 Qg6 Re1 Nge7 '
                'Ba3 b5 Qxb5 Rb8 Qa4 Bb6 Nbd2 Bb7 Ne4 Qf5 '
                'Bxd3 Qh5 Nf6+ gxf6 exf6 Rg8 Rad1 Qxf3 Rxe7+ Nxe7 '
                'Qxd7+ Kxd7 Bf5+ Ke8 Bd7+ Kf8 Bxe7#'
            ),
            "notes": {
                14: "Dufresne hands the pawn straight back. It is the modern idea a century early: kill White's centre before it exists, and worry about the pawn count afterwards.",
                18: 'The same square, the same reason as the main line — the only square that defends f7 and keeps the queen alive.',
                21: 'The move the terminal plan card told you to play — and not for the reason it looks like. The bishop does not hit f8 yet, because Black\'s own knight on e7 is standing in the way. It hits the knight, and the knight is the only thing keeping the bishop out of the square Black wants to castle past.',
                24: 'Count it: six pawns to seven, so Black is one pawn up and the extra one is the pawn stranded on d3. Every white piece is aimed at a king still on e8. This is the Evans bargain in one picture.',
                27: 'Both knights come to the party. Anderssen has not made a single threat yet — he has simply finished developing, which is what makes the next eight moves possible.',
                31: 'Bxd3 takes back the pawn Dufresne handed over on move seven, and the material is now exactly level. Sixteen moves, every piece developed, and Anderssen has not made a single threat — which is the part of this game nobody remembers and the part that makes the rest of it work.',
                33: 'Nf6+ — the piece is offered because the g-file matters more than the knight. Every move from here is check or a threat of mate; the moment White gives Black a free move, Black mates first.',
                36: 'Black brings the rook to the open file with a real threat. This is not a losing position yet.',
                37: 'The quiet move in the middle of a storm. Rad1 develops the last piece and does not check anything — and it is the reason the whole combination works.',
                38: 'Qxf3 threatens 20...Qxg2#, and it is genuinely mate. Find the second attacker before you trust it: the b7-bishop looks like the piece guarding g2 and it is not — its own knight on c6 is in the way. It is the rook on g8, on the file Black opened with 17...gxf6. White now has to give check on every single move or lose.',
                39: 'Rxe7+, the first of four sacrifices. The rook goes so that the knight is dragged off d5 and away from the defence.',
                41: 'Qxd7+!! The queen for nothing. After 21...Kxd7 White is a queen and a rook down and mates in three — the most famous move in nineteenth-century chess.',
                43: 'Bf5+ is the point of Qxd7+: the king was decoyed to d7 so that this bishop check would come with tempo. The king has one square.',
                47: 'Bxe7#. Mate with the two bishops and the pawn on f6. Count what is left on the board: Anderssen finished a queen and a rook down, with two extra pawns for them.',
            },
        },
    ],
    "progression": {
        "arc": "The Italian is where you learn what the opening principles actually mean. Everything you build later stands on this.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Your first week with it",
                "goal": "Reach a healthy position by move ten without thinking.",
                "learn": [
                    "The six-move skeleton: e4, Nf3, Bc4, c3, d3, O-O. Play it against anything Black does on move three.",
                    "Why Bc4 and not Bb5 or Be2 — the f7 square is defended only by the king, so it is the one target that exists from move one.",
                    "The three ways Black can answer 3.Bc4: 3...Bc5 (Giuoco), 3...Nf6 (Two Knights), 3...Be7 (Hungarian). You need a reply to each.",
                ],
                "drill": "Set the board up and play the six-move skeleton twenty times against a friend or an engine at low strength. Your hands should know it before your head does.",
                "mistake": "Playing 4.Ng5 in every position because it 'attacks f7'. It is one idea, not a plan, and a prepared opponent punishes it.",
                "ready": "You can play the first eight moves without pausing and explain why each piece went where it did.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to four",
                "goal": "Understand the d4 break — when it wins the game and when it throws it away.",
                "learn": [
                    "The difference between 5.d4 (immediate, opens the game while Black is behind) and 5.d3 (slow, keeps the tension). Modern practice prefers d3.",
                    "What happens to the pawn structure after ...exd4 cxd4 — White gets d4+e4 and the c-file, Black gets the d5 square and a target.",
                    "Why ...a6 and ...Ba7 exist: Black is removing d4 from your list of good moves before you play it.",
                ],
                "drill": "Take the main-line position after 8.Nbd2 and write down, in words, three plans for White and three for Black. Then check them against the plans card above.",
                "mistake": "Playing d4 the moment it is legal. In the Pianissimo you are supposed to spend eight moves earning it.",
                "ready": "You can look at an Italian position and say whether the centre should be opened or kept closed, and why.",
            },
            {
                "tier": "Plans",
                "when": "Months two and three",
                "goal": "Play the middlegame, not just the opening.",
                "learn": [
                    "The knight tour Nb1–d2–f1–g3 and its cousin ...Nc6–e7–g6. Both sides re-route toward the kingside; whoever finishes first attacks first.",
                    "The rook lift Re1–e3–g3 and when the e-file is worth more than the attack.",
                    "How to meet ...d5: usually exd5 followed by piece pressure, occasionally e5 gaining space.",
                ],
                "drill": "Play ten games where you commit to reaching the Pianissimo tabiya and then attacking the kingside. Lose some. Note where the attack ran out of pieces.",
                "mistake": "Attacking with two pieces. An attack needs three or four attackers against the defenders present — count before you commit.",
                "ready": "You have won a game with the Nf1–g3 manoeuvre and lost one because you attacked too early. Both lessons matter.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Own the sharp branches and the endgames.",
                "learn": [
                    "The Evans Gambit as a surprise weapon, including the critical defences 5...Ba5, 5...Bc5 and 5...Be7.",
                    "The Two Knights in full: the Fried Liver, the Polerio 5...Na5, the Traxler 4...Bc5!?, and the modern 4.d4.",
                    "Endgames from the Italian: bishop against knight with pawns on both wings, and how the extra central pawn tells.",
                ],
                "drill": "Take one Evans Gambit line and analyse it thirty moves deep with an engine, then close the engine and try to explain the evaluation.",
                "mistake": "Treating the gambit lines as tricks. At any decent level they are real openings with real theory.",
                "ready": "You can play both sides of the Two Knights and you know which side you would rather have.",
            },
        ],
        "study": "Paul Morphy for the attacking version, Anatoly Karpov and Magnus Carlsen for the modern slow build. Kasparov–Anand, Riga 1995 is the most famous Evans Gambit of the last century.",
        "next": "Once the Italian feels automatic, learn the Ruy Lopez. The ideas transfer directly and the Ruy is simply a better version of the same opening.",
    },
}
