OPENING = {
    "id": "kid",
    "name": "King's Indian Defence",
    "eco": "E60–E99",
    "section": "black-d4",
    "orientation": "black",
    "tagline": "Give White the whole centre, then blow up the kingside. The most aggressive answer to 1.d4.",
    "level": "Intermediate → World Championship",
    "theory": {
        "big_idea": "Black deliberately allows White to build a huge pawn centre with c4, d4 and e4, then attacks it from a distance with a fianchettoed bishop and the break ...e5. When White closes the centre with d4–d5, the position becomes locked and both sides attack on opposite wings: White pushes c4–c5 on the queenside, Black pushes ...f5–f4 and ...g5–g4 at White's king. It is the purest attacking race in chess, and the side that is one tempo faster usually wins by force.",
        "structure": "The defining structure is the Mar del Plata: locked pawns on c4/d5/e4 for White against c7/d6/e5 for Black. This diagonal pawn wall determines everything — White's pawns point at the queenside, so White attacks there; Black's point at the kingside, so Black attacks there. Neither side defends. Whoever arrives first wins.",
        "white_plans": [
            "Close the centre with d5, then break with c5 and pile onto the c-file and c7.",
            "Play the Sämisch with f3, Be3 and O-O-O, and storm the kingside instead — turning Black's own plan against them.",
            "The Fianchetto Variation with g3: a calm, safe way to blunt the Bg7 and steer the game toward a positional Benoni.",
            "Trade off the g7-bishop with Be3–h6 or Bg5 and Qd2 — Black's attack dies without it.",
        ],
        "black_plans": [
            "Break with ...e5, then re-route the knights (...Ne7 or ...Nd7) out of the way of the f-pawn.",
            "The pawn storm: ...f5, ...f4, ...g5, ...g4, ...h5 and often a rook lift ...Rf6–h6.",
            "Sacrifice material to open the h-file or the g-file. In many KID games Black is a piece down and completely winning.",
            "Meet a queenside break with ...a5 and ...Nc5, blocking the c-file with a knight.",
        ],
        "traps": [
            "Do not play ...e5 too early against 4.e4 — check that White cannot answer dxe5 favourably.",
            "In the Mar del Plata, if Black plays ...f5 before securing the knight route, White can hit with exf5 gxf5 and Ng5 or f4 with a strong attack.",
            "The Bayonet Attack (9.b4) is White's most testing modern try — Black must know 9...Nh5 or 9...a5.",
        ],
        "who": "Play this if you want to attack from move one with the black pieces and you accept that you will be objectively worse for the first thirty moves. Fischer, Kasparov and Radjabov made it famous.",
    },
    "lines": [
        {
            "name": "Classical — Mar del Plata",
            "note": "The main line and the most exciting position in modern chess. Both sides attack on opposite wings and nobody defends.",
            "moves": "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7 Ne1 Nd7 Nd3 f5 f3 f4 Bd2 g5",
            "notes": {
                4: "Black prepares the fianchetto rather than fighting for the centre with pawns.",
                6: "The King's Indian bishop. It aims down the long diagonal at d4 and b2 and it is the most important piece in the position. Black will sacrifice almost anything else to keep it.",
                7: "White takes the full classical centre. Black has allowed this on purpose — the pawns are a target, not a triumph.",
                8: "Supporting the coming ...e5 break.",
                9: "Development.",
                10: "King safety, completing the setup. Black's first six moves are identical against almost anything.",
                11: "Modest development. The Classical Variation.",
                12: "The key break. Black finally hits the centre. White must now choose: take, keep the tension, or close.",
                13: "King safety.",
                14: "Adding a second attacker to d4 and daring White to close.",
                15: "White closes the centre. This is the critical decision of the whole opening — from here the position is locked and the race begins.",
                16: "The knight steps out of the way. It heads for g6 or, later, supports ...f5 and ...g5.",
                17: "White unblocks the f-pawn and heads for d3 where the knight supports c5 and covers f4/e1.",
                18: "Black clears the f-file for the coming pawn storm and prepares ...f5.",
                19: "The knight reaches its best square, supporting the c5 break.",
                20: "The storm begins.",
                21: "Reinforcing e4 and keeping the centre closed.",
                22: "Black pushes past, permanently locking the kingside pawn structure. Now Black's plan is pure: ...g5, ...h5, ...g4 and mate.",
                24: "Black is committed. Every remaining move is aimed at White's king, and White is doing the same on the queenside. This is a race with no defence — one of the most thrilling positions in chess.",
                23: "White gets on with it. The bishop clears the way for Rc1, b4 and c5. Nobody is defending: White has counted the tempi and believes the queenside break arrives first.",
            },
        },
        {
            "name": "Sämisch Variation",
            "note": "White plays f3 to bolster e4 and castles queenside, meeting Black's attack head-on with an attack of its own.",
            "moves": "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3 O-O Be3 e5 d5 Nh5 Qd2 f5 O-O-O Nd7 Kb1 Nc5",
            "notes": {
                9: "The Sämisch. White defends e4 with a pawn instead of a knight, freeing the g1-knight and preparing g4 and h4.",
                10: "King safety.",
                11: "Development. The bishop guards d4 and eyes h6, where it can trade off Black's key bishop.",
                12: "The standard break.",
                13: "White closes the centre.",
                14: "The knight jumps out of the f-pawn's way and heads for f4. Note that ...Nh5 is only possible because White's f3-pawn blocks the natural Bg5 pin.",
                15: "Connecting the rooks and preparing O-O-O.",
                16: "Black's break arrives fast.",
                17: "White castles into the attack. The race is on, and here it is mutual: White pushes g4 and h4, Black pushes ...f4 and ...g5.",
                18: "Re-routing the knight toward c5 and the queenside.",
                19: "Tucking the king safely into the corner before the storm.",
                20: "The knight reaches its best square, hitting e4 and preparing ...a5. A double-edged fight in which Black's counterplay is genuinely fast enough.",
            },
        },
        {
            "name": "Fianchetto Variation",
            "note": "White's safest system. The g2-bishop blunts Black's Bg7 and the whole kingside attack loses its bite.",
            "moves": "d4 Nf6 c4 g6 Nf3 Bg7 g3 O-O Bg2 d6 O-O Nbd7 Nc3 e5 e4 c6 h3 Qb6 Re1 exd4",
            "notes": {
                5: "Development, avoiding the immediate e4.",
                7: "The Fianchetto Variation. White's bishop stares back down the long diagonal, neutralising Black's most important piece.",
                8: "King safety.",
                9: "The bishops face off. This is why the Fianchetto is so annoying for Black: the attacking mechanism is defused before it begins.",
                10: "Supporting ...e5.",
                11: "King safety.",
                12: "The knight goes to d7, not c6, so it does not get hit by d4–d5 and it supports the ...e5 break twice.",
                13: "Development.",
                14: "The break.",
                15: "White takes the extra centre, but with the bishop on g2 rather than the classical setup — a quieter, more positional version.",
                16: "The key difference from the Classical: because White's bishop controls d5, Black wants to fight for that square with the c-pawn rather than launch a kingside storm.",
                17: "Useful prophylaxis against ...Bg4 or ...Ng4.",
                18: "The queen hits b2 and d4 and eyes the queenside, where the play now is.",
                19: "Supporting e4 and preparing d5 or dxe5.",
                20: "Black resolves the tension and heads for a balanced, manoeuvring middlegame. Objectively equal, but the character is nothing like a Mar del Plata — this is a positional game.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Mar del Plata race",
        "note": "The purest attacking race in chess. Neither side defends. Count the moves each attack needs.",
        "moves": "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7 Ne1 Nd7 Nd3 f5 f3 f4 Bd2 g5 Rc1 Ng6 c5 Nf6 cxd6 cxd6 Nb5 Rf7 Qc2 Ne8 a4 h5",
        "notes": {
            25: "White's rook takes the file it will attack down. The queenside operation begins.",
            26: "Black's knight returns from e7 to g6, where it supports the coming ...h5 and ...g4 and covers e5 and h4.",
            27: "The break. White's whole plan in one move: open the c-file and create a target on d6.",
            28: "Black brings the knight back toward the kingside. Note that Black has not defended the queenside once and will not.",
            29: "White cashes in.",
            30: "Forced. Black now has a backward d6-pawn on an open file — objectively a serious weakness, and completely irrelevant if the attack arrives first.",
            31: "The knight jumps to b5, hitting d6 and heading for c7 or a7. White is one or two moves from winning material.",
            32: "The rook lift begins. From f7 the rook can swing to g7 or h7, or double on the f-file. Black is ignoring the queenside entirely.",
            33: "White piles onto the c-file. The threat of Nc7 or Rc7 is real.",
            34: "The knight steps back to defend d6 with the queen's help — the one concession Black makes.",
            35: "White prepares a5 and Ba4 or simply a5–a6 to shatter the queenside.",
            36: "And Black plays on. The pawns will come: ...h5, then ...g4, then ...g3 or a sacrifice on h3 or f3. This is the moment to stop and count. White needs roughly three moves to win material on the queenside; Black needs roughly four to reach White's king. Whether that trade-off favours Black depends on details invisible to any general principle — which is precisely why grandmasters have argued about this position for seventy years.",
        },
    },
    "progression": {
        "arc": "The King's Indian is a bet: you will be objectively worse for thirty moves and then checkmate someone. Learn to enjoy that.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to two",
                "goal": "Learn the six-move setup and the one break that matters.",
                "learn": [
                    "The setup: ...Nf6, ...g6, ...Bg7, ...d6, ...O-O, then ...e5. Play it against nearly everything White does.",
                    "Why you allow the big centre: those pawns are targets, and your Bg7 is aimed at the heart of them.",
                    "The two breaks: ...e5 always, ...c5 when White has committed to a Sämisch or fianchetto.",
                ],
                "drill": "Play the six-move setup fifty times. It is the same against 1.d4, 1.c4 and 1.Nf3, which makes it enormously efficient.",
                "mistake": "Playing ...e5 before you have castled or before the knight route is clear. Timing is everything in the KID.",
                "ready": "You reach the setup automatically against every White system.",
            },
            {
                "tier": "Structure",
                "when": "Months one to two",
                "goal": "Understand the locked centre and what it commands you to do.",
                "learn": [
                    "The Mar del Plata skeleton: White c4-d5-e4, Black c7-d6-e5. Your pawns point at the kingside, so you attack there. No exceptions.",
                    "The knight routes: ...Ne7–g6 or ...Nd7–f6, both clearing the f-pawn's path.",
                    "Why ...f5 then ...f4 permanently locks the position — after that, only the wings matter.",
                ],
                "drill": "Set up the position after ...f4 and play only ...g5, ...h5, ...g4 and ...Rf6–h6. Ten times. Feel the mechanism.",
                "mistake": "Defending the queenside. If you spend moves stopping c5, you lose the race — White's break was going to happen anyway.",
                "ready": "You can explain why Black does not defend in the King's Indian.",
            },
            {
                "tier": "Plans",
                "when": "Months two to eight",
                "goal": "Learn to attack with everything and count the race.",
                "learn": [
                    "The full storm: ...f5, ...f4, ...g5, ...h5, ...g4, then ...g3 or a piece sacrifice on h3 or g4.",
                    "The rook lift ...Rf6–h6 and the queen route ...Qe8–f7–h5 or ...Qd8–e8–g6.",
                    "Counting: White needs roughly the same number of moves on the queenside. Every tempo you spend elsewhere is one you lose.",
                ],
                "drill": "Play twenty Mar del Plata positions from move fifteen. Sacrifice something in each. Learn what compensation actually looks like.",
                "mistake": "Hesitating. In a King's Indian a slow attacking move is often worse than an unsound sacrifice.",
                "ready": "You have won a game while a piece down.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Handle the systems designed to stop you.",
                "learn": [
                    "The Fianchetto Variation, where White's Bg2 neutralises your Bg7 — you must switch to a positional game with ...c6 and ...a5.",
                    "The Sämisch with f3, where White castles queenside and races you back.",
                    "The Bayonet Attack 9.b4, the sharpest modern try, and the ...Nh5 and ...a5 answers.",
                ],
                "drill": "Prepare the Fianchetto lines properly. It is the variation that scores best against the KID and the one most players neglect.",
                "mistake": "Playing the Mar del Plata plan in the Fianchetto. The mechanism is not there and the attack will not arrive.",
                "ready": "You know which of White's systems calls for attack and which calls for manoeuvring.",
            },
        ],
        "study": "Bobby Fischer, Garry Kasparov and Teimour Radjabov are the three great King's Indian players. Kasparov's KID wins from the 1990s are the clearest teaching material available.",
        "next": "Add the Grünfeld or the Benoni as an alternative when White plays a system you dislike — both share the ...g6 move order.",
    },
}
