OPENING = {
    "id": "london",
    "name": "London System",
    "eco": "D02 / A46",
    "section": "white-d4",
    "orientation": "white",
    "tagline": "One setup against almost anything. The lowest-theory way to play 1.d4 well.",
    "level": "Beginner → Grandmaster",
    "theory": {
        "big_idea": "White plays the same first five or six moves regardless of what Black does: d4, Bf4, e3, Nf3, c3, Bd3 (and often Nbd2, h3, O-O). The bishop gets outside the pawn chain before e3 locks it in — this is the single most important move-order point in the whole system. The result is a solid, flexible position with no weaknesses, from which White plays either Ne5 with a kingside attack or a slow queenside expansion.",
        "structure": "White pawns on d4, e3, c3 form a small pyramid — extremely hard to attack. The dark-squared bishop sits outside on f4 or g3 controlling the b8–h2 diagonal. The signature attacking pattern is Ne5, f4, Qf3–h3 and Rf3–h3, throwing pieces at h7.",
        "white_plans": [
            "Plant a knight on e5, support it with f4 and Nd2–f3, then swing the queen and rook to the h-file.",
            "Trade dark-squared bishops on d6, then use the resulting dark-square control and pressure on c7/e5.",
            "Queenside expansion with b4, a4 and Nb3–c5, especially when Black castles kingside and plays ...c5.",
            "The 'Barry/Jobava' aggressive version: Nc3 and e4 for a fast central break.",
        ],
        "black_plans": [
            "Hit d4 immediately with ...c5 and ...Qb6 pressuring b2 — the sharpest test of the system.",
            "Play ...Bd6 to trade off White's good bishop, then ...Qxd6 and ...e5.",
            "Set up a King's Indian structure with ...g6, ...Bg7, ...d6, ...Nbd7 and break with ...e5.",
            "Develop the c8-bishop early with ...Bf5 before ...e6 — the mirror image of White's own idea.",
        ],
        "traps": [
            "If White plays e3 before Bf4, the bishop is stuck behind the pawn chain — this is the mistake that turns a good London into a bad one.",
            "After ...Qb6 hitting b2, White should not panic: Qb3, Nc3 (offering the pawn) or Qc1 all hold. Grabbing with ...Qxb2 often costs Black the queen after Nb5 and Rb1 ideas.",
            "Watch out for ...Nh5 hitting the f4-bishop. Standard answers: Bg3 or Be5, or pre-empt with h3 and Bh2.",
        ],
        "who": "Play this if you want to spend your study time on middlegames and endgames instead of opening theory. It is genuinely sound — Carlsen, Kamsky and Gukesh all use it.",
    },
    "lines": [
        {
            "name": "Main Line vs ...e6 — The Ne5 Attack",
            "note": "The standard London against Black's most common setup, with the classic kingside attacking scheme.",
            "moves": "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 Qf3",
            "notes": {
                2: "Black mirrors solidly.",
                3: "The defining move, and the reason to play the London in this move order. The bishop gets outside the pawn chain before e3 shuts it in.",
                4: "Natural development.",
                5: "Now the pawn chain is complete: d4, e3 and soon c3. Small, but there is nothing to attack.",
                6: "Black develops and prepares to challenge with ...c5.",
                7: "Supporting d4 and preparing to castle.",
                8: "The main challenge. Black hits the base of the pawn chain.",
                9: "Reinforcing d4. Now White's pyramid c3–d4–e3 is complete and rock solid.",
                10: "Adding pressure on d4.",
                11: "The knight goes to d2, not c3, so that the c-pawn stays on c3 supporting d4. It also supports the key e5 square.",
                12: "Black offers a trade of the important dark-squared bishops.",
                13: "The bishop steps back and declines the trade, keeping the good bishop and staying on the b8–h2 diagonal aimed at h7.",
                14: "King safety.",
                15: "The bishop finds the b1–h7 diagonal. Together with the g3-bishop, White now has two bishops pointing at Black's king.",
                16: "Black prepares to fianchetto and challenge the long diagonal.",
                17: "The signature move of the London System. The knight lands on the outpost supported by d4 and the d2-knight, and it takes away Black's key squares.",
                18: "Black develops.",
                19: "The attack begins. The plan is Qh3 (or Qf3–h3), f4 supporting the knight, then Rf3–h3 and a pile-up on h7. If Black ever plays ...h6, the sacrifice Bxh6 becomes real.",
            },
        },
        {
            "name": "London vs the King's Indian Setup",
            "note": "When Black fianchettoes, the London switches gears: White grabs the centre with c4 and plays a Queen's-Gambit-style game.",
            "moves": "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2 d6 h3 Nbd7 O-O Re8 c4 e5 Bh2 exd4 exd4",
            "notes": {
                2: "Black keeps things flexible and hits e4.",
                3: "Still the same move. The London is a system: the bishop always comes out first.",
                4: "Black heads for a King's Indian structure with a fianchettoed bishop.",
                5: "The pyramid begins.",
                6: "Black's bishop now stares down the long diagonal at d4 and b2. White must be aware of that pressure all game.",
                7: "Development.",
                8: "King safety.",
                9: "Modest, but the bishop is fine here — it supports the f3-knight and covers c4/d3.",
                10: "Black prepares the standard KID break ...e5.",
                11: "Useful prophylaxis: it stops ...Bg4 and ...Nh5, and gives the f4-bishop the h2 retreat.",
                12: "Preparing ...e5.",
                13: "Castling and connecting the rooks.",
                14: "Supporting the ...e5 push.",
                15: "White grabs the extra central space now that the kingside is safe. The London has transposed into a Queen's Gambit-style position — a good deal for White.",
                16: "Black finally breaks.",
                17: "Stepping the bishop out of the way in advance. This is why h3 was played earlier.",
                18: "Black releases the tension.",
                19: "White recaptures and has a comfortable, slightly better game: more central space, no weaknesses and a clear plan of d5 or Nc3 and Qb3.",
            },
        },
        {
            "name": "London vs the ...c5 Challenge",
            "note": "The most direct test. Black hits d4 at once and White answers by trading and playing on the resulting structure.",
            "moves": "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3 Bg4 Be2 e6 c3 Bd6 Bxd6 Qxd6 O-O Nge7 Nbd2",
            "notes": {
                4: "The critical challenge. Black hits d4 immediately, before White gets in c3.",
                5: "White calmly builds anyway. Note that grabbing with 4.dxc5 gives Black easy equality with ...e6 and ...Bxc5.",
                6: "Black releases the tension. This is a concession — it gives White a healthy symmetrical structure and the open e-file.",
                7: "Recapturing toward the centre and opening the e-file.",
                8: "Development with pressure on d4.",
                9: "Development.",
                10: "Pinning the knight to increase the pressure on d4.",
                11: "Breaking the pin and offering a trade if Black wants it.",
                12: "Solid.",
                13: "The familiar pyramid. Now d4 is defended by pawn, knight and (soon) queen.",
                14: "Black offers the bishop trade again.",
                15: "This time White accepts, because after the recapture Black's queen is slightly awkward on d6 and White gains time with Nbd2–b3 or Qb3.",
                16: "Forced.",
                17: "King safety.",
                18: "Black develops the last knight — note ...Nf6 was unavailable without blocking, so it goes to e7 heading for f5 or g6.",
                19: "The knight heads for b3 and c5 or f1 and g3. Symmetrical structure, equal material, and a long quiet game where the better player wins. That is exactly what the London is designed to produce.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the London kingside attack",
        "note": "The quiet system stops being quiet. Watch the e5 knight, an en passant capture and the f-pawn tear the kingside open.",
        "moves": "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 Qf3 Nxe5 Bxe5 Bxe5 dxe5 Nd7 Qg3 f5 exf6 Nxf6 O-O Qe7 Rae1 Rad8 f4",
        "notes": {
            20: "Black trades off the outpost knight. Sensible — that knight was the heart of White's position.",
            21: "White recaptures with the bishop, which now sits on e5 doing exactly the same job.",
            22: "Black repeats the idea and trades again.",
            23: "And here is the transformation. White recaptures with the d-pawn, giving up the broad centre for a pawn on e5 that cramps Black and shields the coming build-up.",
            24: "The knight retreats to a passive square. Black is suddenly short of space.",
            25: "The queen sidesteps to g3, unblocking the f-pawn and adding a third attacker to the b8–h2 diagonal.",
            26: "Black blocks the diagonal and stops f4–f5. The standard defensive try.",
            27: "En passant. Because Black's pawn passed the e5-pawn's capture square in a single move, White may take it as though it had moved only one. The f-file cracks open.",
            28: "Forced. Black recaptures, but the kingside is now open — which is what White wanted all along.",
            29: "Only now does White castle, into an already-open position, with the rook landing on the file it will attack down.",
            30: "Black centralises the queen and defends.",
            31: "Both rooks join. White has the e-file, a bishop on d3 aiming at h7 and the queen on g3.",
            32: "Black contests the centre.",
            33: "And the pawn finally advances, with f5 to come. A sharp, roughly balanced position — but look how it arrived. Nine quiet system moves, one knight to e5, and the London became an attack.",
        },
    },
    "progression": {
        "arc": "The London gets you a good position with almost no memorisation. The catch is that the middlegames are entirely up to you.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Day one",
                "goal": "Learn the setup and, above all, the move order.",
                "learn": [
                    "The setup: d4, Bf4, e3, Nf3, c3, Bd3, Nbd2, h3, O-O. Nine moves, playable against almost anything.",
                    "The one rule that matters: Bf4 before e3. Every bad London starts by locking the bishop in.",
                    "Why the knight goes to d2 and not c3 — the c-pawn must stay on c3 supporting d4.",
                ],
                "drill": "Play the nine-move setup in fifty blitz games. It should take you under a minute total.",
                "mistake": "Playing on autopilot into a bad version. If Black plays an early ...c5 and ...Qb6, you must respond, not continue the routine.",
                "ready": "You can reach the full setup against 1...d5, 1...Nf6 and 1...e6 without thinking.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to four",
                "goal": "Recognise which of three middlegames you have landed in.",
                "learn": [
                    "Type 1 — Black plays ...e6 and ...Bd6: you decline the bishop trade with Bg3, play Ne5 and attack the kingside.",
                    "Type 2 — Black fianchettoes: you switch plans entirely, play c4 and treat it as a Queen's Gambit.",
                    "Type 3 — Black plays ...c5 and ...Qb6 hitting b2: you need a concrete answer (Qb3, Qc1 or the Nc3 pawn offer).",
                ],
                "drill": "Write down your answer to ...Qb6 and memorise it. It is the only real theory the London requires.",
                "mistake": "Panicking when b2 is attacked and playing Qc1 passively every time. Sometimes offering the pawn is much stronger.",
                "ready": "You can name which of the three types you are in by move six.",
            },
            {
                "tier": "Plans",
                "when": "Months two to four",
                "goal": "Turn the solid position into an attack.",
                "learn": [
                    "The attacking machine: Ne5, f4, Qf3–h3, Rf3–h3 and the Bxh6 sacrifice when Black weakens with ...h6.",
                    "The trade-on-d6 plan: swap dark-squared bishops, then use the dark squares and the c-file.",
                    "The queenside plan: b4, a4, Nb3–c5 when Black castles kingside and commits to ...c5.",
                ],
                "drill": "Study the Bxh7+ and Bxh6 sacrifice patterns until you can calculate them in ten seconds. The London produces them constantly.",
                "mistake": "Playing solidly forever. The London is not a draw machine — if you never attack, strong opponents simply equalise and outplay you.",
                "ready": "You have won a game with the Qf3–h3 build-up.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Add sharpness and cover the anti-London systems.",
                "learn": [
                    "The Jobava London (2.Nc3 and 3.Bf4) for a much sharper version with e4 ideas.",
                    "The lines where Black plays an early ...Bf5 or ...Bg4, mirroring your own idea.",
                    "Endgames with the c3–d4–e3 structure: they are drawish unless you create an outside passer, so learn to create one.",
                ],
                "drill": "Play the Jobava version for a month and compare your results. Many players find it suits them better.",
                "mistake": "Believing the London is 'safe'. It is sound, which is different — the safety has to come from your play.",
                "ready": "You have two versions of the system and choose between them by opponent.",
            },
        ],
        "study": "Gata Kamsky brought the London back to elite level; Magnus Carlsen and Gukesh Dommaraju both use it as a serious weapon. For attacking models, look at Baadur Jobava's games.",
        "next": "When you want more, learn the Queen's Gambit properly. The London will still be there as a low-preparation option for fast time controls.",
    },
}
