OPENING = {
    "id": "london",
    "name": "London System",
    "eco": "D02 / A46 / A48",
    "section": "white-d4",
    "orientation": "white",
    "tagline": "One setup against almost anything. The lowest-theory way to play 1.d4 well.",
    "level": "Beginner → Grandmaster",
    "theory": {
        "big_idea": "White plays the same first five or six moves regardless of what Black does: d4, Bf4, e3, Nf3, c3, Bd3 (and often Nbd2, h3, O-O). The bishop gets outside the pawn chain before e3 locks it in — this is the single most important move-order point in the whole system. The result is a solid, flexible position with no weaknesses, from which White plays either Ne5 with a kingside attack or a slow queenside expansion.",
        "structure": "White pawns on d4, e3, c3 form a small pyramid — extremely hard to attack. The dark-squared bishop sits outside on f4 or g3 controlling the b8–h2 diagonal, which runs at c7 and d6 and not at Black's king. The king is hit from the other diagonal, by the bishop on d3, and the attacking machine is built around that one square: Ne5 held by d4 and the d2-knight, f2–f4 behind it, Bd3 aimed at h7 and the queen taking whichever of f3, g3 and h4 the bishops have left free.",
        "white_plans": [
            "Plant a knight on e5, hold it with d4 and the d2-knight, add f2–f4, and attack h7 with the d3-bishop and the queen.",
            "Trade the dark-squared bishops on d6 or let Black trade on g3 — and recapture with the h-pawn, so the h-file opens toward the king Black has just castled next to.",
            "Queenside expansion with a4 and Nd2–b3–c5, especially when Black castles kingside and commits to ...c5.",
            "The Jobava version: Nc3 instead of Nbd2, with Nb5 and e3–e4 ideas and a much sharper game.",
        ],
        "black_plans": [
            "Hit d4 immediately with ...c5 and ...Qb6 pressuring b2 — the sharpest test of the system.",
            "Play ...Bd6 to trade off White's good bishop, then ...Qxd6 and ...e5.",
            "Set up a King's Indian structure with ...g6, ...Bg7, ...d6, ...Nbd7 and break with ...e5.",
            "Develop the c8-bishop early with ...Bf5 before ...e6 — the mirror image of White's own idea.",
        ],
        "traps": [
            "e3 before Bf4 shuts the bishop in behind its own pawn chain. It is not a losing move, it is simply not the London any more, and Black takes the good diagonal first with ...Bf5.",
            "...Qb6 has two different answers and they are not interchangeable. Before c3 has been played — 1.d4 d5 2.Bf4 c5 3.e3 Qb6 — the move is 4.Nc3!, offering b2, and 4...Qxb2 5.Nxd5! is close to winning. After c3 — 1.d4 d5 2.Bf4 Nf6 3.e3 e6 4.Nf3 c5 5.c3 Qb6 — Nc3 is not even legal and the pawn may not be offered: 6.Qb3! defends, and 6.Nbd2 Qxb2 7.Rc1 Qxa2 leaves Black better.",
            "2...h5!? is a real trap and not a beginner's move. 3.e3? e5! and the bishop has nowhere to go that keeps it: 4.Bxe5 f6 5.Be2! fxe5 6.Bxh5+ Ke7 7.dxe5 is the best version and it is still bad — three pawns for the bishop, level on the scoresheet and about a pawn worse on the board. Answer 2...h5 with 3.c4 or 3.Nf3 and the whole thing evaporates.",
            "...Nh5 hits the f4-bishop and no move prevents it. The engine's answer is Bg5; Bg3 and Be5 both cost about a quarter of a pawn and are perfectly playable. What you must not do is ignore it — letting the knight take on f4 leaves you with doubled f-pawns and no bishop to show for them.",
        ],
        "who": "Play this if you want to spend your study time on middlegames and endgames instead of opening theory. It is genuinely sound, and the game archives say so: Gata Kamsky has over a thousand games with the Bf4 setup as White, running from 1988 to today, and Magnus Carlsen close to two hundred.",
    },
    "lines": [
        {
            "name": "Main Line vs ...e6 — The Ne5 Attack",
            "note": "The standard London against Black's most common setup, with the classic kingside attacking scheme.",
            "moves": "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 Qf3",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": 'Structure',
                "point": "Nothing has been traded and nothing is weak. Eight pawns each, three a side on each wing, a pawn on d and e each — the material and the wings are dead symmetrical, and that is fine, because the asymmetry is a piece. The knight on e5 is held twice, by the d4-pawn and the d2-knight, and no black pawn will ever be able to drive it away. Your king is still on e1 and that is fine too: there is not a single open file on the board.",
                "next": [
                    "If Black plays 10...Qc7, the answer is 11.Nxc6! and the move order is not optional. Play 11.O-O or 11.Bh4 first and Black gets 11...Nxe5 12.dxe5 Bxe5 — with the queen on c7 holding the bishop, the whole liquidation works and the outpost was for nothing.",
                    "Then Bh4, and understand it as a clearance rather than a retreat: it empties g3, and g3 is the square the queen has to cross to reach h3. Qh3 is the only route she has to the h-file.",
                    "Whenever Black takes on g3, recapture hxg3 — never fxg3. The h-file opens at the king Black has just castled next to, and the pawn landing on g3 covers f4 and h4 for the rest of the game. Carlsen won the model game below on exactly that recapture.",
                ],
                "endgame": "There is no majority anywhere: three against three on both wings, one central pawn each, nothing to promote. So the ending is a draw unless a piece decides it, and the piece to look at is Black's light-squared bishop — on b7 it is behind its own knight on c6 and, behind that, its own pawn on d5. Trade the dark-squared bishops, keep a knight, and steer for a knight against that bishop.",
            },
            "notes": {
                2: "Black mirrors solidly.",
                3: "The defining move, and the reason to play the London in this move order. The bishop gets outside the pawn chain before e3 shuts it in.",
                4: "Natural development.",
                5: "Now the pawn chain is complete: d4, e3 and soon c3. Small, but there is nothing to attack.",
                6: "Black develops and prepares to challenge with ...c5.",
                7: "Supporting d4 and preparing to castle.",
                8: "The main challenge. Black hits the base of the pawn chain.",
                9: "Reinforcing d4, and it does something less obvious as well: it empties c2, so the queen can reach b3 later. That matters, because 5...Qb6 hitting b2 is Black's most annoying idea in this whole structure and 6.Qb3 is the answer to it — see the deviation panel.",
                10: "Adding a second attacker to d4.",
                11: "The knight goes to d2, not c3, because the c-pawn is already standing on c3 holding the centre. From d2 it also covers e5, which is the square the whole system is built around.",
                12: "Black offers a trade of the important dark-squared bishops. The engine's own first choice here is 6...Nh5, hitting the bishop directly — the deviation panel covers it.",
                13: "The bishop steps aside rather than be traded, and from g3 it is still looking down the same diagonal at e5, the square the knight is heading for. Be clear which diagonal that is: b8–h2 runs at d6 and c7, not at Black's king. h7 is a different diagonal and a different bishop's job.",
                14: "King safety.",
                15: "And here is that other bishop. From d3 the b1–h7 diagonal is completely empty as far as h7 — the single square every London attack ends on. The two bishops are not both pointing at the king; the one on g3 is looking at the black bishop on d6.",
                16: "Black prepares to fianchetto and challenge the long diagonal.",
                17: "The signature move of the London System. The knight lands on an outpost held twice, by the d4-pawn and the d2-knight, and no black pawn can ever drive it away: ...f6 would leave e6 and the whole light-square complex hanging. Be honest about the price, though — at depth twenty the engine prefers the immediate 9.e4, and Ne5 gives up about four tenths of a pawn of its edge. What you buy with them is the position every London player recognises.",
                18: "Black develops — and notice how little the bishop does from b7. Its own knight on c6 blocks the diagonal, and behind that stands its own pawn on d5.",
                19: "The attack begins, and it is worth being exact about the queen's route, because the obvious one is not there: Qh3 is illegal while White's own bishop stands on g3. From f3 the queen watches e4, so ...Ne4 is never a free move, and she waits. The moment the dark-squared bishops come off, g3 opens for her and f2–f4 rolls in behind the knight. The deep dive plays exactly that out.",
            },
        },
        {
            "name": "London vs the King's Indian Setup",
            "note": "When Black fianchettoes, the London switches gears: White grabs the centre with c4 and plays a Queen's-Gambit-style game.",
            "moves": "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2 d6 h3 Nbd7 O-O Re8 c4 e5 Bh2 exd4 exd4",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": 'Plans',
                "point": "The system has turned into a Queen's Gambit and the counting says exactly how much that is worth: seven pawns each, three a side on each wing, nobody with a majority anywhere, and the engine calls it dead level. What you have is the pawn on c4 against the pawn on c7 — one extra rank of space in the centre — and an e-file with no pawns left on it at all. That file is the only road either army has.",
                "next": [
                    "Nc3 or Nbd2, then Re1. The queen's knight is the last piece doing nothing, and the rook belongs on the open file before Black's does.",
                    "Hold d4–d5 back. It takes c6 and e6 from Black's knights and hands over c5 and e5 in exchange, so it is a trade of squares and not a gain — make it when Black's knights are already committed, not before.",
                    "Expect 10...Ne4, which is the engine's own choice: it plugs the open file and eyes c3 and d2. Trade it off — 11.Nbd2 and 12.Nxe4 — and after Black recaptures with the rook, 13.Qd2 develops while the rook has to think about where it lives.",
                ],
                "endgame": "Three against three on each wing and one pawn each in the middle, so there is no passed pawn to be made and a rook ending down the e-file is a draw. The whole difference is the pawn on c4: it gives you b5 and d5 as ideas, and it is the pawn Black aims at with ...b5 or ...Nb6. Keep it defended and the small edge lasts all game; lose it and there is nothing left to play for.",
            },
            "notes": {
                2: "Black keeps things flexible and hits e4.",
                3: "Still the same move. The London is a system: the bishop always comes out first.",
                4: "Black heads for a King's Indian structure with a fianchettoed bishop.",
                5: "The pyramid begins.",
                6: "The King's Indian bishop takes the long diagonal — and do not overrate it yet. Its own knight on f6 is standing in the way, so d4 and b2 are not attacked at all. They become attacked the moment that knight moves, which is exactly what ...e5 and ...Nh5 are for.",
                7: "Development.",
                8: "King safety.",
                9: "Modest, and deliberately so. From e2 the bishop supports the f3-knight and covers c4 and d3. Bd3 is the other setup and it belongs against ...d5, not against a fianchetto: on d3 the bishop would be staring at a pawn on g6 that is never going to move.",
                10: "Black prepares the standard King's Indian break ...e5.",
                11: "The most misunderstood move in the system. It takes g4 from ...Bg4 and ...Ng4, which is the reason usually given — and the reason that actually matters here is that it empties h2. Nothing stops ...Nh5; what h3 buys is a square for the bishop when it comes.",
                12: "Preparing ...e5.",
                13: "Castling and connecting the rooks.",
                14: "Supporting the ...e5 push.",
                15: "The gear change. With the kingside safe, White stops playing a system and starts playing a Queen's Gambit: pawns on c4 and d4 against a single pawn on d6, and one extra rank of space in the centre. Nothing here is forced and nothing here is winning — it is a normal, slightly more comfortable game.",
                16: "Black finally breaks.",
                17: "Stepping the bishop out of the way in advance, onto the square h3 cleared for it seven moves ago. It is not sitting on an open diagonal — Black's pawn on e5 stops it two squares along — but nothing on the board can hit it there, and the moment that pawn moves the diagonal runs all the way to b8.",
                18: "Black releases the tension.",
                19: "Recapturing toward the centre. Count what White actually owns: seven pawns each, three a side on each wing, so nobody has a majority anywhere — the whole edge is the pawn on c4 and the space it buys. The e-file is now completely open, which is the one place either side can create something.",
            },
        },
        {
            "name": "London vs the ...c5 Challenge",
            "note": "The most direct test. Black hits d4 at once and White answers by trading and playing on the resulting structure.",
            "moves": "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3 Bg4 Be2 e6 c3 Bd6 Bxd6 Qxd6 O-O Nge7 Nbd2",
            "tier": "Plans",
            "drill": True,
            "plan": {
                "tier": 'Structure',
                "point": "Material is dead level and the pawns are not, which is the whole point of trading on d4 the way White did. Count the wings: three queenside pawns against two, so you own the only majority on the board. Black owns the half-open c-file that comes with it, and you own the half-open e-file — which happens to point at a king still standing on e8. Nobody is attacking anybody yet. This is a position you win in forty moves.",
                "next": [
                    "Re1 first, while the black king is still in the middle. The e-file is the only line either side has and e6 is the one pawn standing on it.",
                    "Then Nb3, heading for c5 or supporting a4–a5. The extra queenside pawn is the long-term asset and the knight is what gets it moving; a4 also takes b5 away before Black's queenside can breathe.",
                    "If Black takes on f3, recapture with the bishop and never with the g-pawn. A broken kingside is exactly the kind of damage that cancels a queenside majority, and the majority is the reason you are better at all.",
                ],
                "endgame": "This is the ending to steer for. Three queenside pawns against two makes a passed pawn, and it is the only passed pawn either side can make on that wing. Black's answer is the extra pawn in the middle — d5 and e6 against your d4 — and the break is ...e5, so a rook on e1 does double duty. Trade queens whenever it is offered; with queens off, the majority is simply a plan and Black has none.",
            },
            "notes": {
                4: "The critical challenge, and Wikibooks calls it the Steinitz Countergambit. Black hits d4 immediately, before White gets in c3.",
                5: "White builds anyway, and the pawn is not really on offer: 3.dxc5 Nc6 4.Nf3 e6 5.e3 Bxc5 hands the centre back and the engine calls the position equal. Steinitz himself demonstrated it against Mason in 1883.",
                6: "Black releases the tension early, and it is a real concession. After the recapture White has three queenside pawns against two, a half-open e-file for the rooks, and no weakness anywhere. What Black gets in exchange is the half-open c-file.",
                7: "Recapturing toward the centre, and the e-file comes half-open with it.",
                8: "Development with pressure on d4.",
                9: "Development.",
                10: "Pinning the knight to increase the pressure on d4 — and it is a real pin only for as long as the queen sits on d1.",
                11: "Breaking the pin and offering a trade if Black wants it. Note the recapture rule for the whole system: if Black takes on f3, take back with the bishop and never with the pawn.",
                12: "Solid.",
                13: "The familiar pyramid, and the third defender of d4 arrives with it.",
                14: "Black offers the bishop trade again.",
                15: "This time White accepts. The point is not the bishop, it is where Black's queen ends up: on d6 she is exposed to Nc4 and to the rook coming to e1, and every tempo White spends improving a piece is a tempo Black spends moving her again.",
                16: "Forced.",
                17: "King safety — and note whose king is still in the middle. Black's is on e8 with a half-open e-file about to be pointed at it.",
                18: "The last knight develops, and e7 rather than f6 is a preference rather than a rule: from e7 it goes to f5, adding a second attacker to d4, or to g6, covering e5 and f4, and it leaves f6 clear. The engine cannot separate the two — the deviation panel shows the ...Nf6 version.",
                19: "The knight has two routes, and neither is the one people expect — Nf1 is impossible with the rook standing on that square. It goes to c4, hitting the queen on d6, or to b3 and then a5. Material is dead level and the pawns are not symmetrical at all: three queenside pawns against two is a long-term asset, and the half-open e-file points at a king that has not moved. A slow game where the better player wins — which is exactly what the London is designed to produce.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the main line to move seventeen",
        "note": "What happens when Black defends correctly. The outpost gets traded, the queen finally reaches h3, the h-file opens — and the position is level. That is the honest London, and it is worth more than a fake attack.",
        "moves": "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 Qf3 Qc7 Nxc6 Bxc6 Bh4 Ne8 Qh3 f5 O-O Nf6 Bg3 Bxg3 hxg3 Rae8 Nf3",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "tier": 'Plans',
            "point": "Seventeen moves and the engine says level, so say so. Eight pawns each, three a side on each wing, a queen, two rooks, a light-squared bishop and a knight each. What you own that Black does not is the h-file — nothing of yours is on it and a queen already stands at the end of it — and the doubled g-pawns that paid for it are not a weakness: g3 covers f4 and h4 and no black piece can ever reach either. What Black owns is a completely solid position, which against this system is the normal result.",
            "next": [
                "Ne5 again, and f2–f4 behind it. The square is free once more and nothing can drive the knight off it — Black's queen on c7 looks at e5 and would be giving up a queen for a knight to take there.",
                "If Black jumps in with 17...Ne4, ask the question: 18.g4! The pawn on f5 is that knight's only support, and g4 makes it choose.",
                "Do not go hunting down the h-file with the queen on her own. She is already on h3 and there is nothing to do there yet; the pieces that make the file matter are the knight coming to e5 and the f-pawn behind it.",
            ],
            "endgame": "Eight pawns each with three a side on the queenside — no majority anywhere, so nothing here promotes on its own and a bare pawn ending is a draw. Two things survive into the ending. The h-file, where you have no pawn and Black does, so keep a rook. And the bishops: Black's on c6 stands behind its own pawn on d5 and can never come out, while yours is only shut out by Black's pawn on f5, which Black may one day have to move. Trade rooks and queens and keep the knight.",
        },
        "notes": {
            20: "The queen backs up the bishop on d6 and steps off the d-file. Note what she does not do: the b8–h2 diagonal is blocked by Black's own bishop, so h2 is not under fire from c7. What the move really achieves is to make ...Nxe5 work, and that changes what White has to play next.",
            21: "And this is the move order, not a trade for its own sake. White must take on c6 first: 11.O-O and 11.Bh4 both allow 11...Nxe5 12.dxe5 Bxe5, and with the queen on c7 backing the bishop that liquidation simply works — the engine has Black more than a pawn better, with nothing left to defend.",
            22: "Forced in spirit. Now look at where the bishop has landed: c6 is the square its own pawn on d5 already blocks. Black has a bishop that will spend the rest of the game behind a pawn.",
            23: "The clearance. It looks like a retreat and it is not — the bishop steps off g3 so that the queen can use it.",
            24: "The knight steps back to defend, unpinning nothing and preparing ...f5.",
            25: "There it is. Qh3 was not legal three moves ago — White's own bishop was standing on g3 when the queen came to f3 — and one bishop move later the third rank is clear. She arrives on the square that looks straight down the h-file at h7.",
            26: "The correct defence, and the only one. ...f5 blocks the b1–h7 diagonal, so the bishop on d3 and the queen on h3 are both looking at a pawn rather than at a king. Count what it costs: Black now has pawns on d5, e6 and f5, and all three of those squares are light — the same colour as the only bishop Black has left. That bishop is going to spend the game behind them.",
            27: "White castles, and it is worth seeing what it costs: the rook on h1 was already sitting behind the queen. Castling gives that up for a king out of the centre and a rook on f1 behind the pawn that is going to advance. With no file open anywhere, king safety was never urgent — the rook's new job is.",
            28: "The knight comes back to a good square now that ...f5 has been played.",
            29: "Back again. The bishop has done its job on h4 and g3 is where it belongs, and White would be perfectly happy to be left alone with it.",
            30: "Black takes, because the alternative is watching that bishop sit there forever.",
            31: "With the h-pawn, always. The h-file opens straight at a castled king, and the pawn that lands on g3 covers f4 and h4 so that no black knight can ever use them. This is the recapture Carlsen made in the model game below, and it is the most important habit in the whole system.",
            32: "Black takes the open file first and is completely fine. Nothing here is going to be decided by force.",
            33: "The last piece comes back into play, and the position is dead level. Read that as the good news it is: nine system moves against a strong defender, no theory memorised, no risk taken, and a middlegame with a file to work on and no weakness of your own.",
        },
    },
    # Deviations, keyed by the position they answer. The London is a system, so
    # most of these are not mistakes — they are Black choosing which structure the
    # game will have. Say what changes; there is usually no punishment to find.
    "branches": {

        # ══ MOVE ORDER — the first three moves ══════════════════════════════════

        # ── ply 1 · what Black actually plays against 1.d4 ──────────────────────
        "d4": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Indian move orders",
             "why": "The most flexible reply and the one you will meet most often. Play 2.Bf4 anyway — the whole point of a system is that it does not care — and after 2...d5 3.e3 you are in the main line by transposition. What does change is that Black can fianchetto instead of playing ...d5, and that is a different middlegame with a line of its own.",
             "line": "Bf4 d5 e3 c5 Nf3 Nc6 Nbd2",
             "see": "london#king-s-indian"},
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "why": "Black prepares ...d5 and locks in the c8-bishop to do it, which is a small gift: that bishop is the piece the London most wants to keep at home. 2.Bf4 and carry on — 2...Nf6 3.e3 c5 4.c3 d5 is the main line with Black's better bishop still behind a pawn.",
             "line": "Bf4 Nf6 e3 c5 c3 d5 Nd2"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "why": "The Modern, and the one first move where the automatic 2.Bf4 is a genuine concession: at depth twenty 2.e4, taking the whole centre while Black has not contested it, is worth about four tenths of a pawn more. Play 2.Bf4 if you want your system, but know that here you chose the quiet road rather than found it.",
             "line": "Bf4 Nf6 c4 Bg7 Nc3 d5 e3"},
            {"san": "f5", "severity": "playable", "tier": "Structure",
             "name": "Dutch Defence",
             "why": "Black takes e4 with a wing pawn. The bishop on f4 is as well placed here as anywhere in the whole opening — it controls e5, and e5 is the square the entire Dutch is an argument about. 2.Bf4 costs you a twentieth of a pawn against it, which is nothing at all.",
             "line": "Bf4 Nf6 Nf3 d6 c4"},
        ],

        # ── ply 3 · your own second move, and the move-order question ───────────
        "d4 d5": [
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "The old move order, and the thing to know about it rather than to fear. 2.Nf3 and 3.Bf4 reach the same positions almost every time; the exception is the one the book that revived the London singles out. After 2...c5 3.Bf4, Black has 3...cxd4 4.Nxd4 Nd7, which Johnsen and Kovacevic call already better for Black — the knight sits in the middle with nothing holding it. 2.Bf4 first sidesteps that, and that is the whole reason the modern move order exists. Carlsen still plays 2.Nf3; the model game below starts with it.",
             "line": "c5 Bf4 cxd4 Nxd4 Nd7",
             "see": "london#carlsen-ghaem"},
            {"san": "c4", "severity": "playable", "tier": "Plans",
             "name": "Queen's Gambit",
             "why": "The main line of chess, and about four centipawns better than 2.Bf4 at depth twenty — which is another way of saying the London is not a compromise on quality, it is a compromise on study time. 2.c4 commits you to the Slav, the Nimzo-Indian, the Grünfeld and the King's Indian. That is the bill you are declining to pay.",
             "see": "queensgambit"},
            {"san": "Nc3", "severity": "playable", "tier": "Mastery",
             "why": "The road to the Jobava London if you follow it with 3.Bf4, and the Veresov if you follow it with 3.Bg5. It commits the queen's knight before you know anything about Black's setup — which is precisely what the ordinary London refuses to do — and it buys Nb5 against c7 and a real e3–e4 break in exchange.",
             "line": "Nf6 Bf4 e6 Nb5 Bb4+ c3"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "why": "The move that turns a good London into a bad one — and the reason is not the evaluation, which is about a tenth of a pawn. It is that the bishop on c1 now has no way out. Black answers 2...Nf6 and 3...Bf5, taking for himself the diagonal you wanted, and you spend the rest of the game with a bishop shut in behind its own pawn chain. Bf4 first, always. This is the one move order mistake the whole system stands on.",
             "line": "Nf6 Nf3 Bf5 c4 e6"},
        ],

        # ── ply 4 · Black's second move against 2.Bf4 ───────────────────────────
        "d4 d5 Bf4": [
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "name": "Steinitz Countergambit",
             "why": "The sharpest reply and the engine's own first choice — Black hits the base of the chain before you have had time to build it. It is not a gambit you can accept: the pawn comes straight back. Play 3.e3 and the game has a line of its own.",
             "line": "e3 Nf6 Nf3 Nc6 Nbd2 e6 c3",
             "see": "london#c5-challenge"},
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "why": "Solid and the most common move at club level. It shuts in the c8-bishop for the moment, which is the standing cost of every ...e6 system. 3.e3 c5 4.Nf3 and you are in the main line a move order later.",
             "line": "e3 c5 Nf3 Nf6 Nbd2 Nc6"},
            {"san": "Bf5", "severity": "playable", "tier": "Structure",
             "why": "Your own idea played back at you, and it is entirely correct. Do not fight for the diagonal — hit the centre instead: 3.c4 is the engine's pick, because with the bishop off c8 the pawn on b7 has nothing at home to guard it. 3...Nf6 4.Nc3 e6 5.Qb3 and the queen hits b7 and d5 at the same moment. Note that Qb3 only becomes possible once the c-pawn has moved off c2 — that is true in every London position where this queen sortie matters.",
             "line": "c4 Nf6 Nc3 e6 Qb3 Nc6"},
            {"san": "Nc6", "severity": "playable", "tier": "Structure",
             "why": "Blocking your own c-pawn on move two, which in a 1.d4 opening is a real cost: ...c5 is off the table and the queenside stays quiet for a long time. 3.e3 Nf6 4.Nf3 and if Black pins with 4...Bg4, then 5.h3 Bxf3 6.Qxf3 hands you the two bishops and an open game.",
             "line": "e3 Nf6 Nf3 Bg4 h3 Bxf3 Qxf3"},
            {"san": "h5", "severity": "inaccuracy", "tier": "Mastery",
             "why": "It looks like a beginner grabbing space on the wing and it is a prepared trap. The automatic 3.e3? loses the bishop for pawns: 3...e5! and there is no square that saves it — 4.Bxe5 f6 5.Be2 fxe5 6.Bxh5+ Ke7 7.dxe5 is the best version White has and it is still three pawns for a piece and the worse position. Play 3.c4 or 3.Nf3 and the h-pawn is simply a weakness Black has committed to for nothing.",
             "line": "c4 e6 Nf3 Bb4+ Nc3"},
        ],

        # ── ply 2 · your own second move against 1...Nf6 ────────────────────────
        "d4 Nf6": [
            {"san": "Nc3", "severity": "playable", "tier": "Mastery",
             "name": "Jobava London",
             "why": "The Rapport–Jobava system: the same bishop on f4, but the queen's knight on c3 instead of d2. It is a genuinely different opening — Nb5 hits c7 and d6, e3–e4 becomes a real break, and White often castles long. Wikipedia's sample line is 1.d4 Nf6 2.Bf4 d5 3.e3 c5 4.Nc3 cxd4 5.exd4 Nc6 6.Qd2 Bf5 7.O-O-O. The price is the one thing the ordinary London never pays: the c-pawn can no longer come to c3 and hold d4.",
             "line": "d5 Bf4 e6 Nb5 Na6 e3"},
            {"san": "c4", "severity": "playable", "tier": "Plans",
             "why": "The main line of chess, and four centipawns better than 2.Bf4 at depth twenty. The gap is not the point; the syllabus is. 2.c4 means learning four defences properly, and the London exists so that you do not have to.",
             "line": "e6 Nf3 d5 g3 dxc4 Bg2",
             "see": "queensgambit"},
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "The other London move order, and here it matters more than it does when Black has already committed to ...d5. 2.Nf3 invites 2...c5, and against that the automatic 3.Bf4 is half a pawn worse at depth twenty: 3...cxd4 4.Nxd4 leaves the knight in the middle with nothing behind it. Meet 2...c5 with 3.d5 — the engine's own choice — or with 3.e3.",
             "line": "d5 Bf4 e6 e3 c5 c3"},
        ],

        # ── ply 3 · Black's second move against the Indian move order ───────────
        "d4 Nf6 Bf4": [
            {"san": "d5", "severity": "playable", "tier": "Foundation",
             "why": "Straight back into the main line: 3.e3 c5 4.Nf3 Nc6 5.Nbd2 is the same position the ...e6 line reaches. Nothing about your plan changes.",
             "line": "e3 c5 Nf3 Nc6 Nbd2 cxd4",
             "see": "london#ne5-attack"},
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "why": "The critical move order, and the one the theory books single out: Black hits d4 before committing to ...d5, which is exactly what makes the coming ...Qb6 sound rather than greedy. The engine's own answer is 3.d5!, turning it into a Benoni where your bishop is already outside the chain; 3.e3 is the system move and perfectly good. What you must not play is 3.Nf3 — 3...cxd4 4.Nxd4 and at depth twenty Black is half a pawn better.",
             "line": "d5 b5 Nf3 g6 e4"},
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "why": "Black keeps every option open and will decide between ...d5 and ...c5 next move. 3.e3 and let him choose — the setup is the same either way, and this is what a system is for.",
             "line": "e3 c5 Nf3 d5 Nbd2 Qb6"},
            {"san": "Ne4", "severity": "playable", "tier": "Mastery",
             "why": "Straight to the middle on move two, and the answer is a pawn move nobody expects in this opening: 3.f3! The knight has to go home and White gets a broad centre with e3–e4 to follow. It is worth about four tenths of a pawn — not a refutation, simply a bad bargain for Black.",
             "line": "f3 Nf6 e4 d5 Nc3"},
        ],

        # ══ MAIN LINE ═══════════════════════════════════════════════════════════

        # ── ply 6 · Black's third move ──────────────────────────────────────────
        "d4 d5 Bf4 Nf6 e3": [
            {"san": "c5", "severity": "playable", "tier": "Foundation",
             "why": "The same challenge as the main line, one move earlier, and it transposes as soon as either side plays another natural move. 4.Nf3 Nc6 5.Nbd2 and you are home.",
             "line": "Nf3 Nc6 Nbd2 e6 Bb5"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "why": "The fianchetto with ...d5 already committed, which is a Grünfeld-flavoured version rather than a King's Indian one — Black cannot play for ...e5 with the pawn on d5. 4.Nf3 Bg7 5.c3 and you get the ordinary setup against a bishop that has nothing to bite on.",
             "line": "Nf3 Bg7 c3 O-O Be2"},
            {"san": "Nc6", "severity": "playable", "tier": "Structure",
             "why": "It takes ...c5 away from Black for good. 4.Nf3 and the natural 4...Nh5 comes: 5.Bg3 Nxg3 6.hxg3 and this is the recapture to learn by heart — with the h-file open and a pawn on g3 covering f4 and h4, White gets more from the trade than Black does.",
             "line": "Nf3 Nh5 Bg3 Nxg3 hxg3"},
        ],

        # ── ply 9 · after 5.c3 — the first ...Qb6 crossroads ────────────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3": [
            {"san": "Qb6", "severity": "playable", "tier": "Structure",
             "name": "...Qb6 — the b2 raid",
             "why": "The move the whole system has to answer, and this is the version where the answer is to defend. 6.Qb3! — legal only because c3 has just emptied c2 — and the queens face each other down the b-file. 6...Qxb3 7.axb3 is a trade White should want: the a-file opens toward a7 and the pawn landing on b3 covers c4 for good. What you must not do here is offer the pawn the way you would one move earlier: 6.Nbd2 Qxb2 7.Rc1 Qxa2 and Black is simply better. And 6...Bd6 in reply to Qb3 drops a piece to 7.Qxb6 axb6 8.Bxd6, because the queen leaving d8 left that bishop with nothing guarding it.",
             "line": "Qb3 Bd7 Nbd2 Nc6 h3"},
            {"san": "Bd6", "severity": "playable", "tier": "Foundation",
             "why": "Offering the bishop trade before developing the knight, which gives you a free check: 6.Bb5+! Nc6 7.Bxc6+ bxc6 8.Qa4 and Black's queenside pawns are damaged for the rest of the game.",
             "line": "Bb5+ Nc6 Bxc6+ bxc6 Qa4 O-O"},
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "The modest square, and it keeps the dark-squared bishops apart — which suits you, since yours is the better one. 6.Nbd2 and expect 6...Nh5 hitting the bishop; 7.Be5 is a good answer here because with no black bishop on d6 the square is free.",
             "line": "Nbd2 Nh5 Be5 Nc6 h3"},
            {"san": "Nbd7", "severity": "playable", "tier": "Structure",
             "why": "Solid and slow. The knight on d7 does not fight for d4, so you get a free hand: 6.Nbd2 Be7 7.h4 is even playable, and any normal move keeps a small pull.",
             "line": "Nbd2 Be7 h4 O-O Bd3"},
            {"san": "cxd4", "severity": "playable", "tier": "Structure",
             "why": "Releasing the tension early. 6.cxd4! is the recapture — toward the centre, keeping the pawn on e3 and the b1-knight's route through d2 — and the c-file comes half-open for Black in exchange. Perfectly balanced and much less rich than leaving the tension.",
             "line": "cxd4 Bd6 Bxd6 Qxd6 Nc3"},
        ],

        # ── ply 11 · after 6.Nbd2 — the ...Nh5 question ─────────────────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2": [
            {"san": "Nh5", "severity": "playable", "tier": "Plans",
             "why": "The engine's own first choice, and not a mistake in any sense: Black asks the question this system always has to answer. 7.Bg5! is the best reply — from g5 the bishop covers f6 and h4 and the knight on h5 cannot touch it. 7.Bg3 Nxg3 8.hxg3 is completely playable and hands you the h-file; the engine rates it a quarter of a pawn worse, which is nothing. What loses the argument is 7.Be2, allowing 7...Nxf4 8.exf4 for free — doubled f-pawns and no bishop to show for them.",
             "line": "Bg5 f6 Bh4 cxd4 cxd4"},
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "Declining to trade the dark-squared bishops, which quietly favours you: yours is outside the pawn chain and Black's is not. 7.h3 O-O 8.Bd3 and the setup completes itself.",
             "line": "h3 O-O Bd3 Bd6 dxc5"},
            {"san": "Qb6", "severity": "playable", "tier": "Structure",
             "why": "The raid one move later, and now the modest answer is best: 7.Rb1, which defends b2 with the piece that was going to sit there anyway and keeps b2–b4 and a4 in hand. Qb3 is available here too and it is fine — the point of Rb1 is that it solves b2 without spending the queen on it.",
             "line": "Rb1 cxd4 exd4 Nh5 Be3"},
            {"san": "cxd4", "severity": "playable", "tier": "Foundation",
             "why": "7.exd4! this time, not cxd4 — with the knight already committed to d2 the c3-pawn is worth more where it is, and recapturing with the e-pawn opens the e-file toward a king that has not castled.",
             "line": "exd4 Nh5 Be3 Bd6 Ne5"},
        ],

        # ── ply 12 · your own seventh move: where the bishop goes ───────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6": [
            {"san": "Bxd6", "severity": "playable", "tier": "Structure",
             "why": "Taking is not wrong and it is not what you want. After 7.Bxd6 Qxd6 Black's structure is untouched, the queen has a good square, and the piece you gave up was the one doing the most work. About a third of a pawn at depth twenty — take it if you want a quiet game, decline it if you want a game.",
             "line": "Qxd6 Bd3 O-O O-O e5"},
            {"san": "Ne5", "severity": "playable", "tier": "Plans",
             "why": "The outpost, three moves early, and it blocks your own bishop: with a knight on e5 the bishop on f4 stops looking at d6 altogether. Black gets 7...Qc7 and 8...c4, takes queenside space, and your knight sits on a square nobody is attacking. Ne5 wants the dark-squared bishops resolved first.",
             "line": "Qc7 Ndf3 c4 Be2 Ne4"},
            {"san": "Bd3", "severity": "inaccuracy", "tier": "Structure",
             "why": "The system move played one move out of order, and it hands the bishop over: 7...Bxf4! 8.exf4 and the structure is ruined — doubled f-pawns, no pawn left that can ever cover e4, and the piece you were supposed to keep is gone. 8...Qb6 9.Qb3 and you are the one defending. Bg3 first, always: the dark-squared bishop steps aside before the other one commits.",
             "line": "Bxf4 exf4 Qb6 Qb3 Qc7"},
            {"san": "Be2", "severity": "inaccuracy", "tier": "Structure",
             "why": "The same mistake as 7.Bd3 with less to show for it — 7...Bxf4 8.exf4 and the bishop on e2 is not even standing on the diagonal that pointed at h7. The rule is worth stating flatly: in this structure the dark-squared bishop moves before the light-squared one does.",
             "line": "Bxf4 exf4 cxd4 Nxd4 Nxd4 cxd4"},
        ],

        # ── ply 13 · after 7.Bg3 — the raid that costs a piece ──────────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3": [
            {"san": "Qb6", "severity": "blunder", "tier": "Structure",
             "why": "The b2 raid at the one moment it loses material, and the mechanism is worth learning: the queen on d8 was the only thing defending the bishop on d6, and ...Qb6 walks away from the job. 8.Bxd6! and now count the whole sequence — 8...Nxd4 9.exd4 Qxd6 10.dxc5 and White has won a bishop, a knight and a pawn for a bishop and a pawn. A clean piece.",
             "line": "Bxd6 Nxd4 exd4 Qxd6 dxc5"},
            {"san": "Bxg3", "severity": "playable", "tier": "Foundation",
             "why": "Black takes rather than be pushed around, and the recapture is the whole lesson: 8.hxg3! and never fxg3. The h-file opens toward the square Black is about to castle next to, and the pawn landing on g3 covers f4 and h4 for the rest of the game.",
             "line": "hxg3 Qb6 Qc2 h6 Nb3"},
            {"san": "cxd4", "severity": "playable", "tier": "Structure",
             "why": "8.exd4 and the position simplifies into a small, durable pull: a half-open e-file, a pawn on c3 that can never be attacked, and a black bishop on d6 that has to keep watching e5.",
             "line": "exd4 O-O Bd3 Nh5 Bxd6"},
            {"san": "Ne4", "severity": "playable", "tier": "Plans",
             "why": "Black plants a knight in the middle. 8.Nxe4! dxe4 and Black's structure changes character completely: doubled e-pawns, no d-pawn at all, and an e4-pawn that only ...f5 can ever support. The engine still calls it fine for Black — this is a structural argument, not a refutation.",
             "line": "Nxe4 dxe4 Nd2 cxd4 exd4"},
        ],

        # ── ply 16 · after 8.Bd3 — and the counting lesson on e5 ────────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3": [
            {"san": "Qc7", "severity": "playable", "tier": "Structure",
             "why": "Backing the bishop up and eyeing the b8–h2 diagonal, which is blocked by Black's own bishop and therefore does nothing yet. 9.dxc5! is the useful reply — it hits the bishop on d6 with a pawn, so when Black wins the pawn back it will be with a piece and a tempo behind.",
             "line": "dxc5 Bxg3 hxg3 Rd8 Qc2"},
            {"san": "Re8", "severity": "playable", "tier": "Foundation",
             "why": "A move that is never wrong and never urgent. 9.Ne5 and carry straight on with the plan — the rook on e8 does not defend e5 and nothing about your setup changes.",
             "line": "Ne5 Qc7 f4 Rf8 O-O"},
            {"san": "Bxg3", "severity": "playable", "tier": "Foundation",
             "why": "The trade again, and the same answer: 9.hxg3. Black usually follows with 9...g6 to stop the bishop and queen ever reaching h7, and that is a permanent hook for your h-file rook to work against.",
             "line": "hxg3 g6 Ne5 h5 Ndf3"},
            {"san": "e5", "severity": "blunder", "tier": "Foundation",
             "why": "The freeing break, and it drops a piece to pure counting. Look at e5: White attacks it three times — the d4-pawn, the f3-knight and the g3-bishop — and Black defends it twice, with the c6-knight and the d6-bishop. One attacker too many, and Black has to capture first. 9.dxe5 Nxe5 10.Nxe5 Bxe5 11.Bxe5 and nothing recaptures.",
             "line": "dxe5 Nxe5 Nxe5 Bxe5 Bxe5"},
        ],

        # ── ply 18 · after 9.Ne5 — the pawn recapture that forks ────────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5": [
            {"san": "Nxe5", "severity": "blunder", "tier": "Foundation",
             "why": "The natural trade, and it loses a piece to a pawn fork. 10.dxe5! — not Bxe5 — and the pawn attacks the bishop on d6 and the knight on f6 at the same moment. Nothing saves both: 10...Be7 11.exf6 Bxf6 and White is a knight up for a pawn. This is the tactic the whole Ne5 idea is built on, and it is why the d-pawn recapture is the one you want.",
             "line": "dxe5 Be7 exf6 Bxf6 Nf3"},
            {"san": "Ba6", "severity": "blunder", "tier": "Structure",
             "why": "It looks like the standard trade of the bad bishop and it loses a piece to a two-move fork. 10.Nxc6! and the knight lands attacking the queen on d8, so Black never gets time to take on d3: 10...Qc7 11.Bxa6 Qxc6 and White has won a bishop and a knight for a knight. 10.Bxa6 first comes to the same thing — the fork on c6 is what does the work either way. The lesson is about tempo: any knight that reaches c6 hits the queen on d8, so a move Black spends on a trade is a move White spends on a fork.",
             "line": "Nxc6 Qc7 Bxa6 Qxc6 Bd3"},
            {"san": "Bxe5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The right trade at a real cost. 10.dxe5 and the knight on f6 has to move; you have swapped the outpost for a pawn wedge on e5 and a half-open d-file. Be exact about the bishop, though: your own pawn now stands on e5, in the middle of the g3-bishop's diagonal, so what that bishop does is hold the wedge rather than sweep the board. It is worth about half a pawn to Black — a deal to make on purpose rather than by accident.",
             "line": "dxe5 Nd7 Nf3 h6 O-O"},
        ],

        # ── ply 20 · after 10.Qf3 — the same fork, one move later ───────────────
        "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 Qf3": [
            {"san": "Nxe5", "severity": "blunder", "tier": "Foundation",
             "why": "Exactly the same mistake one move later and exactly as expensive. 11.dxe5! forks the bishop on d6 and the knight on f6, and Black cannot save both: 11...Be7 12.exf6 Bxf6 and White is a knight up for a pawn. Recapture with the pawn every single time.",
             "line": "dxe5 Be7 exf6 Bxf6 Qe2"},
            {"san": "Rc8", "severity": "playable", "tier": "Structure",
             "why": "Black brings the rook to the file the c-pawn will open and is completely fine. 11.Nxc6 Bxc6 12.Bh4 is the plan: the bishop steps off g3 so that the queen can use it, and Qh3 is the only route she has to the h-file.",
             "line": "Nxc6 Bxc6 Bh4 Be7 O-O"},
            {"san": "cxd4", "severity": "playable", "tier": "Plans",
             "why": "Releasing the tension. 11.Nxc6! first — take on c6 before recapturing, so that Black's bishop is dragged to a square its own pawn on d5 already blocks — and only then 12.exd4.",
             "line": "Nxc6 Bxc6 exd4 Qc7 Bxd6"},
        ],

        # ══ AGAINST THE KING'S INDIAN SETUP ═════════════════════════════════════

        # ── ply 5 · Black's third move after 2...g6 ─────────────────────────────
        "d4 Nf6 Bf4 g6 e3": [
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "why": "Black hits d4 before the bishop even comes out, and the engine likes it as much as anything. 4.Nf3 d6 5.Nc3 is one good setup and 5.c3 is the other; the difference is whether you want e3–e4 or a pawn on c3 holding d4, and you cannot have both.",
             "line": "Nf3 d6 Nc3 Nbd7 h3"},
            {"san": "d5", "severity": "playable", "tier": "Foundation",
             "why": "A Grünfeld-flavoured version: Black takes the centre with a pawn and fianchettoes behind it, which means ...e5 is off the table for good. 4.Nf3 Bg7 5.Be2 and play the ordinary setup against a bishop with nothing to bite on.",
             "line": "Nf3 Bg7 Be2 O-O O-O"},
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "why": "The pure King's Indian move order, and it transposes to the main line of this variation after 4.Nf3 Bg7. Nothing changes — which is the point of playing a system in the first place.",
             "line": "Nf3 Bg7 h3 c5 Be2"},
        ],

        # ── ply 9 · your own fifth move: which bishop setup ─────────────────────
        "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O": [
            {"san": "c4", "severity": "playable", "tier": "Plans",
             "why": "The gear change played at once instead of five moves later. It is sound and it is committal: once the c-pawn is on c4 the only pawn left holding d4 is the one on e3, so 5...c5 6.Nc3 cxd4 7.Nxd4 puts a knight on a square Black can hit. Be2 first and c4 afterwards is the safer order and the one the main line uses.",
             "line": "c5 Nc3 cxd4 Nxd4 d6"},
            {"san": "Bd3", "severity": "playable", "tier": "Structure",
             "why": "The other bishop square, and against a fianchetto it is the worse one — the b1–h7 diagonal runs into a pawn on g6 that is never going to move. From e2 the bishop supports the knight on f3 and stays out of the way of c2–c4. About a fifth of a pawn, and a whole plan.",
             "line": "c5 O-O Nc6 c3 d6"},
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "why": "The pyramid, and against the fianchetto it is the modest choice: it holds d4 forever and gives up on c4 and the extra space. Entirely playable — this is the version to pick if you want one setup and no decisions.",
             "line": "Nh5 Bg5 d6 Nbd2 a5"},
        ],

        # ── ply 10 · after 5.Be2 ────────────────────────────────────────────────
        "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2": [
            {"san": "d5", "severity": "playable", "tier": "Structure",
             "why": "Committing the centre. Black's bishop on g7 now has its own pawn on d5 in front of it as well as the knight on f6, and it will take several moves to matter. 6.O-O c5 7.c3 and you have a small, safe pull.",
             "line": "O-O c5 c3 Nc6 h3"},
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "why": "The immediate challenge, and ...Qb6 usually follows it. 6.O-O d6 7.h3 Qb6 8.Qc1 is the quiet answer in this structure: the queen steps aside, and from c1 she is herself the piece guarding b2 — which is how this works with no pawn on c3.",
             "line": "O-O d6 h3 Qb6 Qc1 Nc6"},
            {"san": "Nh5", "severity": "playable", "tier": "Foundation",
             "why": "The standard question, and the answer here is not the main line's. 6.Be5! The bishop does not retreat, it takes the square in front of Black's own centre, and after 6...Nf6 7.h3 the knight has spent two moves to achieve nothing at all.",
             "line": "Be5 Nf6 h3 c5 Nbd2"},
        ],

        # ── ply 13 · after 7.O-O — the break that comes too early ───────────────
        "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2 d6 h3 Nbd7 O-O": [
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "why": "The other break, one move before the main line's. 8.c4! and you reach the c4-and-d4 duo you were heading for anyway; Black gets the half-open c-file for it, which is a fair exchange and leaves the game balanced.",
             "line": "c4 cxd4 exd4 e5 Be3"},
            {"san": "e5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The break one move too early, and it costs half a pawn: 8.dxe5! Ne4 9.Qd5 and White comes out on top of every line. The reason the main line plays 7...Re8 first is precisely this — the rook backs the pawn up so that the same break works two moves later.",
             "line": "dxe5 Ne4 Qd5 dxe5 Nxe5"},
            {"san": "b6", "severity": "playable", "tier": "Foundation",
             "why": "The engine's own choice: Black finishes developing before committing a pawn. 8.Bh2 is the useful reply — it steps the bishop onto the square h3 cleared for it, in advance, so that ...Nh5 and ...e5 never come with tempo.",
             "line": "Bh2 Bb7 a4 a6 Nbd2"},
        ],

        # ── ply 15 · after 8.c4 ─────────────────────────────────────────────────
        "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2 d6 h3 Nbd7 O-O Re8 c4": [
            {"san": "c5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The wrong break in this structure: with pawns already on c4 and d4, 9.Nc3 and 10.d5 simply lock the position with Black's bishop on g7 staring at a wall of its own making. It costs about half a pawn and, worse, it costs the plan.",
             "line": "Nc3 b6 d5 Nh5 Bh2"},
            {"san": "c6", "severity": "playable", "tier": "Foundation",
             "why": "Preparing ...e5 with more support. 9.Nc3 e5 10.dxe5 dxe5 and the tension resolves on your terms: neither side has a d-pawn any more, the file is open, and Rad1 is your next move while Black's rook is already committed to e8.",
             "line": "Nc3 e5 dxe5 dxe5 Nxe5"},
            {"san": "e6", "severity": "playable", "tier": "Plans",
             "why": "A quieter structure, and a concession: the bishop on g7 now has pawns on e6 and d6 in front of it as well as its own knight. 9.Nc3 and 10.Qc2 and take the space Black has declined.",
             "line": "Nc3 b6 Qc2 Bb7 Rad1"},
        ],

        # ── ply 17 · after 9.Bh2 ────────────────────────────────────────────────
        "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 O-O Be2 d6 h3 Nbd7 O-O Re8 c4 e5 Bh2": [
            {"san": "e4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Gaining space and giving up the tension, and it costs over a pawn. On e4 the pawn is a target rather than a spearhead: 10.Nfd2! attacks it, d4 becomes untouchable, and Black has to spend a move on ...d5 or ...f5 just to hold a pawn that is not doing anything.",
             "line": "Nfd2 Nf8 Nc3 a5 Bg3"},
            {"san": "c6", "severity": "playable", "tier": "Foundation",
             "why": "Keeping the tension and adding a defender to d5. 10.Nc3 exd4 11.exd4 d5 and the position resolves into a normal Queen's Gambit structure where your extra space is worth a small, permanent pull.",
             "line": "Nc3 exd4 exd4 d5 Qb3"},
            {"san": "Qe7", "severity": "inaccuracy", "tier": "Structure",
             "why": "A slow move in a position that needed a decision, and the queen lands on the square her own rook already covers. 10.Nc3 exd4 11.exd4 and Black has released the centre anyway, one tempo down — half a pawn for nothing.",
             "line": "Nc3 exd4 exd4 b6 Re1"},
        ],

        # ══ AGAINST THE ...c5 CHALLENGE ═════════════════════════════════════════

        # ── ply 5 · your own third move against 2...c5 ──────────────────────────
        "d4 d5 Bf4 c5": [
            {"san": "dxc5", "severity": "playable", "tier": "Structure",
             "why": "Accepting, and it is not a pawn you get to keep. 3...Nc6 4.Nf3 e6 5.e3 Bxc5 and Black has it back with a free game — the cost of grabbing was the centre. Steinitz demonstrated this against Mason in 1883 and nothing has changed since.",
             "line": "Nc6 Nf3 e6 e3 Bxc5"},
            {"san": "e4", "severity": "playable", "tier": "Mastery",
             "name": "Morris Countergambit",
             "why": "The gambit answer, named on Wikibooks: White gives the e-pawn to push d4–d5 and cramp Black, which is an Albin Countergambit with the colours reversed. It is a real try, and it is also a third of a pawn worse than 3.e3 at depth twenty, with Black slightly better after 3...dxe4 4.d5. Play it knowing that rather than hoping otherwise.",
             "line": "dxe4 d5 Nf6 Nc3 a6"},
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "why": "Propping up d4 before e3, and perfectly sound. The one difference is that c3 invites 3...Qb6 at once, and the answer then has to be 4.Qb3 rather than the knight offer — 4...Qxb3 5.axb3 opens the a-file toward a7 and leaves a pawn on b3 covering c4 for good.",
             "line": "Qb6 Qb3 Qxb3 axb3 cxd4"},
        ],

        # ── ply 6 · after 3.e3 — ...Qb6 where it is a mistake ───────────────────
        "d4 d5 Bf4 c5 e3": [
            {"san": "Qb6", "severity": "inaccuracy", "tier": "Plans",
             "name": "...Qb6 — the b2 raid",
             "why": "The critical move of the whole system, played in the one version where it costs something — and the reason is the pawn already sitting on d5. 4.Nc3! offers b2 and means it: 4...Qxb2 5.Nxd5! and the knight arrives hitting c7 while the queen is stranded on b2. Depth twenty calls that more than five pawns for White. Black has to decline with 4...e6 5.Nb5 Na6 6.a4, half a pawn worse and passive. Play the same queen sortie one move earlier, before ...d5 commits, and 4...Qxb2 is genuinely playable — that is the whole difference.",
             "line": "Nc3 e6 Nb5 Na6 a4"},
            {"san": "Nc6", "severity": "playable", "tier": "Foundation",
             "why": "The engine's first choice: develop and keep the tension. 4.Nf3 Nf6 5.Nbd2 e6 6.Bb5 and White has a normal small pull with everything still flexible.",
             "line": "Nf3 Nf6 Nbd2 e6 Bb5"},
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "why": "The same position by a different door — 4.Nf3 Nc6 5.Nbd2 and every move order in this corner of the London runs together.",
             "line": "Nf3 Nc6 Nbd2 e6 Bb5"},
            {"san": "a6", "severity": "playable", "tier": "Structure",
             "why": "A useful little move that takes b5 from your bishop and prepares ...Qb6 with ...Nc6 to follow. 4.c3 and answer the queen sortie with Qb3 when it comes.",
             "line": "c3 Nc6 Nf3 cxd4 cxd4"},
        ],

        # ── ply 9 · after 5.Nf3 — the raid that drops the centre ────────────────
        "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "why": "Developing instead of pinning. 6.c3 Bf5 7.Qb3 and the queen hits b7 and d5 at once — with the bishop off c8 there is nothing at home to cover b7, and that is the standing motif in every ...Bf5 line.",
             "line": "c3 Bf5 Qb3 Qc8 Nbd2"},
            {"san": "Bf5", "severity": "playable", "tier": "Structure",
             "why": "The other bishop move, and here 6.c4! is the engine's answer rather than the routine c3: with Black's bishop outside the pawn chain, hitting d5 straight away is worth more than propping up d4.",
             "line": "c4 e6 Nc3 Nge7 Rc1"},
            {"san": "Qb6", "severity": "inaccuracy", "tier": "Plans",
             "why": "The raid a third time, and this version simply drops the centre. Black's queen has left d8 — and d8 was the only thing defending d5. 6.c4! and the pawn cannot be held: 6...e5 7.cxd5 exf4 8.dxc6 and White comes out ahead on every capture. If you take one rule from the three ...Qb6 positions on this page, take this one: before you work out how to defend b2, look at what the queen has stopped defending.",
             "line": "c4 e5 cxd5 exf4 dxc6"},
        ],

        # ── ply 11 · after 6.Be2 ────────────────────────────────────────────────
        "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3 Bg4 Be2": [
            {"san": "Bxf3", "severity": "playable", "tier": "Foundation",
             "why": "Black gives up the bishop pair to damage nothing. 7.Bxf3! and never gxf3 — you keep two bishops against one and a completely healthy structure, and Black has spent two moves to trade a developed piece for a developed piece.",
             "line": "Bxf3 e6 c3 Bd6 Bxd6"},
            {"san": "Qb6", "severity": "playable", "tier": "Structure",
             "why": "Hitting b2 and d4 at once, and with the bishop already committed to g4 it is less annoying than usual. 7.Nbd2 and 9.Qb3 in due course — the queen trade suits you here, because it is Black's queenside pawns that end up doubled.",
             "line": "Nbd2 Nf6 c3 e6 Qb3"},
            {"san": "e5", "severity": "inaccuracy", "tier": "Plans",
             "why": "Striking in the centre with the c-pawn already traded off, and the pawn is not defended enough to survive. Count e5: White attacks it with the bishop on f4, the knight on f3 and the pawn on d4; Black defends it once, with the knight on c6, because the bishop on g4 is on the wrong diagonal to help. 7.Bxe5! and White is a clean pawn up.",
             "line": "Bxe5 Nf6 c3 Be7 Nbd2"},
        ],

        # ── ply 13 · after 7.c3 ─────────────────────────────────────────────────
        "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3 Bg4 Be2 e6 c3": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "why": "Developing first and deciding about the bishop later — the engine cannot separate it from the main line's 7...Bd6. 8.Nbd2 and the setups converge.",
             "line": "Nbd2 Bd6 Bxd6 Qxd6 O-O"},
            {"san": "Bxf3", "severity": "playable", "tier": "Structure",
             "why": "8.Bxf3, always with the bishop. You end up with the two bishops, a pawn structure with no holes in it and a queenside majority — and Black has given up a good piece to remove a knight that was not doing very much.",
             "line": "Bxf3 Nf6 O-O Bd6 Bxd6"},
            {"san": "Qb6", "severity": "playable", "tier": "Plans",
             "why": "The raid once more, and with c3 already played the answer is the familiar one: 9.Qb3 after a developing move, offering the trade. 8.Nbd2 Nf6 9.Qb3 h6 10.Qxb6 axb6 and look at what the trade did to Black's queenside — two pawns on one file, both on b, against your three on three files.",
             "line": "Nbd2 Nf6 Qb3 h6 Qxb6"},
        ],

        # ── ply 17 · after 9.O-O ────────────────────────────────────────────────
        "d4 d5 Bf4 c5 e3 cxd4 exd4 Nc6 Nf3 Bg4 Be2 e6 c3 Bd6 Bxd6 Qxd6 O-O": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "why": "The other knight square, and the engine calls it identical to 9...Nge7. From f6 the knight hits d5 and e4 and does not head for f5; from e7 it does. Pick by what you want it doing in ten moves.",
             "line": "Nbd2 O-O a4 Qc7 Re1"},
            {"san": "Bxf3", "severity": "playable", "tier": "Structure",
             "why": "10.Bxf3 and you have the two bishops against bishop and knight in an open position with a queenside majority. That is the good version of this structure and Black has just handed it over.",
             "line": "Bxf3 Nf6 Nd2 O-O Be2"},
            {"san": "O-O-O", "severity": "inaccuracy", "tier": "Mastery",
             "why": "Castling into the pawns. It is not losing and it is the wrong side of the board: your three queenside pawns against Black's two stop being an endgame asset and become an attack, and a4–a5 costs you nothing at all. 10.Nbd2 Kb8 11.a4 and you have a plan while Black has to invent one.",
             "line": "Nbd2 Kb8 a4 Nf6 Re1"},
        ],
    },
    "games": [
        {
            "id": 'carlsen-ghaem-maghami-2016',
            "name": "Carlsen – Ghaem Maghami, Baku Olympiad 2016 — the h-file recapture",
            "tier": 'Structure',
            "note": "Round ten of the 2016 Olympiad, and the whole game turns on one recapture on move eight. Black offers the bishop trade the London always invites; Carlsen takes back with the h-pawn instead of the f-pawn, and the file that opens is the only one either player gets for the next twenty moves.",
            "moves": (
                'd4 d5 Nf3 Nf6 Bf4 e6 e3 Bd6 Bg3 c5 c3 Nc6 Nbd2 Bxg3 hxg3 Qd6 '
                'Bb5 Bd7 Bxc6 Bxc6 Ne5 Qc7 Qf3 h6 Qf4 Qe7 g4 Nh7 Qg3 Rg8 O-O Nf6 '
                'Rac1 Rc8 c4 dxc4 dxc5 Qxc5 Ndxc4 Ke7 b4 Qxb4 Nd3 Ne4 Nxb4 Nxg3 '
                'fxg3 Bb5 Rxf7+ Kxf7 Nd6+ Ke7 Nxc8+ Kd7 Nxa7 Ba4 Nd3'
            ),
            "notes": {
                3: "The older move order, knight before bishop. Against 1...d5 it costs nothing — Carlsen has used both for twenty years — and the game is in the main line's structure by move six anyway.",
                9: "The bishop steps aside rather than be traded, exactly as in the main line. Black asks the question again one move later.",
                14: "And this time it is not a question, it is a trade. Black gives up the good bishop to spoil White's pawns, which is the standard bargain in this whole system.",
                15: "The move the plan card is about, and the reason the London works. Not fxg3 — hxg3. The h-file opens toward the corner Black is about to castle into, the pawn that lands on g3 covers f4 and h4 so that no black knight can ever use them, and White's own king is perfectly safe because there is nothing else open anywhere.",
                17: "Before the knight can be challenged on e5, Carlsen goes after the piece that challenges it. Everything in this game is about one square.",
                19: "Giving up a bishop for a knight, deliberately. Nobody has the bishop pair here — the dark-squared ones came off on move eight — so what is being traded is a bishop for the last piece that could ever capture on e5 without losing material by it.",
                20: "Forced, and look where the bishop lands. On c6 it is standing behind Black's own pawn on d5, and it never gets out from behind it for the rest of the game.",
                21: "The outpost, permanently. The only black piece that still looks at e5 is the queen, and a queen cannot capture a knight that a pawn is defending.",
                23: "Qf3 — and note that h3 is not available even now. White's own pawn from h2 is standing on g3, so the queen has to take the long way round.",
                24: "Black makes some air, and it is the only target on that wing.",
                25: "So the queen goes and looks at it. h6 is defended by the g-pawn and is not falling; what it is, is a hook, and everything White does from here is aimed at it.",
                27: "The pawn from h2 advances again, and now it has taken f5 and h5 away from Black's pieces for good. Doubled pawns that can march are not weaknesses.",
                29: "Improving before castling. Between her own pawns on g2 and g4 the queen cannot be attacked by anything, she defends the g4-pawn, and she steps off the file the rook wants.",
                31: "Move sixteen, and only now. Count the files: every one of them has pawns of both colours on it except the h-file, and the h-file is White's — which is what the eighth move bought.",
                35: "The break, on the wing where nothing has moved since move six. Every white piece was placed first; that is the order this opening insists on.",
                39: "The disambiguation is the whole point. The d2-knight is the one that takes, so the knight on e5 keeps the square it has owned since move eleven.",
                41: "b4, attacking the queen and giving up a pawn to do it. Black takes — and the next move is why that was the wrong decision.",
                43: "Nd3, hitting the queen — and it is the knight from e5 that does it, after eleven moves on that square. The one on c4 does not have to move at all.",
                47: "The dust settles. Count it: two knights against one bishop, five pawns against six — a piece for a pawn, which is a winning endgame and a very long one.",
                49: "Rxf7+, and it is not the pawn that matters. After 25...Kxf7 the knight comes to d6 with check and forks the king and the rook on c8, and the rook comes back with interest.",
                53: "There it is. Two knights and a rook against a bishop and a rook, five pawns each — a clean piece, and no counterplay anywhere on the board.",
                57: "Nd3, and Ghaem Maghami resigned. A piece and a pawn up, and nothing Black owns does anything: the rook on g8 has no file, the bishop on a4 has no target, and the knight White parked on a7 is not even attacked.",
            },
        },
        {
            "id": 'caruana-shankland-2021',
            "name": "Caruana – Shankland, Sinquefield Cup 2021 — how to answer ...Qb6",
            "tier": 'Plans',
            "note": "Round one at Saint Louis, and Black plays the move this whole page keeps coming back to. Shankland's queen lands on b6 with b2 defended by nothing at all, and Caruana answers with one knight move that hits the queen and covers b2 in the same breath. No panic, no pawn offer, no thinking about it.",
            "moves": (
                'd4 Nf6 Nf3 g6 Bf4 Bg7 e3 d6 h3 c5 Nbd2 cxd4 exd4 O-O Be2 Qb6 '
                'Nc4 Qc7 Ne3 Nc6 c3 e5 Bh2 Qe7 O-O e4 Ne1 d5 N1c2 Be6 Qe1 Nd7 '
                'f3 f5 fxe4 fxe4 Bf4 Rf7 Qg3 Nf6 Rf2 Qd7 Raf1 Raf8 Qh4 Ne8 Ng4 Nd6 '
                'Nce3 Ne7 Ne5 Bxe5 Bxe5 Ndf5 Ng4 h5 Qg5 hxg4 hxg4 Ng7 Qh6 Nef5 '
                'gxf5 Rxf5 Rxf5 Rxf5 Rxf5 Bxf5 g4 Be6 Qxg6 Qf7 Qh6 e3 Bf3'
            ),
            "notes": {
                9: "The same little move as the drilled line, and the game is about to show what it is for.",
                16: "There it is. The queen hits b2 and d4 at once, White has not played c3, and b2 is defended by absolutely nothing — the rook on a1 does not cover it and the bishop that used to is on f4.",
                17: "And this is the answer, and it does more than it looks: from c4 the knight hits the queen on b6 and defends b2 in the same move, and it is on its way to e3 afterwards. One move solves the entire problem the ...Qb6 lines pose. Shankland retreats rather than test it, which at 2700 is a verdict worth as much as an evaluation.",
                19: "The knight completes the trip. From e3 it covers c4, d5, f5 and g4 — every square Black would like to use on that side of the board — and it does not move again for fourteen moves.",
                21: "Only now does the pawn come to c3, with the queen already sent home. Two moves later than the system says, and exactly on time.",
                25: "Castling into the coming pawn storm, because it is not going to be a storm. Every advance Black makes here opens a line toward Black's own king, and White's rook will be on the file when it does.",
                33: "The standard answer to a pawn wedged on e4. It is not a raid — the pawn is held by d5 — it is a demand that Black resolve the centre, and 17...f5 is the only way to keep the wedge there.",
                37: "The bishop steps back out the moment the file opens. From f4 it hits d6 and c7 again, and it stands on the file both sides are about to pile up on — defended by the rook behind it on f1, attacked by the one on f8.",
                45: "Every white piece is now on the kingside: two rooks stacked on f1 and f2, a knight on e3, a bishop on f4, and the queen arriving on h4 where she looks straight down the h-file at h7.",
                51: "Ne5, and Black more or less has to take — a white knight sitting on e5 is worse than anything that follows it.",
                53: "And the recapture is the point. The bishop lands on e5 and the long diagonal beyond it is completely empty: f6, g7, h8, and the king is on g8.",
                57: "Everything converges. Queen on g5, bishop on e5, knight on g4, two rooks on the f-file facing two black rooks — which is why the next four moves are all captures.",
                61: "Two pawns down and it does not matter. The queen on h6 and the bishop on e5 are both trained on g7, Black has had to plant a knight there, and the king behind it has nowhere to go: h7 is covered by the queen and f8 is occupied by Black's own rook.",
                63: "The pawn comes back and the attack is still running.",
                71: "The last pawn in front of the king falls.",
                75: "Bf3, and Shankland resigned. The pawn on e3 is attacked and defended by nobody, the knight on g7 is attacked twice and defended twice so it cannot move, the queen on f7 is one of those two defenders and therefore cannot move either, and two bishops and a queen are pointed at a king with nothing left in front of it.",
            },
        },
    ],
    "progression": {
        "arc": "The London gets you a good position with almost no memorisation. The catch is that the middlegames are entirely up to you.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Day one",
                "goal": "Learn the setup and, above all, the move order.",
                "learn": [
                    "The setup: d4, Bf4, e3, Nf3, c3, Bd3, Nbd2, h3, O-O. Nine moves, playable against almost anything.",
                    "The one rule that matters: Bf4 before e3. Every bad London starts by locking the bishop in.",
                    "Why the knight goes to d2 and not c3 — the c-pawn must stay on c3 supporting d4.",
                ],
                "drill": "Play the nine-move setup in fifty blitz games. It should take you under a minute total.",
                "mistake": "Playing on autopilot into a bad version. If Black plays an early ...c5 and ...Qb6, you must respond, not continue the routine.",
                "ready": "You can reach the full setup against 1...d5, 1...Nf6 and 1...e6 without thinking.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to four",
                "goal": "Recognise which of three middlegames you have landed in.",
                "learn": [
                    "Type 1 — Black plays ...e6 and ...Bd6: you decline the bishop trade with Bg3, play Ne5 and attack the kingside.",
                    "Type 2 — Black fianchettoes: you switch plans entirely, play c4 and treat it as a Queen's Gambit.",
                    "Type 3 — Black plays ...c5 and ...Qb6 hitting b2: you need a concrete answer, and which one depends entirely on whether you have played c3 yet.",
                ],
                "drill": "Write down both answers to ...Qb6 — Nc3 before c3 is played, Qb3 after it — and memorise which is which. It is the only real theory the London requires.",
                "mistake": "Learning one answer to ...Qb6 and using it in both positions. Offering b2 with a knight is strong before c3 and simply loses a pawn after it; defending with Qb3 is the answer after c3 and is not even a legal move before it, because your own pawn is still standing on c2.",
                "ready": "You can name which of the three types you are in by move six.",
            },
            {
                "tier": "Plans",
                "when": "Months two to four",
                "goal": "Turn the solid position into an attack.",
                "learn": [
                    "The attacking machine: Ne5 held by d4 and Nd2, f2–f4 behind it, Bd3 on the b1–h7 diagonal, and the queen taking whichever of f3, g3 and h4 is free — the bishop on g3 blocks more of the third rank than people expect.",
                    "The trade-on-d6 plan: swap dark-squared bishops, then use the dark squares and the c-file.",
                    "The queenside plan: b4, a4, Nb3–c5 when Black castles kingside and commits to ...c5.",
                ],
                "drill": "Study the Bxh7+ and Bxh6 sacrifice patterns until you can calculate them in ten seconds. The London produces them constantly.",
                "mistake": "Playing solidly forever. The London is not a draw machine — if you never attack, strong opponents simply equalise and outplay you.",
                "ready": "You have won a game with the Qf3–h3 build-up.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Add sharpness and cover the anti-London systems.",
                "learn": [
                    "The Jobava London (2.Nc3 and 3.Bf4) for a much sharper version with e4 ideas.",
                    "The lines where Black plays an early ...Bf5 or ...Bg4, mirroring your own idea.",
                    "Endgames with the c3–d4–e3 structure: they are drawish unless you create an outside passer, so learn to create one.",
                ],
                "drill": "Play the Jobava version for a month and compare your results. Many players find it suits them better.",
                "mistake": "Believing the London is 'safe'. It is sound, which is different — the safety has to come from your play.",
                "ready": "You have two versions of the system and choose between them by opponent.",
            },
        ],
        "study": "Gata Kamsky brought the London back to elite level and has never stopped — over a thousand games with it in the archives, spanning nearly forty years. Magnus Carlsen has close to two hundred, including the model game on this page. For the sharp version, the variation is named after Baadur Jobava for a reason.",
        "next": "When you want more, learn the Queen's Gambit properly. The London will still be there as a low-preparation option for fast time controls.",
    },
}
