OPENING = {
    "id": "nimzo",
    "name": "Nimzo-Indian Defence",
    "eco": "E20–E59",
    "section": "black-d4",
    "orientation": "black",
    "tagline": "Pin the knight, trade it off, and play against the doubled pawns. The most respected defence to 1.d4.",
    "level": "Intermediate → World Championship",
    "theory": {
        "big_idea": "3...Bb4 pins the c3-knight, which is the piece guarding e4. Black is not fighting for the centre with pawns — Black is fighting for one square, e4, with pieces. Usually Black trades the bishop for the knight, giving White the bishop pair but leaving White with doubled c-pawns. The rest of the game is a clean philosophical argument: White's two bishops and open lines against Black's superior structure and control of the light squares.",
        "structure": "The archetype is the Sämisch structure: White pawns on c3, c4, d4 (doubled c-pawns) against Black's a7, b7, c5, d6, e6. If the position opens, White's bishops dominate. If it stays closed, the doubled c-pawns are simply weak. Black therefore blockades with ...c5, ...b6, ...Ba6 and ...Na5, and White strives to play e3–e4 and open lines.",
        "white_plans": [
            "Rubinstein (4.e3): quiet development, then Bd3, Nf3, O-O and a central break with e4 or dxc5.",
            "Classical (4.Qc2): pre-empt the doubled pawns by recapturing on c3 with the queen. White gets the bishop pair with no structural damage — at the cost of two tempi.",
            "Sämisch (4.a3): force the trade immediately, accept the doubled pawns and go all-in on e3–e4 and a kingside attack.",
            "Build the big centre with f3 and e4 and use the bishop pair in an open position.",
        ],
        "black_plans": [
            "Trade on c3, then blockade the doubled pawns with ...c5, ...b6, ...Ba6 and ...Na5 hitting c4.",
            "Keep the bishop and play ...d5 and ...c5, treating it like a Queen's Gambit with an extra active bishop.",
            "Control e4 with ...Ne4, ...b6, ...Bb7 and ...f5 — the Nimzowitsch dream setup.",
            "Trade off White's bishop pair advantage at every opportunity.",
        ],
        "traps": [
            "In the 4.Qc2 lines, do not automatically trade on c3 — White recaptures with the queen and there are no doubled pawns.",
            "Watch for the Qd1–a4+ trick winning the loose bishop on b4 if Black plays ...c5 too early.",
            "After 4.e3 O-O 5.Bd3 d5 6.Nf3 c5, Black must know 7.O-O dxc4 8.Bxc4 and the resulting isolated-pawn structures.",
        ],
        "who": "Play this if you want a defence that is theoretically sound at every level and rewards positional understanding. It is arguably the single best answer to 1.d4 ever devised.",
    },
    "lines": [
        {
            "name": "Rubinstein Variation — 4.e3",
            "note": "White's most popular and most flexible line. The game usually transposes into an isolated-pawn or hanging-pawn middlegame.",
            "plan": {
                "structure": 'isolani',
                "point": "Black traded the bishop pair for time and a blockade, and you took an isolated d-pawn in exchange for the two bishops and the squares in front of it. Both sides got what they wanted; now one of you has to prove it was worth more.",
                "next": [
                    'Ne5 or Bg5 and Rac1, aiming at h7 and c7 while the blockade is still being organised.',
                    'd4–d5 the moment the knight leaves d5 or f6 — it is the only move that turns the weakness into an attack.',
                    "Watch the b7-bishop. It is the piece that makes ...Nxd4 sacrifices work, so keep a piece on f3 or a rook on d1.",
                ],
                "endgame": 'The blockading knight on d5 is worth more than your bishop the moment the queens are gone. This is the ending Rubinstein built the variation to reach as Black — do not walk into it, and if you are Black, trade toward it deliberately.',
            },
            "moves": "d4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5 O-O dxc4 Bxc4 Nbd7 Qe2 b6 Rd1 cxd4 exd4 Bb7",
            "notes": {
                4: "Preparing ...d5 or ...Bb4 and keeping every option open.",
                5: "Development, adding a defender to e4 and d5.",
                6: "The Nimzo-Indian. Black pins the knight that guards e4 and puts immediate pressure on the position without moving a single central pawn.",
                7: "The Rubinstein — modest, flexible and the most common choice by far. White simply develops and waits.",
                8: "King safety.",
                9: "The bishop takes the attacking diagonal.",
                10: "Black stakes a classical claim in the centre and prepares ...c5.",
                11: "Development.",
                12: "The critical break, hitting d4 and challenging White's centre.",
                13: "King safety.",
                14: "Black resolves the tension in the centre.",
                15: "Recapturing on the best square.",
                16: "Development, adding a defender to c5 and preparing ...b6.",
                17: "The queen steps off the d-file in anticipation of the coming exchanges.",
                18: "Preparing ...Bb7 to fight for the long diagonal and e4.",
                19: "The rook takes the file where the isolated pawn will appear.",
                20: "Black releases the tension.",
                21: "White now has an isolated queen's pawn on d4 — the same structure as the Panov and the Tarrasch. White attacks with the e5/c5 outposts and open files; Black blockades on d5 and trades pieces.",
                22: "Black completes development and blockades. A rich position that comes up in hundreds of grandmaster games.",
            },
        },
        {
            "name": "Classical Variation — 4.Qc2",
            "note": "White pre-empts the doubled pawns by recapturing on c3 with the queen. The most testing line at the top level.",
            "moves": "d4 Nf6 c4 e6 Nc3 Bb4 Qc2 O-O a3 Bxc3+ Qxc3 b6 Bg5 Bb7 f3 h6 Bh4 d5 e3 Nbd7",
            "notes": {
                7: "The Classical. The queen defends c3 in advance so that if Black takes, White recaptures with the queen and keeps a perfect structure.",
                8: "King safety.",
                9: "Putting the question. Black must now either trade or retreat.",
                10: "Trading. Black gives up the bishop pair — but White has spent two moves (Qc2 and a3) on this, so Black is well ahead in development.",
                11: "The queen recaptures. No doubled pawns. White has the bishop pair and no weaknesses.",
                12: "Black prepares to fight for e4 with the light-squared bishop — Nimzowitsch's original idea.",
                13: "Pinning the knight that would jump to e4.",
                14: "Development. The bishops face off on the long diagonal.",
                15: "Taking e4 away from the knight and preparing e4.",
                16: "Putting the question to the bishop.",
                17: "Keeping the pin.",
                18: "The right moment. Black challenges the centre and opens the position while White's king is still uncastled.",
                19: "Development.",
                20: "Black develops and prepares ...c5. White has the bishop pair and long-term chances; Black has faster development and full central control. A genuinely balanced fight.",
            },
        },
        {
            "name": "Sämisch Variation — 4.a3",
            "note": "White accepts the doubled pawns immediately and goes for the big centre and a direct attack. The clearest illustration of the whole Nimzo debate.",
            "moves": "d4 Nf6 c4 e6 Nc3 Bb4 a3 Bxc3+ bxc3 c5 e3 Nc6 Bd3 O-O Ne2 b6 e4 Ne8 O-O Ba6",
            "notes": {
                7: "The Sämisch. White spends a whole tempo to force the trade at once, accepting a structural weakness for the bishop pair and a huge pawn centre.",
                8: "Black takes.",
                9: "The doubled c-pawns appear. This is the central bargain of the Nimzo-Indian: White gets two bishops and pawns on c3, c4, d4 and later e4; Black gets a permanently weak pawn to attack.",
                10: "Immediately hitting the base of the centre.",
                11: "Supporting d4.",
                12: "Adding pressure to d4.",
                13: "Development.",
                14: "King safety.",
                15: "Note e2, not f3 — the knight must not block the f-pawn, and from e2 it supports both d4 and the coming e4 and g3–f4.",
                16: "Preparing ...Ba6 to hit the c4-pawn, which is the weakest point in White's structure.",
                17: "White builds the dream centre. If White ever gets in f4 and e5, Black is in real danger.",
                18: "Black re-routes the knight so it does not get pushed around by e5, heading for d6 to blockade and hit c4.",
                19: "King safety.",
                20: "The bishop hits c4 directly. Black's whole plan is now clear: blockade the centre, trade pieces, and win the c4-pawn. White's plan is equally clear: push f4–f5 and attack. A perfect strategic argument.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Nimzo bishop trade",
        "note": "Black gives up the bishop, White gets doubled pawns and the pair, and both sides play the argument out.",
        "moves": "d4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5 O-O dxc4 Bxc4 Nbd7 Qe2 b6 Rd1 cxd4 exd4 Bb7 Bg5 Bxc3 bxc3 Qc7 Bd3 Rfe8 c4 h6 Bh4 Rac8 Rac1 Qf4",
        "notes": {
            23: "White develops with a pin. The bishop on g5 also supports a future d5 push by removing the f6-knight.",
            24: "Now Black takes. The moment is chosen: White has just committed the bishop to g5, so the recapture must be with a pawn.",
            25: "White accepts the doubled pawns. In exchange: the bishop pair and a broad c3–d4 centre. The whole Nimzo-Indian debate, in one position.",
            26: "The queen takes the half-open c-file, aiming directly at the doubled pawns.",
            27: "The bishop steps back to the attacking diagonal, where it looks at h7.",
            28: "Black centralises and prepares to blockade.",
            29: "White pushes the doubled pawn forward and un-doubles. Now the c-pawns are gone and White simply has a big centre and two bishops — the doubled-pawn weakness has been converted into space.",
            30: "Putting the question to the bishop and making luft.",
            31: "White keeps the pin. Trading on f6 would give Black the bishop pair back.",
            32: "Both black rooks are placed. Black's plan is fixed: pressure c4 and d4, blockade on d5 or c5, and trade pieces until the centre becomes weak rather than strong.",
            33: "White contests the file.",
            34: "The queen goes on the attack. The position is balanced and instructive: White's two bishops and centre against Black's better structure and pressure on the pawns. Whichever side gets to dictate whether the position opens or closes will win the argument.",
        },
    },
    "progression": {
        "arc": "The Nimzo-Indian is the most respected defence to 1.d4 because it asks a question that has no clean answer. It rewards understanding over memory.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to two",
                "goal": "Understand why 3...Bb4 is a good move at all.",
                "learn": [
                    "The pin on c3 stops e4. Black is not fighting for the centre with pawns but preventing White from occupying it.",
                    "White's four main replies: 4.e3 (Rubinstein), 4.Qc2 (Classical), 4.a3 (Sämisch), 4.f3 and 4.Nf3.",
                    "The move-order problem: after 1.d4 Nf6 2.c4 e6, White can play 3.Nf3 and you never get the Nimzo. Pick a second defence now.",
                ],
                "drill": "Prepare your answer to 3.Nf3 before your first Nimzo game — Queen's Indian (...b6), Bogo-Indian (...Bb4+) or Ragozin (...d5).",
                "mistake": "Trading on c3 automatically. Against 4.Qc2 White recaptures with the queen and there are no doubled pawns to attack.",
                "ready": "You have a complete answer to 3.Nf3 as well as to 3.Nc3.",
            },
            {
                "tier": "Structure",
                "when": "Months one to three",
                "goal": "Learn to play against doubled pawns — and to know when they are not weak.",
                "learn": [
                    "The Sämisch structure: White c3, c4, d4 against your c5, d6, e6. Blockade with ...Na5 and ...Ba6 and the c4-pawn falls.",
                    "The rule that decides everything: doubled pawns are weak in a closed position and strong in an open one, because they support a big centre.",
                    "Your job after trading on c3: keep the position closed and trade pieces, never open lines for the bishops.",
                ],
                "drill": "Play ten Sämisch positions with the plan ...c5, ...b6, ...Ba6, ...Na5 and nothing else. See how often c4 simply drops.",
                "mistake": "Opening the centre after giving up the bishop pair. Every open file you create is a gift to White's two bishops.",
                "ready": "You can look at a doubled-pawn position and say whether they are a weakness or a strength.",
            },
            {
                "tier": "Plans",
                "when": "Months three to eight",
                "goal": "Master the three middlegame types the Nimzo produces.",
                "learn": [
                    "Type 1 — the isolated queen's pawn (from 4.e3 lines): blockade d5, trade minor pieces, win the endgame.",
                    "Type 2 — hanging pawns on c4 and d4: attack them with ...Rc8 and ...Na5 and force one to advance.",
                    "Type 3 — the blockade against doubled pawns: knight to c5, bishop to a6, and total control of the light squares.",
                ],
                "drill": "Take five of your Nimzo games and classify each middlegame into one of the three types. If you cannot, that is the study you need.",
                "mistake": "Playing all three types the same way. The plan comes from the structure, and the Nimzo produces three different ones.",
                "ready": "You name the structure type before you choose a move.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Depth in your chosen branch plus the endgames.",
                "learn": [
                    "One deep line against 4.Qc2 — currently the critical test at every level.",
                    "The Ragozin and Vienna transpositions, which arise constantly from Nimzo move orders.",
                    "Bishop-versus-knight endgames. The Nimzo is a machine for producing them and they decide half your games.",
                ],
                "drill": "Study twenty Karpov or Kramnik games in the Nimzo, guessing every Black move. It is the best positional training available.",
                "mistake": "Neglecting endgame study. The Nimzo produces small, technical advantages — you need the technique to convert them.",
                "ready": "You can convert a one-pawn or good-knight-versus-bad-bishop endgame reliably.",
            },
        ],
        "study": "Aron Nimzowitsch invented it, Capablanca and Karpov perfected the positional treatment, and Kramnik and Caruana carry it today.",
        "next": "Pair it with the Queen's Indian or Ragozin so that 3.Nf3 does not take you out of preparation. Together they form a complete 1.d4 defence.",
    },
}
