OPENING = {
    "id": "queensgambit",
    "name": "Queen's Gambit",
    "eco": "D06–D69",
    "section": "white-d4",
    "orientation": "white",
    "tagline": "The most trusted 1.d4 opening in history. Not really a gambit at all.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "White attacks Black's d5-pawn from the side with c4 instead of head-on. If Black takes with ...dxc4, the pawn cannot be kept — every attempt to hold it with ...b5 runs into a2–a4 — so White recovers it at leisure and builds a centre with e4. If Black declines with ...e6 or ...c6, Black must accept a small structural or developmental concession instead. The whole opening is a fight over whether White gets to play e2–e4, and over which of the two c-pawns comes off the board first.",
        "structure": "The defining structure is the Carlsbad, and the first thing to know about it is what is NOT there: after cxd5 exd5 neither side has a c-pawn where it started. White is left with a2 and b2 on the queenside against Black's a7, b7 and c6 — two pawns against three. That is where the name minority attack comes from. Both sides then attack where their pawns point: White pushes b4–b5 on the queenside, Black plays for ...Ne4 and ...f5 on the kingside. Learning the Carlsbad teaches you more about middlegame planning than any tactics book.",
        "white_plans": [
            "The minority attack: push b2–b4–b5 and trade on c6, leaving Black with a backward c-pawn on a half-open file that no pawn can ever defend.",
            "The other Carlsbad plan: f3 and e3–e4, breaking in the centre. Take it when Black has committed pieces to the kingside or stopped b4 with ...a5.",
            "In the Accepted, regain the pawn with Bxc4, play a4 to stop ...b5, and accept an isolated d-pawn in return for the c5 and e5 squares and open files.",
            "Pile up on the c-file and infiltrate on c7/c8 — in the Carlsbad the c-file is half-open for you and closed for Black.",
        ],
        "black_plans": [
            "Break with ...c5 (Tarrasch style) or ...e5, freeing the position at the cost of structure.",
            "In the Carlsbad, attack on the kingside with ...Ne4, ...f5 and ...Ng6 — Black is faster there because White's pawns are committed to the other wing.",
            "Trade pieces off with the Tartakower plan (...h6, ...b6, ...Bb7) to relieve the cramp before the squeeze starts.",
            "The freeing manoeuvre ...Nd7–f8–g6 or ...Nf6–e4, swapping a pair of pieces and buying room.",
        ],
        "traps": [
            "The Elephant Trap: 1.d4 d5 2.c4 e6 3.Nc3 Nf6 4.Bg5 Nbd7 5.cxd5 exd5 6.Nxd5?? Nxd5! 7.Bxd8 Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8 and Black comes out a minor piece for a pawn ahead. The knight on f6 was never really pinned, because taking the queen is answered by a check that wins White's queen straight back.",
            "The c4-pawn cannot be defended, only recovered. 1.d4 d5 2.c4 dxc4 3.e3 b5?? 4.a4 c6 5.axb5 cxb5 6.Qf3! — the two captures have emptied c6 and b7, so the queen now looks all the way down the diagonal at the rook on a8, and 6...Nc6 7.Qxc6+ picks up the knight with the rook still hanging behind it. Note the exact conditions: after 3.Nf3 instead, the same 3...b5 is merely a poor move, because f3 is no longer available to the queen.",
            "The Rubinstein Trap, out of the Carlsbad: 1.d4 d5 2.Nf3 Nf6 3.c4 e6 4.Bg5 Nbd7 5.e3 Be7 6.Nc3 O-O 7.Rc1 Re8 8.Qc2 a6 9.cxd5 exd5 10.Bd3 c6 11.O-O Ne4 12.Bf4 f5? 13.Nxd5! cxd5?? 14.Bc7 and the black queen has exactly one legal move, Qxc7. Rubinstein lost this position twice, to Euwe in 1928 and to Alekhine in 1930.",
        ],
        "who": "Play this if you want the most solid, most respected 1.d4 opening there is. Every world champion from Steinitz to Ding has played it.",
    },
    "lines": [
        {
            "name": "Exchange Variation — The Minority Attack",
            "note": "The single most instructive plan in all of chess. Learn this and you will understand what a 'plan' actually means.",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "structure": 'carlsbad',
                "tier": "Structure",
                "point": "You have the Carlsbad structure, and it is worth counting before you touch a piece: your a2 and b2 against Black's a7, b7 and c6. Two pawns against three. Neither side has a c-pawn where it started, and the rook on b1 is already behind the one you are about to push.",
                "next": [
                    "b4, then a4, then b5. Two pawns walking into three — and after bxc6 bxc6 Black has a pawn on c6 that no other pawn can ever defend, on the file your rook already owns.",
                    "The knight went to e2 rather than f3 for two reasons. It can reroute to g3 or f4 without asking anyone's permission — and, the one that matters more, it leaves f2–f3 free, so if the queenside plan stalls you switch to f3 and e3–e4. Botvinnik did exactly that from this position in the game below.",
                    "If Black stops the pawns with 11...a5, do not force it. Rbe1, f3 and e4 is the second plan in this structure and it is fully sound; the pawns on a2 and b2 keep the option open all game.",
                ],
                "endgame": "The whole point is an endgame. A backward pawn on c6 on a half-open file cannot advance and cannot be defended by a pawn, so it needs pieces — pile a rook and a knight on it, trade queens, and take it. There is no hurry: the weakness is permanent, and nothing Black does makes it go away.",
            },
            "moves": "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8 Rab1",
            "notes": {
                3: "The Queen's Gambit. White does not really give a pawn — the point is to deflect the d5-pawn so that e2–e4 becomes possible.",
                4: "The Queen's Gambit Declined. Rock-solid: Black supports d5 with a pawn. The cost is that the c8-bishop is locked behind its own pawn chain for a while.",
                5: "Developing, and adding a third attacker to d5.",
                6: "Black develops and defends d5 for the third time.",
                7: "The Exchange Variation. White resolves the tension deliberately, creating the Carlsbad structure and a clear long-term plan. It is a commitment: you trade the c-pawn for Black's e-pawn and both sides know exactly where they are attacking from here.",
                8: "The recapture that keeps the position sound. 4...Nxd5 hands over the centre after 5.e4, and 4...Qxd5?? simply loses the queen — the knight is already standing on c3, so 5.Nxd5 exd5 leaves White a queen for a knight ahead with the pawns level at seven each.",
                9: "Pinning the f6-knight, which is d5's main defender.",
                10: "Black shores up d5 a third time, and this is the Carlsbad skeleton: White has a2 and b2 on the queenside against Black's a7, b7 and c6, because White's c-pawn came off on move four. Two against three — count them now and the whole plan follows.",
                11: "Modest but essential — it supports d4 and opens the f1-bishop.",
                12: "Breaking the pin and preparing to castle.",
                13: "The bishop takes its best diagonal, aiming at h7 and supporting a later e4.",
                14: "The knight goes to d7 rather than c6 so that it does not block the c-pawn, and from d7 it heads for f8 and then e6 or g6.",
                15: "Battery on the b1–h7 diagonal, and the queen also eyes the c-file, which is the file that is half-open for White and closed for Black.",
                16: "King safety.",
                17: "The Carlsbad subtlety: the knight goes to e2, not f3. On e2 it does not block the f-pawn, it can reroute to g3 or f4, and it leaves f3 free for the pawn if you switch to the e3–e4 plan.",
                18: "Black's rook eyes the e-file and supports a future ...Ne4.",
                19: "King safety, and the king's rook lands on f1 — which is the file that opens if you take the f3 and e3–e4 road instead of the queenside one. Botvinnik takes it in the game below.",
                20: "Black's standard defensive manoeuvre. The knight is heading for g6 or e6 — and g6 is the accurate one, because a knight on g6 stands on the b1–h7 diagonal itself and shuts the bishop on d3 out of h7 for good.",
                21: "The minority attack begins. White will play b4, then a4, then b5 — two pawns advancing against three. When they trade on c6 Black is left with a backward c-pawn on a half-open file, and that is the plan for the next twenty moves. Note that the rook goes to b1 before the pawn goes to b4: the pieces come first.",
            },
        },
        {
            "name": "Queen's Gambit Declined — Tartakower",
            "note": "Black's most reliable equalising system. Take the sting out with ...h6, fianchetto the problem bishop, and trade pieces.",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": "Plans",
                "point": "Black has handed you the same two-against-three you get in the Exchange — a2 and b2 against a7, b6 and c7 — and paid for it by trading two pairs of pieces off. Your compensation for the simplification is a central majority: your d- and e-pawns against Black's lone d5.",
                "next": [
                    "Rc1 and Qb3 or Qa4, hitting the queenside before Black gets ...Be6 and ...c5 in. The c-file is half-open for you and Black's c7-pawn is the only pawn standing on it.",
                    "Ne5 followed by f4 is the other plan. Black's one remaining bishop is still on c8, so for a few moves the kingside is where Black is short of defenders.",
                    "Do not rush b4 here. Unlike the Exchange, ...b6 is already played, so Black answers b4 with ...c5 and the pawn on d5 stops being a target the moment the position opens.",
                ],
                "endgame": "Count the wings before you trade. Black has the queenside majority — a7, b6 and c7 against your a2 and b2 — and you have two centre pawns against one. Neither is a passed pawn and neither becomes one by itself, but Black's is the one that can advance without help, so a pawn ending is the wrong ending to head for. Press on the c-file with pieces, keep ...c5 under control, and be honest about the evaluation: at depth twenty this position is level, and the Tartakower is Black's best answer to the whole opening for exactly that reason.",
            },
            "moves": "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6 cxd5 Nxd5 Bxe7 Qxe7 Nxd5 exd5",
            "notes": {
                7: "The classical development, pinning the knight and pressuring d5 indirectly.",
                8: "Breaking the pin by interposing. Black's setup is passive and extremely tough.",
                9: "Solid: supports d4, opens the bishop. White is not in a hurry.",
                10: "King safety.",
                11: "Development. Every piece has an obvious square and there is nothing to attack yet.",
                12: "Putting the question to the bishop. This little move is the start of Black's whole plan — and it also takes g5 away from White's pieces for good.",
                13: "Retreating and keeping the pin. 7.Bxf6 Bxf6 is playable but it hands Black the bishop pair for nothing.",
                14: "The Tartakower move. Black prepares ...Bb7 so that the problem bishop finally gets a diagonal.",
                15: "White strikes before ...Bb7 arrives, so that the recapture on d5 has to be made under slightly awkward circumstances.",
                16: "Recapturing with the knight. 8...exd5 is the alternative and it keeps more pawns in the centre, at the cost of leaving the bishop on c8 staring at its own pawn again.",
                17: "Simplifying. The bishop has done its work and Black's dark squares are the thing worth trading into.",
                18: "Black recaptures with the queen, connecting the rooks.",
                19: "The last trade. The knight on d5 is Black's best-placed piece, and taking it forces Black to settle the pawn structure at once.",
                20: "Black recaptures toward the centre and the position is set. Black's d5-pawn is slightly loose and Black's remaining bishop is still on c8 — but two pairs of pieces are off and cramp is what the Tartakower is designed to cure. This is one of the most reliable ways to equalise as Black against 1.d4.",
            },
        },
        {
            "name": "Queen's Gambit Accepted",
            "note": "Black takes the pawn, gives up the centre, and hits back with ...c5. Fast development and clean structures.",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "structure": 'isolani',
                "tier": 'Plans',
                "point": "The same isolated d-pawn the Panov and the Nimzo reach, arrived at from 1.d4 — and with a2–a4 already in, so Black's queenside has no ...b5 to gain space with while you attack.",
                "next": [
                    'Nc3 and Bg5, then Rac1 or Ne5. The d-pawn buys you c5 and e5; a knight on either is worth more than the pawn is weak.',
                    'd4–d5 when Black stops watching it — usually the moment a piece leaves the kingside.',
                    'a4 has cost you b4 as a square: with no c-pawn and the a-pawn already committed, nothing can ever defend b4 with a pawn. Do not put a piece there and expect it to stay.',
                ],
                "endgame": 'The pawn is a liability the instant the queens come off, and Black knows it. Trade only when the trade wins something concrete; otherwise keep four pieces each on the board and keep asking questions.',
            },
            "moves": "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4 Nc6 Qe2 cxd4 Rd1 Be7 exd4",
            "notes": {
                4: "The Queen's Gambit Accepted. Black does not intend to keep the pawn — the idea is to give up the centre now and attack it later with ...c5 and ...e5.",
                5: "The most flexible move: it develops, it stops ...e5, and it says nothing yet about how the pawn will be recovered.",
                6: "Black develops and controls d5 and e4.",
                7: "Modest, but it opens the bishop's path to c4 and shores up d4.",
                8: "Black opens the bishop and prepares ...c5.",
                9: "White finally regains the pawn, on the best square, with full development and a healthy centre.",
                10: "The essential freeing break. Without ...c5 Black is simply worse with less space and nothing to do.",
                11: "King safety before the centre opens.",
                12: "Preparing ...b5, to kick the bishop and gain queenside space. This is Black's main source of counterplay in the whole variation.",
                13: "Stopping ...b5 in its tracks — and note that it is not merely useful, it is close to necessary: 7...b5 now loses material to 8.axb5, because the rook on a1 is already looking down the file at a8.",
                14: "Developing with pressure on d4.",
                15: "The queen steps off the d-file in advance of the exchanges that are coming.",
                16: "Black releases the tension, handing White an isolated d-pawn in return for free piece play.",
                17: "The rook goes to the file the isolated pawn will sit on — supporting it, and eyeing d5 through it.",
                18: "Completing development. 9...Bd6 and 9...Qc7 are the other main squares.",
                19: "White has an isolated d-pawn: a long-term weakness and a short-term asset. It hands you the c5 and e5 outposts, the half-open e-file, and attacking chances. If White attacks, White wins; if the pieces come off, Black wins the pawn.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the minority attack completed",
        "note": "The most instructive sequence in chess: watch two pawns walk up the board and permanently ruin three.",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "structure": 'carlsbad',
            "tier": "Plans",
            "point": "Sixteen moves of preparation for one permanent fact: Black has a pawn on c6 that no pawn can ever defend, and it is the only pawn left on the a-, b- and c-files. The a- and b-files are open, the c-file is half-open for you, and material is level at five pawns each.",
            "next": [
                "17...Rxa4 18.Qxa4 is a rook for a knight — the knight on a4 is defended by the queen on c2, which is the whole reason it could go there with a black rook on a3.",
                "Nb6 or Nc5 next, then Rfc1 and Bf5. You want three attackers on c6; Black defends it with the bishop on d7 and whatever else can be dragged onto the c-file.",
                "Offer the dark-squared bishops off, keep the light-squared one. Bd3 is the piece that supports Bf5 and eyes c6 from a distance, and Black cannot trade it without spending moves on ...Be6.",
            ],
            "endgame": "This is the endgame the opening was played for. Five pawns each, and exactly one of them cannot move: every queen and rook trade helps you, right up to the last pair of rooks. If you reach a knight ending with the black pawn still on c6, it is over.",
        },
        "moves": "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8 Rab1 Ng6 b4 a6 a4 Bd7 b5 axb5 axb5 Ra3 bxc6 bxc6 Na4",
        "notes": {
            22: "The knight completes its journey to g6, where it covers f4 and h4 — and, the practical point, stands squarely on the b1–h7 diagonal. With a black piece on g6 the bishop on d3 cannot reach h7 at all, which is the whole difference between this and 11...Ne6.",
            23: "The minority attack begins. Two pawns are about to advance against three, and the rook that will stand behind them went to b1 last move.",
            24: "Black stops b5 for a moment and asks White to spend a tempo.",
            25: "White simply prepares b5 again. The attack cannot be refuted, only delayed — which is why it is such a reliable plan: every move Black spends stopping it is a move not spent on the kingside.",
            26: "Developing the last piece, and defending c6 with a piece before it needs defending. Black is playing this correctly.",
            27: "The break arrives.",
            28: "Black takes, because otherwise bxc6 comes anyway and with an extra tempo.",
            29: "Recapturing with the a-pawn, which opens the a-file — a second front Black never asked for. Two files to watch and a weakness still to come; that is what makes the plan so hard to meet.",
            30: "Good defence: activity is the only real answer to a structural attack. From a3 the rook is behind White's lines and hits the knight on c3, which is defended twice.",
            31: "The point of the whole plan, and it is worth being exact about the arithmetic: this is a two-for-two trade, not a two-for-three. What matters is which two come off — Black's a- and b-pawns — and which one is left behind.",
            32: "Forced, and now it is done: Black has a pawn on c6 that stands on a half-open file and can never be defended by another pawn. Count the board — five pawns each, and only one of them is a permanent target.",
            33: "The knight heads for b6 and c5 — two squares a black pawn would normally cover, and Black no longer owns an a-pawn or a b-pawn to cover them with. It is safe on a4 because the queen on c2 defends it, so 17...Rxa4 18.Qxa4 is a rook for a knight. Everything from here is technique: attack c6 with more pieces than defend it, trade into an endgame, and take it. This plan has decided thousands of grandmaster games.",
        },
    },
    # Deviations, keyed by the position they answer rather than by a ply number.
    # This is a White repertoire, so most of these are Black's replies; the sets
    # at White-to-move positions are the doors out of the repertoire.
    "branches": {

        # ── ply 1 · Black does not play 1...d5 ──────────────────────────────────
        "d4": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Indian Defences",
             "why": "Much the most common answer to 1.d4, and there is no Queen's Gambit after it — Black refuses to put a pawn on d5 and fights for the centre with pieces instead. Play 2.c4 anyway: 2...e6 3.Nc3 Bb4 is the Nimzo-Indian, 2...g6 the King's Indian, and 2...e6 3.Nc3 d5 is the Queen's Gambit Declined by transposition.",
             "line": "c4 e6 Nc3 Bb4",
             "see": "nimzo"},
            {"san": "f5", "severity": "playable", "tier": "Structure",
             "name": "Dutch Defence",
             "why": "Black grabs e4 with a wing pawn and opens a diagonal toward their own king to do it. There is nothing to refute — the engine puts it under a third of a pawn behind 1...d5 — so develop naturally with 2.c4 and 3.g3, where the bishop on g2 stares at the weakened light squares Black has just committed to.",
             "line": "c4 Nf6 g3 e6 Bg2"},
        ],

        # ── ply 3 · Black's second move — the whole map of the opening ───────────
        "d4 d5 c4": [
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "name": "Queen's Gambit Declined",
             "why": "The classical main reply and the most solid thing Black has: the d5-pawn is defended by a pawn, and the price is the c8-bishop, which now looks at its own pawn on e6. This is the variation the first two lines here are about.",
             "line": "Nc3 Nf6 cxd5 exd5 Bg5",
             "see": "queensgambit#exchange"},
            {"san": "dxc4", "severity": "playable", "tier": "Foundation",
             "name": "Queen's Gambit Accepted",
             "why": "Perfectly sound, and it is not really a pawn grab: Black gives up the centre in order to hit it later with ...c5. The pawn on c4 comes back to you on move five whatever Black does about it.",
             "line": "Nf3 Nf6 e3 e6 Bxc4",
             "see": "queensgambit#accepted"},
            {"san": "c6", "severity": "playable", "tier": "Foundation",
             "name": "Slav Defence",
             "why": "The other great way to decline: Black supports d5 with the c-pawn instead of the e-pawn, so the c8-bishop keeps its diagonal. It is as sound as the Declined, it is everywhere in club play, and it is a whole opening of its own — study it separately before you meet it.",
             "line": "Nf3 Nf6 Nc3 dxc4 a4",
             "see": "slav"},
            {"san": "Nf6", "severity": "inaccuracy", "tier": "Structure",
             "name": "Marshall Defence",
             "why": "Black defends d5 with a piece that cannot actually hold it. 3.cxd5 Nxd5 4.e4! kicks it at once: 4...Nf6 5.Nc3 and the knight has made three moves to arrive back on f6, while White built the full centre for free. Not losing, and it is the one common second move that simply concedes something for nothing.",
             "line": "cxd5 Nxd5 e4 Nf6 Nc3"},
            {"san": "e5", "severity": "playable", "tier": "Mastery",
             "name": "Albin Countergambit",
             "why": "A pawn for a wedge on d4, and it is far more dangerous than its reputation: at depth twenty it costs Black only about a third of a pawn. Take with 3.dxe5 d4 and then develop — 4.Nf3 Nc6 5.g3 is the safe, tested route. What you must not do is grab space with 4.e3?, because that is the Lasker Trap: 4...Bb4+ 5.Bd2 dxe3! 6.Bxb4?? exf2+ 7.Ke2 fxg1=N+! 8.Rxg1 Bg4+ and White's queen falls. An underpromotion, in a real opening, on move seven.",
             "line": "dxe5 d4 Nf3 Nc6 g3"},
            {"san": "Nc6", "severity": "playable", "tier": "Mastery",
             "name": "Chigorin Defence",
             "why": "Black blocks the c-pawn on purpose and plays for pieces against pawns — the anti-positional opening that has never been refuted. 3.Nf3 Bg4 4.cxd5 Bxf3 5.gxf3 Qxd5 gives you the bishop pair and a broken kingside; it is a genuinely different kind of game and you should decide in advance whether you want it.",
             "line": "Nf3 Bg4 cxd5 Bxf3 gxf3"},
            {"san": "Bf5", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Baltic Defence",
             "why": "Black solves the problem bishop before it becomes one — and pays half a pawn for it. 3.cxd5 Bxb1 4.Rxb1 Qxd5 wins the pawn back, and look at what has happened: Black has given up a bishop for a knight and moved the queen out on move four, and White's rook on b1 supports an immediate b2–b4.",
             "line": "cxd5 Bxb1 Rxb1 Qxd5 Nf3"},
            {"san": "c5", "severity": "playable", "tier": "Structure",
             "name": "Symmetrical (Austrian) Defence",
             "why": "Black hits d4 immediately and accepts an early queen sortie for it. 3.cxd5 Qxd5 4.Nf3 cxd4 5.Nc3 and the queen has to move again while you develop with tempo. Sound enough, but every tempo you gain here is a tempo Black spent on a pawn that is coming off anyway.",
             "line": "cxd5 Qxd5 Nf3 cxd4 Nc3"},
        ],

        # ── ply 5 · your own third move against the Declined ─────────────────────
        "d4 d5 c4 e6": [
            {"san": "Nf3", "severity": "playable", "tier": "Plans",
             "name": "Three Knights move order",
             "why": "Exactly as good as 3.Nc3 by the numbers, and it changes which defences Black gets. Nf3 first opens the Ragozin (3...Nf6 4.Nc3 Bb4), the Vienna (4...dxc4 5.e4 Bb4) and the Semi-Tarrasch (4...c5) — none of which exist once you have answered 3...Nf6 with 4.Bg5 or 4.cxd5. Pick the move order by which of those you would rather not study.",
             "line": "Nf6 Nc3 Bb4 Bg5 h6"},
            {"san": "cxd5", "severity": "playable", "tier": "Structure",
             "why": "The Exchange one move early, and there is a real difference: Black has not committed the knight to f6 yet. After 3...exd5 4.Nc3 c6 5.Bf4 Bd6 Black offers the trade of your good bishop straight away, and the light-squared bishop can still come to f5 before ...Nf6 shuts it in. The Carlsbad you want is the one where the knight is already on f6.",
             "line": "exd5 Nc3 c6 Bf4 Bd6"},
            {"san": "g3", "severity": "playable", "tier": "Plans",
             "name": "Catalan",
             "why": "The same two pawns, a different bishop. Instead of Bg5 and the fight over d5 you fianchetto and press on the long diagonal for the next forty moves. It is a completely respectable choice and a completely different body of theory.",
             "line": "dxc4 Nf3 c5 Qa4+ Bd7",
             "see": "catalan"},
        ],

        # ── ply 6 · after 3.Nc3 — Black's third move ─────────────────────────────
        "d4 d5 c4 e6 Nc3": [
            {"san": "c5", "severity": "playable", "tier": "Plans",
             "name": "Tarrasch Defence",
             "why": "Black volunteers an isolated d-pawn in exchange for free pieces, which is the opposite bargain to the one in the Declined. The main line is 4.cxd5 exd5 5.Nf3 Nc6 6.g3 — the bishop goes to g2 because the pawn on d5 is the thing you are attacking and g2 is the square that stares at it. Do not treat the isolani as a free pawn; it is a weakness in an endgame and an asset in a middlegame.",
             "line": "cxd5 exd5 Nf3 Nc6 g3"},
            {"san": "c6", "severity": "playable", "tier": "Structure",
             "name": "Triangle / Semi-Slav",
             "why": "Both pawns supporting d5. It is solid, and it costs a moment of flexibility that 4.e4! punishes immediately: 4...dxe4 5.Nxe4 Bb4+ 6.Bd2 and you have the full centre while Black's bishop is out on a square it will be chased from. If you would rather not learn that, 4.Nf3 Nf6 heads into Semi-Slav territory.",
             "line": "e4 dxe4 Nxe4 Bb4+ Bd2",
             "see": "slav"},
            {"san": "Be7", "severity": "playable", "tier": "Structure",
             "name": "Alatortsev Variation",
             "why": "A prophylactic move order: by developing the bishop before the knight, Black makes Bg5 pointless — there is nothing on f6 to pin. Answer 4.cxd5 exd5 5.Bf4 — the bishop still gets outside the pawn chain, just on the other diagonal, and you have the Carlsbad structure you were aiming for.",
             "line": "cxd5 exd5 Bf4 Nf6 e3"},
            {"san": "Bb4", "severity": "playable", "tier": "Mastery",
             "name": "Accelerated Ragozin",
             "why": "Black pins the knight before developing anything else, aiming for a Nimzo-Indian without the Nimzo-Indian move order. 4.cxd5 exd5 5.Bf4 c5 6.dxc5 is a good, concrete answer: you open the position while the bishop on b4 is the only black piece off the back rank.",
             "line": "cxd5 exd5 Bf4 c5 dxc5"},
            {"san": "dxc4", "severity": "playable", "tier": "Structure",
             "why": "Taking a move earlier than in the Accepted, and it costs Black the centre a move earlier too: 4.e4! Nf6 5.Bxc4 and White has both centre pawns abreast with the pawn already recovered. Compare it with the real Accepted, where Black plays ...dxc4 before ...e6 and keeps the option of hitting the centre with ...c5 straight away.",
             "line": "e4 Nf6 Bxc4 c5 Nf3"},
        ],

        # ── ply 7 · your own fourth move — the two doors, Exchange and Classical ─
        "d4 d5 c4 e6 Nc3 Nf6": [
            {"san": "Bg5", "severity": "playable", "tier": "Foundation",
             "name": "Classical Queen's Gambit Declined",
             "why": "The other half of this repertoire: keep the tension, pin the knight, and let Black choose between the Orthodox, the Lasker and the Tartakower. The engine cannot separate it from 4.cxd5 — a few centipawns, and they point the other way if anything — so the real difference is that this costs several times as much theory and gives you a game rather than a plan. Step through the Tartakower line before you play it.",
             "line": "Be7 e3 O-O Nf3 h6 Bh4",
             "see": "queensgambit#tartakower"},
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "name": "Exchange Variation",
             "why": "The Carlsbad, and the reason to play it is not the evaluation — it is that you get one structure and two clear plans in every game, for the price of one afternoon's study. Step through the main line and the deep dive; between them they are most of what you need.",
             "line": "exd5 Bg5 Be7 e3 O-O",
             "see": "queensgambit#exchange"},
            {"san": "Nf3", "severity": "playable", "tier": "Plans",
             "name": "Three Knights Variation",
             "why": "Flexible, and it hands Black the choice: 4...Bb4 is the Ragozin, 4...dxc4 5.e4 Bb4 the Vienna, 4...c5 the Semi-Tarrasch. All three are sound and all three are sharper than what Black gets after 4.Bg5 or 4.cxd5. Play it when you want a game and are willing to learn three more variations.",
             "line": "c5 cxd5 cxd4 Qxd4 exd5"},
            {"san": "Bf4", "severity": "playable", "tier": "Structure",
             "why": "The bishop outside the chain on the other diagonal, avoiding ...h6 and the pin question altogether. It is a real system and it costs about a quarter of a pawn against 4.cxd5, mostly because 4...c5 comes with tempo against d4 while the bishop is no longer helping to hold it.",
             "line": "c5 e3 cxd4 exd4 Be7"},
        ],

        # ── ply 8 · after 4.cxd5 — which piece recaptures ────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5": [
            {"san": "Nxd5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Recapturing with the piece, which lets White have the centre for free: 5.e4! Nxc3 6.bxc3 c5 7.Nf3 and White has pawns on c3, d4 and e4 against nothing in the centre. Notice what it does to the shape of the whole game — with White's b-pawn now on c3 there is no Carlsbad and no minority attack, because there is no b-pawn left to walk up the board.",
             "line": "e4 Nxc3 bxc3 c5 Nf3"},
            {"san": "Qxd5", "severity": "blunder", "tier": "Foundation",
             "why": "The queen takes a pawn that a knight is already looking at. 5.Nxd5 exd5 and count it: pawns level at seven each, and White has a queen for a knight. Winning on move five. This is why the main line insists on 4...exd5 — the difference between the three legal captures on d5 is the entire game.",
             "line": "Nxd5 exd5 e3 Nc6 a3"},
        ],

        # ── ply 10 · after 5.Bg5 in the Exchange ─────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5": [
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "Breaking the pin first and deciding about ...c6 later. It transposes to the main line in almost every case: 6.e3 O-O 7.Bd3 h6 8.Bh4 and Black will still have to play ...c6 to hold d5. Nothing changes about your plan.",
             "line": "e3 O-O Bd3 h6 Bh4"},
            {"san": "Nbd7", "severity": "playable", "tier": "Plans",
             "why": "Sound, common, and the position where the Elephant Trap lives. The knight on f6 looks pinned and it is not: 6.Nxd5?? Nxd5! 7.Bxd8 Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8 and Black is a minor piece for a pawn ahead. Play 6.e3 c6 7.Bd3 and you have the main-line Carlsbad with Black's knight already committed to d7.",
             "line": "e3 c6 Bd3 Be7 Nf3"},
            {"san": "h6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Putting the question one move too early, because the answer is 6.Bxf6! and Black has to take with the g-pawn: 6...gxf6 wrecks the kingside, and 6...Qxf6 7.Nxd5 is simply a pawn. After 6...gxf6 7.e3 White is playing the same minority attack against a king that has no cover — this is the one version of the Carlsbad where you should think about castling long and pushing the h-pawn instead.",
             "line": "Bxf6 gxf6 e3 c6 Bd3"},
            {"san": "c5", "severity": "playable", "tier": "Mastery",
             "why": "The principled try: hit d4 before White is set up, and accept an isolated d-pawn for activity. 6.Bxf6 Qxf6 7.Nxd5 Qd8 8.e4 wins a pawn for a couple of moves and Black gets it back with ...Nc6 and ...cxd4. It is playable; what it is not is the quiet game the rest of this variation is about.",
             "line": "Bxf6 Qxf6 Nxd5 Qd8 e4"},
        ],

        # ── ply 12 · after 6.e3 — the Carlsbad crossroads ────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3": [
            {"san": "Bf5", "severity": "playable", "tier": "Plans",
             "why": "The modern main line, and the whole point of the move order: Black gets the problem bishop outside the chain before ...Be7 shuts it in. The critical answer is 7.Qf3!, hitting f5 and b7 at once through the bishop: 7...Bg6 8.Bxf6 Qxf6 9.Qxf6 gxf6 and Black's structure is damaged but the position is close to level.",
             "line": "Qf3 Bg6 Bxf6 Qxf6 Qxf6 gxf6"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Now the question is fair, because 7.Bxf6 Qxf6 costs White nothing and gains Black nothing — the d5-pawn is defended by the c6-pawn, so there is no Nxd5 to follow up with. Play 7.Bh4 and carry straight on with the plan; the pawn on h6 will be a hook if you ever switch to the kingside.",
             "line": "Bh4 Be7 Bd3 O-O Nge2"},
            {"san": "Nbd7", "severity": "playable", "tier": "Foundation",
             "why": "The main-line knight, one move early. 7.Bd3 Be7 8.Nf3 and you are back in the same position by a different road. There is nothing to punish and no reason to change plan.",
             "line": "Bd3 Be7 Nf3 O-O Qc2"},
            {"san": "Na6", "severity": "inaccuracy", "tier": "Structure",
             "why": "The knight heads for c7 to defend the coming weakness, and it wrecks the structure getting there: 7.Bxa6! bxa6 and Black has doubled, isolated a-pawns. Be honest about the trade — Black gets the half-open b-file for a rook and you have given up the good bishop — but a6, a7 and c6 are three pawns that can never defend each other, and you no longer need a minority attack to make them weak. Ne2, O-O and Rfc1, then aim at c6.",
             "line": "Bxa6 bxa6 Nf3 Bd6 Rb1"},
        ],

        # ── ply 14 · after 7.Bd3 ────────────────────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3": [
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Castling first and deciding about the knight later. 8.Nge2 Nbd7 9.Qc2 and you are in the main line one move order over. Nothing about the Carlsbad plan depends on which of these Black plays first.",
             "line": "Nge2 Nbd7 Qc2 Re8 O-O"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Same idea, same answer. 8.Bh4 keeps the pin, and 8.Bf4 is the other treatment worth knowing: the bishop swings to the b8–h2 diagonal, where it eyes the squares the minority attack is aiming at instead of the knight it can no longer usefully pin.",
             "line": "Bf4 O-O h3 Bd6 Nge2"},
            {"san": "Ne4", "severity": "playable", "tier": "Plans",
             "why": "The freeing manoeuvre, and it changes the whole game: 8.Bf4! Nxc3 9.bxc3 and White's b-pawn is now on c3. It is still two queenside pawns against three, but they are a2 and c3 — there is no b-pawn left to push, so the minority attack is dead and the plan switches to f3 and e3–e4 with the b-file half-open for a rook. Trading knights is how Black gets rid of the plan; it is not how Black gets rid of the problem.",
             "line": "Bf4 Nxc3 bxc3 Nd7 Nf3"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "why": "The modern anti-Carlsbad setup: the bishop is coming to f5 with the g-pawn covering it, and the kingside light squares are Black's to keep. It is sound. 8.Nge2 Nbd7 9.Qc2 and get on with the queenside, but note that Bxh7 tricks are gone for the rest of the game.",
             "line": "Nge2 Nbd7 Qc2 Nf8 O-O"},
            {"san": "Bf5", "severity": "blunder", "tier": "Foundation",
             "why": "One move too late. The bishop belonged on f5 before ...Be7 and White's bishop reached d3 — now 8.Bxf5 wins it outright, because nothing on the board can recapture. Sequence matters more than square: ...Bf5 is the modern main line at move six and a piece at move seven.",
             "line": "Bxf5 Nbd7 Nf3"},
        ],

        # ── ply 16 · after 8.Qc2 ────────────────────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2": [
            {"san": "Nh5", "severity": "playable", "tier": "Mastery",
             "why": "The engine's own first choice here, and the reason is precise: with the black king still on e8 there is no Bxh7+ to punish the knight leaving f6. 9.Bxe7 Qxe7 10.Nge2 g6 11.O-O and Black has traded the pinning bishop and blunted the b1–h7 diagonal in two moves. The same move one ply later, after Black has castled, loses a pawn.",
             "line": "Bxe7 Qxe7 Nge2 g6 O-O"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Asking the question with everything else in place, which is the right moment for it. 9.Bh4 and continue: Nge2, O-O, Rab1, b4. Black's ...h6 costs nothing now and may cost something in thirty moves.",
             "line": "Bh4 O-O Nge2 Re8 O-O"},
            {"san": "Nf8", "severity": "playable", "tier": "Structure",
             "why": "The knight sets off for e6 before castling. It is playable and it is slow — 9.Nge2 Ne6 10.Bh4 O-O 11.O-O and White has completed the whole setup while Black moved one knight twice. Take the free moves and start the pawns.",
             "line": "Nge2 Ne6 Bh4 O-O O-O"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "why": "The light-square setup again, this time with the bishop still on c8. 9.Nf3 Nf8 10.Bf4 heads for e5 — with the pawn on g6 and the knight coming to e6, the dark squares round Black's king are the ones nobody is watching.",
             "line": "Nf3 Nf8 Bf4 Bd6 Be5"},
        ],

        # ── ply 18 · after 9.Nge2 — the h7 tactic appears ────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2": [
            {"san": "Nh5", "severity": "blunder", "tier": "Structure",
             "why": "The same manoeuvre as one move ago, played one move too late — and now the king is on g8. 10.Bxe7 Qxe7 11.Bxh7+! and the pawn is simply gone: 11...Kh8 12.Bd3 and White is a clean pawn up with the bishop safe. The knight on f6 is not a developing piece in this structure, it is the guard on h7, and the battery on b1–h7 has been aimed at it since move eight.",
             "line": "Bxe7 Qxe7 Bxh7+ Kh8 Bd3"},
            {"san": "Ne8", "severity": "inaccuracy", "tier": "Structure",
             "why": "The same problem by a different route. 10.Bxh7+! Kh8 11.Bxe7 Qxe7 12.Bd3 and White has won a pawn, because the knight left f6 and nothing replaced it. Whenever you consider moving that knight, look at d3 first.",
             "line": "Bxh7+ Kh8 Bxe7 Qxe7 Bd3"},
            {"san": "a5", "severity": "playable", "tier": "Plans",
             "why": "The best practical answer to the whole plan: Black takes b4 away, so b2–b4 costs a pawn and a4 costs a tempo. Do not force it. 10.O-O h6 11.Bh4 and switch — Rae1, f3 and e3–e4 is the second plan in this structure, and Black has just spent a move making the first one harder.",
             "line": "O-O h6 Bh4 b5 Rac1"},
            {"san": "h6", "severity": "playable", "tier": "Foundation",
             "why": "Fine, and it even helps: with the pawn on h6 the Bxh7 tricks are off for good, which is what Black should want before starting anything on the kingside. 10.Bh4 Re8 11.O-O and both sides get on with it.",
             "line": "Bh4 Re8 O-O"},
        ],

        # ── ply 22 · after 11.Rab1 — the deep dive's position ────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8 Rab1": [
            {"san": "a5", "severity": "playable", "tier": "Plans",
             "why": "The move that stops the plan, and the engine calls it Black's best. b4 is off, a4 achieves nothing, and the answer is to change plan rather than argue: 12.Rbe1 Bd7 13.h3 and White regroups for f3 and e4. That is what the knight on e2 was for, and it is why you should never think of the minority attack as the only idea in this structure.",
             "line": "Rbe1 Bd7 h3 Rc8 Rc1"},
            {"san": "Ne6", "severity": "inaccuracy", "tier": "Structure",
             "why": "The natural square, and it costs a pawn to a two-move trick: 12.Bxf6! Bxf6 13.Bxh7+ Kf8 14.Bd3 and White is a pawn up. Once the knight leaves f8 for e6 rather than g6, nothing covers h7 but the king, and the trade on f6 removes the last piece that did.",
             "line": "Bxf6 Bxf6 Bxh7+ Kf8 Bd3"},
            {"san": "Be6", "severity": "playable", "tier": "Structure",
             "why": "Developing the last piece toward the queenside, where the trouble is coming from. 12.b4 Rc8 13.a4 and the plan runs anyway — the bishop on e6 defends nothing that b5 attacks, because the pawn White is aiming at is c6 and it will be defended by pieces, not by this one.",
             "line": "b4 Rc8 a4 Bg4 h3"},
        ],

        # ══ THE CLASSICAL: 4.Bg5 ════════════════════════════════════════════════

        # ── ply 8 · after 4.Bg5 ────────────────────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 Bg5": [
            {"san": "Nbd7", "severity": "playable", "tier": "Plans",
             "name": "Cambridge Springs move order",
             "why": "Black offers d5 as bait and it is poisoned: 5.cxd5 exd5 6.Nxd5?? Nxd5! 7.Bxd8 Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8 is the Elephant Trap, a minor piece for a pawn. Play 5.e3 c6 6.Nf3 and Black's real idea appears: 6...Qa5, the Cambridge Springs. Know exactly why it is annoying — the queen on a5 pins the knight on c3 against the king on e1, so ...Ne4 comes next and hits the pinned knight and the bishop on g5 at the same time. Meet it with 7.cxd5.",
             "line": "e3 c6 Nf3 Qa5 cxd5"},
            {"san": "h6", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Too early, for the usual reason: 5.Bxf6! and neither recapture is comfortable. 5...Qxf6 6.cxd5 exd5 7.e3 leaves Black's queen misplaced on f6, and 5...gxf6 shatters the kingside for a bishop pair Black cannot yet use. This is a move to play once ...Be7 and ...O-O are in, not before.",
             "line": "Bxf6 gxf6 cxd5 exd5 e3"},
            {"san": "c6", "severity": "playable", "tier": "Structure",
             "why": "The Semi-Slav triangle, and a real choice of opening rather than a mistake. Black keeps both pawns behind d5 and prepares ...dxc4 followed by ...b5. 5.e3 Nbd7 6.Nf3 and you are in Semi-Slav territory, which is the most theory-heavy corner of the whole 1.d4 world.",
             "line": "e3 Nbd7 Nf3 Qa5 cxd5",
             "see": "slav"},
            {"san": "c5", "severity": "playable", "tier": "Mastery",
             "why": "Hitting d4 while the bishop on g5 is not helping to hold it. 5.cxd5 cxd4 6.Qxd4 Be7 7.e4 and White has the centre, a lead in development and, for the moment, an extra pawn on d5 — 7...exd5 8.Bb5+! is the move that keeps hold of something. Black gets the open c-file and active pieces for it, and the engine puts the whole thing within a quarter of a pawn of the main line. Sharp and sound: do not go into it expecting a refutation.",
             "line": "cxd5 cxd4 Qxd4 Be7 e4"},
            {"san": "dxc4", "severity": "playable", "tier": "Mastery",
             "why": "The pawn grab with the pin already in — the same idea as the Vienna, without White's knight on f3. Take the centre rather than chase the pawn: 5.e3 c5 6.Bxf6 Qxf6 7.d5! and Black has a wedge to deal with before there is time to think about holding c4.",
             "line": "e3 c5 Bxf6 Qxf6 d5"},
        ],

        # ── ply 10 · after 5.e3 ────────────────────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3": [
            {"san": "h6", "severity": "playable", "tier": "Structure",
             "why": "Asking the question before castling. Now 6.Bxf6 Bxf6 is a real option and it is the engine's choice: Black gets the bishop pair, White gets a free hand and a small pull after 7.Nf3 O-O 8.Rc1. The Lasker and Tartakower lines both start with this move one ply later; playing it now simply removes White's option of 6.Nf3 first.",
             "line": "Bxf6 Bxf6 Nf3 O-O Rc1"},
            {"san": "Nbd7", "severity": "playable", "tier": "Foundation",
             "name": "Orthodox move order",
             "why": "The classical setup: both knights out, then ...c6 and ...dxc4 with the Capablanca freeing manoeuvre ...Nd5 to follow. 6.Nf3 O-O 7.Qc2 and White carries on. It is the most-played black system in the whole opening's history and it is completely sound; it is also completely passive, which is why the Tartakower replaced it.",
             "line": "Nf3 O-O Qc2 h6 Bh4"},
            {"san": "Ne4", "severity": "playable", "tier": "Plans",
             "name": "Lasker idea, one move early",
             "why": "The freeing knight, before White has castled or developed the king's knight. 6.Bxe7 Qxe7 7.Rc1 Nf6 8.Nf3 and Black has spent two knight moves to trade one pair of bishops, which is exactly the Lasker bargain — a shade slower here, because the knight has to come back to f6 rather than trade itself off on c3.",
             "line": "Bxe7 Qxe7 Rc1 Nf6 Nf3"},
        ],

        # ── ply 12 · after 6.Nf3 ────────────────────────────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3": [
            {"san": "Nbd7", "severity": "playable", "tier": "Foundation",
             "name": "Orthodox Defence",
             "why": "The main line of the whole opening for fifty years. Black completes development and waits, then frees with ...c6, ...dxc4 and ...Nd5. Answer 7.Qc2 h6 8.Bh4 c5 9.dxc5 and note the trade you are aiming for: Black's freeing moves all cost time, and time is the only edge this variation offers you.",
             "line": "Qc2 h6 Bh4 c5 dxc5"},
            {"san": "b6", "severity": "playable", "tier": "Structure",
             "why": "The Tartakower without ...h6, which saves a tempo and leaves the pin in place. 7.Rc1 Bb7 8.cxd5 Nxd5 9.Nxd5 gives you the same structure as the main line with your bishop still on g5 — a small extra for White, and the reason ...h6 is normally played first.",
             "line": "Rc1 Bb7 cxd5 Nxd5 Nxd5"},
            {"san": "dxc4", "severity": "playable", "tier": "Structure",
             "why": "Releasing the tension to free the position, and the price is the centre: 7.Bxc4 c5 8.dxc5 Qxd1+ 9.Rxd1 and the queens are off with White a shade better placed. Perfectly playable — this is how a lot of club games in the Declined actually go.",
             "line": "Bxc4 c5 dxc5 Qxd1+ Rxd1"},
        ],

        # ── ply 14 · after 7.Bh4 — the two great defences ────────────────────────
        "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4": [
            {"san": "Ne4", "severity": "playable", "tier": "Plans",
             "name": "Lasker Defence",
             "why": "The most solid defence in the Queen's Gambit, and the engine cannot separate it from the Tartakower. Black trades pieces off until the cramp is gone: 8.Bxe7 Qxe7 9.Rc1 c6 10.Bd3 Nxc3 11.Rxc3 and Black has one problem left, the c8-bishop, and a plan to solve it with ...dxc4 and ...b6. Play for a slow squeeze; there is nothing sharp here.",
             "line": "Bxe7 Qxe7 Rc1 c6 Bd3"},
            {"san": "Nbd7", "severity": "playable", "tier": "Foundation",
             "why": "The Orthodox with ...h6 thrown in. 8.Rc1 c5 9.dxc5 Nxc5 10.cxd5 and the tension resolves into a position where Black's pieces are active and White's structure is the sounder — a normal, playable Queen's Gambit middlegame.",
             "line": "Rc1 c5 dxc5 Nxc5 cxd5"},
            {"san": "dxc4", "severity": "playable", "tier": "Structure",
             "why": "The simplifying route again. 8.Bxc4 c5 9.dxc5 Qxd1+ 10.Rxd1 and it is an endgame on move ten with a tiny pull for White. If you play the Queen's Gambit for a fight this is the line that will frustrate you, and there is nothing to be done about it.",
             "line": "Bxc4 c5 dxc5 Qxd1+ Rxd1"},
        ],

        # ══ THE ACCEPTED ═══════════════════════════════════════════════════════

        # ── ply 5 · after 2...dxc4 — how to take the pawn back ───────────────────
        "d4 d5 c4 dxc4": [
            {"san": "e4", "severity": "playable", "tier": "Plans",
             "name": "Central Variation",
             "why": "The most ambitious move: take the whole centre now and worry about the pawn later. 3...e5 is the critical reply and after 4.Nf3 exd4 5.Bxc4 Nc6 White has the pawn back and a sharp game. The engine rates it dead level with 3.Nf3; the difference is that it is a theoretical fight from move four instead of a positional squeeze from move ten.",
             "line": "e5 Nf3 exd4 Bxc4 Nc6"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "why": "The straightforward recovery, and the move that makes the famous trap possible: 3...b5?? 4.a4 c6 5.axb5 cxb5 6.Qf3! and the two captures have cleared c6 and b7, so the queen sees the rook on a8 — 6...Nc6 7.Qxc6+ wins a piece. What e3 costs you is that 3...e5 becomes available: 4.Bxc4 exd4 5.exd4 and you are close to level with an isolated d-pawn, since your c-pawn went on move two and your e-pawn has just gone on move five.",
             "line": "e5 Bxc4 exd4 exd4 Bd6"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "Development, and the one third move that does not really fight for the pawn: 3...a6 4.e3 b5 and Black hangs on to it for several moves, because a2–a4 now runs into 5...b4 hitting the knight — the break arrives with tempo for Black instead of against them. 6.Bxc4 recovers it anyway and the position is close to level, which is the point: this is a slower road to the same place.",
             "line": "a6 e3 b5 a4 b4"},
            {"san": "Qa4+", "severity": "playable", "tier": "Mastery",
             "why": "Winning the pawn back immediately and paying for it with the queen's position: 3...Nd7 4.Nf3 c6 5.Qxc4 e5 and Black gets the centre for free while your queen has been the only piece to move twice. At depth twenty this is the one third move here that gives Black a comfortable game, so treat it as a sideline rather than a shortcut.",
             "line": "Nd7 Nf3 c6 Qxc4 e5"},
        ],

        # ── ply 6 · after 3.Nf3 — Black's third move ─────────────────────────────
        "d4 d5 c4 dxc4 Nf3": [
            {"san": "a6", "severity": "playable", "tier": "Plans",
             "name": "Alekhine Variation",
             "why": "The modern move order: ...a6 first, so that ...b5 is a threat before you have decided where the bishop goes. 4.e3 e6 5.Bxc4 c5 6.O-O transposes straight back to the main line. If you prefer to stop ...b5 for good, 4.a4 is the move, at the cost of the b4 square.",
             "line": "e3 e6 Bxc4 c5 O-O"},
            {"san": "c5", "severity": "playable", "tier": "Structure",
             "why": "Hitting d4 before developing, which lets White close the centre: 4.d5! Nf6 5.Nc3 e6 6.e4 and White has a big space advantage in a Benoni-flavoured position. The pawn on c4 will fall in due course; the space will not.",
             "line": "d5 Nf6 Nc3 e6 e4"},
            {"san": "b5", "severity": "playable", "tier": "Structure",
             "why": "Trying to hold the pawn, and here it is merely a poor move rather than a losing one — this is the position where knowing the difference matters. 4.a4 c6 5.axb5 cxb5 6.Nc3 hits b5, and the 6.Qf3 that wins a rook after 3.e3 is here not merely bad but illegal — your own knight is standing on f3. Black keeps the pawn for a while and gets a queenside full of holes for it.",
             "line": "a4 c6 axb5 cxb5 Nc3"},
            {"san": "Be6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Defending the pawn with a piece, which is a plan until you notice the piece can be attacked. 4.Nc3 g6 5.Ng5! and the bishop has to move again or be traded on terms Black did not choose: 5...Bd7 6.e4 and White has the full centre and every piece coming, while Black has spent three moves nursing a pawn on c4. The engine calls it about a pawn's worth of trouble for a pawn Black was never going to keep.",
             "line": "Nc3 g6 Ng5 Bd7 e4"},
            {"san": "Nc6", "severity": "playable", "tier": "Foundation",
             "why": "Developing to the square that gets kicked: 4.d5! Nb8 5.e4 and the knight goes home while White builds the centre with tempo. Not a disaster, but two of Black's first five moves have now been spent on the same knight.",
             "line": "d5 Nb8 e4 e6 Bxc4"},
            {"san": "e5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The break Black wants, one move too early — 3.Nf3 was played precisely to stop it. 4.Nxe5! and Black cannot have both pawns: 4...Nd7 5.Nxc4 and White has recovered the gambit pawn and kept the e-pawn too, seven against six. This is the concrete reason 3.Nf3 is the main move.",
             "line": "Nxe5 Nd7 Nxc4"},
        ],

        # ── ply 8 · after 4.e3 ─────────────────────────────────────────────────
        "d4 d5 c4 dxc4 Nf3 Nf6 e3": [
            {"san": "Bg4", "severity": "playable", "tier": "Structure",
             "why": "Developing the problem bishop before ...e6 locks it in, at the cost of a little time. 5.Bxc4 e6 6.Nc3 Nc6 7.h3 asks the question with the bishop already committed, and after ...Bh5 you have a target for a later g2–g4 once your king is safe.",
             "line": "Bxc4 e6 Nc3 Nc6 h3"},
            {"san": "a6", "severity": "playable", "tier": "Foundation",
             "why": "The same Alekhine idea, one move later, and just as good: 5.Bxc4 c5 6.O-O and you are in the main line with the moves in a different order. Play a4 when you want to stop ...b5 and not before.",
             "line": "Bxc4 c5 O-O"},
            {"san": "Be6", "severity": "playable", "tier": "Structure",
             "why": "Holding the pawn one more move. 5.Nc3 c6 6.Ng5! is the same idea as on move three and it works for the same reason: the bishop has nothing behind it and no way to be defended. Black usually gives the pawn back, having spent two tempi on it.",
             "line": "Nc3 c6 Ng5"},
            {"san": "b5", "severity": "playable", "tier": "Mastery",
             "why": "The modern pawn-holding try, which has been rehabilitated over the last few years and is not a mistake. 5.a4 c6 6.b3! is the point: instead of forcing matters on the a-file, White undermines from the other side and takes the pawn back with a healthy position. Do not try to punish it; treat it as a real line.",
             "line": "a4 c6 b3"},
        ],

        # ── ply 10 · after 5.Bxc4 ──────────────────────────────────────────────
        "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4": [
            {"san": "a6", "severity": "playable", "tier": "Foundation",
             "why": "Preparing ...b5 before ...c5. 6.O-O c5 7.dxc5 Bxc5 8.Qxd8+ Kxd8 is the honest line: an equal endgame where Black's king has lost the right to castle but is perfectly safe. If you want more than that, 7.Be2 keeps the queens on.",
             "line": "O-O c5 dxc5 Bxc5 Qxd8+"},
            {"san": "Nc6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Developing to a square that blocks the pawn Black needs to move. Without ...c5 the whole point of the Accepted is gone, and 6.Nc3 Bb4 7.a3 Bxc3+ 8.bxc3 leaves White with the bishop pair and pawns on c3, d4 and e3. Notice what it does not cost you: nothing is doubled, because your own c-pawn came off the board on move two. Half a pawn's worth, and more than that in practice.",
             "line": "Nc3 Bb4 a3 Bxc3+ bxc3"},
            {"san": "b5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Grabbing space at the bishop it is meant to be chasing. 6.Bxb5+! and it is a clean pawn: 6...c6 7.Be2 and the bishop is home with an extra pawn in the bank, because b5 was defended by nothing at all. Count the defenders before you advance a pawn next to a bishop's diagonal.",
             "line": "Bxb5+ c6 Be2 Be7 b3"},
        ],

        # ── ply 12 · after 6.O-O ───────────────────────────────────────────────
        "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O": [
            {"san": "Nc6", "severity": "playable", "tier": "Foundation",
             "why": "Developing first and keeping ...a6 in hand. 7.Qe2 a6 8.Nc3 and the game transposes toward the main line; the difference is that with the knight already on c6 you can consider 8.dxc5 and an early queen trade instead.",
             "line": "Qe2 a6 Nc3"},
            {"san": "cxd4", "severity": "playable", "tier": "Plans",
             "why": "Handing over the isolated d-pawn immediately and starting to blockade it. 7.exd4 Be7 8.Nc3 O-O 9.Re1 and you have the structure the plan card describes — the difference from the main line is that a2–a4 has not been played, so ...b5 and ...Bb7 are still available to Black.",
             "line": "exd4 Be7 Nc3 O-O Re1",
             "see": "structure#isolani"},
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "Developing and castling before touching the centre. 7.Nc3 O-O 8.e4! is the move to remember: with Black not yet pressing on d4, White is allowed to build the full centre instead of settling for the isolani.",
             "line": "Nc3 O-O e4 cxd4 Nxd4"},
        ],

        # ── ply 14 · after 7.a4 ────────────────────────────────────────────────
        "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4": [
            {"san": "cxd4", "severity": "playable", "tier": "Plans",
             "why": "Taking at once, which is what the engine likes. 8.exd4 Nc6 9.Re1 Be7 10.Nc3 is the isolani with your rook on e1 rather than d1 — a matter of taste, and both are main lines. The plan is the same: c5 and e5 for the knights, d4–d5 when the guard leaves.",
             "line": "exd4 Nc6 Re1 Be7 Nc3"},
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "Development first. 8.Qe2 cxd4 9.Rd1 Nc6 10.exd4 O-O is the main line again by transposition — Black has simply chosen the order of ...Be7 and ...Nc6.",
             "line": "Qe2 cxd4 Rd1 Nc6 exd4"},
            {"san": "b6", "severity": "playable", "tier": "Structure",
             "why": "The other plan: the bishop goes to b7 and Black plays against d5 and e4 rather than against d4. 8.Nc3 Bb7 9.e4! cxd4 10.Nxd4 and White takes the centre while the bishop on b7 is still looking at a pawn.",
             "line": "Nc3 Bb7 e4 cxd4 Nxd4"},
            {"san": "b5", "severity": "blunder", "tier": "Foundation",
             "why": "The move a4 was played to prevent, and it loses material on the spot. 8.axb5! and the a-file is fatal: 8...axb5?? 9.Rxa8 wins a whole rook, because nothing on the board can recapture on a8. Black has to play 8...cxd4 9.exd4 and be a clean pawn down instead. This is the concrete payoff for a4 that the main line's note is about.",
             "line": "axb5 cxd4 exd4 Bb4 Nc3"},
        ],

        # ── ply 16 · after 8.Qe2 ───────────────────────────────────────────────
        "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4 Nc6 Qe2": [
            {"san": "Qc7", "severity": "playable", "tier": "Plans",
             "why": "The most testing answer, and the one Kramnik faced from Sadvakasov in 2001. Black keeps the tension and eyes the b8–h2 diagonal. The reply that keeps an edge is 9.Rd1 Bd6 10.dxc5! — you decline the isolani, because with the queen on c7 and the bishop coming to d6 Black would get real play against h2. Step through the model game from here.",
             "line": "Rd1 Bd6 dxc5 Bxc5 b3",
             "see": "queensgambit#kramnik-sadvakasov-2001"},
            {"san": "Be7", "severity": "playable", "tier": "Foundation",
             "why": "Solid, and it lets you choose the structure: 9.dxc5! O-O 10.Rd1 and instead of the isolani you have an extra pawn on c5 that Black must spend a move to win back, with your pieces already placed.",
             "line": "dxc5 O-O Rd1"},
            {"san": "Bd6", "severity": "playable", "tier": "Structure",
             "why": "The active square, aiming at h2. 9.dxc5 Bxc5 10.e4! and the centre pawns roll: e4–e5 gains a tempo on the knight and opens the diagonal your bishop on c4 has been sitting on since move five.",
             "line": "dxc5 Bxc5 e4 Qc7 e5"},
            {"san": "b5", "severity": "blunder", "tier": "Foundation",
             "why": "Same idea, same refutation, one move later and worse: 9.axb5! and now the knight on c6 hangs as well. 9...Na5 10.Bd3 axb5 11.bxa6 and Black is a pawn down with a knight on the rim and the a-file wide open toward the rook. Once a4 is on the board, ...b5 needs preparation that Black does not have time for.",
             "line": "axb5 Na5 Bd3 Be7 bxa6"},
        ],
    },
    "games": [
        {
            "id": 'botvinnik-keres-1952',
            "name": "Botvinnik – Keres, USSR Championship 1952 — the Carlsbad's other plan",
            "tier": 'Structure',
            "note": "The most famous Carlsbad game ever played, and it reaches the main line's final position exactly — by a different move order, with Keres playing 1...Nf6 first. Then Botvinnik does not play the minority attack at all. He plays Kh1, f3 and e3–e4, and the reason the rook on b1 came back to e1 on move fourteen is the whole lesson: the structure offers two plans and you pick the one Black is not watching.",
            "moves": (
                'd4 Nf6 c4 e6 Nc3 d5 cxd5 exd5 Bg5 Be7 e3 O-O Bd3 Nbd7 Qc2 Re8 '
                'Nge2 Nf8 O-O c6 Rab1 Bd6 Kh1 Ng6 f3 Be7 Rbe1 Nd7 Bxe7 Rxe7 '
                'Ng3 Nf6 Qf2 Be6 Nf5 Bxf5 Bxf5 Qb6 e4 dxe4 fxe4 Rd8 e5 Nd5 '
                'Ne4 Nf8 Nd6 Qc7 Be4 Ne6 Qh4 g6 Bxd5 cxd5 Rc1 Qd7 Rc3 Rf8 '
                'Nf5 Rfe8 Nh6+ Kf8 Qf6 Ng7 Rcf3 Rc8 Nxf7 Re6 Qg5 Nf5 Nh6 Qg7 g4'
            ),
            "notes": {
                7: "The Exchange, out of a 1...Nf6 move order. Keres never played ...d5 until move three, and it makes no difference at all — the Carlsbad is a structure, and structures do not care how you reached them.",
                21: "Move eleven, and this is the identical position to the one the main line ends on — reached by a completely different move order. Everything you drilled is now on the board in a USSR Championship game between the world champion and the man who nearly was.",
                23: "Not b4. Botvinnik tucks the king away first, and this modest move is the announcement that the plan has changed: Kh1 makes sense only if the f-pawn is about to advance.",
                25: "There it is. f3 prepares e3–e4 — and it is available at all only because the knight went to e2 on move nine instead of f3. One decision on move nine bought this plan on move thirteen.",
                27: "The rook goes back. It came to b1 to support two pawns that never moved, and now it backs the e-pawn instead. Changing your mind is not the same as having no plan — and it is only cheap because pawns were never committed.",
                31: "The knight takes the route that e2 was chosen for: e2–g3, heading for f5. Both sides have been re-routing knights toward the kingside for ten moves, and White gets there first.",
                35: "The knight lands on f5, where no pawn can ever touch it — Black's e-pawn has been standing on d5 since move four. That square is a permanent gift from the Exchange Variation, and it is the reason White's knight goes on the tour at all.",
                39: "The break, on move twenty. Seven moves of preparation for one pawn push, and count the support first: the knight on c3, the pawn on f3 and the bishop on f5 all bear on e4. Then look at what Black's ...dxe4 21.fxe4 does — it takes White's f-pawn off and hands the rook on f1 a half-open file pointing at f7.",
                43: "e5 comes with tempo, which is what makes it all work: the knight on f6 has to move, and that is the free move White needs to bring the other knight to e4.",
                47: "The knight lands on d6, supported by the pawn on e5. From there it covers b7, c8, e8 and f7 — the four squares Black's pieces need. Only the rook on d8 attacks it, so taking it costs the exchange, and no black pawn can ever chase it: the c-pawn is on c6 and the e-pawn came off on move four.",
                53: "Bxd5 trades the bishop for the knight that was the last black piece covering f6, and it leaves an isolated pawn on d5 into the bargain. The pawn is not the point. Count f6 after 27...cxd5: three white attackers — the pawn on e5, the rook on f1 and the queen on h4 — and no black defender at all.",
                63: "Qf6, and the queen settles on the square Bxd5 emptied. Rcf3 and Nxf7 are both coming and Black cannot meet both; Keres played on for five more moves.",
                73: "g4 and Keres resigned. Count f5: four white attackers — the rook on f3, this pawn, the queen on g5 and the knight on h6 — against one defender, the pawn on g6. And count what won the game: one pawn break on move twenty, and a plan chosen on move twelve because it was the one Black had not prepared for.",
            },
        },
        {
            "id": 'kramnik-sadvakasov-2001',
            "name": "Kramnik – Sadvakasov, Astana 2001 — the Accepted, punished",
            "tier": 'Plans',
            "note": "Eight moves of the drilled line, and then Sadvakasov chose 8...Qc7 instead of 8...cxd4. Kramnik answered by declining the isolated pawn altogether — 10.dxc5 — and won in twenty-one moves against a 2585-rated grandmaster. Worth studying for the move-ten decision more than for the attack that follows it.",
            "moves": (
                'd4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4 Nc6 Qe2 Qc7 '
                'Rd1 Bd6 dxc5 Bxc5 b3 O-O Bb2 e5 Nc3 e4 Ng5 Bd6 Nd5 Nxd5 '
                'Rxd5 Bxh2+ Kh1 Be5 Qh5 Bf5 Nxf7 Rxf7 Qxf5 g6 Bxe5'
            ),
            "notes": {
                13: "a4, exactly as in the main line, and for exactly the same reason: ...b5 is Black's main source of queenside play and this stops it dead.",
                16: "The deviation. Black keeps the tension and puts the queen on the b8–h2 diagonal, which is a real idea — with a bishop coming to d6 the pawn on h2 becomes a genuine target.",
                19: "And this is the answer. Kramnik declines the isolated d-pawn: with the queen on c7 the isolani version would hand Black a target and a diagonal at the same time. Taking on c5 leaves a symmetrical structure where White is simply better developed.",
                21: "b3 and Bb2, the quiet setup. Nothing is threatened, and the bishop takes the long diagonal — a1 to h8, through the centre to g7 and h8, the two squares beside the black king. Kramnik does not make a threat for five more moves.",
                24: "Black grabs the centre. It is the natural move and it is the mistake: ...e5 and ...e4 leave a hole on d5 that a white knight lands on three moves later, and with no c-pawn and no d-pawn Black has nothing left that can ever chase it away.",
                26: "e4 attacks the knight on f3 and gains nothing by it — 14.Ng5 and the knight is on a better square than it left, eyeing e4, e6 and f7 all at once.",
                29: "Nd5, into the hole. The knight cannot be taken by a pawn and cannot be driven away by one either.",
                32: "Bxh2+ is the pawn Black has been eyeing since move eight, and it is the losing move. Count the pieces near the black king before you take on the other side of the board: White has a queen, a rook, a knight and two bishops within two moves of it.",
                35: "Qh5 puts a second attacker on h7 beside the knight on g5, against the king alone. Sadvakasov found the only move that adds a defender without opening the king — 18...Bf5 — and it walks straight into the next one.",
                37: "Nxf7! A genuine offer — 19...Rxf7 is legal and it is what Black played. Be exact about what it buys: after 20.Qxf5 the material is dead level again, and Black's problem is that the bishop on e5 and the queen on c7 are now standing on the same diagonal as the bishop on b2.",
                41: "Bxe5 and Sadvakasov resigned. Both queens are attacked; after 21...gxf5 22.Bxc7 White is a bishop ahead with an easy technical win, and every other move loses more than that.",
            },
        },
    ],
    "progression": {
        "arc": "The Queen's Gambit is the best strategic education in chess. Learn it and you will understand pawn structures for the rest of your life.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to two",
                "goal": "Know why the pawn cannot be held and get a healthy position against each defence.",
                "learn": [
                    "Why 2...dxc4 does not win a pawn: after 3.e3 b5? 4.a4 c6 5.axb5 cxb5 6.Qf3! the two captures have emptied c6 and b7 and the rook on a8 is hanging on the long diagonal.",
                    "Your basic setup against the Declined: Nc3, Bg5, e3, Bd3, Qc2, Nge2, O-O. Nearly the same seven moves every game.",
                    "The three defences you will actually face: 2...e6 (Declined), 2...c6 (Slav), 2...dxc4 (Accepted).",
                ],
                "drill": "Play twenty games with the Exchange Variation. One structure, one plan, endless repetition — this is the fastest way to improve at chess.",
                "mistake": "Playing cxd5 at random. The Exchange is a commitment: you get a clear plan and Black gets the e-file and a free hand on the kingside.",
                "ready": "You can set up the seven-move scheme against any Black move order.",
            },
            {
                "tier": "Structure",
                "when": "Weeks three to eight",
                "goal": "Master the Carlsbad structure. It is the single most valuable structure in chess.",
                "learn": [
                    "The pawn skeleton, and what is missing from it: neither side has a c-pawn on its own file. White has a2 and b2 against Black's a7, b7 and c6 — two against three, which is where the name comes from.",
                    "Why White plays on the queenside and Black on the kingside: your pawns point that way, and pawns decide where you attack.",
                    "The knight to e2 rather than f3 — it keeps f3 free for the pawn and lets the knight go to g3 or f4.",
                ],
                "drill": "Set up the Carlsbad and play only the minority attack: b4, a4, b5, bxc6. Do it ten times. Feel how the backward c-pawn appears.",
                "mistake": "Starting the minority attack before your pieces are placed. Rab1 and Qc2 come first, then the pawns.",
                "ready": "You can draw the Carlsbad structure from memory and name both sides' plans.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Learn the plans available in the Carlsbad and how to choose between them.",
                "learn": [
                    "Plan A, the minority attack (b4–b5) — the workhorse, and the one the deep dive walks through move by move.",
                    "Plan B, the central break f3 and e3–e4 — Botvinnik's choice in the model game, and the right one when Black has stopped b4 with ...a5.",
                    "Plan C, piece pressure on the c-file with Rc1, Na4 and Nc5, once bxc6 has made c6 a target.",
                ],
                "drill": "Take the position after 11.Rab1 and play each plan once against an engine. Note which one it defends worst.",
                "mistake": "Switching plans halfway through the pawn moves. Pieces can change their minds; pawns cannot come back.",
                "ready": "You choose your plan based on where Black's pieces are, not on habit.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Cover the whole 1.d4 d5 landscape and the resulting endgames.",
                "learn": [
                    "The Queen's Gambit Accepted, including the isolated-queen's-pawn positions that come with it.",
                    "The Slav and Semi-Slav — you will face them constantly, and the Meran and Botvinnik lines are theory-heavy.",
                    "Rook endgames with a backward pawn on a half-open file. Most Carlsbad games end there.",
                ],
                "drill": "Study twenty of Botvinnik's or Karpov's Carlsbad games. Cover the moves and guess each one.",
                "mistake": "Neglecting the Slav because the Declined is more common in books. In practice the Slav is everywhere.",
                "ready": "You have a prepared answer to 2...e6, 2...c6, 2...dxc4 and 2...Nf6.",
            },
        ],
        "study": "Capablanca and Botvinnik for the classical Carlsbad, Karpov for the modern squeeze, Kramnik and Ding Liren for the current treatment.",
        "next": "Add the Catalan. It uses the same c4/d4 pawns with a different bishop and gives you a second, quieter way to play for a win.",
    },
}
