OPENING = {
    "id": "queensgambit",
    "name": "Queen's Gambit",
    "eco": "D06–D69",
    "section": "white-d4",
    "orientation": "white",
    "tagline": "The most trusted 1.d4 opening in history. Not really a gambit at all.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "White attacks Black's d5-pawn from the side with c4 instead of head-on. If Black takes with ...dxc4, the pawn cannot be held (b5 is always met by a4), and White simply recovers it while building a big centre with e4. If Black declines with ...e6 or ...c6, Black must accept a small structural or developmental concession. The whole opening is a fight over whether White gets to play e2–e4.",
        "structure": "The defining structure is the Carlsbad: White pawns on a2, b2, c3, d4, e3 against Black pawns on a7, b7, c6, d5, f7. It arises from the Exchange Variation and it hands both sides a completely clear plan — White attacks on the queenside with a minority attack, Black attacks on the kingside with a piece storm. Learning the Carlsbad teaches you more about middlegame planning than any tactics book.",
        "white_plans": [
            "The minority attack: push b2–b4–b5 to trade off on c6, leaving Black with a weak backward c-pawn on an open file.",
            "Play for the e3–e4 break, converting the space advantage into an attack.",
            "In the Accepted, regain the pawn with Bxc4 and build the ideal centre with e4, accepting an isolated d-pawn for activity.",
            "Pile up on the c-file and infiltrate on c7/c8.",
        ],
        "black_plans": [
            "Break with ...c5 (Tarrasch style) or ...e5, freeing the position at the cost of structure.",
            "In the Carlsbad, attack on the kingside with ...Ne4, ...f5, ...Ng6 and a piece storm — Black is faster there because White's pawns are committed to the other wing.",
            "Trade off pieces with the Tartakower plan (...b6, ...Bb7) to relieve the cramp.",
            "The 'freeing manoeuvre' ...Nd7–f8–g6 or ...Nf6–e4 to trade a pair of pieces.",
        ],
        "traps": [
            "The Elephant Trap: 1.d4 d5 2.c4 e6 3.Nc3 Nf6 4.Bg5 Nbd7 5.cxd5 exd5 6.Nxd5?? Nxd5! 7.Bxd8 Bb4+! 8.Qd2 Bxd2+ 9.Kxd2 Kxd8 and Black is a piece up.",
            "Never try to defend the c4-pawn with 2...dxc4 3.e3 b5?? 4.a4 c6 5.axb5 cxb5 6.Qf3! forking a8 and b7.",
            "The Rubinstein Trap: Black playing ...Nbd7 and then ...Re8 too early can drop a pawn to Nxd5!",
        ],
        "who": "Play this if you want the most solid, most respected 1.d4 opening there is. Every world champion from Steinitz to Ding has played it.",
    },
    "lines": [
        {
            "name": "Exchange Variation — The Minority Attack",
            "note": "The single most instructive plan in all of chess. Learn this and you will understand what a 'plan' actually means.",
            "moves": "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8 Rab1",
            "notes": {
                3: "The Queen's Gambit. White does not really give a pawn — the point is to deflect the d5-pawn so that e2–e4 becomes possible.",
                4: "The Queen's Gambit Declined. Rock-solid: Black supports d5 with a pawn. The cost is that the c8-bishop is temporarily locked behind its own pawn chain.",
                5: "Developing and adding a third attacker to d5.",
                6: "Black develops and defends d5 for the third time.",
                7: "The Exchange Variation. White resolves the tension deliberately, creating the Carlsbad structure and a clear long-term plan.",
                8: "Black must recapture with the e-pawn: 4...Nxd5 would concede the centre and 4...Qxd5 loses time to Nc3.",
                9: "Pinning the f6-knight, which is d5's main defender.",
                10: "Black shores up d5 a third time. This is the Carlsbad structure: White has pawns a2-b2-c3-d4-e3, Black has a7-b7-c6-d5-f7.",
                11: "Modest but essential — it supports d4 and opens the f1-bishop.",
                12: "Breaking the pin and preparing to castle.",
                13: "The bishop takes its best diagonal, aiming at h7 and supporting a future e4.",
                14: "The knight goes to d7 rather than c6 so it does not block the c-pawn, and it heads for f8 and g6.",
                15: "Battery on the b1–h7 diagonal, and the queen also eyes the c-file where the action will be.",
                16: "King safety.",
                17: "Note: the knight goes to e2, not f3, so that the f-pawn stays free and the knight can go to g3 or f4. A key Carlsbad subtlety.",
                18: "Black's rook eyes the e-file and supports a future ...Ne4.",
                19: "White is fully developed and now commits to the plan.",
                20: "Black's standard defensive manoeuvre: the knight heads for g6 or e6 to guard the kingside.",
                21: "The minority attack begins. White will play b4, then a4, then b5 — attacking Black's three queenside pawns with two. When the pawns trade on c6, Black is left with a backward c-pawn on an open file, and White wins it in the endgame. That is the plan for the next twenty moves.",
            },
        },
        {
            "name": "Queen's Gambit Declined — Tartakower",
            "note": "Black's most reliable equalising system. Fianchetto the bishop and trade pieces.",
            "moves": "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6 cxd5 Nxd5 Bxe7 Qxe7 Nxd5 exd5",
            "notes": {
                7: "The classical development, pinning the knight and pressuring d5 indirectly.",
                8: "Breaking the pin by interposing. Black's setup is passive but extremely tough.",
                9: "Solid: supports d4, opens the bishop. White is not in a hurry.",
                10: "King safety.",
                12: "Putting the question to the bishop. This little move is the start of Black's whole plan.",
                13: "Retreating and keeping the pin. 7.Bxf6 Bxf6 gives Black the bishop pair too easily.",
                14: "The Tartakower move. Black prepares ...Bb7 so the problem bishop finally gets a diagonal.",
                15: "White strikes first to stop ...Bb7 coming with full effect.",
                16: "Recapturing with the knight, since ...exd5 would leave a passive bishop. Now trades start.",
                17: "Simplifying.",
                18: "Black recaptures with the queen, connecting the rooks.",
                19: "Another trade — White eliminates the active knight.",
                20: "Black recaptures toward the centre. Black has a slightly loose d5-pawn but excellent piece activity, the bishop on b7 and easy development. This is one of the most reliable ways to equalise as Black against 1.d4.",
                11: "Development. White is in no hurry: every piece has an obvious square and there is nothing to attack.",
            },
        },
        {
            "name": "Queen's Gambit Accepted",
            "note": "Black takes the pawn, gives up the centre, and hits back with ...c5. Fast development and clean structures.",
            "plan": {
                "structure": 'isolani',
                "point": "The same isolated d-pawn the Panov and the Nimzo reach, arrived at from 1.d4 — and with a2–a4 already in, so Black's queenside has no ...b5 to gain space with while you attack.",
                "next": [
                    'Nc3 and Bg5, then Rac1 or Ne5. The d-pawn buys you c5 and e5; a knight on either is worth more than the pawn is weak.',
                    'd4–d5 when Black stops watching it — usually the moment a piece leaves the kingside.',
                    'a4 has cost you b4 as a square. Do not put a piece there and expect it to stay.',
                ],
                "endgame": 'The pawn is a liability the instant the queens come off, and Black knows it. Trade only when the trade wins something concrete; otherwise keep four pieces each on the board and keep asking questions.',
            },
            "moves": "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4 Nc6 Qe2 cxd4 Rd1 Be7 exd4",
            "notes": {
                4: "The Queen's Gambit Accepted. Black does not intend to keep the pawn — the idea is to give up the centre now and attack it later with ...c5 and ...e5.",
                5: "The most flexible: White stops ...e5 and develops before recapturing.",
                6: "Black develops and controls d5/e4.",
                7: "Modest, but it opens the bishop's path to c4 and shores up d4.",
                8: "Black opens the bishop and prepares ...c5.",
                9: "White finally regains the pawn on the best square, with full development and a nice centre.",
                10: "The essential freeing break. Without ...c5, Black would simply be worse with less space.",
                11: "King safety before the centre opens.",
                12: "Preparing ...b5 to kick the bishop and gain queenside space.",
                13: "Stopping ...b5 in its tracks. It slightly weakens b4, but stopping Black's counterplay is worth it.",
                14: "Developing with pressure on d4.",
                15: "The queen steps off the d-file in advance of the coming exchanges.",
                16: "Black releases the tension, giving White an isolated queen's pawn.",
                17: "The rook goes to the file where the isolated pawn will sit — supporting it and eyeing d5.",
                18: "Completing development.",
                19: "White has an isolated d-pawn. That is a long-term weakness but a short-term asset: it gives White the e5 and c5 outposts, open e- and c-files, and attacking chances. If White attacks, White wins; if pieces come off, Black wins the pawn.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the minority attack completed",
        "note": "The most instructive sequence in chess: watch two pawns walk up the board and permanently ruin three.",
        "moves": "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nge2 Re8 O-O Nf8 Rab1 Ne6 Bxf6 Bxf6 b4 a6 a4 Bd7 b5 axb5 axb5 Ra3 bxc6 bxc6 Nc1",
        "notes": {
            22: "The knight completes its journey to e6, where it guards c5 and c7 and eyes d4 and f4. Black's defensive setup is complete.",
            23: "White trades off the good bishop to remove a defender of the queenside dark squares and to gain a tempo.",
            24: "Black recaptures with the bishop, which now looks impressive on the long diagonal but does nothing about the coming pawns.",
            25: "The minority attack begins. Two pawns are about to advance against three.",
            26: "Black stops b5 for a moment and prepares to meet it.",
            27: "White simply prepares b5 again. The attack cannot be stopped, only delayed — that is why it is such a reliable plan.",
            28: "Black develops and prepares to defend c6 with pieces.",
            29: "The break arrives.",
            30: "Black must take, otherwise bxc6 comes anyway with an extra tempo.",
            31: "Recapturing, and now the a-file is open too — a second front that Black did not ask for.",
            32: "Black grabs the open file first. Good defence: activity is the only real answer to a structural attack.",
            33: "The point of the whole plan. White exchanges two pawns for one and hands Black a permanent problem.",
            34: "Forced. Black now has a backward pawn on c6, sitting on a half-open file, unable ever to be defended by another pawn.",
            35: "The knight redeploys toward b3 and a5 or d3 and c5, to attack the pawn White just created. Everything from here is technique: pile on c6, trade into an endgame, win the pawn. This plan has decided thousands of grandmaster games.",
        },
    },
    "progression": {
        "arc": "The Queen's Gambit is the best strategic education in chess. Learn it and you will understand pawn structures for the rest of your life.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to two",
                "goal": "Know why the pawn cannot be held and get a healthy position against each defence.",
                "learn": [
                    "Why 2...dxc4 does not win a pawn: 3.e3 b5? 4.a4 c6 5.axb5 cxb5 6.Qf3! forks a8 and b7.",
                    "Your basic setup against the Declined: Nc3, Nf3, Bg5, e3, Bd3, Qc2, O-O. Same seven moves nearly every game.",
                    "The three main defences you will actually face: 2...e6 (Declined), 2...c6 (Slav), 2...dxc4 (Accepted).",
                ],
                "drill": "Play twenty games with the Exchange Variation. One structure, one plan, endless repetition — this is the fastest way to improve at chess.",
                "mistake": "Playing cxd5 at random. The Exchange is a commitment: you get a clear plan and Black gets the e-file and a free hand on the kingside.",
                "ready": "You can set up the seven-move scheme against any Black move order.",
            },
            {
                "tier": "Structure",
                "when": "Weeks three to eight",
                "goal": "Master the Carlsbad structure. It is the single most valuable structure in chess.",
                "learn": [
                    "The pawn skeleton: White a2-b2-c3-d4-e3 against Black a7-b7-c6-d5-f7. Learn to recognise it from any move order.",
                    "Why White plays on the queenside and Black on the kingside: your pawns point that way, and pawns decide where you attack.",
                    "The knight to e2 rather than f3 — it keeps the f-pawn free and allows Ng3 or Nf4.",
                ],
                "drill": "Set up the Carlsbad and play only the minority attack: b4, a4, b5, bxc6. Do it ten times. Feel how the backward c-pawn appears.",
                "mistake": "Starting the minority attack before your pieces are placed. Rab1 and Qc2 come first, then the pawns.",
                "ready": "You can draw the Carlsbad structure from memory and name both sides' plans.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Learn the four plans available in the Carlsbad and how to choose between them.",
                "learn": [
                    "Plan A, the minority attack (b4–b5) — the workhorse.",
                    "Plan B, the central break e3–e4 — stronger when Black has committed to a kingside attack.",
                    "Plan C, the kingside pawn storm with f3 and g4 — for when Black's minor pieces have left that wing.",
                    "Plan D, piece pressure on the c-file with Rc1, Na4 and Nc5.",
                ],
                "drill": "Take the position after 11.Rab1 and play each of the four plans once against an engine. Note which one it defends worst.",
                "mistake": "Switching plans halfway. Each plan commits pawns, and pawns do not come back.",
                "ready": "You choose your plan based on where Black's pieces are, not on habit.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Cover the whole 1.d4 d5 landscape and the resulting endgames.",
                "learn": [
                    "The Queen's Gambit Accepted, including the isolated-queen's-pawn positions that come with it.",
                    "The Slav and Semi-Slav — you will face them constantly, and the Meran and Botvinnik lines are theory-heavy.",
                    "Rook endgames with a queenside majority. Most Carlsbad games end there.",
                ],
                "drill": "Study twenty of Botvinnik's or Karpov's Carlsbad games. Cover the moves and guess each one.",
                "mistake": "Neglecting the Slav because the Declined is more common in books. In practice the Slav is everywhere.",
                "ready": "You have a prepared answer to 2...e6, 2...c6, 2...dxc4 and 2...Nf6.",
            },
        ],
        "study": "Capablanca and Botvinnik for the classical minority attack, Karpov for the modern squeeze, Kramnik and Ding Liren for the current treatment.",
        "next": "Add the Catalan. It uses the same c4/d4 pawns with a different bishop and gives you a second, quieter way to play for a win.",
    },
}
