OPENING = {
    "id": "ruylopez",
    "name": "Ruy Lopez (Spanish Game)",
    "eco": "C60–C99",
    "section": "white-e4",
    "orientation": "white",
    "tagline": "The most respected opening in chess. Slow pressure that never goes away.",
    "level": "Intermediate → World Championship",
    "theory": {
        "big_idea": "3.Bb5 attacks the knight that defends e5. The threat is not immediate — after 4.Bxc6 dxc6 5.Nxe5?? Qd4 wins the piece back — but it is a permanent nagging question. White's real plan is to build the centre with c3 and d4 while Black's pieces are tangled defending e5, then manoeuvre the knight to g3 and attack the kingside. It is the opening of long-term positional pressure.",
        "structure": "White gets a broad centre with pawns on d4 and e4 supported by c3. Black usually plays ...d6 and ...b5 and then either holds with ...c5 (the Chigorin) or breaks with ...d5 (the Marshall Attack, a whole-pawn gambit). The Exchange Variation produces a completely different structure: Black gets doubled c-pawns but the bishop pair.",
        "white_plans": [
            "The Spanish manoeuvre: Nb1–d2–f1–g3 (sometimes on to f5 or h5), the classic slow build-up toward a kingside attack.",
            "Establish the pawn centre with c3 and d4, then decide whether to release the tension with d5 (closing) or dxe5 (opening).",
            "The Exchange Variation: 4.Bxc6 dxc6 wrecks Black's queenside pawn structure. White plays for a winning king-and-pawn endgame from move four.",
            "a4 undermining Black's b5–c6 queenside chain.",
        ],
        "black_plans": [
            "The Breyer/Chigorin retreat: re-route the knight from c6 to b8–d7 or a5–c4 and slowly untangle.",
            "The Marshall Attack: sacrifice a pawn with ...d5 for a lasting initiative against White's king.",
            "The Berlin Defence: force an early queen trade and head for a slightly worse but extremely tough endgame with the bishop pair. This is the opening that ended Kasparov's title reign.",
            "Break with ...d5 or ...f5 once White's centre is committed.",
        ],
        "traps": [
            "The Noah's Ark Trap: after an early ...b5 and ...c5, Black's queenside pawns can roll forward and physically trap White's bishop on b3 — ...c4 and ...b5–b4 nets a piece.",
            "Do not play 4.Ba4 Nf6 5.O-O Nxe4 6.Re1?! d5 7.Nxe5 — this is the Riga/Open Spanish, sharp and double-edged, not a free piece.",
            "Never grab with 4.Bxc6 dxc6 5.Nxe5?? — 5...Qd4! forks e5 and e4.",
        ],
        "who": "Play this if you are willing to invest in theory and you enjoy squeezing opponents slowly. It rewards patience and understanding, not memorised tricks.",
    },
    "lines": [
        {
            "name": "Closed Ruy Lopez — Chigorin",
            "note": "The classical main line, played in thousands of grandmaster games. Both sides develop fully before the fight begins.",
            "moves": "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7",
            "notes": {
                5: "The Spanish bishop. It does not win the e5-pawn — but it asks a question Black has to answer for the next thirty moves.",
                6: "The Morphy Defence. Black kicks the bishop first and asks it to make a decision. This gains the option of ...b5 later.",
                7: "Retreating along the diagonal, keeping the pressure and the future option of Bxc6 at a better moment.",
                8: "Hitting e4. White will not defend it with d3 — instead comes the famous temporary pawn sacrifice.",
                9: "Castling and ignoring e4! If 5...Nxe4 6.d4 Black cannot hold the extra pawn, because of the Bb3/Re1 pressure and d4–d5 tricks.",
                10: "Solid development, unpinning nothing but preparing to castle and stay compact.",
                11: "Now the e-pawn is properly defended and the rook sits on the file it will fight on.",
                12: "The critical moment: Black must gain space on the queenside before White plays a4, and this hits the bishop.",
                13: "The bishop retreats to its long-term home. From b3 it will keep staring at f7 and the a2–g8 diagonal for the rest of the game.",
                14: "Shoring up e5 and finally freeing the c8-bishop.",
                15: "Preparing d4 and giving the bishop the retreat square c2 in advance. The Ruy Lopez is a slow-motion opening.",
                16: "King safety.",
                17: "Almost always played in the Ruy: it stops ...Bg4 pinning the knight, which would undermine the defence of d4.",
                18: "The Chigorin plan. The knight goes to the edge on purpose to hit the b3-bishop, and later returns via c6 or c4.",
                19: "The bishop finds its final home. It now aims at h7 — the future attacking diagonal.",
                20: "Black challenges the centre before White gets in d4 for free.",
                21: "White finally plays the break, with maximum support. Now the whole game is about whether White plays d5 (closing the centre and attacking on the kingside) or keeps the tension.",
                22: "Black's queen takes up its standard post, adding pressure to e5 and c-file.",
            },
        },
        {
            "name": "Exchange Variation",
            "note": "White voluntarily gives up the bishop pair to ruin Black's structure. A pure, teachable endgame plan you can play at any level.",
            "moves": "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 O-O f6 d4 exd4 Nxd4 c5 Nb3 Qxd1 Rxd1 Bd6",
            "notes": {
                7: "Straight to the point. White doubles Black's pawns on the c-file and creates a 4v3 healthy majority on the kingside.",
                8: "Forced in practice — 4...bxc6 leaves Black with an even worse structure and no development.",
                9: "The key strategic fact: if all the pieces come off, White wins the king and pawn endgame, because White's four kingside pawns can create a passer and Black's four queenside pawns (with doubled c-pawns) cannot.",
                10: "Ugly but necessary, propping up e5 without allowing Nxe5.",
                11: "Opening the position for the pieces while Black's structure is compromised.",
                12: "Black must take, otherwise White simply builds up.",
                13: "White recaptures with the knight and stands better developed.",
                14: "Kicking the knight and grabbing space. Black's compensation for the structure is the bishop pair and open lines.",
                15: "Retreating to a useful square and eyeing c5/a5.",
                16: "Black offers the queen trade, which normally helps the side with the worse structure less — but here it stops White's initiative.",
                17: "White recaptures with the rook, keeping a comfortable endgame edge. Play on: Nc3, Be3, Rd2 and grind the queenside.",
                18: "Black develops actively and will follow with ...Ne7, ...Be6 and try to make the two bishops count in an open position.",
                6: "The Morphy Defence. Black puts the question to the bishop first — which is exactly what invites the Exchange Variation.",
            },
        },
        {
            "name": "Berlin Defence — The Berlin Wall",
            "note": "The world-championship drawing weapon. Black gives up castling rights and the queens come off by move eight.",
            "moves": "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8 Nc3 Ke8 h3 Be7",
            "notes": {
                6: "The Berlin. Instead of kicking the bishop, Black immediately counterattacks e4.",
                7: "White ignores the threat, again. This is the whole flavour of the Ruy Lopez.",
                8: "Black takes. It is not really a pawn win — White regains it by force — but it changes the structure permanently.",
                9: "Opening the centre against the loose knight on e4.",
                10: "The knight retreats to a passive but resilient square, blocking the d-file.",
                11: "Now the trade comes, wrecking Black's queenside structure again.",
                12: "Forced.",
                13: "White wins the pawn back and Black's knight must move again.",
                14: "The knight finds an active square.",
                15: "The defining moment. Queens come off and Black cannot recapture with a rook.",
                16: "Black's king takes on d8 and has lost the right to castle. In return, Black owns the bishop pair and a rock-solid structure. The engine says roughly equal; humans find it miserable to attack.",
                17: "White develops and controls d5/e4.",
                18: "The king starts walking home by hand: Ke8, then ...Be7, ...h6, ...Kf8 and eventually ...Kg8 or ...Kc7.",
                19: "Stopping ...Bg4 and making luft.",
                20: "Black completes the plan. This exact position has been played hundreds of times at the highest level and is the reason 3.Bb5 Nf6 is called the Berlin Wall.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Chigorin middlegame",
        "note": "From the tabiya into the real fight: the centre resolves, the knight comes home, and both sides commit to a wing.",
        "moves": "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7 Nbd2 cxd4 cxd4 Nc6 Nb3 a5 Be3 a4 Nbd2 Bd7 Rc1 Qb7 Bb1",
        "notes": {
            23: "The knight finally develops — to d2, of course, heading for f1 and g3. In the Ruy this knight is always the last piece out and often the most important.",
            24: "Black resolves the tension. It concedes the centre a little, but it opens the c-file and frees the c6 square for the offside knight.",
            25: "Recapturing with the pawn, keeping a broad centre on d4 and e4.",
            26: "The knight comes home from a5. Four moves for one knight — but it dragged the bishop from b3 to c2 and opened the c-file. That is the Chigorin bargain.",
            27: "White's knight also redeploys, eyeing c5 and a5 and stopping Black's queenside expansion.",
            28: "Black gains space and drives the knight away. Both sides are now committed: Black on the queenside, White on the kingside.",
            29: "Development at last. The bishop supports d4 and eyes the queenside dark squares.",
            30: "The pawn goes on, fixing White's a2-pawn as a target and taking b3 away from the knight for good.",
            31: "Back to d2, where the knight is heading for f1 and g3 exactly as planned. In the Ruy, being pushed around is not the same as being worse.",
            32: "Black completes development. Every piece is placed; now the plans collide.",
            33: "The rook takes the open file it has been waiting fifteen moves for.",
            34: "The queen slides out of the way of the rook and eyes the long diagonal.",
            35: "The famous Spanish battery. Bb1 and Qd3 (or Qc2) aim at h7. This is the moment the Ruy stops being a positional opening and becomes a kingside attack — White has spent thirty-five moves earning the right to start it.",
        },
    },
    "progression": {
        "arc": "The Ruy is a five-year opening. You will keep finding new layers in it, which is exactly why every world champion has played it.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to three",
                "goal": "Survive the first ten moves and understand why the bishop goes to b5.",
                "learn": [
                    "The Morphy main line: 3...a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 d6 8.c3 O-O 9.h3. Memorise it as one unit.",
                    "Why 5.O-O ignores the e4-pawn: after 5...Nxe4 6.d4 the pawn always comes back.",
                    "The Exchange Variation 4.Bxc6 as your safety net — it is fully playable and needs almost no theory.",
                ],
                "drill": "Play the Exchange Variation for a month. It teaches you the structure without the memorisation, and you will win endgames.",
                "mistake": "Playing 5.Nxe5 after 4.Bxc6 dxc6. It loses a pawn to 5...Qd4 and it is the single most common Ruy Lopez blunder.",
                "ready": "You can reach move nine of the Closed Ruy from memory and you have won a game with the Exchange endgame plan.",
            },
            {
                "tier": "Structure",
                "when": "Months one to three",
                "goal": "Understand the two centres — the tense one and the closed one.",
                "learn": [
                    "After c3 and d4, the three ways the centre can resolve: d5 (closed, play on the wings), dxe5 (open, piece play), or keeping the tension (usually best).",
                    "The Carlsbad-like queenside chain b5–c6–a6 and White's undermining a4.",
                    "Why the h3 move is played in almost every line — it stops ...Bg4, which would undermine the defence of d4.",
                ],
                "drill": "Set up the position after 11.d4 in the Chigorin and play it out against an engine ten times from both sides. Note what changes when White plays d5.",
                "mistake": "Releasing the central tension because it feels uncomfortable. Whoever resolves the tension first usually helps the other side.",
                "ready": "You can explain what changes about both sides' plans the moment White plays d5.",
            },
            {
                "tier": "Plans",
                "when": "Months three to nine",
                "goal": "Learn the manoeuvres that make the Ruy the Ruy.",
                "learn": [
                    "The Spanish knight tour Nb1–d2–f1–g3 (or e3) — the model for slow attacking build-ups in every opening.",
                    "Black's counterplans: the Chigorin ...Na5, the Breyer ...Nb8–d7, the Zaitsev ...Bb7 and ...Re8.",
                    "The a4 break and when to take on b5 versus when to leave the tension.",
                ],
                "drill": "Play twenty games reaching the Closed tabiya and write one sentence after each about where your pieces belonged.",
                "mistake": "Rushing the kingside attack. In the Ruy the attack arrives around move twenty-five, not move fifteen.",
                "ready": "You can name the square each of your eight pieces wants without looking at a book.",
            },
            {
                "tier": "Mastery",
                "when": "Year two and beyond",
                "goal": "Handle the theoretical branches and the endgames the Ruy produces.",
                "learn": [
                    "The Berlin Defence and its endgame — you will face it, and knowing how to press without queens is a genuine skill.",
                    "The Marshall Attack and your chosen Anti-Marshall (8.a4 or 8.h3), because Black gets a free pawn sacrifice otherwise.",
                    "The Noah's Ark Trap and the whole family of positions where the b3-bishop gets short of squares.",
                ],
                "drill": "Study ten Berlin endgames move by move. It is the least glamorous and most valuable study you will do this year.",
                "mistake": "Avoiding the Berlin by playing something else. Learn to play against it — the small edge is real.",
                "ready": "You are comfortable in a queenless middlegame with a small structural plus.",
            },
        ],
        "study": "Fischer and Karpov for the classical treatment, Kasparov for the attacking version, Carlsen for the modern grind. Kramnik–Kasparov, London 2000 is the match that made the Berlin Wall famous.",
        "next": "Add a second line against the Berlin, then start studying the Ruy's cousin structures — the Italian with d4 and the Scotch — so you can transpose when it suits you.",
    },
}
