OPENING = {
    "id": "scholarsmate",
    "name": "Scholar's Mate",
    "eco": "C20",
    "section": "traps",
    "orientation": "white",
    "tagline": "Four moves to checkmate — and the cure that turns the queen raid into a lost tempo.",
    "level": "Beginner",
    "theory": {
        "big_idea": "Queen to h5, bishop to c4, both aimed at f7 — the one square only the king defends. If Black develops on autopilot, 4.Qxf7 is mate on move four. The whole opening is one threat made twice, and the whole defence is three moves: ...Nc6, ...g6, ...Nf6, each of which answers the threat and develops at the same time. Learn it from both chairs: the mate wins games for years below 1000, and the defence turns the early queen into a target that loses White the opening.",
        "structure": "The open-game skeleton — e-pawns on e4 and e5, everything else at home. Nothing structural is at stake; the entire argument is about time. White has spent it on queen moves, and every queen retreat hands Black another free developing move.",
        "white_plans": [
            "Make the threat twice: 2.Qh5 hits f7 and e5, and after ...g6 the queen slides to f3 renewing the mate threat. Two questions, and either can be fumbled.",
            "Punish the natural-looking answers on the spot: 2...g6?? loses the rook to 3.Qxe5+, 3...Nf6?? and 3...d6?? are mate in one, 3...Nd4?? after 4.Qf3 is mate again.",
            "When Black answers correctly, stop: retreat the queen to a quiet square, develop knights to e2 and c3, castle, and play the position a tempo or so worse than a normal Italian.",
            "Never renew the threat a third time. Qb3 and g4 and every other lunge hands Black the initiative for good — the deviation panel prices each one.",
        ],
        "black_plans": [
            "Answer both threats with developing moves: 2...Nc6 defends e5, 3...g6 blocks the h5–f7 diagonal, and 4...Nf6 meets Qf3 by standing in the queen's road down the f-file — while attacking e4.",
            "Then make the queen pay rent: ...Nd4 hits queen and c2 at once, ...Bg7 and ...O-O finish development, and every queen retreat is another free move for you.",
            "If White doubles down with 5.Qb3, punish it: 5...Nd4! and the queenside forks arrive before the attack does.",
            "Never defend passively. The refutation of an early queen is never to hide — it is to develop with threats until the queen has no squares left.",
        ],
        "traps": [
            "The mate itself: 2.Qh5 Nc6 3.Bc4 Nf6?? 4.Qxf7#. The knight develops, attacks the queen — and steps past the only diagonal that mattered.",
            "The counter-blunder: 2...g6?? blocks the diagonal a move too early, and 3.Qxe5+ forks king and rook — the punisher becomes the punished.",
            "The quiet mates: 3...d6?? and 3...Nd4?? both leave f7 unguarded and the d7 flight square covered through the empty e7 — Qxf7 is mate in one in both.",
            "The second wave: after 3...g6 4.Qf3, the same mate is threatened again — 4...Nd4?? allows Qxf7# even now. Only 4...Nf6 answers it properly.",
        ],
        "who": "The first trap every player meets, from both chairs. Learn the White side to understand why it works — the geometry of f7 — and the Black side so that no early queen ever beats you again. One session covers it for life.",
    },
    "lines": [
        {
            "name": "The attack, met correctly",
            "note": "The honest main line: both threats made, both answered, and White retreating into a quiet game a tempo down. This is what the trap costs against a prepared opponent.",
            "moves": "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Ne2 Bg7 Nbc3 d6 d3 O-O O-O",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": 'Structure',
                "point": 'Count the ledger: the queen moved twice and sits on f3 blocking her own knight\'s best square, Black developed three pieces and castled. The engine calls it about half a pawn for Black — not lost, just a normal game where you gave the first move away and then some.',
                "next": [
                    'The queen needs a real square: Qd1 via a later h3 and Be3 setup, or g3 after h3, out of the way of the e2-knight.',
                    'Play like a slow Italian a tempo short: c3 and d4 later, or f4 with the king already safe — the c4-bishop still points at the right diagonal.',
                    'Watch for ...Nd4: it hits the f3-queen and c2 at once, and answering it is the first thing to solve on every move.',
                ],
                "endgame": 'Dead level pawn structure, so the tempo is the whole story: if it simplifies before you catch up in development, you are simply worse. Keep pieces on until the ledger is even.',
            },
            "notes": {
                3: "The raid. The queen attacks e5 and f7 in one move, and the threat is mate in two more. It is also the last moment this opening is going well for White against good defence — every reply that matters develops with tempo on this queen.",
                4: "The correct answer, and the first lesson: it defends e5 by developing a piece. Not 2...g6?? — the deviation panel shows the rook leaving the board.",
                5: "The bishop joins the queen on f7, and the mate is genuinely on: from here every natural-looking Black move except one loses on the spot.",
                6: "The move that answers it: the pawn blocks the h5–f7 diagonal and gains a tempo on the queen. The defence keeps developing; the attack keeps retreating.",
                7: "The threat renewed on the other diagonal — f3, f7, mate again. This is the point of the Scholar's pattern, and one more correct reply defuses it for good.",
                8: "The second answer, and the best move on the board: the knight stands in the queen's road down the f-file, attacks e4, and develops. Both threats are spent. Now watch what the queen moves cost.",
                9: "The retreat begins. Ne2 guards against ...Nd4 — the fork on queen and c2 that punishes almost everything else — and finally develops a piece.",
                10: "The bishop takes the long diagonal, and Black's position simply builds itself. Every move from here is a move White wishes the queen sortie had not cost.",
                11: "The other knight out. White's development is honest now — two knights, a bishop, the queen misplaced but safe.",
                12: "Solid: the e5-pawn gets a second guard, and the c8-bishop gets a diagonal.",
                13: "Making luft for the bishop's retreat and holding e4. White's setup is a slow Italian with the queen on the wrong square.",
                14: "Castled. Count Black's position: three pieces out, king safe, no weaknesses — the trap has cost White the opening argument entirely.",
                15: "Castled too, and the position is playable for both sides — the engine says Black is a shade better, which is the whole verdict on 2.Qh5 in one number.",
            },
        },
        {
            "name": "The four-move mate",
            "note": "The trap landing in full: Black develops the wrong knight first, and the game ends on move four.",
            "moves": "e4 e5 Qh5 Nc6 Bc4 Nf6 Qxf7#",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": 'Foundation',
                "point": 'Checkmate. Understand exactly why: the bishop guards the queen on f7, the king cannot take; e7 is empty, so the queen covers the d7 flight square along the rank; and the black queen still occupies d8. Three accidents, one geometry — the same three facts make 3...d6 and 3...Nd4 lose to the identical move.',
                "next": [
                    'Say the pattern out loud before moving on: two attackers on f7, zero defenders that are not the king, no flight square, no block.',
                    'Now flip the board and learn the defence — the other two lines of this opening are the cure.',
                ],
                "endgame": 'There is no endgame after move four. That is the sales pitch, and the reason the pattern must be in your hands before your rating stops it working.',
            },
            "notes": {
                3: "The raid: e5 and f7 attacked at once, mate threatened in two.",
                4: "Right so far — the knight defends e5 and develops.",
                6: "The losing move, played by every beginner once: it develops, it attacks the queen, and it ignores the only diagonal on the board that matters. f7 is now attacked twice and defended once.",
                7: "Mate, move four. The king cannot take — the c4-bishop guards f7. It cannot run to d7 — the queen sees along the seventh rank through the empty e7. And d8 is its own queen. Every piece of the geometry gets used.",
            },
        },
        {
            "name": "Defusing it as Black",
            "note": "The defence from Black's chair: three correct answers, then the counterattack that makes the queen sortie cost the game's initiative.",
            "moves": "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Ne2 Bg7 Nbc3 Nd4",
            "tier": "Foundation",
            "drill": True,
            "side": "black",
            "plan": {
                "tier": 'Structure',
                "point": 'The knight lands on d4 hitting the queen and eyeing c2, and White must answer it instead of developing — the third tempo the queen raid has cost. You are not winning material; you are winning every argument about who develops faster.',
                "next": [
                    'After the queen retreats, take stock: ...d5 or ...c6-and-...d5 breaks the centre open while White is still untangling.',
                    'Castle before opening the game if the c4-bishop still points at f7 — the one White piece doing its job is that bishop.',
                    'Trade the d4-knight only for something that develops you further; it is your best piece and White has no good way to evict it.',
                ],
                "endgame": 'A structurally equal endgame is fine for you — the development lead converts to activity, not material. But the real prize is a middlegame where White\'s queen keeps being asked questions.',
            },
            "notes": {
                3: "The raid you will see a hundred times: queen hits e5 and f7, mate threatened. Every answer you are about to drill develops a piece — that is the whole philosophy of the defence.",
                4: "Answer one: defend e5 with a developing move. Do not block with 2...g6 yet — with the queen on h5 that loses the e5-pawn and the h8-rook to 3.Qxe5+.",
                5: "The bishop arrives and the mate threat is real. One move answers it.",
                6: "Answer two: block the diagonal with tempo. The g7-square is waiting for your bishop anyway — the defence costs nothing.",
                7: "The threat again, from f3. Beginners crack here by defending passively; you have a better move.",
                8: "Answer three, and the best move on the board: the knight blocks the f-file in front of the queen, attacks e4, and develops. Both waves of the attack are spent, and the game is now about White's lost time.",
                9: "White's best: guard the d4 fork square and finally develop. Anything greedier — 5.Qb3, say — walks into the queen hunt drilled in the next line.",
                10: "The bishop takes the long diagonal. Your moves develop; White's moves apologise.",
                11: "The second knight comes out, and White's setup is nearly honest again — which is why now is the moment to press.",
                12: "The counterattack, fully prepared: the knight hits the f3-queen, and White's least-bad answer is to trade it off and accept the tempo ledger as it stands. You are not winning material — you are winning every argument about who develops faster, and that was the point of all three correct answers.",
            },
        },
        {
            "name": "Punishing the wayward queen",
            "note": "What happens when White doubles down: 5.Qb3 renews the threats a third time, and the fork on d4 wins material by force.",
            "moves": "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Qb3 Nd4 Bxf7+ Ke7 Qc4 b5 Qd3 Kxf7",
            "tier": "Structure",
            "drill": True,
            "side": "black",
            "plan": {
                "tier": 'Plans',
                "point": 'A bishop for a pawn, and your king on f7 is safer than it looks — White has one developed piece and it is the queen, which is not a developed piece. Consolidate and the material decides.',
                "next": [
                    'The king walks back: ...Rf8, ...Kg8, and you are effectively castled with the rook already active.',
                    'The d4-knight is the anchor. Support it with ...c5 if attacked, and meet c3 with ...Ne6 keeping every trade favourable.',
                    'Develop the queenside with tempo where you can — ...Bb7 hits e4, ...Qe8-c6 ideas pile on the queen\'s diagonal.',
                ],
                "endgame": 'Any endgame wins on material. White must keep queens on to justify anything, so your trades are all offers White cannot afford to accept.',
            },
            "notes": {
                3: "The raid, met the same way as always.",
                4: "Develop and defend. The script does not change.",
                5: "The bishop joins. So far this is the mate line — and your answers are the same.",
                6: "Block with tempo. Two threats down.",
                7: "The threat renewed. One more correct answer.",
                8: "The knight move that answers everything. A prepared White retreats here; the greedy one plays the move this line exists for.",
                9: "The third lunge: the queen hits b7 and lines up behind the bishop against f7, and it finally goes too far. Three queen moves to make threats; you are about to show why that loses.",
                10: "The fork in return: the knight hits the b3-queen and the c2-square behind it, and every White answer loses something — the deviation panel prices the retreats. Mind which fork: the same idea via a5, hitting queen and bishop, meets 6.Bxf7+! Ke7 7.Qa3+ and the advantage changes hands. d4 is the square, because after it f7 comes with no tempo attached.",
                11: "The desperado grab: a pawn with check before the queen runs. It wins f7 and loses the game — watch the bishop.",
                12: "The only legal move, which says everything about the desperado: the king cannot take — the b3-queen defends f7 through the emptied diagonal — and d8 is the queen's own square. Forced to e7, and happy to be there: the f7-bishop now has no way home.",
                13: "The queen defends her bishop and threatens nothing. One pawn move ends the defence of both.",
                14: "The point of the whole line: the pawn attacks the c4-queen, and when she moves, the bishop on f7 is lost. Two pieces on one diagonal, one pawn move, no answers.",
                15: "The queen finds the one square where nothing hits her — White's best, and it concedes the point: she has left the bishop's diagonal, and the piece on f7 now belongs to you.",
                16: "Take the bishop. A clean piece for a pawn, the attack over, and the king one move from artificial castling. This is the full price of asking the same question three times.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — how the tempo gets spent",
        "note": "The main line six plies further, from White's chair: Black cashes in with the fork too early, and every exchange buys White's lost time back. Play it out to see why simplification is the trailing side's friend.",
        "moves": "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Ne2 Bg7 Nbc3 d6 d3 O-O O-O Nd4 Nxd4 exd4 Nd5 Nxd5 Bxd5",
        "notes": {
            16: "The fork square — but this time it is the impatient choice: with everything guarded, the knight leap only starts a chain of trades, and trades are exactly what you want. The engine keeps more of Black's edge with the quiet 8...h6.",
            17: "Take it at once. This is what 5.Ne2 was for, and every piece that comes off the board is a tempo you no longer owe.",
            18: "Look at what the recapture did for Black: the d4-pawn stands on its own bishop's diagonal, and the e5-strongpoint is gone. Structure traded for activity that is not there.",
            19: "The knight finds the one active square and offers the next trade. Black should decline — and rarely does.",
            20: "Taken, and the last of the tempo lead goes with it.",
            21: "Recapture and take stock: dead level at depth twenty. The tempo Black won on move two was real, and simplification spent it — which is the deep lesson of the whole opening, read from either chair: ahead in time, keep pieces on; behind in time, trade.",
        },
    },
    "branches": {
        # ── ply 3 · instead of the raid ─────────────────────────────────────────
        "e4 e5": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "The move theory prefers, and the whole reason this chapter exists is to show why: it develops toward the same attack on e5 without offering the queen as a target. When you outgrow 2.Qh5, this is where the tempo goes instead.",
             "see": "italian"},
        ],

        # ── ply 4 · Black's answers to 2.Qh5 ────────────────────────────────────
        "e4 e5 Qh5": [
            {"san": "g6", "severity": "blunder", "tier": "Foundation",
             "why": "The right idea one move too early, and the most instructive counter-blunder in chess: with nothing defending e5, 3.Qxe5+ forks the king and the h8-rook. Block the diagonal only after ...Nc6 has guarded the pawn.",
             "line": "Qxe5+ Qe7 Qxh8"},
            {"san": "Nf6", "severity": "playable", "tier": "Structure",
             "why": "A real gambit, not a blunder: Black offers e5 to develop with tempo on the queen. After 3.Qxe5+ Be7 White is a pawn up and behind in development with the queen still exposed — the engine calls it close to level, which says everything about where White's second move went.",
             "line": "Qxe5+ Be7 Qf4"},
            {"san": "Qe7", "severity": "playable", "tier": "Foundation",
             "why": "Guarding e5 and f7 with one queen move. It works, at the price of blocking the f8-bishop — solid, passive, and a fair trade of one awkward queen for another.",
             "line": "Bc4 Nc6 Nc3"},
            {"san": "Qf6", "severity": "playable", "tier": "Foundation",
             "why": "It defends e5 and stops nothing else — and the queen takes the g8-knight's best square to do it. White is fine after 3.Nc3, and both sides have now spent their queen early.",
             "line": "Nc3 Nc6 Bc4"},
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "why": "The Philidor answer: e5 is defended by a pawn and the c8-bishop can hit the queen with ...g6 or ...Be6 next. Nothing wrong with it beyond the passive bishop on f8.",
             "line": "Bc4 g6 Qd1"},
            {"san": "g5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Blocking nothing and weakening everything: 3.d4! opens the game while the kingside is full of holes, and the g5-pawn is a target on the very diagonal Black just opened for White's bishop.",
             "line": "d4 Nf6 Qe2"},
        ],

        # ── ply 6 · Black's answers to 3.Bc4 — the moment of the mate ───────────
        "e4 e5 Qh5 Nc6 Bc4": [
            {"san": "Nf6", "severity": "blunder", "tier": "Foundation",
             "why": "The move the whole trap exists for: it develops, it attacks the queen, and it allows mate in one. f7 is attacked twice, defended only by the king, and the king has nowhere to go — the bishop guards f7, the queen covers d7 through the empty e7, and d8 is occupied.",
             "line": "Qxf7#"},
            {"san": "d6", "severity": "blunder", "tier": "Foundation",
             "why": "The quiet mate: ...d6 opens the c8-bishop and does nothing for f7 — and it is already too late for the king to breathe. 4.Qxf7 is mate on the spot: taking is illegal, d7 is covered along the rank, d8 is the queen's own square.",
             "line": "Qxf7#"},
            {"san": "Nd4", "severity": "blunder", "tier": "Foundation",
             "why": "The fork that works one move later loses here: it walks the defender of e5 away while f7 hangs, and 4.Qxf7 is mate — same geometry, third costume. The d4-knight ideas only work after ...g6 and ...Nf6 have dealt with the mate.",
             "line": "Qxf7#"},
            {"san": "g6", "severity": "playable", "tier": "Foundation",
             "why": "The cure: block the diagonal with gain of time now that e5 is guarded. This is the move the defence lines drill — the queen must find a new idea, and there isn't one.",
             "see": "scholarsmate#defusing"},
            {"san": "Qe7", "severity": "playable", "tier": "Foundation",
             "why": "One queen move guards both e5 and f7 — legal and safe. But it blocks the f8-bishop, and the cleaner ...g6 answer costs nothing at all. Choose the move that develops your position rather than the one that merely survives.",
             "line": "d3 g6 Qe2"},
            {"san": "Nh6", "severity": "inaccuracy", "tier": "Structure",
             "why": "Defending f7 with a piece — on the rim, where the bishop can later take it and wreck the pawns. It holds, but 4.Nc3 leaves White comfortably placed and the knight on h6 never finds a real square. The specific cost is half a pawn of comfort and a misplaced piece.",
             "line": "Nc3 g6 Qd1"},
        ],

        # ── ply 7 · White's fourth after 3...g6 ─────────────────────────────────
        "e4 e5 Qh5 Nc6 Bc4 g6": [
            {"san": "Qd1", "severity": "playable", "tier": "Structure",
             "why": "The engine's admission: go home, having spent two tempi learning that Black knows the defence. Objectively best — and the honest end of the trap. The main line's 4.Qf3 asks one more question first, at the cost of a few centipawns.",
             "line": "Bg7 d3"},
            {"san": "Qe2", "severity": "playable", "tier": "Structure",
             "why": "A retreat onto a forkable diagonal: 4...b5! 5.Bxb5 Nd4 hits queen and bishop at once and wins the pawn back with interest. Even dodged, the queen has taken the e2-knight's square — she keeps getting in her own army's way, which is the story of this opening.",
             "line": "b5 Bxb5 Nd4"},
            {"san": "Qh4", "severity": "blunder", "tier": "Foundation",
             "why": "The queen stays on the h-file and simply hangs: 4...Qxh4 wins her for nothing — the g5 and h4 squares belong to Black's queen from d8 the moment the g-pawn moved. Check every queen retreat against the d8–h4 diagonal.",
             "line": "Qxh4"},
            {"san": "Qh3", "severity": "blunder", "tier": "Foundation",
             "why": "Sidestepping onto the one diagonal Black is about to open: 4...d5! and the c8-bishop wins the queen or forces her to run while Black's centre arrives with tempo after tempo.",
             "line": "d5 Qd3 dxc4 Qxd8+ Kxd8"},
        ],

        # ── ply 8 · Black's answers to 4.Qf3 — the second wave ──────────────────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3": [
            {"san": "Nd4", "severity": "blunder", "tier": "Foundation",
             "why": "The right knight to the right square at exactly the wrong moment: it hits the queen and abandons the mate defence — 5.Qxf7 is mate, right now. The second wave is still a mate threat; answer it first, fork later.",
             "line": "Qxf7#"},
            {"san": "f6", "severity": "inaccuracy", "tier": "Foundation",
             "why": "It stops the mate and nothing else: the king's diagonal is weakened for good, g6 has no defender behind it, and after 5.Ne2 White develops against a position full of holes. The cost is not a piece — it is every later attack down the light squares.",
             "line": "Ne2 Bg7 Nbc3"},
            {"san": "d5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The right break at the wrong time: 5.Bxd5 takes a clean pawn — the d5-square is attacked twice and defended once, and the mate threat on f7 means the c6-knight cannot help. Count defenders before pushing in front of your own king.",
             "line": "Bxd5 Qd7 Ne2"},
            {"san": "Nh6", "severity": "playable", "tier": "Foundation",
             "why": "A piece defence of f7 that develops toward the rim. It holds comfortably enough here — but 4...Nf6 does the same job while attacking e4, and the difference between the two knights is the difference between defending and playing.",
             "line": "Ne2 Na5 d3 Nxc4 dxc4"},
        ],

        # ── ply 9 · White's fifth after 4...Nf6 — retreat or double down ────────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6": [
            {"san": "Qb3", "severity": "blunder", "tier": "Structure",
             "why": "The third lunge: the queen hits b7 and stacks up behind the bishop against f7 — and it loses by force. 5...Nd4! hits the queen and covers c2's counter-tricks, and even White's best wriggle — 6.Bxf7+ Ke7 — leaves the bishop trapped in Black's camp. The punishment is drilled move by move in its own line.",
             "line": "Nd4 Bxf7+ Ke7 Qc4",
             "see": "scholarsmate#punishing"},
            {"san": "Qd3", "severity": "inaccuracy", "tier": "Structure",
             "why": "A retreat that stands on the wrong file: 5...d5! breaks open the centre with the queen in the crossfire — 6.Bxd5 Nxd5 7.Qxd5 Qg5! and Black's pieces arrive before White's ever move. The cost is close to two pawns of evaluation.",
             "line": "d5 Bxd5 Nxd5 Qxd5 Qg5"},
            {"san": "g4", "severity": "blunder", "tier": "Structure",
             "why": "Lunging with a pawn at a knight that simply steps to the fork square: 5...Nd4 6.Qd1 d5! and White's position has a hole on every light square with the king still in the middle. The g-pawn cannot come back.",
             "line": "Nd4 Qd1 d5"},
        ],

        # ── ply 10 · Black's answers to 5.Qb3 ───────────────────────────────────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Qb3": [
            {"san": "Qe7", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Guarding everything with one queen move — it holds, and it hands back most of what the fork would have won. Black stays better; the point of this position is that 5...Nd4! wins material, and a defence that merely survives is the expensive choice.",
             "line": "Nf3 Nxe4 O-O"},
            {"san": "d5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The right break a move early: 6.Bb5! pins the c6-knight and White untangles at the cost of a pawn's worth of position instead of a piece. The fork move first — the break keeps.",
             "line": "Bb5 Nxe4 Nc3"},
        ],

        # ── ply 11 · White's sixth after 5...Nd4 — every road is downhill ───────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Qb3 Nd4": [
            {"san": "Qc3", "severity": "inaccuracy", "tier": "Structure",
             "why": "Guarding c2 and forgetting the third prong: 6...Nxe4! — the fork was never only about the queenside, and the c3-queen is now the target of a discovered knight dance. The desperado 6.Bxf7+ was the least bad; this loses more.",
             "line": "Nxe4 Qa5 b5"},
            {"san": "Qd3", "severity": "inaccuracy", "tier": "Structure",
             "why": "The retreat that keeps c2 covered and still walks into 6...d5! — every square the queen has leads downhill from here; this one merely skips the desperado check that the main line at least collects a pawn with.",
             "line": "d5 Bb3 Nxe4"},
        ],

        # ── ply 15 · White's queen has three squares — two lose more ────────────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Qb3 Nd4 Bxf7+ Ke7 Qc4 b5": [
            {"san": "Qxb5", "severity": "blunder", "tier": "Foundation",
             "why": "The pawn was bait with a hook in it: 8...Nxb5 — the d4-knight has covered b5 since the fork began. A queen for a knight, and the game with it.",
             "line": "Nxb5"},
            {"san": "Qc3", "severity": "inaccuracy", "tier": "Structure",
             "why": "One square worse than d3: on c3 the queen stands where 8...Nxe4! hits her yet again, and the knight dance costs White more than the bishop already spent. The d3-retreat at least caps the bill at one piece.",
             "line": "Nxe4"},
        ],

        # ── ply 12 (defence line) · White's sixth in the main defence ───────────
        "e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Ne2 Bg7 Nbc3": [
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "why": "The solid continuation the White chapter follows: second guard on e5, diagonal for the c8-bishop, and castling next. The immediate 6...Nd4 is the sharper cash-in.",
             "see": "scholarsmate#met-correctly"},
            {"san": "Nd4", "severity": "playable", "tier": "Structure",
             "why": "The fork square again — this time fully prepared. The e2-knight holds the square, but the queen still has to answer, and every answer costs White another beat of development.",
             "see": "scholarsmate#defusing"},
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "King safety first never hurts here — the counterattack keeps: ...Nd4 and ...d5 work just as well one move later, with the king already tucked away.",
             "line": "d3 d6 O-O"},
        ],
    },
    "progression": {
        "arc": "One geometry — two attackers on f7 — learned so thoroughly from both chairs that neither the mate nor the fear of it ever costs you a game again.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "One sitting",
                "goal": "Know the mate cold, and the three answers colder.",
                "learn": [
                    "The mate line as White: Qh5, Bc4, Qxf7# — and exactly why the king has no escape: guarded f7, covered d7, occupied d8.",
                    "The three quiet losers: 2...g6??, 3...d6??, 3...Nd4?? — each one a natural move, each one losing on the spot, each for a reason you can say out loud.",
                    "The defence as a script: ...Nc6, ...g6, ...Nf6. Three moves, all developing, both threats dead.",
                ],
                "drill": "Drill the mate line, then the defence line, alternating, until the answers come from your hands. Ten minutes covers both.",
                "mistake": "Blocking with ...g6 before ...Nc6 has guarded e5. The counter-blunder loses a whole rook, and it comes from knowing the defence's moves without knowing their order.",
                "ready": "You can state, without a board, why 4.Qxf7 is mate after 3...Nf6 but loses the queen after 4...Nf6.",
            },
            {
                "tier": "Structure",
                "when": "The following week",
                "goal": "Turn the defence into a refutation.",
                "learn": [
                    "The queen hunt: 5.Qb3 Nd4! and the fork geometry — queen and c2, then the trapped bishop after Bxf7+ Ke7.",
                    "What to do when White retreats correctly: bank the tempo, develop with threats, and play the resulting position like a normal opening you are winning slightly.",
                    "The ...Nd4 fork square as a permanent feature — it works on move five, and it still works on move eight in the deep dive.",
                ],
                "drill": "Play the punishment line from Black until 8...Kxf7 is automatic, then set an engine to play 2.Qh5 with random follow-ups and refute whatever comes.",
                "mistake": "Chasing the queen with weakening pawn moves instead of developing pieces. Every tempo you win must leave a piece better placed, or you are spending the lead, not growing it.",
                "ready": "An early queen on your board makes you quietly happy, from either chair.",
            },
        ],
        "study": "Any beginner's tactics collection has a hundred Scholar's Mate games. For the other chair, look up how the Wayward Queen Attack has been used as a surprise weapon in blitz — even strong players have tried 2.Qh5, and the games where it meets the full defence are the best argument this page makes.",
        "next": "The Italian Game: the same bishop on c4 and the same designs on f7, built with developing moves instead of the queen. It is what 2.Qh5 grows up into.",
    },
}
