OPENING = {
    "id": "scotch",
    "name": "Scotch Game",
    "eco": "C44–C45",
    "section": "white-e4",
    "orientation": "white",
    "tagline": "Open the centre on move three. Far less theory than the Ruy, and it fights for an advantage immediately.",
    "level": "Beginner → Master",
    "theory": {
        "big_idea": "White plays d4 at once, exchanges in the centre and gets an open position with a small development lead. Where the Ruy Lopez builds pressure over thirty moves, the Scotch resolves the central tension immediately. The trade-off: releasing the tension gives Black clear equalising targets, so White's edge is small — but the positions are easy to understand and there is far less to memorise.",
        "structure": "After 3...exd4 4.Nxd4, White has a pawn on e4 against Black's pawn on d6/d7 — a small space edge and a half-open d-file. In the Mieses main line, White ends up with a healthy 4v3 queenside majority while Black has doubled c-pawns and the bishop pair, exactly the sort of imbalance you can play for a win with.",
        "white_plans": [
            "Occupy the centre with e4–e5 gaining space and driving Black's knight away.",
            "Play against the doubled c-pawns with a healthy queenside majority; steer toward endgames.",
            "Castle queenside in the Mieses line and push the kingside pawns with g3, Bg2, f4 and h4.",
            "In the 4...Bc5 lines, kick the bishop with Nb3 or challenge it with Be3, and aim for a Maroczy-style bind with c4.",
        ],
        "black_plans": [
            "4...Bc5 hitting the knight on d4 and provoking a concession; then ...Qf6 and quick development.",
            "4...Nf6 aiming for the Mieses lines with the bishop pair and pressure on White's e5-pawn.",
            "Break with ...d5 as soon as possible to free the position — the standard antidote to a space advantage.",
            "Target the e5-pawn with ...Qe7, ...Ba6 and ...O-O-O.",
        ],
        "traps": [
            "4.Nxd4 Qh4?! 5.Nc3! (not 5.Nf5?? Qxe4+) — Black's early queen sortie is bad but you must know the refutation.",
            "In the Scotch Gambit (4.Bc4), 4...Bc5 5.Ng5?! Nh6! and White has nothing; do not chase f7 blindly.",
            "4...Bc5 5.Nxc6 Qf6! is the point — Black regains the piece; White should meet 4...Bc5 with 5.Nb3 or 5.Be3.",
        ],
        "who": "Play this if you want an open, principled 1.e4 opening without memorising a Ruy Lopez encyclopaedia. Kasparov revived it at world-championship level in the 1990s.",
    },
    "lines": [
        {
            "name": "Mieses Variation — Main Line",
            "note": "The modern main line. White gains space with e5 and plays against the doubled c-pawns.",
            "moves": "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 e5 Qe7 Qe2 Nd5 c4 Ba6 b3 O-O-O g3",
            "notes": {
                5: "The Scotch. White strikes at once instead of building slowly. Black almost has to take, because 3...d6 4.dxe5 gives White a clear space edge.",
                6: "Accepting. Black temporarily wins a pawn back but White will regain it immediately with a lead in development.",
                7: "Recapturing with the knight. It looks great on d4 — but it is also a target, and much of the theory revolves around chasing it.",
                8: "Hitting e4 and heading into the sharpest line.",
                9: "White voluntarily trades on c6 to damage Black's structure and gain a tempo for e4–e5.",
                10: "Forced: 5...dxc6? 6.Qxd8+ Kxd8 gives White a risk-free endgame edge and Black loses castling rights.",
                11: "Kicking the knight and grabbing serious space. This pawn will be both White's pride and White's biggest weakness for the rest of the game.",
                12: "The star move. Black pins the e5-pawn against the white king along the e-file, so the knight on f6 cannot simply be captured.",
                13: "The only good answer: White unpins by stepping the queen onto the same file. Now the pin is neutralised.",
                14: "The knight jumps to the strong central outpost, attacking nothing yet but sitting beautifully.",
                15: "White challenges the knight immediately. It has to decide: b6 (passive) or the sharp lines after ...Ba6.",
                16: "Both hitting c4 and preparing ...O-O-O. Black's bishop is unusually active for a Scotch.",
                17: "Propping up c4 with the pawn so the bishop cannot simply take.",
                18: "Black castles long and the game becomes a race: White attacks the queenside where Black's king is, Black attacks the e5-pawn and the kingside.",
                19: "Preparing Bg2 to hit c6 and contest the long diagonal. A rich, unbalanced middlegame with chances for both.",
            },
        },
        {
            "name": "Classical Variation — 4...Bc5",
            "note": "Black's most natural reply: develop with tempo by hitting the d4-knight.",
            "moves": "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3 Qf6 c3 Nge7 Bc4 Ne5 Be2 Qg6 O-O d6 Nd2",
            "notes": {
                8: "Developing with an attack on the knight. Note that 5.Nxc6?! Qf6! regains the piece for Black, so White must support d4 first.",
                9: "The best answer: White defends the knight and offers a trade of the strong bishop.",
                10: "Black avoids the trade and eyes both f2 and the b2/d4 squares. The queen is active here rather than exposed.",
                11: "Supporting d4 permanently, so the tension resolves in White's favour.",
                12: "Not 6...Nf6, which allows Bg5. The knight on e7 keeps things flexible and supports a later ...d5.",
                13: "Back to the Italian diagonal, hitting f7 and controlling d5.",
                14: "Black jumps in to hit the bishop and swap off White's most dangerous piece.",
                15: "Sidestepping. White keeps every piece and prepares f4 to kick the knight later.",
                16: "The queen slides off the f-file to a safe active square, eyeing g2.",
                17: "Castling into the position. White stands slightly better with the bishop pair potential and pressure on the d-file.",
                18: "Black solidifies the knight and prepares to develop the last bishop.",
                19: "The knight heads to f3 or b3 to challenge Black's active pieces. Balanced but rich.",
            },
        },
        {
            "name": "Scotch Gambit",
            "note": "Instead of recapturing on d4, White develops the bishop and plays for a rapid attack. Excellent at club level.",
            "moves": "e4 e5 Nf3 Nc6 d4 exd4 Bc4 Nf6 e5 d5 Bb5 Ne4 Nxd4 Bd7 Bxc6 bxc6 O-O Bc5",
            "notes": {
                7: "The Scotch Gambit. White declines to regain the pawn immediately and hurls a piece into the game aiming at f7.",
                8: "The best reply, counterattacking e4. Black should avoid 4...Bc5 5.c3! when White gets a strong centre for free.",
                9: "Kicking the knight and grabbing space. This is a real gambit now — White may not get the d4-pawn back at all.",
                10: "The correct counter. Black hits back in the centre and refuses to let White's attack build.",
                11: "Pinning the c6-knight so that the e5-pawn holds. A sharp and necessary move.",
                12: "The knight finds a great outpost in the middle of the board.",
                13: "Finally regaining the pawn. Material is level and both sides have active pieces.",
                14: "Unpinning and connecting the pieces.",
                15: "White resolves the tension, giving Black doubled c-pawns.",
                16: "Forced — 8...Bxc6 9.Nxc6 loses a piece to the fork.",
                17: "Castling and completing development. White plays against the doubled pawns; Black has the bishop pair and central pawns.",
                18: "Black develops with tempo on the d4-knight and the game is roughly balanced, but sharp.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the opposite-castling race",
        "note": "Both kings are committed. Watch White build slowly on the long diagonal while Black works to undermine the e5-pawn.",
        "moves": "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 e5 Qe7 Qe2 Nd5 c4 Ba6 b3 O-O-O g3 Nb6 Bg2 Qe6 O-O Kb7 Nd2 Be7 Bb2 Rhe8 Rfe1 f6 Nf3 fxe5 Nxe5",
        "notes": {
            20: "The knight steps back rather than be traded on d5. From b6 it hits c4 and watches the queenside.",
            21: "The bishop takes the long diagonal, pointing at c6 and a8 — straight at Black's king.",
            22: "The queen steps off the pinned file and takes aim at the weak e5-pawn from behind.",
            23: "White castles at last. Opposite wings, and the race begins.",
            24: "Tucking the king onto the square the b-pawn vacated. In opposite-castling positions one prophylactic king move is almost always worth it.",
            25: "The last piece develops, heading for f3 or e4 to shore up e5.",
            26: "Development, and the bishop covers the dark squares around the king.",
            27: "The bishop joins the long diagonal. Two pieces now aim through the doubled c-pawns at Black's king.",
            28: "The rook swings across to the e-file. Everything Black owns is now aimed at one pawn.",
            29: "White contests the same file. Notice that neither side has thrown a single pawn at the enemy king — in the Scotch the fight is over e5 first.",
            30: "The undermining move. If Black wins e5, White's space advantage disappears and the doubled pawns stop mattering.",
            31: "White reinforces. The e5-pawn is the entire argument of the position.",
            32: "Black cashes in and opens the f-file toward White's king.",
            33: "White recaptures with the knight, which lands centrally hitting c6, d7 and f7. Material is level, the structures are unequal, and the whole middlegame turned on one pawn. That is the Scotch in miniature.",
        },
    },
    "progression": {
        "arc": "The Scotch is the fast route to a real 1.e4 repertoire: open positions, clear plans, and roughly a tenth of the Ruy Lopez's theory.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Know what to do after 3...exd4 4.Nxd4 against each of Black's four replies.",
                "learn": [
                    "The two main branches: 4...Nf6 (Mieses) and 4...Bc5 (Classical). Learn one line against each and nothing more at first.",
                    "Why 5.Nxc6 is played in the Mieses — it damages Black's structure and buys the tempo for e4–e5.",
                    "The refutation of 4...Qh4: 5.Nc3! (never 5.Nf5?? Qxe4+).",
                ],
                "drill": "Play the Scotch exclusively for two weeks. The positions repeat quickly and you will learn the patterns fast.",
                "mistake": "Answering 4...Bc5 with 5.Nxc6? — Black plays 5...Qf6! and wins the piece back with a good game.",
                "ready": "You can reach move eight in both main branches without hesitation.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Learn to play with and against doubled pawns and a space advantage.",
                "learn": [
                    "The Mieses structure: Black's doubled c-pawns against White's healthy queenside majority. That majority is your winning plan.",
                    "The double edge of the e5-pawn: it grabs space and it is a permanent target for ...Qe7, ...Ba6 and ...O-O-O.",
                    "When to castle queenside yourself and turn the game into a race.",
                ],
                "drill": "Play out the Mieses tabiya after 9...O-O-O ten times from both sides. Notice how often the game is decided by whose attack lands first.",
                "mistake": "Defending the e5-pawn passively. It is a spearhead, not a possession — sometimes you give it up for activity.",
                "ready": "You can explain why the doubled c-pawns matter more in an endgame than a middlegame.",
            },
            {
                "tier": "Plans",
                "when": "Months two to four",
                "goal": "Convert the small opening edge into something.",
                "learn": [
                    "The queenside pawn majority: how to create a passed pawn against doubled pawns and trade into the endgame.",
                    "The kingside expansion with g3, Bg2, f4 and h4 in the opposite-castling lines.",
                    "Meeting ...d5 breaks: usually you take and blockade rather than push past.",
                ],
                "drill": "Take five of your own Scotch games and mark the exact move where you stopped having a plan. That is your study list.",
                "mistake": "Trading pieces without a reason. Your edge is space and structure — trade pawns to keep the structural plus, not pieces at random.",
                "ready": "You have won a Scotch endgame purely on the queenside majority.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Add the gambit lines and the anti-Scotch systems.",
                "learn": [
                    "The Scotch Gambit 4.Bc4 as a second weapon, especially against opponents who prepare 4.Nxd4 lines.",
                    "The Göring Gambit 4.c3 for when you want the game to catch fire.",
                    "How Black avoids the Scotch entirely with 2...Nf6 (Petrov) or 2...d6 (Philidor) — you need a plan against both.",
                ],
                "drill": "Prepare one complete line against the Petrov. It is the most common way strong players sidestep everything you have learned.",
                "mistake": "Assuming Black must play 2...Nc6. At club level roughly one game in five will not.",
                "ready": "Every Black second move has an answer in your file.",
            },
        ],
        "study": "Garry Kasparov's Scotch games from the early 1990s revived the whole opening. For the modern positional treatment, look at how Ian Nepomniachtchi and Anish Giri handle the Mieses.",
        "next": "The Scotch pairs naturally with the Italian — same principles, different pace. Learn both and you can choose the character of the game on move three.",
    },
}
