OPENING = {
    "id": "sicilian",
    "name": "Sicilian Defence",
    "eco": "B20–B99",
    "section": "black-e4",
    "orientation": "black",
    "tagline": "The most popular and most successful answer to 1.e4. Black plays to win, not to equalise.",
    "level": "Intermediate → World Championship",
    "theory": {
        "big_idea": "1...c5 refuses symmetry from move one. Black trades a flank pawn (c) for a central pawn (d) and gets, in return: a half-open c-file pointing straight at c2 and White's king if it castles queenside, and a 2-to-1 central pawn majority. The cost is that White gets a lead in development and space, and usually gets to attack first. Every Sicilian is a race — White attacks the kingside, Black attacks the queenside, and whoever is faster wins.",
        "structure": "After ...cxd4 the defining structure is the 'Sicilian small centre': Black pawns on d6 and e6/e5 against White's e4. The half-open c-file is Black's motorway. In the Najdorf and Dragon, White typically castles long and storms the kingside with f3, g4, h4; Black storms the queenside with ...b5, ...b4, ...a5 and sacrifices on c3.",
        "white_plans": [
            "English Attack: Be3, f3, Qd2, O-O-O, then g4 and h4 with a direct pawn storm.",
            "Yugoslav Attack against the Dragon: Bc4, Bе3, Qd2, O-O-O, h4–h5 and Bh6 trading the fianchetto bishop.",
            "The positional bind: c4 and Be2 (Maroczy Bind), taking away ...b5 and ...d5 and squeezing Black to death.",
            "The classical setup with Be2, O-O, f4 and a central e5 break.",
        ],
        "black_plans": [
            "Queenside expansion with ...a6, ...b5, ...b4 hitting the c3-knight, plus ...Rc8 and the exchange sacrifice ...Rxc3!",
            "Fight for the d5 square — the whole Najdorf is about whether Black gets in ...d5 in one move.",
            "The Dragon bishop on g7 pointing down the long diagonal at b2 and White's queenside king.",
            "Trade off White's dangerous attackers with ...Nxd4 or ...Ne5–c4.",
        ],
        "traps": [
            "Beware the Siberian Trap in the Smith-Morra: after ...Qc7 and ...Nf6, if White plays Nd5?? then ...Nxe4! wins.",
            "In the Najdorf Poisoned Pawn (6.Bg5 e6 7.f4 Qb6 8.Qd2 Qxb2), Black's queen goes on a raid — this is one of the most analysed positions in chess. Do not enter it unprepared.",
            "Black must never delay too long: many Sicilians are lost to a quick Nd5 or Nf5 sacrifice ripping open the centre before Black castles.",
        ],
        "who": "Play this if you want winning chances with Black and you do not mind sharp, theory-heavy positions. Fischer, Kasparov, Anand and Carlsen all built careers on it.",
    },
    "lines": [
        {
            "name": "Najdorf — English Attack",
            "note": "The most famous opening variation in chess, in its most popular modern form. Sharp, opposite-side castling, mutual attacks.",
            "moves": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4",
            "notes": {
                3: "The Open Sicilian move order. White prepares d4.",
                4: "Supporting a later ...e5 and controlling e5 now. The Najdorf, Dragon and Classical all start here.",
                5: "White opens the centre while ahead in development.",
                6: "The Sicilian bargain. Black trades a wing pawn for a centre pawn and gets the half-open c-file.",
                7: "The knight sits proudly in the centre — but it is also the piece Black will attack all game.",
                8: "Hitting e4 and forcing White to defend it.",
                9: "Defending e4 and eyeing d5 — the critical square in every Sicilian.",
                10: "The Najdorf move. It looks tiny, but it does three enormous things: it stops Nb5 and Bb5 forever, it prepares ...b5 to gain queenside space, and it makes ...e5 possible without the knight jumping to b5.",
                11: "The English Attack. White develops, prepares f3 and Qd2, and heads for queenside castling.",
                12: "The point of ...a6. Black grabs the centre and kicks the knight. Yes, it weakens d5 — the entire Najdorf is a bet that Black's activity outweighs that hole.",
                13: "Retreating to b3 where the knight watches c5 and a5 and stays out of the way.",
                14: "Bringing the bishop to its best square, guarding d5 (the hole!) and preparing ...Nbd7.",
                15: "Supporting e4 and, crucially, preparing g2–g4. The pawn storm begins.",
                16: "Development.",
                17: "Connecting the rooks and preparing O-O-O.",
                18: "Black castles into the coming storm — but Black is castling toward safety relative to the counterattack Black is about to launch.",
                19: "White commits the king to the queenside. The race is now official: White's pawns come at Black's king, Black's pawns come at White's.",
                20: "Supporting the e5-pawn and preparing ...b5, ...Nb6 and ...Rc8.",
                21: "The storm begins. g4–g5 will hit the f6-knight, then h4–h5. Black must be fast: ...b5, ...Nb6, ...Na4 and ...Rc8 with the exchange sacrifice on c3 always in the air.",
            },
        },
        {
            "name": "Accelerated Dragon — Maroczy Bind",
            "note": "Black fianchettoes early to avoid the Yugoslav Attack. White answers with the space-gaining Maroczy Bind.",
            "moves": "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 c4 Bg7 Be3 Nf6 Nc3 O-O Be2 d6 O-O Bd7 Qd2 Nxd4 Bxd4 Bc6",
            "notes": {
                4: "Black develops the knight first instead of ...d6. The point: Black wants to play ...d5 in one move, not two.",
                8: "The Accelerated Dragon. By omitting ...d6, Black threatens ...d5 immediately — the ideal freeing break.",
                9: "The Maroczy Bind. White stops ...d5 and ...b5 forever with a pawn wedge on c4 and e4. Black gets a very cramped but very solid position with no weaknesses.",
                10: "The Dragon bishop points down the long diagonal at d4 and b2 — Black's best piece in every Dragon line.",
                11: "Reinforcing d4 against the bishop's pressure.",
                12: "Development.",
                13: "Development.",
                14: "King safety.",
                15: "Note the bishop goes to e2, not c4 — in the Maroczy the c4-pawn already does the bishop's job.",
                16: "Solid, preparing ...Nd7 and ...a5.",
                17: "King safety.",
                18: "The bishop heads for c6 to pressure e4 along the long diagonal — Black's standard regrouping.",
                19: "Connecting and preparing Rac1/Rfd1.",
                20: "Black trades off a strong white piece and relieves the cramp. This is Black's core method against a bind: trade pieces, keep the structure.",
                21: "White recaptures and offers the trade of dark-squared bishops.",
                22: "Black's bishop takes its ideal post. White is slightly better with more space, but Black is extremely solid and has a clear plan of ...a5, ...Nd7 and ...Bxd4.",
            },
        },
        {
            "name": "Sveshnikov Variation",
            "note": "Black accepts a weak d5-square and a shattered kingside in exchange for enormous piece activity. Carlsen used it in a World Championship match.",
            "moves": "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5 Bxf6 gxf6 Nd5 f5 c3 Bg7",
            "notes": {
                10: "The Sveshnikov. Black plays ...e5 immediately, kicking the knight but permanently weakening d5. For fifty years this was thought to be bad; then Sveshnikov proved it works.",
                11: "The knight jumps to b5, hitting d6 — the immediate consequence of Black's ...e5.",
                12: "Forced.",
                13: "Pinning the knight that guards d5, and threatening to take and permanently plant a knight on d5.",
                14: "Kicking the knight to the edge before it settles.",
                15: "The knight has to go to a3, the worst square on the board — but it will come back via c2 or c4.",
                16: "Grabbing space and stopping the knight from returning via c4.",
                17: "White cashes in, giving Black doubled f-pawns.",
                18: "Recapturing toward the centre. Black's kingside looks wrecked, but the g-file is now a highway for the rook and the f6-pawn controls e5.",
                19: "The knight occupies the famous hole. It looks dominant.",
                20: "Black immediately attacks e4 and prepares ...f4 or ...Bg7. This is the whole Sveshnikov philosophy: activity beats structure.",
                21: "Supporting the knight and preparing Nc2–e3.",
                22: "The bishop goes to the long diagonal, and Black is ready for ...O-O, ...Be6 and ...f4. Wildly unbalanced and full of winning chances for both sides.",
                9: "Development, guarding e4 and eyeing d5 — the square the whole Sveshnikov is about.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the English Attack race",
        "note": "Both sides ignore defence completely. Count the tempi as the pawns run at each other.",
        "moves": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4 b5 g5 b4 Ne2 Ne8 f4 a5 f5 a4 Nbd4 exd4 Nxd4",
        "notes": {
            22: "The Najdorf counterattack begins. Black's pawns move toward White's king exactly as White's move toward Black's.",
            23: "White gains a tempo by hitting the f6-knight. Every attacking move that also gains time is worth two.",
            24: "Black hits the knight that defends e4 and d5. This is the standard Sicilian lever, and it usually decides where White's pieces end up.",
            25: "The knight retreats to e2 rather than a4 or b1, keeping it in play and heading for g3 or d4.",
            26: "The knight steps back to make room for the f-pawn and to head for c7 and b5 or d6.",
            27: "The pawn storm continues. White has spent five moves on pawns and none on defence.",
            28: "So has Black. Neither king has a single defensive piece nearby.",
            29: "Hitting the bishop on e6 and threatening to open the f-file.",
            30: "Black ignores it and pushes on, attacking the b3-knight. This is the moment the position becomes pure arithmetic.",
            31: "The knight moves and lands centrally, blocking the pawn's advance.",
            32: "Black eliminates the strong knight.",
            33: "White recaptures with the other knight, which now sits on d4 hitting e6 and c6. The position is somewhere near balanced and utterly unclear. But notice what neither player did at any point: defend. In the English Attack, the player who spends a move on safety is usually the player who loses.",
        },
    },
    "progression": {
        "arc": "The Sicilian is the biggest body of theory in chess. The way through it is to learn one variation properly rather than six badly.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to three",
                "goal": "Choose one Sicilian and understand the trade you are making.",
                "learn": [
                    "The core bargain: you give up a wing pawn for a centre pawn and receive the half-open c-file. Everything else follows from that.",
                    "Pick one: Najdorf (sharpest, most theory), Accelerated Dragon (solid, less theory), Sveshnikov (unbalanced, forcing), Kan/Taimanov (flexible, low theory).",
                    "The Anti-Sicilians you will actually face more than the Open: 2.Nc3, 2.c3 (Alapin), 3.Bb5 (Rossolimo/Moscow) and the Smith-Morra.",
                ],
                "drill": "Prepare your Anti-Sicilian answers first. Below master level you will meet 2.c3 and 3.Bb5 more often than the Open Sicilian.",
                "mistake": "Learning twenty moves of the Najdorf and nothing against 2.c3. You will lose to the Alapin repeatedly and never reach your preparation.",
                "ready": "You have one line against every White second and third move, written down.",
            },
            {
                "tier": "Structure",
                "when": "Months one to three",
                "goal": "Learn your chosen structure's skeleton and the squares that decide it.",
                "learn": [
                    "In the Najdorf: the d5 square. Every move in the opening is about whether Black achieves ...d5 in one move or not.",
                    "In the Dragon and Accelerated Dragon: the long diagonal and the g7-bishop. It is worth more than a rook in many positions.",
                    "In every Sicilian: the half-open c-file, the exchange sacrifice ...Rxc3, and the ...b5–b4 lever.",
                ],
                "drill": "Play out your tabiya twenty times from move ten. Do not study new lines until the tabiya is second nature.",
                "mistake": "Playing ...d5 because it is 'freeing' when it loses a pawn or a piece. Count the defenders every time.",
                "ready": "You know the key square in your variation and can explain what happens if you never control it.",
            },
            {
                "tier": "Plans",
                "when": "Months three to nine",
                "goal": "Win the race.",
                "learn": [
                    "The counting principle in opposite-castling positions: count how many moves each attack needs. That number, not the evaluation, decides the game.",
                    "The standard sacrifices: ...Rxc3 (exchange), ...Nxe4 (opening lines), ...b4 and ...a5–a4 (pure pawns).",
                    "When to defend instead: ...h5 stopping the g-pawn, ...Kb8 and ...Rc8 tucking away.",
                ],
                "drill": "Take ten opposite-castling Sicilians and, at move fifteen, count both attacks before looking at the result. Train the counting.",
                "mistake": "Defending passively. In a race, one defensive move is one attacking move you did not make — defend only when the arithmetic demands it.",
                "ready": "You can look at an English Attack position and say who is faster, with a reason.",
            },
            {
                "tier": "Mastery",
                "when": "Year two and beyond",
                "goal": "Depth in your line, plus the endgames.",
                "learn": [
                    "Your variation's deepest branches — in the Najdorf that means the Poisoned Pawn and the 6.Bg5 complex.",
                    "The Maroczy Bind and how to break it: ...b5 sacrifices, ...Nxd4 trades and the ...f5 break.",
                    "Sicilian endgames: the queenside majority Black often has, and why a good knight beats a bad bishop in these structures.",
                ],
                "drill": "Analyse five of your own losses in the Sicilian and classify them: lost the race, lost the structure, or lost to preparation. Fix the biggest category.",
                "mistake": "Switching variations after a loss. Depth beats breadth in the Sicilian by an enormous margin.",
                "ready": "You have a line you have played fifty times and still find new ideas in.",
            },
        ],
        "study": "Fischer and Kasparov for the Najdorf, Carlsen and Caruana for the modern Sveshnikov — their 2018 World Championship match is the best available course in it.",
        "next": "Once one Sicilian is deep, add a second as a surprise weapon rather than starting over. The structures overlap more than the move orders suggest.",
    },
}
