OPENING = {
    "id": "sicilian",
    "name": "Sicilian Defence",
    "eco": "B20–B99",
    "section": "semi-open",
    "orientation": "black",
    "tagline": "The most popular and most successful answer to 1.e4. Black plays to win, not to equalise.",
    "level": "Intermediate → World Championship",
    "theory": {
        "big_idea": "1...c5 refuses symmetry from move one. Black trades a flank pawn (c) for a central pawn (d) and gets, in return: a half-open c-file pointing straight at c2 and White's king if it castles queenside, and a 2-to-1 central pawn majority. The cost is that White gets a lead in development and space, and usually gets to attack first. Every Sicilian is a race — White attacks the kingside, Black attacks the queenside, and whoever is faster wins.",
        "structure": "After ...cxd4 the defining structure is the 'Sicilian small centre': Black pawns on d6 and e6 or e5 against White's e4, with the c-file half-open. In the Najdorf and Dragon, White typically castles long and storms the kingside with f3, g4, h4; Black storms the queenside with ...b5, ...b4, ...a5 and sacrifices on c3. But the trade only happens if White plays d4 — the Anti-Sicilians keep the d-pawn at home and ask a completely different question.",
        "white_plans": [
            "English Attack: Be3, f3, Qd2, O-O-O, then g4 and h4 with a direct pawn storm.",
            "Yugoslav Attack against the Dragon: Bc4, Be3, Qd2, O-O-O, h4–h5 and Bh6 trading the fianchetto bishop.",
            "The positional bind: c4 and Be2 (Maroczy Bind), taking away ...b5 and ...d5 and squeezing Black to death.",
            "Refuse the trade altogether: 2.c3, 2.Nc3 or 3.Bb5, keeping the d-pawn at home so that Black never gets the half-open c-file at all.",
        ],
        "black_plans": [
            "Queenside expansion with ...a6, ...b5, ...b4 hitting the c3-knight, plus ...Rc8 and the exchange sacrifice ...Rxc3!",
            "Fight for the d5 square — the whole Najdorf is about whether you get in ...d5 in one move.",
            "The Dragon bishop on g7 pointing down the long diagonal at d4 and b2 and White's queenside king.",
            "Trade off White's dangerous attackers with ...Nxd4 or ...Ne5–c4 — against a space advantage every trade is worth half a tempo.",
        ],
        "traps": [
            "The Siberian Trap in the Smith-Morra, and it is mate: 1.e4 c5 2.d4 cxd4 3.c3 dxc3 4.Nxc3 Nc6 5.Nf3 e6 6.Bc4 Qc7 7.O-O Nf6 8.Qe2 Ng4 9.h3?? Nd4! 10.Nxd4 Qh2#. The queen lands on h2 because White's own pawn has just left it, the knight on g4 defends her there, and the king has nowhere to go: f1 is its own rook, f2 and g2 are its own pawns, and h1 is covered from h2.",
            "In the Najdorf Poisoned Pawn (6.Bg5 e6 7.f4 Qb6 8.Qd2 Qxb2 9.Rb1 Qa3), your queen goes on a raid on move eight and does not come home for twenty moves. It is sound and it is the single most analysed position in chess. Do not enter it unprepared.",
            "The trap that costs you the game most often has no name: playing a useful-looking move in a position where White has a sacrifice on d5 or f5 ready. Before every quiet move, ask which of your pieces is the only defender of something.",
        ],
        "who": "Play this if you want winning chances with Black and you do not mind sharp, theory-heavy positions. Fischer, Kasparov, Anand and Carlsen all built careers on it. Be warned about the workload in the other direction: below master level you will meet the Anti-Sicilians far more often than the Open Sicilian, so that is where your first week goes.",
    },
    "lines": [
        {
            "name": "Najdorf — English Attack",
            "note": "The most famous opening variation in chess, in its most popular modern form. Sharp, opposite-side castling, mutual attacks.",
            "moves": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4",
            "tier": "Plans",
            "drill": True,
            "plan": {
                "structure": 'sicilian-small-centre',
                "tier": "Plans",
                "point": "White has spent one move on the attack and you have spent none. That is the whole deficit, and it is smaller than it looks: White's pawns have to reach g5 and h5 and then break through with a piece, while your ...b5 and ...b4 hit the knight on c3 on the way past. Three things cover d5 — that knight, the queen on d2 and the pawn on e4 — but the knight is the one that wants to land there, and chasing it is not the same as defending the square.",
                "next": [
                    "11...b5 is the move, and 12...b4 after it. The knight on c3 is the only piece holding both d5 and e4, so every move that hits it is worth two.",
                    "Behind the pawns come ...Nb6, ...Na4 and ...Rc8, and the exchange sacrifice ...Rxc3 is always in the air — it removes the defender of d5 and opens the b-file toward the king in the same move, because b2 is the pawn that has to recapture.",
                    "When g4–g5 comes, the f6-knight goes to e8: d7 is taken by your own knight, and from e8 it guards d6 and comes back via c7 to cover d5 and b5.",
                ],
                "endgame": "There is no endgame in this line and that is the honest verdict — it is decided in the middlegame. If the queens do come off, the pawn count is seven each and it is White's king that has less cover, because the f- and g-pawns have already left home and yours have not.",
            },
            "notes": {
                3: "The Open Sicilian move order. White prepares d4.",
                4: "Supporting a later ...e5 and controlling e5 now. The Najdorf, Dragon and Classical all start here.",
                5: "White opens the centre while ahead in development.",
                6: "The Sicilian bargain. You trade a wing pawn for a centre pawn and get the half-open c-file.",
                7: "The knight sits proudly in the centre — but it is also the piece you will attack all game.",
                8: "Hitting e4 and forcing White to defend it.",
                9: "Defending e4 and eyeing d5 — the critical square in every Sicilian.",
                10: "The Najdorf move. It looks tiny, but it does three enormous things: it stops Nb5 and Bb5 forever, it prepares ...b5 to gain queenside space, and it makes ...e5 possible without the knight jumping to b5.",
                11: "The English Attack. White develops, prepares f3 and Qd2, and heads for queenside castling.",
                12: "The point of ...a6. You grab the centre and kick the knight. Yes, it weakens d5 — the entire Najdorf is a bet that your activity outweighs that hole.",
                13: "Retreating to b3 where the knight watches c5 and a5 and stays out of the way.",
                14: "Bringing the bishop to its best square, guarding d5 (the hole!) and preparing ...Nbd7.",
                15: "Supporting e4 and, crucially, preparing g2–g4. The pawn storm begins.",
                16: "Development, and a square for the king. Note the bishop does not go to g7 here — with a pawn on e5 the long diagonal is blocked by your own pawn.",
                17: "Connecting the rooks and preparing O-O-O.",
                18: "You castle into the coming storm — but you are castling away from the side where your own counterattack is about to land, which is the whole logic of opposite-side castling.",
                19: "White commits the king to the queenside. The race is now official: White's pawns come at your king, your pawns come at White's.",
                20: "Supporting the e5-pawn and preparing ...b5, ...Nb6 and ...Rc8.",
                21: "The storm begins. g4–g5 will hit the f6-knight, then h4–h5. You must be fast: ...b5, ...Nb6, ...Na4 and ...Rc8 with the exchange sacrifice on c3 always in the air.",
            },
        },
        {
            "name": "Accelerated Dragon — Maroczy Bind",
            "note": "Black fianchettoes early to avoid the Yugoslav Attack. White answers with the space-gaining Maroczy Bind.",
            "moves": "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 c4 Bg7 Be3 Nf6 Nc3 O-O Be2 d6 O-O Bd7 Qd2 Nxd4 Bxd4 Bc6",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "You are cramped and you have no weaknesses, and against a bind that is the whole deal: White cannot break through without creating a target, so every piece you trade makes the extra space worth less.",
                "next": [
                    "12...a5 next, taking b4 from White's pieces and giving your own knight a5 and c5 to work with after ...Nd7.",
                    "...Nd7 and then ...Bxd4 — the trade you want is the dark-squared bishops, because after them White has no way to attack the dark squares your fianchetto left behind.",
                    "The break is ...b5, and it usually costs a pawn. Play it only when White's rook has left c1 or when ...Qb6 comes with it; otherwise wait, because the position does not get worse on its own.",
                ],
                "endgame": "Count before you trade into one, because the count is not symmetrical: seven pawns each, but White has three against two on the queenside thanks to the pawn on c4, and you have two against one in the centre. So White's extra queenside pawn is a real long-term asset and your central pair is the answer to it — trade pieces, not pawns, and keep the d6-pawn exactly where it is.",
            },
            "notes": {
                4: "You develop the knight first instead of ...d6. The point: you want to play ...d5 in one move, not two.",
                8: "The Accelerated Dragon. By omitting ...d6, you threaten ...d5 immediately — the ideal freeing break.",
                9: "The Maroczy Bind. White stops ...d5 and ...b5 with a pawn wedge on c4 and e4. You get a very cramped but very solid position with no weaknesses.",
                10: "The Dragon bishop points down the long diagonal at d4 and b2 — your best piece in every Dragon line.",
                11: "Reinforcing d4 against the bishop's pressure.",
                12: "Development.",
                13: "Development.",
                14: "King safety.",
                15: "Note the bishop goes to e2, not c4 — in the Maroczy the c4-pawn already does the bishop's job.",
                16: "Solid, preparing ...Nd7 and ...a5. The Accelerated Dragon has spent its accelerator: ...d5 is not coming, so ...d6 takes the square e5 away from White's pieces instead.",
                17: "King safety.",
                18: "The bishop heads for c6 to pressure e4 along the long diagonal — the standard regrouping.",
                19: "Connecting and preparing Rac1 or Rfd1.",
                20: "You trade off a strong white piece and relieve the cramp. This is the core method against a bind: trade pieces, keep the structure.",
                21: "White recaptures and offers the trade of dark-squared bishops.",
                22: "The bishop takes its ideal post, hitting e4 through the long diagonal. White is slightly better with more space, and you are extremely solid with a clear plan of ...a5, ...Nd7 and ...Bxd4.",
            },
        },
        {
            "name": "Sveshnikov Variation",
            "note": "Black accepts a weak d5-square and a shattered kingside in exchange for enormous piece activity. Carlsen used it in a World Championship match.",
            "moves": "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5 Bxf6 gxf6 Nd5 f5 c3 Bg7",
            "tier": "Mastery",
            "drill": True,
            "plan": {
                "tier": "Mastery",
                "point": "Look at what you have paid: a hole on d5 with a white knight already sitting in it, and doubled f-pawns. Look at what you bought: two bishops, the g-file, ...f4 coming, and a white knight stranded on a3.",
                "next": [
                    "12...O-O and then ...f4 — the pawn takes e3 away from the knight on a3 and frees f5 for your own pieces.",
                    "...Ne7 is the standard offer: trade the knight on d5 and the hole stops being a hole, because after exd5 the d5-pawn is a target and not a post.",
                    "...Be6 and ...Rc8 down the half-open c-file. Note who is guarding the pawn on c3: the knight on d5. Every rook you add to that file is one more reason the knight in your hole cannot move.",
                ],
                "endgame": "The two bishops are the reason to head for one. Pawns are seven each and yours are the uglier set, but doubled f-pawns matter far less than a pair of bishops on an open board — so trade the knights, keep both bishops, and open the position.",
            },
            "notes": {
                9: "Development, guarding e4 and eyeing d5 — the square the whole Sveshnikov is about.",
                10: "The Sveshnikov. You play ...e5 immediately, kicking the knight but permanently weakening d5. For fifty years this was thought to be bad; then Sveshnikov proved it works.",
                11: "The knight jumps to b5, hitting d6 — the immediate consequence of ...e5.",
                12: "Forced.",
                13: "Pinning the knight that guards d5, and threatening to take and permanently plant a knight on d5.",
                14: "Kicking the knight to the edge before it settles.",
                15: "The knight has to go to a3, the worst square on the board — but it will come back via c2 or c4.",
                16: "Grabbing space and stopping the knight from returning via c4.",
                17: "White cashes in, giving you doubled f-pawns.",
                18: "Recapturing toward the centre. Your kingside looks wrecked, but the g-file is now a highway for the rook and the f6-pawn controls e5.",
                19: "The knight occupies the famous hole. It looks dominant.",
                20: "You immediately attack e4 and prepare ...f4 or ...Bg7. This is the whole Sveshnikov philosophy: activity beats structure.",
                21: "Supporting the knight and preparing Nc2–e3 — and, as a side effect, leaving the c3-pawn backward on the file your rook wants.",
                22: "The bishop goes to the long diagonal, and you are ready for ...O-O, ...Be6 and ...f4. Wildly unbalanced and full of winning chances for both sides.",
            },
        },
        {
            "name": "Alapin — 2.c3",
            "note": "The Anti-Sicilian you will meet most often. White supports d4 with the c-pawn so that the Sicilian trade never happens — and pays for it by giving the b1-knight nowhere to go.",
            "moves": "e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3 Nc6 cxd4 d6 Bc4 Nb6 Bb5 dxe5 Nxe5 Bd7 Nxd7 Qxd7 Nc3 e6",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "structure": "isolani",
                "tier": "Structure",
                "point": "This is the whole point of 2...Nf6: you have traded White's ambitious pawn centre down to one isolated pawn on d4, and the square in front of it is yours. Blockade d5, trade pieces, and the isolani becomes what it is in every endgame — a pawn that needs defending.",
                "next": [
                    "...Be7 and ...O-O first. The pawn is not going anywhere and there is no rush; finish developing before you touch it.",
                    "...Nd5 or ...Nb4–d5 to blockade. A knight in front of an isolated pawn is worth more than the pawn it stops, and it cannot be driven off by another pawn.",
                    "Trade a pair of minor pieces at every honest opportunity, and refuse the tempting ...Nxd4 while White still has pieces aimed at your king.",
                ],
                "endgame": "This is where you are heading. Six pawns each and White's are the worse set: with the queens and a pair of rooks off, d4 needs a piece to hold it and your knight on d5 needs nothing. If you are ever offered a queen trade in this structure, take it.",
            },
            "notes": {
                3: "The Alapin. White wants to answer ...cxd4 with cxd4 and keep a pawn on d4 and e4 — the big centre the Open Sicilian gives up. The price is c3: the b1-knight's own square, so that piece has to find a home later or never come out at all.",
                4: "The critical answer, and the reason is arithmetic: it attacks e4, and the one piece that would normally defend e4 is the knight on b1, whose square White has just filled with a pawn.",
                5: "The pawn has to advance rather than be defended. It gains space and kicks the knight.",
                6: "The knight is perfectly happy here. It is not attacked, it eyes b4 and f4, and the only pawn that could chase it is the one on c3 — which would have to abandon d4 to do it.",
                7: "White builds the centre anyway.",
                8: "Taking at the moment White cannot recapture with the c-pawn and keep the knight on d5 hemmed in — after cxd4 the b1-knight still has no square.",
                9: "Development before recapture. 5.cxd4 first is the same position one move later.",
                10: "Hitting d4 immediately. Your knight on d5 and your knight on c6 both point at it.",
                11: "White recaptures and now owns an isolated d-pawn — no c-pawn and no e-pawn beside it.",
                12: "The break that dissolves White's last central asset. It hits e5 and prepares to open the position while your pieces are the better placed ones.",
                13: "Developing with tempo against the knight on d5.",
                14: "The knight steps back and hits the bishop. Note it does not go to f6 — from b6 it keeps an eye on d5 and c4.",
                15: "Sidestepping and pinning nothing yet; the bishop wants to be on the a4–e8 diagonal when your king is still in the middle.",
                16: "Cashing in. The e5-pawn was the last thing giving White space, and taking it leaves the isolated d-pawn alone on the board.",
                17: "Recapturing with the knight, which now stands on a square your bishop can chase it from.",
                18: "Offering the trade at once, because the knight on e5 is White's most active piece and your bishop is not.",
                19: "White takes.",
                20: "Recapturing with the queen, which now stands on the open d-file directly opposite the isolated pawn. That is not a coincidence — it is the plan.",
                21: "White's last piece finally comes out. Count the moves it took: the pawn went to c3 on move two, and the knight it displaced reaches c3 on move eleven.",
                22: "Taking d5 away from White's pieces and opening the bishop. Now ...Be7, ...O-O and a knight to d5, and the isolated pawn has nothing to do for the rest of the game.",
            },
        },
        {
            "name": "Rossolimo — 3.Bb5",
            "note": "The computer's own first choice against the Sicilian, and the reason many strong players never play the Open at all. White trades the bishop for the knight and plays against your doubled pawns.",
            "moves": "e4 c5 Nf3 Nc6 Bb5 g6 Bxc6 dxc6 d3 Bg7 h3 Nf6 Nc3 Nd7 Be3 e5 O-O O-O",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "State the bargain exactly. Eight pawns each; on the queenside you have four against three, and two of yours are on the c-file, so that majority can never make a passed pawn. In exchange you own the bishop pair, and the pawn on c5 covers d4 for the rest of the game.",
                "next": [
                    "...Nf8–e6 is the manoeuvre. From e6 the knight hits d4 and f4, and it is the only piece that stops White's own knight from settling on d5.",
                    "...Qe7 and ...b6, then ...Be6 or ...Ba6 depending on where White's queen goes. The light-squared bishop is now unopposed — White traded the only piece that could challenge it.",
                    "Break with ...f5 once the knight has left d7. The kingside is where your extra pawn actually is, and h3 has given you a hook.",
                ],
                "endgame": "The bishop pair is the asset and the doubled c-pawns are the liability, and which one decides it comes down to whether the position is open. So trade the knights, keep both bishops, and do not fix your own pawns with ...c4 — the pawn on c5 is doing real work where it stands.",
            },
            "notes": {
                5: "The Rossolimo, and it is not a Ruy Lopez: there is no pawn on e5 to attack, so the bishop is not pinning or pressuring anything. It is here to be traded for the knight, which is a real plan and a completely different one.",
                6: "The main answer. You will recapture on c6 with the d-pawn, and the fianchettoed bishop is exactly what that structure wants.",
                7: "White takes without being asked. Leaving the bishop on b5 lets you play ...Nd4 with tempo.",
                8: "Toward the centre, and this is the whole decision of the variation. ...bxc6 keeps the pawns healthier but shuts in the bishop; ...dxc6 doubles them and opens the d-file, the queen's diagonal and a route for the c8-bishop.",
                9: "White declines to open the position, because open positions favour your bishops.",
                10: "Onto the long diagonal, where the bishop stares at b2 through a square — d4 — that White can no longer occupy with a pawn.",
                11: "Taking g4 away from your bishop before it gets there. It is a useful move and it is also a hook: a pawn on h3 gives ...g5 and ...f5 something to hit.",
                12: "Development, and a second attacker on e4.",
                13: "Development.",
                14: "The knight steps aside so the e-pawn can advance, and heads for f8 and e6 — the square from which it covers d4, f4 and d8.",
                15: "White's bishop takes the diagonal that points at c5.",
                16: "The centre closes on your terms. The pawns on c5 and e5 both cover d4, so White's only central break — d3–d4 — can never be more than a trade.",
                17: "King safety.",
                18: "Both kings are safe and the position is closed, which is unusual for a Sicilian and completely fine for you: nobody is attacking, the manoeuvring starts, and you own the two bishops for when it opens.",
            },
        },
        {
            "name": "Closed Sicilian — 2.Nc3",
            "note": "White develops behind the pawns and plays for a slow kingside attack. There is very little theory here and a great deal of plan.",
            "moves": "e4 c5 Nc3 Nc6 g3 g6 Bg2 Bg7 d3 d6 f4 e6 Nf3 Nge7 O-O O-O Be3 Nd4",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": "Plans",
                "point": "Nobody has traded anything and there is no half-open c-file, so forget the Open Sicilian entirely. This is a King's Indian with colours reversed: White attacks on the kingside with f4–f5, you attack on the queenside with ...b5 and ...Rb8, and the winner is whoever gets there first.",
                "next": [
                    "9...Nd4 is already the plan: the knight cannot be driven off by a pawn, and if White ever trades on d4 your c-pawn recaptures toward the centre and the b-file opens.",
                    "...Rb8, ...b5 and ...b4. The knight on c3 is the only piece holding d5, so the pawn that hits it is the most valuable pawn you own.",
                    "Meet f4–f5 with ...exf5, not with ...e5. Taking keeps lines open on the side where your knight on d4 already sits; ...e5 shuts the centre and gives White a free hand with g4 and h4.",
                ],
                "endgame": "Pawns are eight each and level on both wings, so nothing here is decided by material — it is decided by which king got attacked. If the queens do come off with the centre still closed, the piece to want is a knight on d4: no white pawn can challenge it while White's own knight is standing on c3.",
            },
            "notes": {
                5: "The defining move of the Closed. White is not going to play d4 at all: the bishop goes to g2, the pawns stay put, and the attack comes later with f4 and f5.",
                6: "You mirror it. Against a closed centre the fianchetto is the right development, because the bishop's diagonal is the one line nobody can block with a pawn.",
                7: "The bishop eyes d5 and c6 through the centre.",
                8: "And yours eyes d4 and b2 through it.",
                9: "Propping up e4 and opening the c1-bishop's diagonal. White's centre is now fixed and modest — which is the point.",
                10: "The same. Both sides have built the same house, and the game will be decided by which wing each attacks.",
                11: "The Closed Sicilian's real move. White intends f4–f5 and a rook lift, and everything before this was preparation for it.",
                12: "Taking f5 and d5 away from White's pieces before either becomes a problem, and preparing ...Nge7 without blocking the c6-knight.",
                13: "Development, and support for the coming e-pawn advance.",
                14: "The knight goes to e7 rather than f6 so that it does not block the g7-bishop and so that both knights can reach d4 and f5.",
                15: "King safety.",
                16: "King safety.",
                17: "White prepares Qd2 and, in some lines, Bh6 to trade off the bishop that defends your king.",
                18: "The key square. A knight on d4 cannot be chased by a pawn — c3 is occupied by White's own knight — and if White ever takes it, ...cxd4 opens the c-file and gains a central pawn at the same time.",
            },
        },
        {
            "name": "Smith-Morra Gambit Accepted",
            "note": "A pawn for two tempi and open lines. It scores well below master level for exactly one reason: Black does not know what to do, and there is a mate in ten waiting for White if the wrong pawn moves.",
            "moves": "e4 c5 d4 cxd4 c3 dxc3 Nxc3 Nc6 Nf3 d6 Bc4 e6 O-O Nf6 Qe2 Be7 Rd1 e5 h3 O-O",
            "tier": "Structure",
            "drill": True,
            "plan": {
                "tier": "Plans",
                "point": "You are a pawn up, castled, and every White piece is aimed at you — which is the deal, and the deal is a good one as long as you never let a file open near your king. There is nothing left for White to develop, so from here White has to prove it or lose slowly.",
                "next": [
                    "...Be6 to trade the bishop on c4, which is the one White piece with a target. After the trade your extra pawn is simply an extra pawn.",
                    "...a6 and ...b5 next, taking d5 and b5 from the knights. In this structure every square you take away is a piece White has to move twice.",
                    "Never move the f-pawn or the g-pawn while a white rook is on d1 and a bishop on c4 — the whole gambit is a bet on your king, and it is the only bet White has left.",
                ],
                "endgame": "This is the answer to the Morra, and it is why 3...dxc3 is the critical move: pawns are seven to six, the extra one is a healthy central pawn on d6, and every trade makes it worth more. If you survive to move twenty-five with the material intact, you are simply winning a pawn-up endgame.",
            },
            "notes": {
                3: "The Smith-Morra. White will follow with c3, offering a pawn to open the c-file and the d-file and to get every piece out in six moves.",
                4: "Taking, because refusing on principle is how you end up worse: the pawn on d4 is White's, and leaving it there just gives White the centre for free.",
                5: "The gambit, and look at what it does to the file the Sicilian is played for. After ...dxc3 Nxc3 neither side has a c-pawn at all, so the c-file is fully open rather than half-open — it belongs to whoever puts a rook on it first, and White is several moves closer to doing that.",
                6: "Accepting. At depth twenty this is the engine's own first choice, and every decline hands part of the pawn straight back. Take it, and then defend properly.",
                7: "White recaptures with the knight, gaining the tempo the gambit was played for.",
                8: "Development, and the knight covers d4, e5 and a5.",
                9: "Development.",
                10: "The move that holds the position together. It takes e5 away from White's pieces and frees the c8-bishop — and it is the pawn every White plan in this gambit is aimed at for the next twenty moves.",
                11: "The Italian bishop, on the diagonal that points at f7 — and f7 is defended only by your king.",
                12: "Blunting it. Now the bishop stares at a pawn — and count what is aimed at d5: three white pieces and the e4-pawn, and one black pawn on e6 keeps all four of them out.",
                13: "King safety.",
                14: "Development, hitting e4.",
                15: "The last developing move, and it puts the queen behind the e-pawn and out of the way of the rooks.",
                16: "Development. The bishop goes to e7, not d6, so it does not block the d-pawn and so it does not stand on the file White's rook is about to seize.",
                17: "White's rook takes the file the gambit pawn opened. This is the move to respect: everything in the Morra flows down the d-file at the pawn on d6.",
                18: "The main line's answer, and it is a concession as much as a solution: ...e5 takes d4 away from White's pieces for good and leaves the pawn on d6 backward on the file White has just seized. It holds — d6 is attacked once and defended twice — but every White plan from here is about that pawn.",
                19: "Taking g4 away and giving the king air before starting anything.",
                20: "You are a pawn up, developed and castled, with no weaknesses and no open file near your king. From here the plan is ...Be6, ...a6 and trade — every exchange makes the extra pawn worth more.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the English Attack race",
        "note": "Both sides ignore defence completely. Count the tempi as the pawns run at each other.",
        "moves": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4 b5 g5 b4 Ne2 Ne8 f4 a5 f5 a4 Nbd4 exd4 Nxd4",
        "tier": "Mastery",
        "drill": True,
        "plan": {
            "structure": 'sicilian-small-centre',
            "tier": "Mastery",
            "point": "Seventeen moves and neither side has spent one on defence. Now count, and count honestly: on paper you are a knight up for a pawn, and it is worth nothing — the bishop on e6 is attacked twice and defended once, so it comes off next move and the engine calls the position a quarter of a pawn. That is what the last four moves were, on both sides: a trade with the tempo attached.",
            "next": [
                "17...b3! before anything else, and before you rescue the bishop. 18.Kb1 bxc2+ 19.Nxc2 drags the king to b1 and pulls a knight back to c2 — two defenders bought with one pawn, and the bishop was never going to survive anyway.",
                "The pawn on a4 is not passed and it does not need to be. It exists to reach a3, and once it does, b2 is defended by the king and by nothing else.",
                "Keep the knight on e8. It looks miserable, and it is the only piece covering both c7 and d6 — the two squares every White sacrifice on d5 needs.",
            ],
            "endgame": "Do not plan for one, and do not read the material count as an advantage: the bishop on e6 is already gone in every line, and what is left is roughly level. If you do reach an endgame, the asset is the half-open c-file and the pawn on a4, not the piece count on the board today.",
        },
        "notes": {
            22: "The Najdorf counterattack begins. Your pawns move toward White's king exactly as White's move toward yours.",
            23: "White gains a tempo by hitting the f6-knight. Every attacking move that also gains time is worth two.",
            24: "You hit the knight that defends e4 and d5. This is the standard Sicilian lever, and it usually decides where White's pieces end up.",
            25: "The knight retreats to e2 rather than a4 or b1, keeping it in play and heading for g3 or d4.",
            26: "The knight steps back to make room for the f-pawn and to head for c7 and b5 or d6.",
            27: "The pawn storm continues. White has spent five moves on pawns and none on defence.",
            28: "So have you. Neither king has a single defensive piece nearby.",
            29: "Hitting the bishop on e6 and threatening to open the f-file.",
            30: "You ignore it and push on, attacking the b3-knight. This is the moment the position becomes pure arithmetic.",
            31: "The knight moves and lands centrally, blocking the pawn's advance.",
            32: "You eliminate the strong knight.",
            33: "White recaptures with the other knight, which now sits on d4 hitting e6 and c6. The position is somewhere near balanced and utterly unclear. But notice what neither player did at any point: defend. In the English Attack, the player who spends a move on safety is usually the player who loses.",
        },
    },
    # Deviations, keyed by the position they answer. You are Black here, so with
    # two exceptions — the sets at odd ply, where the alternatives are your own —
    # every entry below is a move WHITE played instead, and `playable` means
    # playable for White and perfectly survivable for you.
    "branches": {

        # ══ WHITE'S SECOND MOVE — the Anti-Sicilians ════════════════════════════
        "e4 c5": [
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "name": "Alapin Variation",
             "why": "The Anti-Sicilian you will meet most often, and a real opening: White intends to answer ...cxd4 with cxd4 and keep two pawns abreast in the centre, so the trade the whole Sicilian is built on never happens. Answer 2...Nf6! — it attacks e4, and the piece that would normally defend e4 is the b1-knight, whose square White has just filled with a pawn. Step through the Alapin before you meet it.",
             "line": "Nf6 e5 Nd5 d4 cxd4 Nf3",
             "see": "sicilian#alapin"},
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "name": "Closed Sicilian",
             "why": "White is not going to play d4 at all. No trade, no half-open c-file, and almost no theory — what there is instead is a plan: g3, Bg2, d3, f4 and a kingside attack. You build the same house with ...Nc6, ...g6 and ...Bg7 and race on the other wing.",
             "line": "Nc6 g3 g6 Bg2 Bg7 d3",
             "see": "sicilian#closed"},
            {"san": "d4", "severity": "playable", "tier": "Structure",
             "name": "Smith-Morra Gambit",
             "why": "The gambit: 2...cxd4 3.c3 offers a pawn for two tempi and the open c- and d-files. Take it and keep it. At depth twenty accepting is the engine's own first choice from that position, and every polite decline hands part of the pawn straight back.",
             "line": "cxd4 c3 dxc3 Nxc3 Nc6 Nf3 d6",
             "see": "sicilian#morra"},
            {"san": "f4", "severity": "playable", "tier": "Foundation",
             "name": "McDonnell Attack",
             "why": "The Grand Prix Attack one move early, and the move order is what costs it: with the knight still on b1 nothing defends e4, so 2...d5! hits it at once. Recapture with the knight after 3.exd5 — 3...Nf6! — because 3...Qxd5 lets Nc3 come with tempo and is worth about a third of a pawn less.",
             "line": "d5 exd5 Nf6 Nc3 Nxd5 Nxd5 Qxd5"},
            {"san": "Bc4", "severity": "playable", "tier": "Foundation",
             "name": "Bowdler Attack",
             "why": "The Italian bishop in a position that is not the Italian. There it points at f7 down an open diagonal; here 2...e6 puts a pawn on the diagonal on move two and prepares ...d5 as well. Nothing to punish, nothing to fear — just develop.",
             "line": "e6 Nf3 Nf6 Qe2 Nc6"},
            {"san": "g3", "severity": "playable", "tier": "Foundation",
             "name": "Lasker-Dunne Attack",
             "why": "A King's Indian Attack set-up. It threatens nothing and it is not bad; you develop naturally with ...Nc6, ...g6 and ...Bg7 and reach a Closed Sicilian in which White has not even committed the b1-knight.",
             "line": "Nc6 Bg2 g6 Ne2 Bg7 O-O"},
            {"san": "b3", "severity": "playable", "tier": "Structure",
             "name": "Snyder Variation",
             "why": "White fianchettoes the dark-squared bishop toward e5 and g7. Meet the diagonal head on: after 2...g6 3.Bb2 Bg7 the two bishops face each other down a1–h8 and neither gets anywhere, which suits the side who did not spend two moves on the plan. At depth twenty this is already a quarter of a pawn to Black.",
             "line": "g6 Bb2 Nf6 e5 Nd5 d4"},
            {"san": "Ne2", "severity": "playable", "tier": "Structure",
             "name": "Keres Variation",
             "why": "A waiting move that keeps d4, f4 and Nbc3 all available at the cost of shutting in the f1-bishop for a move. It usually turns into an Open or a Closed Sicilian anyway, and you get to choose which by whether you allow d4.",
             "line": "Nf6 Nbc3 a6 e5 Ng4"},
            {"san": "b4", "severity": "inaccuracy", "tier": "Structure",
             "name": "Wing Gambit",
             "why": "A pawn offered to drag the c-pawn away from d4. Take it, and then hit the centre rather than clinging to it: 2...cxb4 3.a3 d5! 4.exd5 Qxd5 and you are a pawn up with every piece free to come out. At depth twenty that is more than half a pawn to Black, which is what a gambit with no development behind it is worth.",
             "line": "cxb4 a3 d5 exd5 Qxd5"},
        ],

        # ── ply 3 · your own second move after 2.Nf3 ────────────────────────────
        "e4 c5 Nf3": [
            {"san": "Nc6", "severity": "playable", "tier": "Foundation",
             "name": "Old Sicilian",
             "why": "Your other main move and the door to the Accelerated Dragon and the Sveshnikov. The concrete difference from 2...d6: the d-pawn stays at home so it can go to d5 in one move — and 3.Bb5, the Rossolimo, becomes available to White.",
             "line": "d4 cxd4 Nxd4 g6 c4",
             "see": "sicilian#accelerated"},
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "name": "Taimanov and Kan",
             "why": "The lowest-theory Open Sicilians there are: ...e6 with ...Nc6 and ...Qc7 is the Taimanov, with ...a6 the Kan. Flexible, solid, and you keep ...d5 as a one-move break. The price is that the c8-bishop has to go the long way out, usually to b7.",
             "line": "d4 cxd4 Nxd4 a6 Nc3"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "name": "Hyper-Accelerated Dragon",
             "why": "The fianchetto a move earlier still, and the point is to dodge the Yugoslav Attack. It usually transposes: 3.d4 cxd4 4.Nxd4 Nc6 5.c4 is the Maroczy Bind reached from the other door. The thing to know before you play it is that 3.d4 cxd4 4.Qxd4 is available here — no knight on c6 to hit the queen, and no bishop on g7 either.",
             "line": "d4 cxd4 Nxd4 Nc6 c4"},
        ],

        # ── ply 4 · White's third move after 2...d6 ─────────────────────────────
        "e4 c5 Nf3 d6": [
            {"san": "Bb5+", "severity": "playable", "tier": "Foundation",
             "name": "Moscow Variation",
             "why": "The check has to be blocked, and both blocks are sound: 3...Nd7 keeps the pawns healthy and defends c5 a second time, 3...Bd7 invites the trade of light-squared bishops and a quiet game. Nothing is lost except the Open Sicilian — White has no intention of playing d4 now.",
             "line": "Nd7 c4 g6 Nc3 Bg7"},
            {"san": "c3", "severity": "playable", "tier": "Foundation",
             "name": "Delayed Alapin",
             "why": "The Alapin a move later, and ...d6 has already taken the sting out of e4–e5. Develop simply: 3...Nf6 4.Be2 Bd7 and ...Qc7, and remember what c3 cost White — the b1-knight's own square.",
             "line": "Nf6 Be2 Bd7 Qc2 Qc7"},
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "why": "Flexible, and usually just a transposition: 3...Nf6 4.d4 cxd4 5.Nxd4 a6 and you are in the Najdorf with the moves in a different order. Nothing about your preparation changes.",
             "line": "Nf6 d4 cxd4 Nxd4 a6"},
            {"san": "c4", "severity": "playable", "tier": "Structure",
             "name": "Maroczy set-up",
             "why": "White claims d5 and b5 with a pawn before either knight comes out. Answer 3...e5, taking d4 away from White's pieces, and settle in for a manoeuvring game: 4.Nc3 g6 5.d3 Bg7 is level at depth twenty. Nobody is attacking anybody here for twenty moves.",
             "line": "e5 Nc3 g6 d3 Bg7"},
        ],

        # ── ply 4 · White's third move after 2...Nc6 ────────────────────────────
        "e4 c5 Nf3 Nc6": [
            {"san": "Bb5", "severity": "playable", "tier": "Foundation",
             "name": "Rossolimo Attack",
             "why": "Not a sideline — from the starting position of the Sicilian this is the move the engine itself picks. White trades bishop for knight and plays against your doubled c-pawns. There is nothing to refute and a great deal to understand; step through the Rossolimo line before you meet it.",
             "line": "g6 O-O Bg7 Re1 e5 Bxc6 dxc6",
             "see": "sicilian#rossolimo"},
            {"san": "Nc3", "severity": "playable", "tier": "Foundation",
             "why": "A waiting move, and it hands you a free option: 3...e5 stakes out d4 at once and costs nothing, because White's own knight is now standing on the square the c-pawn would need to challenge it from.",
             "line": "e5 Bc4 Be7 d3 d6"},
            {"san": "c3", "severity": "playable", "tier": "Structure",
             "name": "Delayed Alapin",
             "why": "The Alapin, and ...Nc6 was exactly the move that prepares the answer: 3...d5! 4.exd5 Qxd5 5.d4 Nf6 and the queen sits in the centre in complete safety, because the knight that would chase her cannot reach c3.",
             "line": "d5 exd5 Qxd5 d4 Nf6 Be2"},
            {"san": "Bc4", "severity": "playable", "tier": "Foundation",
             "name": "Delayed Bowdler",
             "why": "Club chess's favourite move, and it is not a mistake — it is just aimless. 3...Nf6 hits e4 and asks White to prove something; 4.d3 d6 5.O-O g6 and you have a comfortable Closed-style game with a bishop on c4 staring at a pawn on d5's neighbourhood.",
             "line": "Nf6 d3 d6 O-O g6 h3"},
        ],

        # ── ply 6 · White's fourth move, once the centre has been traded ────────
        "e4 c5 Nf3 d6 d4 cxd4": [
            {"san": "Qxd4", "severity": "playable", "tier": "Foundation",
             "why": "Recapturing with the queen, which gives back the tempo the Open Sicilian was played to win: 4...Nc6! develops and hits her at the same time. 5.Bb5 Bd7 6.Bxc6 bxc6 and you have both bishops and a solid pawn mass; White has a small lead in development and nothing else.",
             "line": "Nc6 Bb5 Bd7 Bxc6 bxc6"},
            {"san": "c3", "severity": "playable", "tier": "Structure",
             "why": "The Morra gambit offered a move late, and the delay helps you: ...d6 is a move you were going to play in the Morra defence anyway. 4...dxc3 5.Nxc3 Nc6 6.Bc4 e6 and you are a pawn up in the structure the Smith-Morra line teaches, with the useful move already made.",
             "line": "dxc3 Nxc3 Nc6 Bc4 e6",
             "see": "sicilian#morra"},
        ],

        # ══ NAJDORF ═════════════════════════════════════════════════════════════

        # ── ply 10 · White's sixth move: the great crossroads ───────────────────
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6": [
            {"san": "Bg5", "severity": "playable", "tier": "Mastery",
             "name": "6.Bg5 — the main line and the Poisoned Pawn",
             "why": "The sharpest move in the opening and the historical main line: the pin threatens Bxf6 and a permanent grip on d5. The critical answer is the Poisoned Pawn — 6...e6 7.f4 Qb6 8.Qd2 Qxb2 9.Rb1 Qa3 — where your queen spends twenty moves in White's camp and the engine says you are fine. It is also the single most analysed position in chess, so do not enter it on general principles.",
             "line": "e6 f4 Qb6 Qd2 Qxb2 Rb1 Qa3"},
            {"san": "Bc4", "severity": "playable", "tier": "Plans",
             "name": "Fischer-Sozin Attack",
             "why": "Fischer's move: the bishop takes the a2–g8 diagonal before you can block it, which is why the answer is 6...e6 immediately. After 7.a4 Be7 8.Be3 O-O you have a normal Scheveningen and White's bishop is biting on a pawn.",
             "line": "e6 a4 Be7 Be3 O-O"},
            {"san": "Be2", "severity": "playable", "tier": "Foundation",
             "name": "Opocensky Variation",
             "why": "The quiet one, and the one you will meet most often below master level. White castles short and plays for a small edge. 6...e5 7.Nb3 Be7 8.Be3 Be6 and there is no storm coming — this is a manoeuvring game about the d5 square, and you have all the moves you need for it.",
             "line": "e5 Nb3 Be7 Be3 Be6"},
            {"san": "f4", "severity": "playable", "tier": "Structure",
             "name": "Amsterdam Attack",
             "why": "White hits e5 before you can occupy it. Take the square anyway: 6...e5 7.Nb3 Nc6 8.Be2 Be7 and the pawn on f4 has committed White's kingside without a piece behind it yet.",
             "line": "e5 Nb3 Nc6 Be2 Be7"},
            {"san": "h3", "severity": "playable", "tier": "Structure",
             "name": "Adams Attack",
             "why": "An odd-looking pawn move with a real point: it prepares g4 without spending a move on f3, so the storm arrives a tempo sooner. Treat it as the English Attack and get on with your own plan — 6...e5 7.Nb3 Be6 8.Be3 Nbd7 and the race begins from the same start line.",
             "line": "e5 Nb3 Be6 Be3 Nbd7"},
            {"san": "g3", "severity": "playable", "tier": "Structure",
             "name": "Zagreb Variation",
             "why": "The bishop is going to g2 to fight for d5 from a distance, which is a completely different argument from the English Attack — no storm, just pressure on one square. 6...e5 7.Nb3 Be7 8.Bg5 O-O and you finish developing while White finishes the fianchetto.",
             "line": "e5 Nb3 Be7 Bg5 O-O"},
            {"san": "a4", "severity": "playable", "tier": "Plans",
             "why": "Prophylaxis: it stops ...b5 before you have spent a move preparing it, at the cost of the b4 square and a tempo White would rather spend attacking. 6...e5 7.Nf3 Be7 8.Bg5 Be6 and your knight will eventually be very happy on b4 or c5.",
             "line": "e5 Nf3 Be7 Bg5 Be6"},
            {"san": "e5", "severity": "blunder", "tier": "Foundation",
             "why": "Pushing past instead of defending, and it simply loses a pawn: 6...dxe5! and the knight on d4 has to move, so there is no recapture. 7.Nb3 Qc7 8.Bd3 Bd7 and you are a clean pawn up with a healthy structure. Note the shape of it — the d4-knight covers b5, c6, e6 and f5 and not one of them is e5.",
             "line": "dxe5 Nb3 Qc7 Bd3 Bd7"},
        ],

        # ── ply 11 · your own sixth move after 6.Be3 ────────────────────────────
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3": [
            {"san": "e6", "severity": "playable", "tier": "Plans",
             "name": "English Attack vs the Scheveningen",
             "why": "The other great answer, and the most popular alternative to 6...e5. A pawn on e6 covers d5 instead of conceding it, and the price is a cramped position and a backward pawn on d6 — nothing defends it once the e-pawn has gone past. Choose by temperament: ...e5 fights for space, ...e6 fights for the square.",
             "line": "Be2 Qc7 a4 Nc6 Nb3"},
            {"san": "Ng4", "severity": "playable", "tier": "Structure",
             "why": "Hitting the bishop at once, and it is a real line rather than a lunge — but count the moves. 7.Bc1 Nf6 and both sides have spent two moves to arrive back where they started, after which 8.f3 e5 is the English Attack again. Play it if you want to see whether White retreats to c1 or to g5.",
             "line": "Bc1 Nf6 f3 e5 Nb3"},
        ],

        # ── ply 13 · White's seventh, after 6...e5 kicks the knight ─────────────
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5": [
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "The other retreat. From f3 the knight eyes e5 and d4, and it blocks the f-pawn — which means no f3, no g4 and no pawn storm. The game becomes slow and that suits you: 7...Be7 8.Nd2 b5 and White has to build a completely different plan.",
             "line": "Be7 Nd2 b5 a4 b4"},
            {"san": "Nde2", "severity": "playable", "tier": "Structure",
             "why": "Keeping both knights and heading for g3 and f5. Solid, passive, and it shuts the f1-bishop in for now. 7...Be6 8.f4 g6 and you have the time to place every piece before anything happens.",
             "line": "Be6 f4 g6 g3 Nc6"},
            {"san": "Nf5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The knight jumps to a square it can be driven from, and the answer is not to drive it — it is to open the centre while it stands there. 7...d5! 8.Bg5 d4 and every white piece is short of squares. Kicking with ...g6 first would cost you the tempo the whole idea is built on.",
             "line": "d5 Bg5 d4 Bxf6 gxf6"},
        ],

        # ── ply 15 · White's eighth ─────────────────────────────────────────────
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6": [
            {"san": "Qd2", "severity": "playable", "tier": "Foundation",
             "why": "The same plan in a different order — Qd2 now, f3 next. Nothing changes for you: 8...Be7 9.f3 Nbd7 and you are back in the main line with the moves swapped.",
             "line": "Be7 f3 Nbd7 g4 b5"},
            {"san": "f4", "severity": "playable", "tier": "Plans",
             "why": "Hitting e5 before castling. Take it — 8...exf4 9.Bxf4 Nc6 10.Qd2 d5! — and you have the freeing break in one move, which is the thing the entire Najdorf is played to reach.",
             "line": "exf4 Bxf4 Nc6 Qd2 d5"},
            {"san": "g4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The storm one move too early, and there is nothing on g4: the f-pawn is still on f2 and the h-pawn does not reach. 8...Nxg4! takes it. 9.Bd2 Nc6 10.Qe2 Be7 and you are a pawn up. This is exactly what f2–f3 is for in the main line, and it is why White plays it first.",
             "line": "Nxg4 Bd2 Nc6 Qe2 Be7"},
        ],

        # ── ply 19 · White's tenth, with both sides fully developed ─────────────
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O": [
            {"san": "h4", "severity": "playable", "tier": "Plans",
             "why": "The h-pawn first, keeping g4 in reserve. It is the same race and White has spent a move on a pawn that is not attacking anything yet — so spend yours the same way: 10...b5 11.O-O-O Nbd7 12.g4 Nb6 and you are exactly level on tempi.",
             "line": "b5 O-O-O Nbd7 g4 Nb6"},
            {"san": "a4", "severity": "playable", "tier": "Plans",
             "why": "Stopping ...b5 before it starts, and it is a genuine plan — but it is also a move not spent on the attack. 10...Qc7 11.g4 d5! and the break arrives anyway, one file over from where White was looking.",
             "line": "Qc7 g4 d5 Nxd5 Bxd5"},
            {"san": "g4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Storming with the king still on e1, which is the one thing that makes the central break work: 10...d5! 11.exd5 Nxd5 12.Nxd5 Bh4+ and the check lands on the diagonal that f2–f3 opened. White has to block on f2 and the attack is over before it started.",
             "line": "d5 exd5 Nxd5 Nxd5 Bh4+"},
        ],

        # ── ply 22 · deep dive · White's twelfth, once both storms are moving ───
        "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4 b5": [
            {"san": "h4", "severity": "playable", "tier": "Mastery",
             "why": "Bringing the second pawn up before pushing the first. 12...Nb6 13.g5 Nh5 and the knight on h5 is awkward and perfectly safe, while your queenside pawns keep rolling at a king that has nowhere else to go.",
             "line": "Nb6 g5 Nh5 Na5 Rc8"},
            {"san": "Rg1", "severity": "playable", "tier": "Mastery",
             "why": "The rook goes behind the pawn before it moves. Same race, one more white piece in it — and one fewer move spent on the pawns. 12...Nb6 13.Na5 Rc8 and you do the identical thing on the other wing.",
             "line": "Nb6 Na5 Rc8 g5 Nh5"},
            {"san": "Qf2", "severity": "inaccuracy", "tier": "Mastery",
             "why": "The queen steps off the d-file to eye b6 and a7, and she was the piece supporting the jump to d5. 12...b4! at once: 13.Nd5 a5 14.Nxe7+ Qxe7 and the hole is gone, because a knight that has to trade itself was never occupying anything.",
             "line": "b4 Nd5 a5 Nxe7+ Qxe7"},
        ],

        # ══ THE ...Nc6 SICILIANS ════════════════════════════════════════════════

        # ── ply 7 · your own fourth move after 3...cxd4 4.Nxd4 ──────────────────
        "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "why": "Development first, and it keeps both big doors open: 5.Nc3 e5 is the Sveshnikov, 5.Nc3 d6 the Classical. The one thing it gives up is the Accelerated Dragon, because ...g6 and ...Nf6 together lose the ...d5-in-one-move point.",
             "line": "Nc3 e5 Ndb5 d6 Nd5",
             "see": "sicilian#sveshnikov"},
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "name": "Taimanov",
             "why": "The flexible one: ...Qc7, ...a6 and ...Nf6 in some order, with very little to memorise. Know one concrete line before you play it — 5.Nc3 Nf6 6.Nxc6 bxc6 7.e5 Nd5 gives White space and you a big central pawn mass with doubled c-pawns behind it.",
             "line": "Nc3 Nf6 Nxc6 bxc6 e5 Nd5"},
            {"san": "e5", "severity": "playable", "tier": "Mastery",
             "name": "Kalashnikov",
             "why": "The Sveshnikov without ...Nf6, which saves you a move and costs you a defender of d5. 5.Nb5 d6 6.c4 is the critical try, and it is the Maroczy Bind version of the same argument — White takes d5 with a pawn instead of a piece.",
             "line": "Nb5 d6 c4 g6 N1c3"},
        ],

        # ── ply 9 · White's fifth against the Accelerated Dragon ────────────────
        "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6": [
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "Declining the bind and heading for an ordinary Dragon — which is the one thing the Accelerated Dragon exists to avoid, because Bc4 and the Yugoslav Attack follow. 5...Bg7 6.Be3 Nf6 7.Bc4 O-O is playable and sharp; if you would rather not, ...Nf6 before ...Bg7 keeps the ...d5 break alive.",
             "line": "Bg7 Be3 Nf6 Bc4 O-O"},
            {"san": "Be3", "severity": "playable", "tier": "Structure",
             "why": "Development before commitment, and it usually transposes into either the bind or the Dragon within two moves. 5...Nf6 6.Nc3 Bg7 7.Bc4 Na5 and you go straight after the bishop that makes the Yugoslav Attack work.",
             "line": "Nf6 Nc3 Bg7 Bc4 Na5"},
            {"san": "Nxc6", "severity": "playable", "tier": "Plans",
             "why": "The move to know, because it comes with a trick: 5...bxc6 6.Qd4! and the queen hits h8 through the square your bishop has not reached yet. 6...Nf6 is the answer — develop and block, do not panic — 7.e5 Nd5 and the position is level. This is precisely why ...Bg7 is not an automatic move here.",
             "line": "bxc6 Qd4 Nf6 e5 Nd5"},
        ],

        # ── ply 9 · your own fifth move after 4...Nf6 5.Nc3 ─────────────────────
        "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3": [
            {"san": "d6", "severity": "playable", "tier": "Foundation",
             "name": "Classical Sicilian",
             "why": "The solid one. Every piece gets a normal square and you keep ...e5 and ...e6 both in reserve; 6.Bg5 e6 7.Qd2 is the Richter-Rauzer and the main test. Nothing here is wrong — it is simply a quieter bargain than the Sveshnikov.",
             "line": "Bg5 e6 Qd2 Nxd4 Qxd4 a6"},
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "name": "Four Knights Sicilian",
             "why": "Covering d5 with a pawn instead of conceding it. The critical answer is 6.Nxc6 bxc6 7.e5 Nd5 8.Ne4, when your c-pawns are doubled, your pawn mass in the centre is the compensation and White has the space. It is a real line and a different game from the one you drilled.",
             "line": "Nxc6 bxc6 e5 Nd5 Ne4"},
            {"san": "g6", "severity": "playable", "tier": "Structure",
             "name": "Dragon by transposition",
             "why": "The fianchetto one move late, and the lateness matters: with the knight already on f6, 6.Nxc6 dxc6 7.Qxd8+ Kxd8 trades queens and takes your castling rights in the same move. The resulting endgame is fine — but it is an endgame, on move seven, and it is not what you were playing for.",
             "line": "Nxc6 dxc6 Qxd8+ Kxd8 Bc4"},
        ],

        # ── ply 11 · White's sixth against the Sveshnikov ───────────────────────
        "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5": [
            {"san": "Nf3", "severity": "playable", "tier": "Structure",
             "why": "Retreating instead of jumping in. It costs White the whole point of ...e5 as a weakness, and it gives you a free hand: 6...Bb4! pins the knight that guards e4 and d5, and after 7.Bc4 O-O 8.O-O Bxc3 you have traded off the piece the hole was for.",
             "line": "Bb4 Bc4 O-O O-O Bxc3"},
            {"san": "Nf5", "severity": "playable", "tier": "Structure",
             "why": "The knight lands where it can be traded, and the answer is the break, not the kick: 6...d5! 7.exd5 Bxf5 and you have handed back the d5 square in exchange for the knight, the initiative and a white pawn on d5 that is a target rather than an outpost.",
             "line": "d5 exd5 Bxf5 dxc6 bxc6"},
            {"san": "Nde2", "severity": "playable", "tier": "Structure",
             "why": "The modest retreat, heading for g3. It keeps more pieces on than Nf3 and blocks the f1-bishop; 6...Bc5 7.Ng3 d6 and you have the extra central pawn and the more natural development.",
             "line": "Bc5 Ng3 d6 Na4 Bb4+"},
            {"san": "Nxc6", "severity": "playable", "tier": "Structure",
             "why": "Trading first. 6...bxc6! is the recapture — toward the centre, and it opens the b-file for the rook. You get doubled c-pawns and a big pawn mass; White gets nothing in particular, which is why this is not the critical move.",
             "line": "bxc6 Bc4 Bb4 Qf3 O-O"},
        ],

        # ── ply 13 · White's seventh in the Sveshnikov ──────────────────────────
        "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6": [
            {"san": "Nd5", "severity": "playable", "tier": "Mastery",
             "name": "7.Nd5 — the modern main line",
             "why": "The move Carlsen and Caruana argued over for a whole World Championship match. Instead of pinning first, White puts the knight on the hole immediately. 7...Nxd5 8.exd5 Nb8! — the knight goes home to come back to d7 — 9.a4 Be7 and the position is a long, quiet fight about whether that pawn on d5 is a spearhead or a target.",
             "line": "Nxd5 exd5 Nb8 a4 Be7"},
            {"san": "a4", "severity": "playable", "tier": "Structure",
             "why": "Stopping ...b5 before the knight is even kicked, so that the a3-knight has c4 to come back to. 7...a6 8.Na3 Be7 and you develop normally; the knight on a3 is still the worst-placed piece on the board and now it has a route home.",
             "line": "a6 Na3 Be7 Bc4 Be6"},
            {"san": "Be3", "severity": "playable", "tier": "Structure",
             "why": "Developing rather than pinning, which lets you get the useful move in first: 7...a6 8.Na3 Rb8! preparing ...b5 without allowing Bxf6. The engine calls this comfortable for Black, and it is the reason 7.Bg5 and 7.Nd5 are the moves that get played.",
             "line": "a6 Na3 Rb8 Bg5 b5"},
        ],

        # ══ ALAPIN ══════════════════════════════════════════════════════════════

        # ── ply 3 · your own second move against 2.c3 ───────────────────────────
        "e4 c5 c3": [
            {"san": "d5", "severity": "playable", "tier": "Foundation",
             "name": "Barmen Defence",
             "why": "The old main line, and completely sound: strike the centre before White builds it. 3.exd5 Qxd5 4.d4 Nf6 and your queen is exposed for exactly one move, because c3 means there is no Nc3 to gain a tempo on her. Choose between this and 2...Nf6 by whether you would rather be a piece ahead in development or a pawn ahead in the centre.",
             "line": "exd5 Qxd5 d4 Nf6 Nf3 Nc6"},
            {"san": "e6", "severity": "playable", "tier": "Structure",
             "why": "Heading for a French Advance where White has already committed to c3 — which is where the c-pawn goes in that opening anyway, so nothing is wasted for either side. 3.d4 d5 4.e5 and you play the French plan: ...Nc6, ...Qb6 and pressure on d4.",
             "line": "d4 d5 e5 Bd7 Nf3 Nc6"},
            {"san": "Nc6", "severity": "playable", "tier": "Foundation",
             "why": "Playable and a move-order matter: after 3.d4 cxd4 4.cxd4 White has the two-pawn centre you were trying to prevent. Play ...d5 next and you transpose to the Barmen; do not drift into ...e6 and ...Nf6 and let White keep both centre pawns for free.",
             "line": "d4 d5 exd5 Qxd5 Nf3 Nf6"},
        ],

        # ── ply 6 · White's fourth after 3...Nd5 ────────────────────────────────
        "e4 c5 c3 Nf6 e5 Nd5": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "Development first, d4 next — the same position by a different road in almost every line. 4...d6 5.d4 cxd4 6.exd6 and the pawn tension in the centre resolves early; you are fine and there is very little to remember.",
             "line": "d6 d4 cxd4 exd6 Qxd6 Nxd4"},
            {"san": "Bc4", "severity": "playable", "tier": "Structure",
             "why": "Hitting the knight with a developing move. 4...Nb6! 5.Bb3 c4! is the point — the pawn hits the bishop, and after 6.Bc2 Nc6 White's centre has been frozen before it was built.",
             "line": "Nb6 Bb3 c4 Bc2 Nc6"},
            {"san": "c4", "severity": "inaccuracy", "tier": "Structure",
             "why": "Kicking the knight with the pawn that was the whole point of 2.c3 — and now d4 can never be supported by it. 4...Nb4! and the knight is not being chased anywhere: it eyes d3 and c2, and White's d-pawn is stuck on d3 for the rest of the game. At depth twenty that is more than half a pawn to Black.",
             "line": "Nb4 Nf3 g6 Nc3 Bg7 d3"},
        ],

        # ── ply 13 · White's seventh in the Alapin main line ────────────────────
        "e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3 Nc6 cxd4 d6": [
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "Offering the trade on d5 to keep the pawn on e5 alive. Take everything: 7...dxe5 8.Nxe5 Nxc3 9.bxc3 Nxe5 10.dxe5 and White is left with doubled c-pawns and a pawn on e5 that no longer cramps anybody.",
             "line": "dxe5 Nxe5 Nxc3 bxc3 Nxe5 dxe5"},
            {"san": "Be2", "severity": "playable", "tier": "Foundation",
             "why": "Quiet development, which gives you time for the best setup there is against an isolated pawn: 7...g6, ...Bg7, ...O-O and a knight to d5. 8.Nc3 dxe5 9.dxe5 Be6 and you are already the more comfortable side.",
             "line": "g6 Nc3 dxe5 dxe5 Be6"},
            {"san": "exd6", "severity": "playable", "tier": "Structure",
             "why": "Releasing the tension yourself, which hands you the isolated pawn to play against immediately. Do not hurry to recapture: 7...Bg4! develops with a threat first, 8.h3 Bxf3 9.Qxf3 e6 and the pawn on d6 is not going anywhere.",
             "line": "Bg4 h3 Bxf3 Qxf3 e6"},
        ],

        # ══ ROSSOLIMO ═══════════════════════════════════════════════════════════

        # ── ply 5 · your own third move against 3.Bb5 ───────────────────────────
        "e4 c5 Nf3 Nc6 Bb5": [
            {"san": "e6", "severity": "playable", "tier": "Foundation",
             "why": "The engine's own preference and the most solid answer: ...e6 prepares ...Nge7, which defends the knight on c6 so that Bxc6 never comes with a structural cost at all. 4.O-O Nge7 5.d4 cxd4 6.Nxd4 and you have an ordinary good Sicilian.",
             "line": "O-O Nge7 d4 cxd4 Nxd4 Qb6"},
            {"san": "d6", "severity": "playable", "tier": "Structure",
             "why": "Transposing toward the Moscow: ...Bd7 unpins next move and the bishop trade happens on your terms. 4.O-O Bd7 5.Re1 a6 6.Bxc6 Bxc6 and you recapture with a piece, so there are no doubled pawns anywhere.",
             "line": "O-O Bd7 Re1 a6 Bxc6 Bxc6"},
            {"san": "Nf6", "severity": "playable", "tier": "Structure",
             "why": "Development with a hit on e4, and it invites the trade at once: 4.Bxc6 dxc6 5.d3 Qc7 and you have the same doubled-pawn structure as the main line with the knight already out. Nothing wrong with it — just be sure you want the pawn on c6, because it is permanent.",
             "line": "Bxc6 dxc6 d3 Qc7 a4 e5"},
        ],

        # ── ply 7 · White's fourth after 3...g6 ─────────────────────────────────
        "e4 c5 Nf3 Nc6 Bb5 g6": [
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Castling first and trading later, which is the same thing one move on. 4...Bg7 5.Bxc6 bxc6 6.Re1 Qc7 and you have a choice of recaptures — with the b-pawn here, because the rook on e1 makes ...e5 harder to arrange.",
             "line": "Bg7 Bxc6 bxc6 Re1 Qc7"},
            {"san": "c3", "severity": "playable", "tier": "Structure",
             "why": "Keeping the bishop and preparing d4 — the Rossolimo turning into an Alapin. 4...Nf6! hits e4 straight away and, as always in this structure, the knight that would defend it has no c3 to go to.",
             "line": "Nf6 Qe2 Qb6 Na3 Bg7"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "Development, and it gives up on the trade. 4...Bg7 5.O-O e5! and you take d4 permanently: with a pawn on c5 and a pawn on e5 there is no square in the centre left for a white pawn or knight.",
             "line": "Bg7 O-O e5 a3 Nge7"},
        ],

        # ── ply 13 · your own seventh in the Rossolimo tabiya ───────────────────
        "e4 c5 Nf3 Nc6 Bb5 g6 Bxc6 dxc6 d3 Bg7 h3 Nf6 Nc3": [
            {"san": "b6", "severity": "playable", "tier": "Plans",
             "why": "The engine's first choice and Carlsen's, and it is a different plan from ...Nd7: the bishop is heading for a6 or b7 and the b6-pawn holds c5 so the knight never has to. Step through the model game from here — it is this exact position.",
             "line": "Be3 Qc7 Qd2 e5 Bh6 O-O",
             "see": "sicilian#caruana-carlsen-2015"},
            {"san": "e5", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The right pawn at the wrong moment. 8.Nxe5! works because e4 is defended twice, by the knight on c3 and the pawn on d3: 8...Nxe4 9.Nxe4 Bxe5 comes out dead level on material and you have spent your central pawn for nothing. Play ...Nd7 first and ...e5 is a move rather than a trade.",
             "line": "Nxe5 Nxe4 Nxe4 Bxe5 O-O O-O"},
        ],

        # ══ CLOSED SICILIAN AND THE GRAND PRIX ══════════════════════════════════

        # ── ply 4 · White's third after 2.Nc3 Nc6 ───────────────────────────────
        "e4 c5 Nc3 Nc6": [
            {"san": "f4", "severity": "playable", "tier": "Foundation",
             "name": "Grand Prix Attack",
             "why": "The real Grand Prix, with e4 defended this time. White wants f5, a rook lift and a mating attack. Take the sting out of it by fianchettoing: 3...g6 4.Nf3 Bg7 5.Be2 d6, and the bishop on g7 is the piece that holds the dark squares in front of your own king. When f4–f5 comes, take with the e-pawn rather than closing with ...e5.",
             "line": "g6 Nf3 Bg7 Be2 d6"},
            {"san": "Nge2", "severity": "playable", "tier": "Structure",
             "why": "Flexible: the knight keeps d4 available and does not block the f-pawn. The move that punishes the slowness is 3...Nd4! — with the c-pawn behind its own knight, White cannot chase your knight off d4 with a pawn at all. 4.d3 e6 5.Be3 e5 and you have the strongest square on the board.",
             "line": "Nd4 d3 e6 Be3 e5"},
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "Back to a normal Sicilian move order, except that Nc3 has already been spent. Take the free option: 3...e5! costs nothing here, because the c-pawn can no longer come to c3 to fight for d4.",
             "line": "e5 Bc4 Be7 d3 d6"},
            {"san": "d4", "severity": "blunder", "tier": "Foundation",
             "why": "The natural move, and it loses a pawn on the spot, because White has no way to recapture: 3...cxd4! and 4.Qxd4 loses the queen outright to 4...Nxd4, while the knight on c3 cannot reach d4 at all. 4.Nd5 e6 5.Nf4 Nf6 is the best try and you are simply a pawn up. Look at what defends the square before you push the pawn to it.",
             "line": "cxd4 Nd5 e6 Nf4 Nf6"},
        ],

        # ── ply 8 · White's fifth in the Closed ─────────────────────────────────
        "e4 c5 Nc3 Nc6 g3 g6 Bg2 Bg7": [
            {"san": "Nge2", "severity": "playable", "tier": "Structure",
             "why": "The knight goes to e2 rather than f3 so that the f-pawn is free to storm. It is the main move order and nothing changes: 5...d6 6.d3 e5 and you take the centre squares while White prepares f4.",
             "line": "d6 d3 e5 Nd5 Nge7"},
            {"san": "f4", "severity": "playable", "tier": "Structure",
             "why": "Starting the attack before the pieces are ready. It is playable and it is early: 5...d6 6.d3 e6! and you take f5 and d5 away from White, which is where the whole attack was going to land.",
             "line": "d6 d3 e6 Nf3 Nge7"},
            {"san": "d4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The same mistake as on move three and for the same reason: nothing recaptures on d4. 5...cxd4! and the queen cannot come — the bishop on g7 is looking straight down the diagonal at her — so 6.Nce2 d6 7.Nf3 Qa5+ and you are a pawn up with a check to collect first.",
             "line": "cxd4 Nce2 d6 Nf3 Qa5+"},
        ],

        # ══ SMITH-MORRA ═════════════════════════════════════════════════════════

        # ── ply 5 · your own third move: take it or leave it ────────────────────
        "e4 c5 d4 cxd4 c3": [
            {"san": "Nf6", "severity": "playable", "tier": "Foundation",
             "name": "Alapin Declined",
             "why": "Declining by transposing: 4.e5 Nd5 5.Nf3 Nc6 6.cxd4 d6 is an Alapin, and a perfectly good one. What you give up is the pawn, and with it the reason White should not have played this. Take the pawn if you have prepared it; play this if you have not.",
             "line": "e5 Nd5 Nf3 Nc6 cxd4 d6",
             "see": "sicilian#alapin"},
            {"san": "d5", "severity": "playable", "tier": "Structure",
             "why": "Hitting back in the centre instead of grabbing. 4.exd5 Qxd5 5.cxd4 e5! and you break up White's centre at once. Sound, and about half a pawn less good than taking — the pawn on d4 was free and this gives it back.",
             "line": "exd5 Qxd5 cxd4 e5 Nf3 exd4"},
            {"san": "d3", "severity": "inaccuracy", "tier": "Structure",
             "name": "Advance Variation",
             "why": "Pushing the pawn on rather than taking or holding it, so that White has to spend a piece move recapturing. It is the club player's favourite decline and it costs about three-quarters of a pawn: 4.Bxd3 recaptures with a developing move, and White gets the open lines of the gambit without having paid a pawn for them.",
             "line": "Bxd3 Nc6 c4 e6 Nf3 Bc5"},
        ],

        # ── ply 14 · White's eighth in the Morra tabiya ─────────────────────────
        "e4 c5 d4 cxd4 c3 dxc3 Nxc3 Nc6 Nf3 d6 Bc4 e6 O-O Nf6": [
            {"san": "Bg5", "severity": "playable", "tier": "Structure",
             "why": "Pinning the knight that covers d5 and attacks e4. Break the pin rather than allowing Bxf6: 8...Be7 9.Qe2 h6 10.Bf4 e5 and the bishop has been asked twice and achieved nothing. You are still a pawn up.",
             "line": "Be7 Qe2 h6 Bf4 e5"},
            {"san": "Bf4", "severity": "playable", "tier": "Structure",
             "why": "Aiming at d6, which is the pawn every Morra plan is really about. 8...Be7 9.Qe2 e5! solves it in one move: the pawn steps forward to a square the d6-pawn defends, and the bishop has nothing left to hit.",
             "line": "Be7 Qe2 e5 Bg5 O-O"},
            {"san": "Nb5", "severity": "inaccuracy", "tier": "Plans",
             "why": "The knight lunges at d6 and it is the pawn on e4 that pays for it: 8...Nxe4! 9.Re1 a6 10.Rxe4 axb5 11.Bxb5 and the dust settles with the pieces dead level and you still a pawn up — except that White's knight has gone and the initiative the gambit was bought with has gone with it. The engine gives Black more than a pawn.",
             "line": "Nxe4 Re1 a6 Rxe4 axb5 Bxb5"},
        ],
    },
    "games": [
        {
            "id": "shirov-kasparov-1997",
            "name": "Shirov – Kasparov, Tilburg 1997 — the English Attack race, won by a move",
            "tier": "Plans",
            "note": "Round five at Tilburg, and the position you have drilled arrives by a different move order: Kasparov delays castling and plays ...Nbd7 and ...h6 first. Watch the arithmetic. Shirov gets the g-pawn to g5 on move twenty-three; Kasparov gets the b-pawn to b4 on move thirteen, and by the time the kingside attack is ready there is nothing left of the queenside to defend it with.",
            "moves": (
                "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 "
                "Qd2 Nbd7 g4 h6 O-O-O b5 h4 Nb6 Kb1 b4 Bxb6 Qxb6 Nd5 Bxd5 "
                "exd5 a5 Qd3 O-O Nd2 a4 Ne4 Rfc8 Nxf6+ Bxf6 Qe4 Qc5 Bd3 Kf8 "
                "g5 hxg5 hxg5 Bxg5 Qf5 Bh6 Rh4 Ke7 Rc4 Qxc4 Bxc4 Rxc4 "
                "Qd3 Rac8 Re1 Bf4 Re4 Rxe4 fxe4 g5 a3 bxa3 Qa6 Rd8 Qb6 g4 "
                "c4 g3 c5 g2 cxd6+ Rxd6 Qc7+ Kf6 Qxd6+ Kg7"
            ),
            "notes": {
                18: "The same tabiya, a different order: Kasparov puts the knight on d7 before castling, which keeps ...O-O and ...h6 both in hand and means the king is not yet a target.",
                20: "Not a defensive move but a hook in reverse — it asks the g-pawn to commit itself, and after g4–g5 the file opens toward White's own king as much as Black's.",
                22: "The pawn that decides Sicilians. It goes to b4 next, and the knight on c3 is the only piece defending both d5 and e4.",
                26: "...b4 on move thirteen, and it comes with a threat: the knight on c3 has to move, and it is the piece holding d5. That is the difference between the two attacks in this structure — Black's pawns hit pieces, White's pawns hit pawns.",
                27: "Shirov gives up a bishop for the knight, and with it the bishop pair. It is not a whim: the knight on b6 guards d5 and is heading for a4 and c4, and it had to go before it got there.",
                29: "The knight lands on the hole at last, and Kasparov takes it immediately. This is the Sveshnikov lesson turning up in a Najdorf: a knight that can be traded off d5 was never occupying it.",
                31: "White recaptures with the pawn and the hole is filled by White's own pawn — which now blocks the very diagonal Shirov's remaining bishop would want.",
                32: "The a-pawn joins in: pawns on a5 and b4, aimed at a king on b1, with ...a4 and ...b3 still to come. The b-file opens whichever way White resolves it.",
                45: "g5 at last, on move twenty-three — and it wins nothing at all: 23...hxg5 24.hxg5 Bxg5 and Black has simply eaten the storm and come out a pawn up. The attack took ten moves to prepare and lasted three.",
                53: "Rc4 stops the invasion by offering the exchange, and Kasparov answers with a much bigger trade: 27...Qxc4 28.Bxc4 Rxc4 gives the queen for a rook and a bishop, which is level on material and leaves White without a single minor piece.",
                63: "31.Re4 Rxe4 32.fxe4 and the exchange comes straight back. Count it: queen and five pawns for White, rook, bishop and six for Black — dead level. What is not level is where the pawns are, and two of Black's are on a3's doorstep.",
                65: "a3 tries to build a wall on the queenside, one move after the queenside stopped being where the game is: Black's g-pawn is already running, and ...bxa3 opens a second front while it does.",
                71: "c4 and c5 are White's own attempt at a race, and they are two moves too late.",
                75: "cxd6+ comes with check, which is the only reason White gets another move — the black pawn is already sitting on g2.",
                79: "39.Qc7+ and 40.Qxd6+ win the rook and leave White four points of material ahead, and Shirov resigned on 40...Kg7 anyway. There is no perpetual: the engine's own move in the final position is not even a check, and ...g1=Q ends it.",
            },
        },
        {
            "id": "caruana-carlsen-2015",
            "name": "Caruana – Carlsen, Wijk aan Zee 2015 — the Rossolimo, ground down",
            "tier": "Structure",
            "note": "The sixth round at Tata Steel, and the position you have drilled to move seven arrives exactly, with 7...b6 instead of 7...Nd7. Nobody sacrifices anything for twenty moves. Carlsen takes the doubled pawns, closes the centre, invites Caruana to open a wing, and then uses the two bishops the trade on c6 paid for.",
            "moves": (
                "e4 c5 Nf3 Nc6 Bb5 g6 Bxc6 dxc6 d3 Bg7 h3 Nf6 Nc3 b6 "
                "Be3 e5 O-O O-O a3 Qe7 Qb1 Nh5 b4 f5 bxc5 f4 Bd2 bxc5 "
                "Qb3+ Be6 Qa4 Rac8 Qa5 g5 Na4 g4 hxg4 Bxg4 Qxc5 Qf6 "
                "Nh2 f3 Nxg4 Qg6 Qe7 fxg2 Rfb1 Qxg4 Qg5 Qe2 Qe3 Qg4 "
                "Qg5 Qxg5 Bxg5 Nf4 Bxf4 exf4 Kxg2 f3+ Kf1 Rf4 c3 Rd8 "
                "d4 Bh6 Ke1 Rxe4+ Kd1 c5 Kc2 cxd4 Kd3 Re2 c4 Rxf2 Rd1 Re2"
            ),
            "notes": {
                8: "Toward the centre, and this is the whole choice of the variation. The pawns on c5 and c6 are doubled, and between them they cover b4, b5, d4 and d5 — every square on that wing a white piece would want. The d-file is now open for the queen and the rook as well.",
                14: "Carlsen's move rather than the ...Nd7 of the main line, and it is the engine's first choice too: the bishop is going to a6 or b7 and the pawn on b6 holds c5, so no piece has to.",
                16: "The centre closes. Count what White has left: no pawn break at all, because c5 and e5 both hit d4 and White cannot defend that square often enough to push a pawn onto it.",
                19: "a3 and then b4 — Caruana opens the only wing he can. Every file that opens is a file for two bishops.",
                22: "The knight steps to the rim on purpose. It is heading nowhere; what it does is unblock the f-pawn, and ...f5 is the break this structure is built for.",
                24: "...f5, and the extra kingside pawn finally moves. Note that h3 was played on move six: the pawn on h3 is what gives ...g5 and ...f4 something to hit.",
                26: "...f4 shuts the bishop out of the queenside and leaves it staring at its own pawns. From here Black is playing with an extra piece on that side of the board.",
                34: "...g5 and ...g4, using the hook. This is not an attack on the king — it is a way of opening lines for the two bishops with pawns Black can afford to lose.",
                40: "...Qf6 offers the queens. Carlsen is a pawn down at this point and offering trades anyway, because the bishops are the asset and the queens are what keeps the position complicated.",
                46: "...fxg2! Carlsen is a whole piece down for one move here — 24.Rfb1 Qxg4 takes it straight back — and the pawn he has spent it on lands on g2 and stays there for twelve moves.",
                55: "The queens come off. Count what is left: a knight, a bishop and two rooks each, five pawns each, and a black pawn on g2 in front of White's king. Dead level on material, and not level at all on comfort.",
                58: "28...Nf4 29.Bxf4 exf4 — Carlsen trades his knight for the bishop and keeps his own. The pawn that lands on f4 is what makes it a good trade: it fixes White's kingside and leaves the knight without an outpost anywhere.",
                60: "30.Kxg2 finally removes the pawn, and 30...f3+ puts another one there. The king has spent the whole game on squares Black chose for it.",
                68: "...Rxe4+ collects the pawn this whole endgame was about. Count now: two rooks and one minor piece each, four pawns each, and Black's f-pawn is on f3 with the white king in front of it.",
                78: "Two passed pawns, on d4 and f3. They are not connected and it does not matter — they are on opposite sides of a king that has to pick one. Caruana resigned here.",
            },
        },
    ],
    "progression": {
        "arc": "The Sicilian is the biggest body of theory in chess. The way through it is to learn one variation properly rather than six badly — and to learn the Anti-Sicilians first, because that is what you will actually be shown.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Weeks one to three",
                "goal": "Have an answer to every second move, and understand the trade you are making.",
                "learn": [
                    "The core bargain: you give up a wing pawn for a centre pawn and receive the half-open c-file. Everything else follows from that.",
                    "The Anti-Sicilians you will actually face more than the Open: 2.c3 (Alapin), 2.Nc3 (Closed), 3.Bb5 (Rossolimo and Moscow), 2.d4 (Smith-Morra) and 2.f4.",
                    "Then pick one Open Sicilian: Najdorf (sharpest, most theory), Accelerated Dragon (solid, less theory), Sveshnikov (unbalanced, forcing).",
                ],
                "drill": "Prepare your Anti-Sicilian answers first, in this order: 2.c3, 3.Bb5, 2.Nc3, 2.d4. Below master level you will meet all four more often than the Open Sicilian.",
                "mistake": "Learning twenty moves of the Najdorf and nothing against 2.c3. You will lose to the Alapin repeatedly and never reach your preparation.",
                "ready": "You have one line against every White second and third move, written down.",
            },
            {
                "tier": "Structure",
                "when": "Months one to three",
                "goal": "Learn your chosen structure's skeleton and the squares that decide it.",
                "learn": [
                    "In the Najdorf: the d5 square. Every move in the opening is about whether you achieve ...d5 in one move or not.",
                    "In the Dragon and Accelerated Dragon: the long diagonal and the g7-bishop. It is worth more than a rook in many positions.",
                    "In every Sicilian: the half-open c-file, the exchange sacrifice ...Rxc3, and the ...b5–b4 lever.",
                ],
                "drill": "Play out your tabiya twenty times from move ten. Do not study new lines until the tabiya is second nature.",
                "mistake": "Playing ...d5 because it is 'freeing' when it loses a pawn or a piece. Count the defenders every time.",
                "ready": "You know the key square in your variation and can explain what happens if you never control it.",
            },
            {
                "tier": "Plans",
                "when": "Months three to nine",
                "goal": "Win the race.",
                "learn": [
                    "The counting principle in opposite-castling positions: count how many moves each attack needs. That number, not the evaluation, decides the game.",
                    "The standard sacrifices: ...Rxc3 (exchange), ...Nxe4 (opening lines), ...b4 and ...a5–a4 (pure pawns).",
                    "When to defend instead: ...h5 stopping the g-pawn, ...Kb8 and ...Rc8 tucking away.",
                ],
                "drill": "Take ten opposite-castling Sicilians and, at move fifteen, count both attacks before looking at the result. Train the counting.",
                "mistake": "Defending passively. In a race, one defensive move is one attacking move you did not make — defend only when the arithmetic demands it.",
                "ready": "You can look at an English Attack position and say who is faster, with a reason.",
            },
            {
                "tier": "Mastery",
                "when": "Year two and beyond",
                "goal": "Depth in your line, plus the endgames.",
                "learn": [
                    "Your variation's deepest branches — in the Najdorf that means the Poisoned Pawn and the 6.Bg5 complex.",
                    "The Maroczy Bind and how to break it: ...b5 sacrifices, ...Nxd4 trades and the ...f5 break.",
                    "Sicilian endgames: what the doubled c-pawns of the Rossolimo are actually worth, and why a good knight beats a bad bishop in these structures.",
                ],
                "drill": "Analyse five of your own losses in the Sicilian and classify them: lost the race, lost the structure, or lost to preparation. Fix the biggest category.",
                "mistake": "Switching variations after a loss. Depth beats breadth in the Sicilian by an enormous margin.",
                "ready": "You have a line you have played fifty times and still find new ideas in.",
            },
        ],
        "study": "Fischer and Kasparov for the Najdorf, Carlsen and Caruana for the modern Sveshnikov — their 2018 World Championship match is the best available course in it. For the Anti-Sicilians, watch what Carlsen does with Black against 3.Bb5: he does not try to refute it, he trades and grinds.",
        "next": "Once one Sicilian is deep, add a second as a surprise weapon rather than starting over. The structures overlap more than the move orders suggest.",
    },
}
