OPENING = {
    "id": "slav",
    "name": "Slav Defence",
    "eco": "D10–D19",
    "section": "black-d4",
    "orientation": "black",
    "tagline": "Support d5 with the c-pawn and keep the good bishop. The Caro-Kann of 1.d4.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "Against the Queen's Gambit, Black must support d5. The Queen's Gambit Declined does it with ...e6, which locks the c8-bishop in behind its own pawn. The Slav does it with ...c6, keeping the bishop's path to f5 and g4 open. Black's basic plan is to develop the bishop outside, then play ...e6 and take on c4 at a moment when White has to spend time recovering the pawn. It is the soundest, least compromising answer to 1.d4 there is — and the numbers say so: the main line below ends with the engine giving White about a third of a pawn, which is what it gave White after 1.d4 d5.",
        "structure": "Black keeps a pawn on c6 and d5 and gives up neither. In the main line the d-pawn takes on c4, and the pawns that are left — a7, b7 and c6 against a4 and b2 — are a three-against-two majority on the queenside, paid for by White's two-against-one in the centre. In the Semi-Slav (with ...e6 as well) the c8-bishop is boxed in for a while and the c-pawn buys the same queenside majority a different way, with ...dxc4 and ...b5. In the Exchange Slav every pawn is mirrored and the only open file is the c-file.",
        "white_plans": [
            "Play a4 early to stop ...b5. It works, and the standing price is b4: with the c-pawn traded off and the a-pawn past a3, no White pawn can ever cover that square again.",
            "Win the pawn back with Bxc4, then build with e3–e4 and push e5, taking d6 and f6 away from Black's knights.",
            "In the Exchange, trade on c6 and play against what it leaves: Bb5, Qa4, Bxc6 and Qa6. Not a minority attack — after cxd5 cxd5 both sides have two pawns on that wing and there is no minority to attack with.",
            "In the Semi-Slav, 5.Bg5 and the gambits behind it: the Botvinnik and the Anti-Moscow, some of the sharpest theory in the game.",
        ],
        "black_plans": [
            "Develop the bishop to f5 or g4 before playing ...e6 — the single defining idea of the whole opening.",
            "Take on c4 when White has to spend a move recovering it, and hold with ...b5 whenever a4 has not been played.",
            "The Meran plan: ...dxc4, ...b5, ...Bb7, ...a6 and the break ...c5 — which hits d4 and opens the b7-bishop's diagonal in the same move.",
            "Break with ...c5 or ...e5. A Slav that never breaks is a cramped position with no weaknesses and no future.",
        ],
        "traps": [
            "Do not hurry the bishop out: 3.Nf3 Bf5? runs into 4.cxd5 cxd5 5.Qb3, and b7 is hanging because the piece that used to guard it is standing on f5. After 5...Nf6 6.Qxb7 Nbd7 White has a pawn, and the engine says so.",
            "After 4...dxc4 5.a4, do not try to keep the pawn with 5...b5?: 6.axb5 cxb5 7.Nxb5! and the pawn on c4 drops next. The line the old books give, 7.b3, is nothing at all — the engine has it level.",
            "Know what 4...e6 5.Bg5 dxc4 6.e4 b5 7.e5 h6 8.Bh4 g5 9.Nxg5 is before you play it. That is the Botvinnik, it is twenty moves of forced theory, and at the end of the forcing sequence the engine still likes White by half a pawn. 5...h6 — the Moscow — sidesteps the whole thing.",
        ],
        "who": "Play this if you want a defence to 1.d4 that is completely sound, gives you a healthy structure, and does not require you to accept a bad bishop or a cramped position.",
    },
    "lines": [
        {
            "name": "Main Line Slav",
            "note": "The classical main line: Black takes on c4, gets the bishop outside the chain, and reaches a position where White's centre and Black's queenside are worth the same.",
            "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "Count the two majorities, because the rest of the game is in them: your a7, b7 and c6 against White's a4 and b2 is three pawns to two on the queenside, and White's d4 and e4 against your e6 is two to one in the centre. White has to make the centre count before you make the queenside count — and White is the one who has to hurry.",
                "next": [
                    "11.Bd3 Bh5 — keep hitting f3. After 12.e5 Nd5 13.Nxd5 cxd5 you have spent the queenside majority to kill the centre, and that is a fair price: step through the deep dive from here.",
                    "If White leaves you alone, finish with ...Re8 and ...Qe7 and then break with ...e5 or ...c5. Every plan you have runs through one of those two pawn moves.",
                    "If White drifts — 11.Rd1 or 11.Bg5 — the answer is 11...Bxc3 12.bxc3 and e4 is attacked twice and defended once. Count the defenders of e4 every move White spends elsewhere.",
                ],
                "endgame": "Trade into it happily. Nothing in your structure is weak on either wing, and White's a4 is a pawn that needs b2–b3 or a piece to look after it the moment a knight comes to b6. The one thing to watch is White's e4–e5 with the pawn on d4 behind it: that duo takes d6 and f6 from your knights, so break it up with ...c5 before you trade the pieces that could.",
            },
            "notes": {
                4: "The Slav. Black supports d5 with the c-pawn, which — unlike ...e6 — leaves the c8-bishop free.",
                5: "The main move and the flexible one: White develops and keeps cxd5, e3 and Nc3 all in hand for another move.",
                6: "Development, and another guard for d5. Notice what Black has not done: the e-pawn stays home until the light-squared bishop is out.",
                7: "The last natural developing move before the tension has to be resolved. It puts a second attacker on d5, next to the pawn on c4.",
                8: "Now the capture works. The point is not the pawn — Black cannot hold it against a4 — it is that White has to spend a move getting it back, and Black spends that move putting the bishop where the whole opening wants it.",
                9: "White's main move, and the one standing concession in the Slav: with the c-pawn traded off and the a-pawn past a3, no White pawn can ever cover b4 again. Your dark-squared bishop is going to that square on move seven.",
                10: "The whole point of the Slav. The bishop comes out in front of the pawn chain — the move that ...e6 makes impossible for the rest of the game in the Queen's Gambit Declined.",
                11: "Modest, and it does two jobs: it props up d4 and it opens the f1-bishop's road to c4, where the pawn is.",
                12: "Only now. The bishop is already outside, so ...e6 costs nothing — it takes d5 and f5 under control and lets the f8-bishop out.",
                13: "White wins the pawn back. The bishop looks aggressive on c4 and it is not: your pawn on e6 has already shut the diagonal it wants.",
                14: "Onto the square a4 created. It pins the knight on c3 against the king on e1 — d2 is empty, because that pawn went to d4 on move one — and it clears f8 for castling.",
                15: "White castles, and the pin is over: the knight on c3 was only pinned while the king stood on e1.",
                16: "The knight's square here is d7, not c6, because c6 is a pawn. From d7 it covers b6, c5 and e5 — the three squares Black's counterplay needs.",
                17: "Preparing e4. With the pawn on e3 the queen sees nothing down the file; the moment it steps to e4 she is behind it — and e4 needs the help, because your knight on f6 and your bishop are both looking at that square.",
                18: "The bishop steps out of the pawn's way before it is asked to. On g6 it keeps the same diagonal, and White's e4 arrives without a tempo attached.",
                19: "The big centre, and the deal the whole variation is about: two pawns to one for White in the middle, three to two for you on the queenside.",
                20: "You castle, and this is the main-line tabiya. The engine gives White about a third of a pawn — which is what it gave White after 1.d4 d5, before any of this happened. Kramnik reached this exact position against Topalov in the second game of the 2006 world championship match; the game is on this page.",
            },
        },
        {
            "name": "Semi-Slav — Meran Variation",
            "note": "Black plays both ...c6 and ...e6, boxes the light-squared bishop in on purpose, and gets the queenside majority and both central breaks for it.",
            "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 Bb7 O-O a6 e4 c5",
            "tier": "Mastery",
            "drill": True,
            "plan": {
                "tier": "Plans",
                "point": "The same two majorities as the main line, one degree sharper: a6, b5 and c5 against a2 and b2, White's d4 and e4 against your e6. Your last move did two things at once — it hit d4, and it cleared c6 so that the bishop on b7 finally sees the long diagonal. The engine calls this position level, which for a defence to 1.d4 is the whole ballgame.",
                "next": [
                    "11.d5 is the critical try, the Reynolds Attack: 11...Qc7 12.dxe6 fxe6 and you have the pawn mass and the half-open f-file pointing at f2.",
                    "11.e5 cxd4 12.Nxb5 is the same knight sacrifice as in the model game — and here you answer 12...Bxf3, which Anand could not, because in the game the bishop was not yet on b7.",
                    "11.dxc5 Nxc5 gives it all back: the queens come off on d1 and e4 falls. The engine already prefers Black.",
                ],
                "endgame": "Three queenside pawns against two, and they are worth having only if you survive the middlegame with them — so take every free queen trade and refuse every one that costs a tempo. The pawn to watch is your own on d4 in the sacrifice lines: it is a passed pawn while pieces are on and a target the moment they are not.",
            },
            "notes": {
                5: "The same start as the main line. Everything up to here is shared.",
                6: "Development, and another guard for d5. In this opening the knight on f6 is not attacking anything yet — there is no pawn on e4 to hit.",
                7: "White's most testing move order, and the one that forces Black to choose: the bishop outside with ...dxc4, or the Semi-Slav with ...e6.",
                8: "The Semi-Slav. Black plays both ...c6 and ...e6 and accepts the boxed-in bishop for one reason: it comes out later at a much better moment, and both ...c5 and ...e5 are live breaks in the meantime.",
                9: "The quiet approach, and the one you will meet most. 5.Bg5 is the sharp one — it is on the deviation panel with the honest warning attached.",
                10: "Development. The knight goes to d7 rather than c6 so that the c-pawn can still play ...c5.",
                11: "The Meran invitation. On d3 the bishop points at h7 — and it is also standing on the square Black's c-pawn is about to attack.",
                12: "The Meran. Black takes now, because ...b5 will come next with tempo against the bishop when it recaptures.",
                13: "White wins the pawn back, onto the square Black wants to hit.",
                14: "The tempo and the wing in one move. Count the pawns: a7, b5 and c6 against a2 and b2 — a three-to-two majority that lasts to the end of the game.",
                15: "Back to the diagonal that matters, aiming at h7.",
                16: "The problem bishop comes out — and it is still not doing anything, because your own pawn on c6 stands on its diagonal. ...c5 is the move that switches it on, which is why it is coming.",
                17: "White castles. The centre is next.",
                18: "Backing the b-pawn up, so that a2–a4 can be met by ...b4 or ...bxa4 without a pawn falling.",
                19: "White takes the centre, and now it is a race: two pawns against one in the middle, three against two on the queenside.",
                20: "The break. It hits d4 and it opens the b7-bishop's road to e4 in the same move — which is the whole reason the bishop went to b7 two moves early.",
            },
        },
        {
            "name": "Exchange Slav",
            "note": "White resolves the centre at once and heads for a symmetrical position. Solid, safe, and far less drawish than its reputation — the engine already prefers Black at the end of this line.",
            "moves": "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6 Bb5 Nd7 Qa4 Rc8 O-O Be7",
            "tier": "Foundation",
            "drill": True,
            "plan": {
                "tier": "Structure",
                "point": "Symmetry is not a draw offer. Every pawn is mirrored, the c-file is the only open one, and the engine has Black a shade better here — because White has spent two moves on a queen sortie to set up one idea, Bxc6 followed by Qa6, and you can simply let it happen.",
                "next": [
                    "11.Bxc6 bxc6 12.Qxa7 g5! — give the pawn. You get the half-open b-file pointing at b2, a pawn pair on c6 and d5, the bishop pair, and a white queen sitting on a7 with nothing to do. The engine still prefers Black.",
                    "Contest the file and take the c4 square: ...Nb6 hits the queen on a4 and heads for c4. Castle first, though — the moment the knight leaves d7 the bishop on b5 pins the c6-knight to your king again.",
                    "...Ne4 and ...Bf6, and the pressure lands on d4. In a symmetrical structure the win comes from one open file and one target, and d4 is the target.",
                ],
                "endgame": "Mirror pawns, one open file, and it is decided by who gets a rook to the seventh rank first. The one asymmetry that matters is the trade on c6: after Bxc6 bxc6 you have an isolated a-pawn, a half-open b-file and the two bishops. Know which of those you are playing for before you allow it.",
            },
            "notes": {
                5: "The Exchange Slav. White resolves the centre and heads for a symmetrical structure with the c-file open. Its drawish reputation is real at the top and worth nothing below it — Black has scored with this for a century by outplaying opponents who relaxed.",
                6: "Automatic. Recapturing with the queen instead puts her on the square Nc3 attacks, and Black would spend the next three moves moving her again.",
                7: "The knight comes out hitting d5.",
                8: "And Black guards d5 again. Every move in this variation is about that pawn and that file.",
                9: "Development.",
                10: "Here the knight does belong on c6: the c-pawn has gone, so it blocks nothing.",
                11: "The bishop gets outside the pawn chain before e3 shuts it in — the London System's idea, played from the White side of a Slav.",
                12: "And Black does exactly the same thing, for exactly the same reason. Symmetry here is not laziness: whoever puts the bishop inside the chain owns the worse minor piece for the next forty moves.",
                13: "Both sides now close the door behind the bishop.",
                14: "Same again. The position is a mirror, and the first player to do something asymmetrical is the one taking a risk.",
                15: "And that is White. It is a real pin, not a gesture: b5, c6, d7, e8 with d7 empty since the d-pawn went to d5 on move one, so the knight on c6 cannot legally move.",
                16: "Breaking it. The knight that goes is the one from f6 — it interposes on d7, and the other knight is free again.",
                17: "The queen backs the bishop up on the same diagonal. White's plan is not the c-file: it is Bxc6 and then Qa6, hitting a7 and c6 at once, once your b-pawn has been made to recapture.",
                18: "The rook takes the open file. In a position with one file and no weaknesses, whoever owns the file owns whatever gets created later.",
                19: "King safety.",
                20: "Black completes development, and here is the honest evaluation: the engine has Black a shade better. Symmetry did not make it a draw — it made it a game where the first inaccuracy counts double, and White has already spent two moves on the queen.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Slav into a clean structure",
        "note": "The main line continued to move seventeen, exactly as Topalov and Kramnik played it. Black solves every problem by trading, and what is left is a position no one can attack.",
        "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O Bd3 Bh5 e5 Nd5 Nxd5 cxd5 Qe3 Bg6 Bxg6 hxg6 Bd2 Bxd2 Nxd2 Rc8",
        "tier": "Plans",
        "drill": True,
        "plan": {
            "tier": "Plans",
            "point": "Look at what is left: queen, two rooks and a knight each, one open file, and an engine evaluation of about a third of a pawn for White — the same number it gave after 1.d4 d5, thirty-three plies ago. Nothing went wrong. That is the entire claim the Slav makes, and this is what it looks like when it is true.",
            "next": [
                "18.Rac1 is White's move, and the answer is 18...Qa5 and ...b5, hitting a4 while the file is contested. Trading both pairs of rooks on c1 suits you: the fewer pieces, the less White's extra space is worth.",
                "...Qe7 and ...Rc6 doubling. The c-file is the only road into White's position and it is yours first.",
                "Do not send the rook after a4 while White's knight sits on d2 — from there it covers b3 and c4, the two squares your queenside play has to use.",
            ],
            "endgame": "Count the pawns before you plan it: White a4, b2, d4, e5, f2, g2, h2 against your a7, b7, d5, e6, f7, g6, g7. Two a side on the queenside, three a side on the kingside — but yours are doubled on the g-file, so the side that can manufacture a passed pawn over there is White, with f4 and g4. That is the real price of ...hxg6, and it is worth paying while the rooks are on and the h-file is yours. Trade into the pawn ending only if you have made something of that file first.",
        },
        "notes": {
            21: "White retreats to the attacking diagonal, aiming at h7, and prepares to push e5.",
            22: "Black sidesteps and eyes the f3-knight. The bishop is unusually active for a queen's pawn defence — that is the Slav's whole promise.",
            23: "White gains space and kicks the knight.",
            24: "The knight jumps into the hole in front of White's pawn. It looks strong, and White will trade it immediately.",
            25: "White removes the blockader.",
            26: "Black recaptures toward the centre, and the queenside majority is spent: pawns on a7, b7, d5, e6, f7, g7 and h7, two a side on the queenside now instead of three against two. What it bought is a centre White can no longer push, and not one weak pawn in the structure.",
            27: "The queen steps off the pin and eyes the kingside.",
            28: "Black repositions the bishop to challenge the attacking diagonal.",
            29: "White trades it off — the bishop was the piece pointing at h7.",
            30: "Black recaptures with the h-pawn. It doubles the g-pawns and it opens the h-file, which is half-open rather than open, because White's pawn is still on h2. That is the trade: the h-file for your rook, against doubled pawns that are ugly to look at and slow to get at.",
            31: "White offers the last minor-piece trade.",
            32: "Black accepts. Every trade helps the side with the healthier structure.",
            33: "White recaptures — and note which knight: the one from f3, so White's remaining knight now sits on d2 covering b3 and c4.",
            34: "The rook takes the open file. Be honest about the position rather than romantic: White has more space with the pawn on e5, you have a sound structure, the only open file and doubled g-pawns. The engine says a third of a pawn for White, which is what it said at the start. You have not been worse for a single move — that is what people mean when they call the Slav the soundest defence to 1.d4.",
        },
    },
    # Deviations, keyed by the position they answer. The Slav is a BLACK
    # repertoire, so every entry here is a move WHITE can play and every `why` is
    # about what Black does next. All three lines share their first four plies,
    # so a set written once fires in every line that reaches the position.
    "branches": {

        # ── ply 2 · White's second move, before c4 has been played ─────────────
        "d4 d5": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "White keeps every move order open. Answer 2...Nf6 and wait: if c4 comes you are in the Slav, and if it does not you have committed to nothing.",
             "line": "Nf6 c4 c6 Nc3 dxc4"},
            {"san": "Bf4", "severity": "playable", "tier": "Foundation",
             "name": "London System",
             "why": "The one thing that does not transfer from the Slav. Your ...c6 exists to keep the c8-bishop free — and here White's bishop is already outside, so there is nothing to be clever about: the pawn belongs on c5, hitting the base of the centre. Of the three sensible second moves the engine likes 2...c6 least.",
             "line": "Nf6 e3 c5 Nf3 Nc6",
             "see": "london"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "Develop first: 2...Nf6. The Slav reflex 2...c6 does not work before White has committed the c-pawn, because 3.e4 is then available — 3...dxe4 4.Nxe4 and White has the free centre the Slav exists to deny. Once c4 has been played, ...c6 is the move; before it, it is a tempo.",
             "line": "Nf6 Bf4 e6"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "why": "A Colle or a slow London, and White has shut the c1-bishop in first. That is your cue to take the free move and get your own bishop out before ...e6 — the Slav rule works in every 1.d4 opening, not just this one.",
             "line": "Nf6 Nf3 Bf5 c4 e6"},
            {"san": "e4", "severity": "inaccuracy", "tier": "Mastery",
             "name": "Blackmar–Diemer Gambit",
             "why": "A pawn for open lines, aimed at exactly the player who has prepared a defence to the Queen's Gambit and nothing else. Take it and hand it back when it suits you: 2...dxe4 3.Nc3 Nf6 4.f3 exf3 5.Nxf3 and the engine has Black about half a pawn better. People lose this by trying to keep both pawns.",
             "line": "dxe4 Nc3 Nf6 f3 exf3 Nxf3"},
        ],

        # ── ply 4 · White's third move: the real branch point of the Slav ──────
        "d4 d5 c4 c6": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "The main move, and the main line of this page: White develops and keeps cxd5, e3 and Nc3 all in hand for another move.",
             "line": "Nf6 Nc3 dxc4 a4 Bf5",
             "see": "slav#main-line"},
            {"san": "Nc3", "severity": "playable", "tier": "Structure",
             "why": "The other knight first. One real difference: 3...e6 now allows 4.e4, the Marshall Gambit, which the engine rates as an ordinary small pull for White rather than anything to fear — but there is no need to allow it. Play 3...Nf6 and after 4.Nf3 dxc4 you are in the main line. Topalov opened this way against Kramnik in the game below.",
             "line": "Nf6 Nf3 dxc4 a4 Bf5",
             "see": "slav#topalov-kramnik-2006"},
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "name": "Exchange Slav",
             "why": "The move club opponents actually play, and the one that looks like a draw offer. It is not. Recapture and play the file: the whole game becomes one open c-file, one tempo, and whoever relaxes first.",
             "line": "cxd5 Nc3 Nf6 Nf3 Nc6",
             "see": "slav#exchange"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "name": "Slow Slav",
             "why": "White shuts the c1-bishop in to hold d4, so get yours out at once with 3...Bf5. Be ready for 4.Qb3, the only move here that asks you anything: 4...Qc7 defends b7 and everything holds.",
             "line": "Bf5 Qb3 Qc7 Nc3 e6"},
            {"san": "g3", "severity": "playable", "tier": "Plans",
             "why": "The Catalan set-up. It is a real system and it is slow, and the Slav copes with it better than most defences for one reason: the bishop on g2 runs into your own pawn on c6 and stops there whatever happens in the centre.",
             "line": "Nf6 Bg2 Bf5",
             "see": "catalan"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "The queen steps out early, eyeing b7 — which your bishop still guards — and she cannot see d5 through her own pawn on c4. Take the pawn and make her come and get it: 3...dxc4 4.Qxc4 Nd7 and White's queen is the piece with no comfortable square.",
             "line": "dxc4 Qxc4 Nd7 Nf3 e5"},
        ],

        # ── ply 6 · White's fourth move after 3.Nf3 Nf6 ────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6": [
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "name": "Quiet Slav",
             "why": "White holds d4 and shuts the c1-bishop in behind the pawn to do it. That is the cue: 4...Bf5, the Schallopp, and you have the good bishop outside while White has the bad one inside.",
             "line": "Bf5 Nc3 e6 Nh4 Bg6"},
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "why": "The Exchange with two more pieces developed. Same structure, same plan: recapture and take the c-file.",
             "line": "cxd5 Nc3 Nc6 Bf4 Bf5",
             "see": "slav#exchange"},
            {"san": "Qc2", "severity": "playable", "tier": "Structure",
             "why": "A useful move that commits nothing: it covers e4 and steps off the c-file before you get there. The engine's answer is the Schlechter set-up, 4...g6 and ...Bg7 — nothing is wrong with 4...dxc4 either, but with the queen already on c2 it comes without a tempo.",
             "line": "g6 Nc3 Bg7 cxd5 cxd5"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "The queen eyes b7 down a file your bishop still covers, and she cannot see d5 through her own pawn on c4. So remove it: 4...dxc4 5.Qxc4 Bf5 and you have the bishop outside and White's queen in the middle of the board.",
             "line": "dxc4 Qxc4 Bf5 Nc3 Nbd7"},
            {"san": "Bg5", "severity": "inaccuracy", "tier": "Structure",
             "why": "A pin with nothing behind it, and it costs the gambit pawn: 4...dxc4 and this time it sticks. 5.e3 b5 6.Be2 Bb7 and White has spent a move on a bishop that is doing nothing while Black spent it on the queenside. The engine has Black comfortably better.",
             "line": "dxc4 e3 b5 Be2 Bb7"},
        ],

        # ── ply 8 · White's fifth move, once the pawn is taken ─────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4": [
            {"san": "e3", "severity": "playable", "tier": "Structure",
             "name": "Alekhine Variation",
             "why": "Quieter, and the moment White does not play a4 the pawn can actually be held: 5...b5 6.a4 b4 7.Nb1 Ba6 and Black keeps the extra pawn and the queenside space. The engine's number has already crossed to Black's side of level.",
             "line": "b5 a4 b4 Nb1 Ba6"},
            {"san": "e4", "severity": "playable", "tier": "Mastery",
             "name": "Geller Gambit",
             "why": "White takes the whole centre and lets you keep the pawn. It is a real gambit, and the way to meet it is to hold what you have and develop: 5...b5 and finish the queenside. The pawn is a means to a comfortable game, not the game itself.",
             "line": "b5 Be2 e6 O-O Bb7"},
            {"san": "Ne5", "severity": "playable", "tier": "Plans",
             "why": "White refuses to spend the bishop's tempo and heads for c4 with the knight instead. 5...Nbd7 6.Nxc4 b5 kicks it again and takes the queenside on the way: 7.Ne5 Nxe5 8.dxe5 and the engine has the position level.",
             "line": "Nbd7 Nxc4 b5 Ne5 Nxe5 dxe5"},
            {"san": "g3", "severity": "playable", "tier": "Plans",
             "why": "The fianchetto version, and slower still. 5...e6 6.Bg2 b5 and the pawn is held by the same idea as everywhere else in this opening — the c-pawn supports the b-pawn, which is the whole reason it went to c6.",
             "line": "e6 Bg2 b5 Ne5 a6"},
            {"san": "Qa4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Chasing a pawn with the most expensive piece on the board. 5...b5 hits the queen and holds everything: 6.Qc2 Bb7 and Black has the extra pawn, the queenside and the tempo. The engine gives Black most of a pawn here.",
             "line": "b5 Qc2 Bb7 e4 e6"},
        ],

        # ── ply 10 · White's sixth move after 5.a4 Bf5 ─────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5": [
            {"san": "Ne5", "severity": "playable", "tier": "Mastery",
             "name": "Krause Variation",
             "why": "White's most ambitious: the knight goes to e5 first, heading for f3 and e4 with the pawns. The main line runs 6...e6 7.f3 Bb4 8.e4 and now the piece sacrifice 8...Bxe4 is theory and it holds — at depth twenty the engine cannot separate the position after it from the position before it. The quiet 6...Nbd7 7.Nxc4 Qc7 is a normal game. What loses is 8...Nxe4, which is more than two pawns worse.",
             "line": "e6 f3 Bb4 e4 Bxe4 fxe4 Nxe4"},
            {"san": "Nh4", "severity": "playable", "tier": "Plans",
             "name": "Bled Attack",
             "why": "White goes after the bishop before doing anything else. 6...e6 7.Nxf5 exf5 and be clear about the trade: you get doubled f-pawns, a half-open e-file and a pawn covering e4; White gets the bishop pair and something to aim at. The engine calls it the same small pull as everything else here.",
             "line": "e6 Nxf5 exf5 e3 Bb4"},
            {"san": "e4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Grabbing the centre on a square that is attacked twice — by the knight on f6 and the bishop on f5 — and defended once, by the knight on c3. 6...Nxe4 and Black is a pawn to the good. The move that does not work is 6...e6, when 7.exf5 simply wins the bishop.",
             "line": "Nxe4 Bxc4 e6 a5 Be7"},
            {"san": "Nd2", "severity": "inaccuracy", "tier": "Foundation",
             "why": "The knight steps off d4's defence and blocks its own queen's defence of d4 in the same move, so there is nothing left guarding the pawn: 6...Qxd4 and Black is simply ahead. 7.e3 Qd8 and White has no compensation at all.",
             "line": "Qxd4 e3 Qd8 e4 Bg6"},
        ],

        # ── ply 14 · White's eighth move after 7...Bb4 ─────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4": [
            {"san": "Ne5", "severity": "playable", "tier": "Structure",
             "why": "White grabs the outpost before castling. 8...Nbd7 9.Nxd7 Nxd7 and the trade suits you: every pair of pieces that comes off makes White's extra space worth less and your structure worth more.",
             "line": "Nbd7 Nxd7 Nxd7 O-O Bg6"},
            {"san": "Qb3", "severity": "playable", "tier": "Plans",
             "why": "It looks like a hit on b7 and it is not — your own bishop on b4 stands between the queen and the pawn. What she really does is back a4 up, so 8...a5 takes the a4–a5 advance away for good and leaves her with nothing to do.",
             "line": "a5 O-O Nbd7 Bd2 Qc7"},
            {"san": "Bd2", "severity": "playable", "tier": "Foundation",
             "why": "Unpinning by hand instead of by castling. 8...c5 is the point: with the pin gone the bishop on b4 has no job left, so cash it in for a share of the centre.",
             "line": "c5 O-O O-O Ne2 Nc6"},
            {"san": "Qc2", "severity": "blunder", "tier": "Foundation",
             "why": "The most natural developing square on the board, and it loses the queen: your bishop has been standing on f5 since move five, and 8...Bxc2 is simply a capture. Count what could take back on c2 — the knight on c3 does not cover it, the bishop on c1 cannot move sideways, the king is still on e1. Nothing does. This is the move that pays for the bishop coming out early.",
             "line": "Bxc2 Bd2 Nbd7"},
        ],

        # ── ply 16 · White's ninth move after 8...Nbd7 ─────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7": [
            {"san": "Nh4", "severity": "playable", "tier": "Plans",
             "why": "White goes after the one piece you would rather keep. It is a real plan and it costs time: Piket–Anand, Amsterdam 1993 went 9...Bg6 10.h3 Bh5 11.Qb3 a5 12.f4 O-O, and Black won in thirty moves. Simply castling first is fine too.",
             "line": "O-O Qe2 Rc8"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "Again the queen leans through your own bishop on b4 rather than at b7, and again the real idea is backing up a4–a5. 9...a5 ends it, and the queen is left guarding a pawn that can no longer move.",
             "line": "a5 Bd2 Rb8 Rfd1 O-O"},
            {"san": "Ne5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The outpost, one move too late. 9...Nxe5 10.dxe5 Qxd1 11.Rxd1 Nd7 and look at the pawn on e5: attacked once, defended by nothing, so White has to spend f2–f4 or a piece on it. Trading queens is not a concession here, it is the point.",
             "line": "Nxe5 dxe5 Qxd1 Rxd1 Nd7"},
            {"san": "h3", "severity": "playable", "tier": "Foundation",
             "why": "A waiting move that takes g4 from nobody — your bishop is on f5 and has no interest in g4. Castle and carry on; you have been handed a free move.",
             "line": "O-O Nh4 Nb6 Bb3 Nbd5"},
        ],

        # ── ply 18 · White's tenth move after 9...Bg6 ──────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6": [
            {"san": "Ne5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Same idea, same answer: 10...Nxe5 11.dxe5 Bh5 and the bishop hits the queen on e2 down an empty diagonal while the pawn on e5 becomes a fixed target. The engine has crossed to Black's side.",
             "line": "Nxe5 dxe5 Bh5 Qc2 Nd7"},
            {"san": "Rd1", "severity": "playable", "tier": "Plans",
             "why": "Sensible — the rook goes behind the pawn that wants to advance. 10...O-O and you are in the main line a tempo later with the rook committed.",
             "line": "O-O h3 Qe7 Nh4 e5"},
        ],

        # ── ply 20 · White's eleventh, where the deep dive starts ──────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O": [
            {"san": "e5", "severity": "playable", "tier": "Plans",
             "why": "Pushing at once instead of putting the bishop on d3 first. 11...Nd5 12.Bd3 Bxd3 13.Qxd3 reaches the deep dive's structure in a version that is better for you: the bishops come off on d3, so your h-pawn never recaptures and your g-pawns are never doubled.",
             "line": "Nd5 Bd3 Bxd3 Qxd3 h6"},
            {"san": "Rd1", "severity": "inaccuracy", "tier": "Structure",
             "why": "A developing move in a position with a tactic in it. 11...Bxc3 12.bxc3 Nxe4 — once the knight has gone from c3, e4 is attacked by your knight and your bishop and defended by the queen alone.",
             "line": "Bxc3 bxc3 Nxe4 Bb2 Nef6"},
            {"san": "Bg5", "severity": "inaccuracy", "tier": "Structure",
             "why": "The pin costs the pawn, by the same count: 11...Bxc3 12.bxc3 Bxe4 and everything that was holding e4 together has left the board.",
             "line": "Bxc3 bxc3 Bxe4 Ne5 Qa5"},
        ],

        # ── ply 22 · White's twelfth, inside the deep dive ─────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O Bd3 Bh5": [
            {"san": "h3", "severity": "playable", "tier": "Plans",
             "why": "Taking g4 away for good, which matters now that the bishop is on h5 with nowhere else to go on that diagonal. 12...Bxf3 13.Qxf3 e5 and the break arrives on schedule.",
             "line": "Bxf3 Qxf3 e5 d5 cxd5"},
            {"san": "Bg5", "severity": "inaccuracy", "tier": "Plans",
             "why": "12...e5 is the freeing break, and it works here because White's twelfth move did nothing to stop it: 13.Be3 exd4 14.Bxd4 Re8 and the cramping pawn has gone. The engine has crossed to Black's side of level.",
             "line": "e5 Be3 exd4 Bxd4 Re8"},
            {"san": "Rd1", "severity": "inaccuracy", "tier": "Plans",
             "why": "The same pawn move answers it: 12...e5 13.Be3 exd4 14.Bxd4 Re8. Two of White's most natural twelfth moves lose the thread to one break, which is the rule for this structure — e5 is a race, and whoever gets there first wins the argument.",
             "line": "e5 Be3 exd4 Bxd4 Re8"},
        ],

        # ══ SEMI-SLAV ═══════════════════════════════════════════════════════════

        # ── ply 8 · White's fifth move after 4...e6 ────────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6": [
            {"san": "Bg5", "severity": "playable", "tier": "Mastery",
             "name": "Anti-Meran",
             "why": "The door to the sharpest theory in chess. 5...dxc4 is the Botvinnik and that is a different hobby; 5...h6 asks White to choose instead — 6.Bxf6 Qxf6 is the Moscow and hands you the bishop pair for an ordinary game, and 6.Bh4 dxc4 7.e4 g5 is the Anti-Moscow, which is another gambit but a smaller one.",
             "line": "h6 Bxf6 Qxf6 e3 Nd7"},
            {"san": "g3", "severity": "playable", "tier": "Plans",
             "why": "The fianchetto. Take the pawn: 5...dxc4, because the bishop coming to g2 wants the long diagonal and your pawn on c6 is going to be standing on it whatever happens.",
             "line": "dxc4 Ne5 Nbd7 Nxc4 b5"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "The queen supports c4 and asks about d5. 5...Be7 6.cxd5 exd5 and the one concession the Semi-Slav makes is undone — recapturing with the e-pawn opens the c8-bishop's diagonal again.",
             "line": "Be7 cxd5 exd5 Bf4 O-O",
             "see": "queensgambit"},
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "why": "The exchange with ...e6 already played. 5...exd5 and your bishop is free again: this is a Queen's Gambit Declined structure in which the problem piece is not a problem.",
             "line": "exd5 Qc2 g6 Bg5 Be7",
             "see": "queensgambit"},
            {"san": "e4", "severity": "inaccuracy", "tier": "Mastery",
             "why": "A genuine gambit, but only if White knows the follow-up. 5...dxe4 6.Ne5 is the move, and 6.Nxe4 loses a piece on the spot to 6...Nxe4, because nothing on the board covers e4 — not the knight on f3, not the queen on d1. After 6.Ne5 c5 Black is a healthy pawn up with a game to play.",
             "line": "dxe4 Ne5 c5 Be3 cxd4"},
        ],

        # ── ply 10 · White's sixth move after 5...Nbd7 ─────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7": [
            {"san": "Qc2", "severity": "playable", "tier": "Mastery",
             "name": "Anti-Meran (Stoltz)",
             "why": "The serious alternative to Bd3: White takes the b1–h7 diagonal first and keeps the bishop at home, so that ...dxc4 will not come with a tempo attached. 6...Bd6 7.Bd3 O-O 8.O-O e5 is the standard answer — if you cannot get ...c5 in, get ...e5 in.",
             "line": "Bd6 Bd3 O-O O-O e5"},
            {"san": "Be2", "severity": "playable", "tier": "Foundation",
             "why": "The modest square, and it gives up the diagonal that points at h7. 6...Bd6 7.O-O O-O and you can prepare ...e5 with no white piece aimed at your king.",
             "line": "Bd6 O-O O-O b3 b6"},
            {"san": "b3", "severity": "playable", "tier": "Structure",
             "why": "Propping the c-pawn up and preparing Bb2. 6...Bb4 uses the moment: the bishop comes out with a pin against the king on e1 before White's queenside is arranged.",
             "line": "Bb4 Bd2 O-O Qc2 b6"},
            {"san": "cxd5", "severity": "playable", "tier": "Foundation",
             "why": "The exchange, which releases the piece the Semi-Slav had locked up: 6...exd5 and the c8-bishop has f5 again. Recapturing with the e-pawn also leaves you with a7, b7 and c6 against a2 and b2 — the Carlsbad, where White plays a minority attack and you play on the kingside.",
             "line": "exd5 Bd3 Bd6 Qc2 O-O",
             "see": "structure#carlsbad"},
            {"san": "Ne5", "severity": "playable", "tier": "Structure",
             "why": "The outpost before the bishops are out. 6...Nxe5 7.dxe5 Nd7 and the pawn on e5 needs f2–f4 to stay where it is, which is a move White would rather spend on development.",
             "line": "Nxe5 dxe5 Nd7 f4 a5"},
        ],

        # ── ply 12 · White's seventh, and the two moves that hang the bishop ───
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4": [
            {"san": "e4", "severity": "blunder", "tier": "Foundation",
             "why": "Look at what your last move attacked. A black pawn on c4 hits b3 and d3, and the bishop on d3 has just been left there: 7...cxd3 wins a bishop for a pawn. This is the commonest blunder in the whole Meran, because 7.e4 is exactly the move the position seems to want.",
             "line": "cxd3 Qxd3 Be7 O-O O-O"},
            {"san": "a4", "severity": "blunder", "tier": "Foundation",
             "why": "The same thing with a different first move: a4 stops ...b5 and does nothing about the pawn already attacking d3. 7...cxd3 and Black is a bishop for a pawn up.",
             "line": "cxd3 e4 Be7 O-O a5"},
        ],

        # ── ply 14 · White's eighth after 7...b5 ───────────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5": [
            {"san": "Be2", "severity": "playable", "tier": "Structure",
             "why": "The quiet retreat: out of ...c5's way and off the diagonal that points at your king. 8...Bb7 9.O-O Be7 and the engine calls it dead level.",
             "line": "Bb7 O-O Be7 e4 b4"},
            {"san": "Bb3", "severity": "playable", "tier": "Structure",
             "why": "Out of ...c5's way and onto a diagonal your own pawn on e6 has already closed. 8...Be7 9.O-O Bb7 and Black has a free hand on the queenside.",
             "line": "Be7 O-O Bb7 e4 b4"},
            {"san": "a4", "severity": "blunder", "tier": "Foundation",
             "why": "Hitting b5 and forgetting c4: 8...bxc4 and the bishop goes for nothing. In this variation the question before every white move is what is attacking the light-squared bishop, and the answer is nearly always a pawn.",
             "line": "bxc4 e4 a5 O-O Bb4"},
            {"san": "Bxb5", "severity": "blunder", "tier": "Structure",
             "why": "The sacrifice does not work from here: 8...cxb5 9.Nxb5 Qa5 arrives with check on the empty a5–e1 diagonal, and 10.Nc3 Ba6 leaves Black a clean piece up.",
             "line": "cxb5 Nxb5 Qa5+ Nc3 Ba6"},
        ],

        # ── ply 16 · White's ninth after 8...Bb7 ───────────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 Bb7": [
            {"san": "e4", "severity": "playable", "tier": "Plans",
             "why": "Straight into the centre without castling first. 9...b4 sends the knight to the rim: 10.Na4 c5 11.e5 Nd5 and Black is fine. In the model game White got this push in a move earlier, because Black had spent the move on ...a6 rather than ...Bb7.",
             "line": "b4 Na4 c5 e5 Nd5",
             "see": "slav#kramnik-anand-2008"},
            {"san": "a3", "severity": "playable", "tier": "Plans",
             "why": "The engine's own preference and the most annoying move here: it takes b4 away before ...b4 exists, so that e4 can come next with the knight staying on c3. 9...a6 and answer 10.b4 with ...a5.",
             "line": "a6 b4 a5 Rb1 axb4"},
            {"san": "Qc2", "severity": "playable", "tier": "Structure",
             "why": "Queen and bishop lined up at h7 before castling. 9...a6 and the skeleton holds: a2–a4 is met by ...b4, and the break is still ...c5.",
             "line": "a6 a4 b4 Ne4 c5"},
        ],

        # ── ply 18 · White's tenth after 9...a6 ────────────────────────────────
        "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 Bb7 O-O a6": [
            {"san": "a4", "severity": "playable", "tier": "Structure",
             "why": "The standard test of the chain. 10...b4 11.Ne4 c5 and the knight has to come back or be traded — which is precisely what ...a6 was played for.",
             "line": "b4 Ne4 c5 Nxf6+ Qxf6"},
            {"san": "b3", "severity": "playable", "tier": "Foundation",
             "why": "Slow. 10...c5 arrives with everything the opening promised intact, and the engine already prefers Black.",
             "line": "c5 Bb2 Bd6 Rc1 Qe7"},
            {"san": "Qe2", "severity": "playable", "tier": "Foundation",
             "why": "A useful move that lets you break for free: 10...c5 11.dxc5 Bxc5 and Black has the freer game.",
             "line": "c5 dxc5 Bxc5 a3 O-O"},
        ],

        # ══ EXCHANGE SLAV ═══════════════════════════════════════════════════════

        # ── ply 6 · White's fourth in the Exchange ─────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5": [
            {"san": "Nf3", "severity": "playable", "tier": "Foundation",
             "why": "The other knight first, and it transposes. 4...Nf6 5.Bf4 Nc6 and every piece is where it belongs.",
             "line": "Nf6 Bf4 Nc6 Nc3 Bf5"},
            {"san": "Bf4", "severity": "playable", "tier": "Foundation",
             "why": "The bishop before the knights, which is the modern order. The rule for you does not change: develop the queenside knight and get your own bishop outside before ...e6.",
             "line": "Nc6 e3 Nf6 Nc3 Bf5"},
            {"san": "e3", "severity": "playable", "tier": "Structure",
             "why": "Shutting the bishop in before it has been out. In a symmetrical position that is a real concession, and the engine's number has already crossed to Black's side: 4...Nc6 5.Nc3 a6 and Black has the freer hand.",
             "line": "Nc6 Nc3 a6 Bd3 Nf6"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "Now that the c-pawn has gone the queen really does hit b7 and d5 at once — and both are covered, b7 by the bishop and d5 by the queen. 4...Nc6 5.Nf3 e6 and there is nothing there.",
             "line": "Nc6 Nf3 e6 Nc3 Nf6"},
            {"san": "e4", "severity": "inaccuracy", "tier": "Foundation",
             "why": "Trying to make something happen with nothing developed. 4...dxe4 and there is no compensation to come: 5.Nc3 Nf6 6.Bc4 a6 and Black is a pawn up for a little development.",
             "line": "dxe4 Nc3 Nf6 Bc4 a6"},
        ],

        # ── ply 8 · White's fifth in the Exchange ──────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6": [
            {"san": "Bf4", "severity": "playable", "tier": "Foundation",
             "why": "The main move order. 5...Nc6 6.e3 Bf5 and you are in the line on this page by another route.",
             "line": "Nc6 e3 Bf5 Nf3 e6"},
            {"san": "Bg5", "severity": "playable", "tier": "Structure",
             "why": "A pin with a queen behind it rather than a king, which is worth much less than it looks. 5...Ne4 hits the bishop and steps out of the pin at once — and the bishop cannot punish it by taking on d8, because your own pawn is still on e7 blocking the diagonal. 6.Bd2 Nxd2 7.Qxd2 e6 and a pair of pieces has come off on your terms.",
             "line": "Ne4 Bd2 Nxd2 Qxd2 e6"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "why": "The quiet one. 5...a6 is a good little move here: it takes b5 from the bishop for good, and b5 is the square White's bishop wants in every line of this variation.",
             "line": "a6 Nf3 e6 Bd3 b5"},
        ],

        # ── ply 10 · White's sixth in the Exchange ─────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6": [
            {"san": "Bg5", "severity": "playable", "tier": "Structure",
             "why": "Same pin, same answer: 6...Ne4 and the bishop has to move a second time. The engine has Black a quarter of a pawn better after it.",
             "line": "Ne4 Bf4 e6"},
            {"san": "e3", "severity": "playable", "tier": "Foundation",
             "why": "White shuts the bishop in first — so you can afford to do the same. 6...e6 7.Bd3 Bd6 and the bishops are symmetrical again, which in this structure is all you need.",
             "line": "e6 Bd3 Bd6 O-O O-O"},
            {"san": "Ne5", "severity": "playable", "tier": "Structure",
             "why": "The outpost, and it is supported by the pawn on d4, so it is not going to be chased away. It can still be traded: 6...e6 7.e3 Be7 and ...Nd7 or ...Nxe5 comes whenever you want it.",
             "line": "e6 e3 Be7 Bb5 Qb6"},
        ],

        # ── ply 12 · White's seventh after 6...Bf5 ─────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5": [
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "The queen hits b7 the moment your bishop stops guarding it. The answer is 7...Na5, kicking her with tempo: 8.Qa4+ Bd7 9.Qc2 e6 and the knight is heading for c4. What you must not play is 7...Rb8, when 8.Bxb8 simply takes the rook — the bishop on f4 has been looking at that square all along. And 7...Qb6 lets White trade into doubled b-pawns for you.",
             "line": "Na5 Qa4+ Bd7 Qc2 e6"},
            {"san": "Rc1", "severity": "playable", "tier": "Foundation",
             "why": "Straight for the file, which is the right idea in this structure and not yet a threat. 7...e6 8.e3 Bb4 and you contest it in time.",
             "line": "e6 e3 Bb4 Be2 Ne4"},
            {"san": "Ne5", "severity": "playable", "tier": "Structure",
             "why": "The outpost with d4 behind it. 7...e6 8.e3 Bb4 finishes your development; the knight is not going anywhere and it is not doing anything either.",
             "line": "e6 e3 Bb4 Bb5 O-O"},
        ],

        # ── ply 14 · White's eighth after 7...e6 ───────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6": [
            {"san": "Bd3", "severity": "playable", "tier": "Foundation",
             "why": "The trade. 8...Bxd3 9.Qxd3 Be7 10.O-O O-O and the position is exactly as level as it looks — this is the version of the Exchange Slav that really is a draw unless one side tries too hard.",
             "line": "Bxd3 Qxd3 Be7 O-O O-O"},
            {"san": "Qb3", "severity": "playable", "tier": "Structure",
             "why": "The queen once more, and now b7 is attacked once and defended by nothing. 8...Bb4 is worth more than the pawn: 9.Ne5 Bxc3+ 10.bxc3 Nxe5 and it is White's structure that has changed, with the b-pawn now on c3 and the a-pawn standing alone.",
             "line": "Bb4 Ne5 Bxc3+ bxc3 Nxe5"},
            {"san": "Rc1", "severity": "playable", "tier": "Foundation",
             "why": "The file first. 8...Bb4 9.Be2 Ne4 and you are in time everywhere.",
             "line": "Bb4 Be2 Ne4 O-O Nxc3"},
        ],

        # ── ply 16 · White's ninth after 8...Nd7 ───────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6 Bb5 Nd7": [
            {"san": "O-O", "severity": "playable", "tier": "Foundation",
             "why": "Sensible, and it gives up the Qa4 plan. 9...Be7 10.Bd3 Bxd3 11.Qxd3 O-O and there is nothing in the position for either side except the file.",
             "line": "Be7 Bd3 Bxd3 Qxd3 O-O"},
            {"san": "Ne5", "severity": "playable", "tier": "Structure",
             "why": "Trading while your knight on c6 is still pinned to the king. 9...Ndxe5 10.Bxe5 Rc8 and the engine has crossed to Black's side — the knight that could not move has been replaced by the one that could.",
             "line": "Ndxe5 Bxe5 Rc8"},
            {"san": "Bxc6", "severity": "playable", "tier": "Structure",
             "why": "The trade White is aiming for, taken at once. 9...bxc6 and be clear about the deal: you get the two bishops and the half-open b-file, White gets a target in your a-pawn, which now stands alone. The engine has it a shade in Black's favour.",
             "line": "bxc6 O-O Be7 Rc1 Rc8"},
        ],

        # ── ply 18 · White's tenth after 9...Rc8 ───────────────────────────────
        "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6 Bb5 Nd7 Qa4 Rc8": [
            {"san": "Ne5", "severity": "inaccuracy", "tier": "Structure",
             "why": "Too committal with the queen already out on the rim. 10...Ncxe5 11.Bxe5 a6 and White's bishop has to trade itself off; the engine gives Black most of a pawn.",
             "line": "Ncxe5 Bxe5 a6 Bxd7+ Qxd7"},
            {"san": "Bxc6", "severity": "playable", "tier": "Structure",
             "why": "Cashing in — and this is what the rook on c8 was for: 10...Rxc6, recapturing with the rook instead of the pawn, so the structure stays whole and the file stays yours.",
             "line": "Rxc6 O-O Qb6 Rfc1 Be7"},
            {"san": "Qb3", "severity": "playable", "tier": "Foundation",
             "why": "The queen admits the trip was pointless and comes back to the useful square. 10...Be7 11.Rc1 O-O and you have completed development for nothing.",
             "line": "Be7 Rc1 O-O"},
        ],
    },
    "games": [
        {
            "id": "topalov-kramnik-2006",
            "name": "Topalov – Kramnik, Elista 2006 — game two of the world championship",
            "tier": "Plans",
            "note": "The first twenty-eight plies are the main line and the deep dive on this page, move for move. Topalov varied on move fifteen, Kramnik took the a-pawn on move twenty-four, and the game was still level after the queens came off on move forty-one — one bishop move later it was not.",
            "moves": (
                "d4 d5 c4 c6 Nc3 Nf6 Nf3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 "
                "O-O Bd3 Bh5 e5 Nd5 Nxd5 cxd5 Qe3 Bg6 Ng5 Re8 f4 Bxd3 Qxd3 f5 Be3 Nf8 Kh1 "
                "Rc8 g4 Qd7 Rg1 Be7 Nf3 Rc4 Rg2 fxg4 Rxg4 Rxa4 Rag1 g6 h4 Rb4 h5 Qb5 Qc2 "
                "Rxb2 hxg6 h5 g7 hxg4 gxf8=Q+ Bxf8 Qg6+ Bg7 f5 Re7 f6 Qe2 Qxg4 Rf7 Rc1 "
                "Rc2 Rxc2 Qd1+ Kg2 Qxc2+ Kg3 Qe4 Bf4 Qf5 Qxf5 exf5 Bg5 a5 Kf4 a4 Kxf5 a3 "
                "Bc1 Bf8 e6 Rc7 Bxa3 Bxa3 Ke5 Rc1 Ng5 Rf1 e7 Re1+ Kxd5 Bxe7 fxe7 Rxe7 Kd6 "
                "Re1 d5 Kf8 Ne6+ Ke8 Nc7+ Kd8 Ne6+ Kc8 Ke7 Rh1 Ng5 b5 d6 Rd1 Ne6 b4 Nc5 "
                "Re1+ Kf6 Re3"
            ),
            "notes": {
                5: "Topalov's move order, 3.Nc3 before Nf3. Kramnik develops, White plays Nf3 anyway, and the game is in the main line by move four — which is why the deviation panel answers 3.Nc3 with 'transpose and carry on'.",
                8: "The main line, reached through the other door.",
                19: "10.e4, and this is the tabiya your first line ends on.",
                27: "14.Qe3. Up to here the game and the deep dive are the same moves in the same order.",
                29: "15.Ng5, and Topalov varies. The deep dive plays 15.Bxg6 hxg6 and trades everything; from g5 the knight looks at e6 and h7 and asks a question instead.",
                34: "17...f5, the clamp. One pawn move takes e4 and g4 away from every white piece for the rest of the middlegame, and Black's structure is still the one from the plan card: nothing weak, and the c-file to work with.",
                44: "22...Rc4 — the rook finally uses the file the whole variation is played for, and it arrives attacking a4.",
                48: "24...Rxa4. There is the account settled: a4 stopped ...b5 on move five and spent nineteen moves as a pawn that needed a piece or b2–b3 to look after it. Black is a pawn up here, with two queenside pawns against one.",
                61: "31.gxf8=Q+ is not a promotion so much as a trade — Black takes the new queen with the bishop, and what is left on the board is a black passed pawn on g4 and a white king with no pawns in front of it.",
                82: "41...exf5, and the queens are off. Count it: Kramnik has rook and bishop against bishop and knight and one pawn more, and the engine says 0.00 — because the pawn on f6 freezes the bishop on g7 and the rook that has to babysit it.",
                83: "42.Bg5 is the losing move, and it is worth seeing what it costs: dead level before it, a pawn and a quarter for Black after. 42.Ng5 held. From here the a-pawn runs and White's pieces cannot both stop it and hold the centre.",
                88: "44...a3. Kramnik gives the f-pawn to push the a-pawn — the queenside majority arriving twenty moves after the middlegame that was supposed to be about it.",
                126: "63...Re3, and Topalov resigned. The black king covers d7 and d8 so the d-pawn can never move, and the b-pawn costs the knight: 64.Nb3 Rxb3 is the end of it.",
            },
        },
        {
            "id": "kramnik-anand-2008",
            "name": "Kramnik – Anand, Bonn 2008 — game three, the Meran",
            "tier": "Mastery",
            "note": "The Semi-Slav line on this page, one move order along: Anand played the classical 8...a6 instead of 8...Bb7 and walked straight into the knight sacrifice on b5. He came out of it a pawn up, was two pawns down by move twenty-four, and the engine calls that position dead level — because Kramnik's king had no pawns left in front of it. It ends in mate.",
            "moves": (
                "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 a6 e4 c5 e5 cxd4 "
                "Nxb5 axb5 exf6 gxf6 O-O Qb6 Qe2 Bb7 Bxb5 Bd6 Rd1 Rg8 g3 Rg4 Bf4 Bxf4 "
                "Nxd4 h5 Nxe6 fxe6 Rxd7 Kf8 Qd3 Rg7 Rxg7 Kxg7 gxf4 Rd8 Qe2 Kh6 Kf1 Rg8 a4 "
                "Bg2+ Ke1 Bh3 Ra3 Rg1+ Kd2 Qd4+ Kc2 Bg4 f3 Bf5+ Bd3 Bh3 a5 Rg2 a6 "
                "Rxe2+ Bxe2 Bf5+ Kb3 Qe3+ Ka2 Qxe2 a7 Qc4+ Ka1 Qf1+ Ka2 Bb1+"
            ),
            "notes": {
                16: "8...a6, the classical Meran. The line you have drilled plays 8...Bb7 first and ...a6 after castling; Anand invites the whole avalanche a move earlier, and one move is the difference between the two variations.",
                19: "10.e5, the avalanche. The pawn takes f6 and d6 from Black's pieces and the knight on f6 has to move or be traded.",
                21: "11.Nxb5, the sacrifice that defines the classical Meran — and it is a loan, not a gift: after 11...axb5 12.exf6 the knight comes straight back. What White has really bought is the wrecked kingside that ...gxf6 leaves behind.",
                24: "12...gxf6. Count where that leaves things: material back to a pawn in Black's favour, Black's kingside shattered, and a passed pawn on d4 in the middle of the board. This is the Meran bargain and it has been argued about for ninety years.",
                26: "13...Qb6, and look at what the queen actually does from there: she defends b5 and she defends d4 — the two pawns the whole position hangs on — and she is not attacking anything, because Black's own pawns on b5 and d4 block both of her lines.",
                37: "19.Nxd4. White finally collects the passed pawn, and the position is roughly level.",
                48: "24...Rd8. Count the pawns: five against three, Kramnik is two clean pawns up, and the engine says 0.00. The g-file is open in front of the white king, the bishop on b7 has a clear road to g2, and that is worth exactly two pawns.",
                74: "37...Qe3+. Every black move from here is a check or a threat of mate, and White's passed a-pawn never gets the free move it needs to finish the journey.",
                82: "41...Bb1+, and Kramnik resigned. White has exactly two moves. 42.Kxb1 is not legal, because the queen on f1 covers b1 along the first rank; and 42.Ka1 Bc2+ 43.Ka2 Qb1 is mate.",
            },
        },
    ],
    "progression": {
        "arc": "The Slav is the defence you can play for thirty years without ever having a structurally bad position. The depth is in the details.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Understand why ...c6 beats ...e6 for supporting d5.",
                "learn": [
                    "The whole point: ...c6 supports d5 without locking in the c8-bishop. Get the bishop out before you play ...e6.",
                    "The main line: 3.Nf3 Nf6 4.Nc3 dxc4 5.a4 Bf5. Know why White nearly always plays a4, and what the square b4 costs.",
                    "The three families: Main Line Slav, Semi-Slav (with ...e6) and Exchange Slav.",
                ],
                "drill": "Play the main line twenty times and notice that b4 is available to you every single game, because White played a4.",
                "mistake": "Getting the bishop out one move too early. 3.Nf3 Bf5? loses a pawn to 4.cxd5 cxd5 5.Qb3 — the order is ...Nf6 first, then ...dxc4, then the bishop.",
                "ready": "You never play ...e6 before the bishop is developed, unless you have chosen the Semi-Slav deliberately.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Learn the two majorities and what each is worth.",
                "learn": [
                    "After 5.a4 Bf5, your a7, b7 and c6 are three pawns against two — a queenside majority you were given, not one you had to make.",
                    "White's d4 and e4 are two against one in the centre, which is why White has to hurry and you do not.",
                    "The Exchange Slav's symmetry: one open file, no majority anywhere, and a game decided by one tempo.",
                ],
                "drill": "Play ten Exchange Slavs and win the c-file every time. It is very nearly the entire content of the variation.",
                "mistake": "Treating the Exchange Slav as an automatic draw. Black has scored well in it for a century against opponents who relaxed.",
                "ready": "You can say what a4 costs White and what your own ...cxd5 recapture costs you.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Learn the freeing breaks and when to use them.",
                "learn": [
                    "The ...c5 break, which turns a solid position into an active one. It is the goal of nearly every Slav plan.",
                    "The ...e5 break, which arrives the moment White stops watching d4 — two of the deviations on this page are punished by nothing else.",
                    "How to meet e4: ...Bg6 first, then hit the centre. Blocking it with ...e5 immediately usually helps White.",
                ],
                "drill": "In ten games, count how many moves it takes you to achieve ...c5 or ...e5. Under fifteen is good; over twenty means you were too passive.",
                "mistake": "Never breaking. A Slav that never plays ...c5 or ...e5 is a cramped position with no weaknesses and no future.",
                "ready": "You reach ...c5 or ...e5 in most of your games under good circumstances.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Take on the Semi-Slav and decide how sharp you want your life to be.",
                "learn": [
                    "The Meran: the queenside majority, the ...c5 break, and the knight sacrifice on b5 that comes with them.",
                    "The 5.Bg5 family. 5...h6 is the Moscow and it is a normal game; 5...dxc4 is the Botvinnik and it is twenty moves of memory. You get to choose, and the choice is one move.",
                    "Slav endgames: how a three-against-two majority becomes an outside passed pawn, and why every trade helps you.",
                ],
                "drill": "Take the Botvinnik main line to move fifteen with an engine, then close it and try to explain the evaluation. If you cannot, play 5...h6.",
                "mistake": "Drifting into the Semi-Slav without preparation. It is a different opening from the Main Line Slav, not a version of it.",
                "ready": "You have chosen your branch and know it fifteen moves deep.",
            },
        ],
        "study": "Vladimir Kramnik is the model for the main line — his win over Topalov in Elista 2006 is on this page and follows the deep dive to move fourteen. For the Semi-Slav, the Anand–Kramnik games of the 2000s are the whole argument, and game three of Bonn 2008 is here too.",
        "next": "Add the Queen's Gambit Declined as a second option. Between the Slav and the QGD you have an answer to every 1.d4 system White can build.",
    },
}
