OPENING = {
    "id": "slav",
    "name": "Slav Defence",
    "eco": "D10–D19",
    "section": "black-d4",
    "orientation": "black",
    "tagline": "Support d5 with the c-pawn and keep the good bishop. The Caro-Kann of 1.d4.",
    "level": "Beginner → World Championship",
    "theory": {
        "big_idea": "Against the Queen's Gambit, Black must support d5. The Queen's Gambit Declined does it with ...e6, which locks the c8-bishop in. The Slav does it with ...c6, keeping the bishop's path to f5 and g4 open. Black's basic plan is to develop the bishop outside, then play ...e6 and ...dxc4 at a moment when the pawn can be held with ...b5 — grabbing genuine queenside space. It is the soundest, least compromising answer to 1.d4 there is.",
        "structure": "Black keeps pawns on c6 and d5 with a healthy, unbreakable structure. In the main line Black takes on c4 and holds with ...b5, ...a6 and ...Bb7, gaining queenside space. In the Semi-Slav (with ...e6 too) the c8-bishop is temporarily locked in but Black gets the powerful ...c5 and ...e5 breaks. In the Exchange Slav the position is completely symmetrical and famously drawish.",
        "white_plans": [
            "Play a4 early to stop ...b5 and take the b5 square for a knight or bishop.",
            "Build the centre with e3, Bxc4 and e4, converting into a big pawn centre.",
            "In the Exchange Slav, play the minority attack with b4–b5 on the queenside.",
            "In the Semi-Slav, launch the Botvinnik or Anti-Moscow gambits with e4 and g4 — some of the sharpest theory in chess.",
        ],
        "black_plans": [
            "Develop the bishop to f5 or g4 before playing ...e6 — the single defining idea of the whole opening.",
            "Take on c4 and hold with ...b5, gaining queenside space and a queenside pawn majority.",
            "The Meran plan: ...dxc4, ...b5, ...a6 and the central break ...c5.",
            "Trade into a good endgame with the healthy structure and queenside majority.",
        ],
        "traps": [
            "Do not play ...Bf5 before ...dxc4 in some move orders — White can hit with Qb3 forking b7 and d5.",
            "After 4...dxc4 5.a4, remember that ...b5?? 6.axb5 cxb5 7.b3! wins the pawn back with a great position.",
            "In the Semi-Slav Botvinnik (5.Bg5 dxc4 6.e4 b5 7.e5 h6 8.Bh4 g5), do not enter without preparation — it is one of the most forcing lines in existence.",
        ],
        "who": "Play this if you want a defence to 1.d4 that is completely sound, gives you a healthy structure, and does not require you to accept a bad bishop or a cramped position.",
    },
    "lines": [
        {
            "name": "Main Line Slav",
            "note": "The classical main line. Black takes on c4, develops the bishop outside, and gets a comfortable game.",
            "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O",
            "notes": {
                4: "The Slav. Black supports d5 with the c-pawn, which — unlike ...e6 — leaves the c8-bishop free.",
                5: "Development.",
                6: "Development.",
                7: "Development.",
                8: "Now the capture works, because Black threatens ...b5 to hold the pawn (having played ...c6 first).",
                9: "White's essential answer. It stops ...b5 permanently, at the cost of weakening the b4 square for the rest of the game.",
                10: "The whole point of the Slav. The bishop develops outside the pawn chain — the move that would be impossible in the Queen's Gambit Declined.",
                11: "Modest but necessary: it opens the f1-bishop's route to c4.",
                12: "Only now does the pawn go to e6, completing a solid fortress with the bishop already out.",
                13: "Regaining the pawn.",
                14: "Black uses the b4 square that a4 created, pinning the knight and preparing to castle.",
                15: "King safety.",
                16: "Development.",
                17: "Preparing e4 and connecting the rooks.",
                18: "The bishop steps back to a safe square, out of the way of the coming e4–e5.",
                19: "White takes the big centre. This is the standard main-line Slav position, played thousands of times.",
                20: "Black castles and is ready for ...Bh5 or ...e5. Black has a completely healthy structure and no weaknesses; White has more space. Balanced and rich.",
            },
        },
        {
            "name": "Semi-Slav — Meran Variation",
            "note": "Black plays both ...c6 and ...e6, accepting a locked bishop in exchange for the powerful ...c5 and ...e5 breaks.",
            "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 Bb7 O-O a6 e4 c5",
            "notes": {
                8: "The Semi-Slav. Black plays both ...c6 and ...e6 — the bishop is locked in for now, but Black gets an extremely resilient structure and both central breaks.",
                9: "The quiet approach, avoiding the wild Botvinnik and Moscow gambits with 5.Bg5.",
                10: "Development. The knight supports both ...e5 and ...c5.",
                11: "Development.",
                12: "The Meran. Black takes on c4 at the moment when ...b5 comes with tempo.",
                13: "Recapturing.",
                14: "Kicking the bishop and gaining serious queenside space. Black now has a queenside pawn majority.",
                15: "The bishop retreats to its best diagonal.",
                16: "Finally the problem bishop emerges — it eyes the long diagonal through e4.",
                17: "King safety.",
                18: "Reinforcing b5 so that a4 does not undermine everything.",
                19: "White grabs the centre. Now the position becomes very sharp.",
                20: "Black's key break. The centre opens, both sides have active pieces, and the resulting positions are among the richest in all of chess theory.",
            },
        },
        {
            "name": "Exchange Slav",
            "note": "White simplifies immediately into a symmetrical structure. Solid, safe, and much less drawish than its reputation.",
            "moves": "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6 Bb5 Nd7 Qa4 Rc8 O-O Be7",
            "notes": {
                5: "The Exchange Slav. White resolves the centre and heads for a symmetrical structure with an open c-file. It has a drawish reputation, but that is exactly why it is dangerous — Black must not relax.",
                6: "Forced.",
                7: "Development.",
                8: "Development.",
                9: "Development.",
                10: "Development.",
                11: "The bishop develops outside the chain — the same idea as the London System, on the other side.",
                12: "And Black does exactly the same. Perfect symmetry.",
                13: "Solidifying.",
                14: "Solidifying.",
                15: "The first asymmetrical move. White pins nothing but pressures c6 and prepares Qa4 and Ne5.",
                16: "Breaking the potential pin and reinforcing.",
                17: "Piling onto the c-file and the a4–e8 diagonal.",
                18: "Contesting the open file — the single most important thing to do in a symmetrical structure.",
                19: "King safety.",
                20: "Black completes development and is fine. The lesson of the Exchange Slav: in a symmetrical position the fight is over one open file and one tempo, and the player who understands that wins the endgame.",
            },
        },
    ],
    "deep": {
        "name": "Deep dive — the Slav into a clean structure",
        "note": "Black solves every problem by trading. Watch the pieces come off and a completely healthy structure remain.",
        "moves": "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O Nbd7 Qe2 Bg6 e4 O-O Bd3 Bh5 e5 Nd5 Nxd5 cxd5 Qe3 Bg6 Bxg6 hxg6 Bd2 Bxd2 Nxd2 Rc8",
        "notes": {
            21: "White retreats the bishop to the attacking diagonal, aiming at h7, and prepares to push e5.",
            22: "Black sidesteps and eyes the f3-knight. The bishop is unusually active for a queen's pawn defence — that is the Slav's whole promise.",
            23: "White gains space and kicks the knight.",
            24: "The knight jumps into the hole in front of White's pawn. It looks strong, and White will trade it immediately.",
            25: "White removes the blockader.",
            26: "Black recaptures toward the centre. Notice: Black now has pawns on a7, b7, d5, e6, f7, g7, h7. Not one of them is weak, doubled or backward.",
            27: "The queen steps off the pin and eyes the kingside.",
            28: "Black repositions the bishop to challenge the attacking diagonal.",
            29: "White trades it off — the bishop was the piece pointing at h7.",
            30: "Black recaptures with the h-pawn, opening the h-file for the rook and keeping the structure sound. Doubled g-pawns look ugly but they control f5 and h5 and neither is attackable.",
            31: "White offers the last minor-piece trade.",
            32: "Black accepts. Every trade helps the side with the healthier structure.",
            33: "White recaptures.",
            34: "The rook takes the open file. Look at the resulting position honestly: White has more central space with the e5-pawn, Black has a completely sound structure, an open c-file and a comfortable game. Black has not been in danger for a single move. That is what people mean when they call the Slav the soundest defence to 1.d4.",
        },
    },
    "progression": {
        "arc": "The Slav is the defence you can play for thirty years without ever having a structurally bad position. The depth is in the details.",
        "stages": [
            {
                "tier": "Foundation",
                "when": "Week one",
                "goal": "Understand why ...c6 beats ...e6 for supporting d5.",
                "learn": [
                    "The whole point: ...c6 supports d5 without locking in the c8-bishop. Get the bishop out before you play ...e6.",
                    "The main line move order: 3.Nf3 Nf6 4.Nc3 dxc4 5.a4 Bf5. Know why a4 is forced and what it weakens.",
                    "The three families: Main Line Slav, Semi-Slav (with ...e6) and Exchange Slav.",
                ],
                "drill": "Play the main line twenty times and note that b4 is available to you every game because White played a4.",
                "mistake": "Taking on c4 before ...c6 is in. Without the c-pawn ready to support ...b5, the capture just loses a tempo.",
                "ready": "You never play ...e6 before the bishop is developed, unless you have chosen the Semi-Slav deliberately.",
            },
            {
                "tier": "Structure",
                "when": "Weeks two to six",
                "goal": "Learn the queenside majority and what it is worth.",
                "learn": [
                    "After ...dxc4 and ...b5, you own a queenside pawn majority. That is a long-term endgame asset.",
                    "The b4 square that White's a4 permanently weakens — your bishop and knight both want it.",
                    "The Exchange Slav's symmetry: the whole game is about the c-file and one tempo.",
                ],
                "drill": "Play ten Exchange Slavs and win the c-file every time. It is the entire content of the variation.",
                "mistake": "Treating the Exchange Slav as an automatic draw. Black has scored well in it for a century by outplaying opponents who relaxed.",
                "ready": "You can explain what the a4-pawn costs White.",
            },
            {
                "tier": "Plans",
                "when": "Months two to five",
                "goal": "Learn the freeing breaks and when to use them.",
                "learn": [
                    "The ...c5 break, which turns your solid position into an active one. It is the goal of nearly every Slav plan.",
                    "The ...e5 break, available when White's pieces drift to the queenside.",
                    "How to meet e4: usually ...Bg6 and then hit the centre with ...c5, rather than blocking with ...e5 immediately.",
                ],
                "drill": "In ten games, count how many moves it takes you to achieve ...c5. Under fifteen is good; over twenty means you were too passive.",
                "mistake": "Never breaking. A Slav that never plays ...c5 or ...e5 is just a cramped position with no weaknesses and no future.",
                "ready": "You reach ...c5 or ...e5 in most of your games under good circumstances.",
            },
            {
                "tier": "Mastery",
                "when": "Ongoing",
                "goal": "Take on the Semi-Slav and the theoretical monsters.",
                "learn": [
                    "The Meran, where you get a queenside majority and enormous complications.",
                    "The Botvinnik and Anti-Moscow gambits — among the sharpest lines in all of chess theory, and unavoidable if you play 4...e6.",
                    "Slav endgames with a queenside majority: how to create the outside passed pawn.",
                ],
                "drill": "Decide honestly whether you want the Botvinnik. If not, choose the Moscow Variation move order and avoid it entirely.",
                "mistake": "Drifting into the Semi-Slav without preparation. It is a completely different opening from the Main Line Slav.",
                "ready": "You have chosen your branch and know it fifteen moves deep.",
            },
        ],
        "study": "Viswanathan Anand and Vladimir Kramnik played the defining Semi-Slav battles of the 2000s. For the classical Main Line, look at Max Euwe and Anatoly Karpov.",
        "next": "Add the Queen's Gambit Declined as a second option. Between the Slav and the QGD you have an answer to every 1.d4 system White can build.",
    },
}
